### ISSUE TITLE
Any way how to set decimal/thousands separator when formatting number?

### ISSUE THREAD

**Issue by skorunka** [robisim74/angular-l10n#100]
For example while using this pipe `{{ pi | localeDecimal:defaultLocale:'1.5-5' }}`. I would liek to globally override the decimal/thousands separators.

**Comment by robisim74** [comment]
Explain what are you trying to do.

**Comment by skorunka** [comment]
I would like to format number and be able to set the decimal and thousands separator explicitly.

**Comment by robisim74** [comment]
As explained in docs, to localize dates and numbers, this library uses Intl API, through Angular. The format changes according to default locale.
I don't know why you need to overwrite the official format, but to do this you could just create your own custom pipe.

Greetings

**Comment by skorunka** [comment]
@robisim74 Ok, thank you. That's actually what I thought ;)
