### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ili** [robisim74/angular-l10n#105]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```
1. Make it possible to avoid using `lang` or `defaultLocale` in pipe:
```html
<p>{{ 'TextWithParams' | translate::{ value: count}}</p>
<p>{{ 'Today' | translate:lang:{date:today | localeDate::'fullDate'} }}</p>
```

2. allow to use parameters with `l10n-attribute`:
```html
<p l10n-title="{date:today | localeDate::'fullDate'}" title='Today' l10nTranslate></p>
```

**Comment by robisim74** [comment]
1. Impossible: _pure pipes_ invoke the transform method only if input or the parameters change.
2. You can already do it: you do not have to assign it to the attribute, but to the master directive: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.2.3

**Comment by ili** [comment]
@robisim74 oh, I see, shame on me, I'v missed sample with greeting!
