### ISSUE TITLE
Translate method of Translation service doesn't work in lazy loaded module

### ISSUE THREAD

**Issue by DavidDomB** [robisim74/angular-l10n#106]
**I'm submitting a...**
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Call this.translation.translate( 'Translation key' ) in lazy loaded module should return traslated message not the key.

In lazy loaded module:
`this.translation.translate( 'Translation key' )`

Returns _Translated message_

**Actual behavior**
In lazy loaded module:
`this.translation.translate( 'Translation key' )`

Returns _Translation key_

**Steps to reproduce the behavior**
This escenario can be reproduced within the angular-l10n-sample-master app removing `preloadingStrategy: PreloadAllModules` of app-routing.module.ts file.
In a lazy loaded module of app configured to not preload modules:

list.component.ts
`translatedMessage:string = this.translation.translate('Translation key');`

list.component.html
<div>{{translatedMessage}}</div>

Prints _<div>Translation key</div>_

Plunker template: http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/

**Specifications: Angular version, library version, environment, browser**
Angular version: 4.2.5
Library version: 3.4.1
angular-cli version: 1.1.2
webpack version: 2.6.1
Chrome version: 58.0.3029.110 (64-bit)

**Comment by robisim74** [comment]
https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.4

In this case, if you are trying to translate when the component is loaded (in the constructor or OnInit method), preloading makes sure that also the translation files have been loaded.

**Comment by robisim74** [comment]
I'm closing this issue. If you need, reopen it.
