### ISSUE TITLE
Add comments into translation files

### ISSUE THREAD

**Issue by atsyba** [robisim74/angular-l10n#107]
Translation files can be really big.
I would like to make it more clear and easier to read by adding comments (e.g. page descriptions).

I will be really appreciate if there has already been implemented similar functionality or added to the next releases in other case.

**Comment by robisim74** [comment]
Json doesn't support comments. 

I think you could use a [custom provider](https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4.4) with an external library like [JSON5](https://github.com/json5/json5)
