### ISSUE TITLE
[need help] Add the localization into URL and switching between localization from URL

### ISSUE THREAD

**Issue by JTOne123** [robisim74/angular-l10n#108]
I'm looking for an approach to take out localization switcher to URL. 

Do you have ideas how I should configure the router?

Thank you!

**Comment by robisim74** [comment]
What do you mean with _Add the localization into URL_ and _switching between localization from URL_?

**Comment by JTOne123** [comment]
something like that: http://site/#/home/en-us

**Comment by robisim74** [comment]
Do you want to add the currente _locale_ to each URL without changing the active route?

**Comment by JTOne123** [comment]
I want to have 2 URLs

http://site/#/home/en-us
http://site/#/home/ru-ru

When I insert it Url in browser my localization is setting up
When I change en-us to ru-ru in URL, localization will change also
When I click by language in my UI, URL will change also to according localization

Do you see my point?

**Comment by robisim74** [comment]
Yes, now I see. But this is an Angular question.

Anyway, I think that to change localization when the URL changes, you could subscribe to a [router event](https://angular.io/guide/router#router-events) like _RouterRecognized_ and then use the `setDefaultLocale` method of `LocaleService`.

To change the URL when you change language in UI, you could use the `go` method of [Location](https://angular.io/api/common/Location) class. See also this question: https://stackoverflow.com/questions/35618463/change-route-params-without-reloading-in-angular-2

But I've never tried them: so maybe there are better solutions.

**Comment by JTOne123** [comment]
thank you
