### ISSUE TITLE
Compatibility Angular 4.3 (New HTTP module)

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#109]
On new Angular version http module has been replaced by common/http (https://www.infoq.com/news/2017/07/angular-43-released)

```javascript
peer dep missing: @angular/http@>= 4.1.0, required by angular-l10n@3.4.1
```

**Comment by robisim74** [comment]
`HttpModule` has not been replaced by `HttpClientModule`, at least for now. See the official announcement: https://blog.angular.io/angular-4-3-now-available-8d57b57eb5a8

Anyway, I will adopt it in the next major version, when Angular v5 will be released. But first I have to do some checks:
- Check compatibility with Server Side Rendering
- Check that the interceptors of the client app do not break the operation of this library

If you want to avoid importing `HttpModule` and use the new module, you can implement a [Custom Provider](https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4.4): basically you shoud rewrite only one line: https://github.com/robisim74/angular-l10n/blob/master/src/services/translation-provider.ts#L36

**Comment by johaven** [comment]
Thank you for the answer ;)

**Comment by robisim74** [comment]
New major version 4.0.0 for Angular v5 uses `HttpClientModule` instead of `HttpModule`: https://github.com/robisim74/angular-l10n/releases. Greetings
