### ISSUE TITLE
Feature request: add ability to pass language code to the pipe

### ISSUE THREAD

**Issue by AhmedMozaly** [robisim74/angular-l10n#11]
Currently, the translate pipe reads the language code from LocaleService which is fine **as a default behavior**

But with being the **only available behavior** This caused a limitation, where some areas in the view need to translate to certain language (language is already supported in the app) but no way to do so without changing the entire language in the app

We managed to add such feature in-house, with this syntax

`"UserName" | translate : "ar"`

But it will be much better to be supported in the library, to avoid duplicating the effort of modifying the pipe again after each new release

**Comment by robisim74** [comment]
I understand the need. I think you throw the `lang` parameter of the pipe to the `translate` method, right?

Please, make a Pull request or confirm my intuition and I provide myself. Thanks!

**Comment by AhmedMozaly** [comment]
Yes, exactly, I provided `languageCode` to the pipe, then it will pass it to the `translate` method.

Which will require some changes in both `TranslatePipe` & `LocalizationService`

**Comment by robisim74** [comment]
Just one question: this also requires that all translations are simultaneously loaded into LocalizationService even in the case of asynchronous loading? I would need to see changes to evaluate well.

**Comment by AhmedMozaly** [comment]
Unfortunately, I can't make pull request now, any ways, this is our modified version, appreciate any feedback

`

transform(key: string, languageCode: string = null): string {

```
    var isLocaleLangChanged = this.locale.getCurrentLanguage() != "" && this.locale.getCurrentLanguage() != this.localization.languageCode;

    var ignoreLocaleLang = (languageCode || "").length > 0;

    if (!ignoreLocaleLang && isLocaleLangChanged) {
        this.localization.updateTranslation();
    }

    languageCode = languageCode || this.localization.languageCode;
    var isServiceReady = this.localization.serviceState == ServiceState.isReady;
    var isTranslationNeeded = this.key != key || this.value == "" || this.languageCode != languageCode;

    if (!isServiceReady || !isTranslationNeeded)
        return this.value;

    var formatKey: string = key.replace(/^\d+\b/, '');
    formatKey = formatKey.trim();
    this.localization.translate(formatKey, languageCode).forEach(
        (value: string) => {
            this.value = key.replace(formatKey, value);
        }
    ).then(
        () => {
            this.languageCode = languageCode;
            this.key = key;
            return this.value;
        });
}`
```

**Comment by robisim74** [comment]
There is a problem: this seems like the old version of the library. Since version 0.7.0 there have been important changes: [releases](https://github.com/robisim74/angular2localization/releases). Now this library uses pure pipes, and the implementation of the pipes is completely different.
I do not know if we can get the same result that you expect using the same method.

**Comment by AhmedMozaly** [comment]
I  just checked the latest version source code,
Shouldn't this modification in `LocalizationService.translate` do the trick, or I'm missing something?

`
translate(key: string, languageCode:string = null): string {

```
var value: string;
languageCode = languageCode || this.languageCode ;
if (this.translationData[languageCode] != null) {

    // Gets the translation by language code. 
    var translation: any = this.translationData[languageCode];
    // Gets the value of translation by key.   
    value = translation[key];

}

// If the value of translation is not present, the same key is returned (see issue #1).
if (value == null || value == "") {

    value = key;

}
return value;
```

}`

**Comment by robisim74** [comment]
See [here](https://github.com/robisim74/angular2localization/blob/master/src/pipes/translate.pipe.ts): the translate pipe has changed.

**Comment by AhmedMozaly** [comment]
Yes, I check it too, my previous comment assumed the pipe will be modified too, with such modification

```
/**
* TranslatePipe transform method.
* 
* @param key The key to be translated
* @param lang The current language code for the LocalizationService
* @return The value of translation
*/
transform(key: string, lang: string): string {

        // Checks the service state.
        if (this.localization.serviceState == ServiceState.isReady) {

            // i18n: removes the value of template locale variable. 
            var formatKey: string = key.replace(/^\d+\b/, '');
            formatKey = formatKey.trim();

            // Gets the value of translation for the key.
            var value = this.localization.translate(formatKey, lang); // <---- NOTE the change here

            return key.replace(formatKey, value);

        }

    }

```

**Comment by robisim74** [comment]
Listen, with the new version of the library, I have a solution to your problem without changing anything: create a child component with different language in the parent component, and create a new instance of the services in it:

```
@Component({
    selector: 'home-child',
    template: `{{ 'TITLE' | translate:lang }}`,
    pipes: [TranslatePipe],
    providers: [LocaleService, LocalizationService] // Inherited by all descendants.
})

export class HomeChildComponent {

    constructor(public locale: LocaleService, public localization: LocalizationService) {

        this.locale.addLanguage('ar');

        this.locale.setCurrentLanguage('ar');

        // Initializes LocalizationService: asynchronous loading.
        this.localization.translationProvider('./resources/locale-'); // Required: initializes the translation provider with the given path prefix.
        this.localization.updateTranslation(); // Need to update the translation.


    }

    get lang(): string {

        return this.localization.languageCode;

    }

}
```

**Comment by MedAnd** [comment]
Is it possible for the translate pipe to use the localization.languageCode by default? For example:

<i class="fa fa-bar-chart-o fa-fw"></i> <span>{{'DASHBORAD_TOTAL_TITLE' | translate}}</span>

Would be equivalent to: 

<i class="fa fa-bar-chart-o fa-fw"></i> <span>{{'DASHBORAD_TOTAL_TITLE' | translate:localization.languageCode}}</span>

**Comment by robisim74** [comment]
Hello. When you add this:

```
    get lang(): string {

        return this.localization.languageCode;

    }
```

`LocalizationService` calls the translate pipe through Change Detection, and passes the languageCode property. If you intend to force a value to the language of the translate pipe, with pure pipes it will not work, because the pipe `transform` method is invoked only when Change Detection detects a change in the input parameters.
