### ISSUE TITLE
[QUESTION] This library is able to translate the key values of the objects ?

### ISSUE THREAD

**Issue by ALPNP** [robisim74/angular-l10n#110]
Hi ! Thanks for the library :1st_place_medal: 
This library is able to translate the key values of the object ?

My backend gives me the object(JSON) with key values and I would like them translated before it is displayed in the component.

`{ type: 'typeName'}`

Can I localize the value of the type object before displaying in the component ?

Why ?
Because I pass this object to a component which relates to third-party libraries and to modify that component in the layout I can't.

Maybe it's quite futuristic, but still worth to ask about this option.

Thanks for the help !
Best regards !

**Comment by robisim74** [comment]
Hi @ALPNP,

maybe you need to do something like this (second way): https://github.com/robisim74/angular-l10n/issues/51#issuecomment-275703800

**Comment by ALPNP** [comment]
Thanks for answer !
Tomorrow I will try to use the second way from your comment. And give feedback.

**Comment by robisim74** [comment]
Ok, see also here: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.4

**Comment by ALPNP** [comment]
Hi @robisim74 ,
everything went perfectly. Apparently missed this method when viewing the documentation. Thank you very much !

**Comment by robisim74** [comment]
Well. Greetings
