### ISSUE TITLE
Can't get this working...

### ISSUE THREAD

**Issue by rusagent** [robisim74/angular-l10n#111]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
Translation of text
**Actual behavior**
Usage of the Keynames
**Steps to reproduce the behavior**
I'm using this project-> https://github.com/cornflourblue/mean-angular2-registration-login-example <- as a starting point and used your supplied Quick Start Guide for Angular 4 here: https://github.com/robisim74/angular-l10n/blob/master/doc/quick-start.md#1

Installed the lib  `- npm install angular-l10n --save`
then added         `'angular-l10n': 'npm:angular-l10n/bundles/angular-l10n.umd.js' to the system.config.js `as specified.

Added this to the app.module.ts: 

```
import { TranslationModule, LocaleService, TranslationService } from 'angular-l10n';

@NgModule({
    imports: [  
        BrowserModule,
        FormsModule,
        HttpModule,
        routing,
        TranslationModule.forRoot()
    ],
    declarations: [
        AppComponent,
        AlertComponent,
        HomeComponent,
        LoginComponent,
        RegisterComponent,
        OptionsComponent
    ],
    providers: [
        customHttpProvider,
        AuthGuard,
        AlertService,
        AuthenticationService,
        UserService,
        LocaleService,
        TranslationService
    ],
    bootstrap: [AppComponent]
})

export class AppModule {

    constructor(public locale: LocaleService, public translation: TranslationService) {
        this.locale.addConfiguration()
            .addLanguages(['de', 'en'])
            .setCookieExpiration(30)
            .defineLanguage('de');

        this.translation.addConfiguration()
            .addProvider('./assets/locale-');

        this.translation.init();
    }

}

```

Then in the login/login.component.ts i added the 

```
import { LocaleService, Language } from 'angular-l10n';
export class LoginComponent implements OnInit {
    model: any = {};
    loading = false;
    returnUrl: string;
    @Language() lang: string;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private authenticationService: AuthenticationService,
        private alertService: AlertService,
        public locale: LocaleService) { }

    ngOnInit() {
        // reset login status
        this.authenticationService.logout();

        // get return url from route parameters or default to '/'
        this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/';
    }
    
    selectLanguage(language: string): void {
        this.locale.setCurrentLanguage(language);
    }

    login() {
        this.loading = true;
        this.authenticationService.login(this.model.username, this.model.password)
            .subscribe(
                data => {
                    this.router.navigate([this.returnUrl]);
                },
                error => {
                    this.alertService.error(error);
                    this.loading = false;
                });
    }
}

```

and into the login/login.component.html i added 

```
<div style="right:0px;">
    <button (click)="selectLanguage('de');" l10nTranslate>German</button>
    <button (click)="selectLanguage('en');" l10nTranslate>English</button>
</div>

```

and directives for the keynames like this 
`
    <h2 l10nTranslate>Login</h2>
`

I also added the assets folder with 2 files inside called locale-de.json and locale-en.json.
 I added the assets folder to the src folder but also to the src/app folder just for testing purposes.
My localization looks like this...
```

{
    "Title": "Secure API Puller",
    "Subtitle": "Sicher ist sicher!",
    "Change language": "Sprache ändern",
    "Greeting": "Hallo",
    "Register": "Registrieren",
    "Logout": "Ausloggen",
    "Delete": "Löschen",
    "Login": "Einloggen",
    "Password": "Passwort",
    "Username": "Benutzername",
    "PasswordRequired": "Passwort wird benötigt!",
    "UsernameRequired": "Benutzername wird benötigt!",
    "German": "Deutsch",
    "English": "Englisch",
}

```

I can't seem to find the mistake i made. I looked through this all day long and there's not even error messages coming in the debug windows.

I also tried Firefox and Chrome. With deleting the cache...

**Comment by robisim74** [comment]
Hi @kazoooka,

you can remove `LocaleService` and `TranslationService` from `providers` in AppModule.

About your problem: open the console, and check if you are getting a 404 from the http get requests instead of a 200:

![immagine](https://user-images.githubusercontent.com/14012361/28627251-8520bbf4-7221-11e7-986f-f24761a24981.png)

If you are getting a 404, the `assets` folder is the wrong place (in the starter you linked there isn't a `src` folder).

**Comment by rusagent** [comment]
I don't get a 404. Also there doesn't appear any locale-en.json or locale-de.jsonin the ntwork tab.

**Comment by robisim74** [comment]
If you can create a repo (just to reproduce the problem), later I'll give it a look.

**Comment by kazoooka** [comment]
I don't get a 404. Also there doesn't appear any locale-en.json or locale-de.jsonin the ntwork tab.

**Comment by rusagent** [comment]
I could give you a zip file but i have a mongoose database set up instead of the file system. Maybe i can send you a zip file via mail or something?

**Comment by robisim74** [comment]
Just a moment: what is `customHttpProvider`?

I'm reading here: http://jasonwatmore.com/post/2017/02/22/mean-with-angular-2-user-registration-and-login-example-tutorial#custom-http-ts that:

- It automatically adds the JWT token (if logged in) to the http authorization header of all requests
- Prepends request urls with the api url from the appConfig file

I fear that our problem is this...

**Comment by robisim74** [comment]
Do a try ro remove `customHttpProvider` from providers, and see if before the login the translation works.

**Comment by rusagent** [comment]
I tried to remove the customHttpProvider but sadly it didn't help. 
Uploaded the project here https://github.com/kazoooka/secureapiserver . Thank you very much already for your help and this project! As i said - you need a mongodb either locally or at mlabs for free online. Also you gotta specify the connection string in the server/config.json file.

**Comment by robisim74** [comment]
Ok, let you know.

**Comment by robisim74** [comment]
The problem is the second point of `customHttpProvider`:

>Prepends request urls with the api url from the appConfig file

1) Change `app.config.ts` in this way:
```
export const appConfig = {
    apiUrl: ''
};
```
2) Your json files dont work because you have a comma in the last line. Remove it:
```
{
    ...
    "English": "Englisch"
}
```
Then it works:

![image](https://user-images.githubusercontent.com/14012361/28633034-b1918f72-7232-11e7-9fff-db31f623bcb6.png)

**Comment by rusagent** [comment]
That breaks the application though :/

For example when you click register and try to register you will get Cannot POST /users/register 
or if you click login with some faulty credentials Cannot POST /users/authenticate

**Comment by robisim74** [comment]
Yes, you are using an example that prepends always the same path _to each request to the server_ (_another server_: another port means another IP address).  I think it is just an example, and it is difficult to applied in a real scenario. For example, you can't send any request to another server.
So, I think you should customize the example, removing the `apiUrl`, or passing it only when necessary (for example, the login request).

**Comment by robisim74** [comment]
Anyway, I don't know why you are using that example to start your app, but to add the token to header of your requests, you have a lot of ways. Just for example, you could use [angular2-jwt](https://github.com/auth0/angular2-jwt) or the new interceptors of Angular [HttpClient](https://angular.io/guide/http#intercepting-all-requests-or-responses). 

Just to complete the argument: once you understand and solve the problem, this library provides a lot of ways (even customized) of uploading translations: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4

**Comment by rusagent** [comment]
I was just looking for something like a boilerplate with user managment and jwt and an api server and that seemed like the perfect project to start it with.  If i remove that CustomHttp Stuff and replace it with the angular2-jwt it'll work you think?

**Comment by robisim74** [comment]
Yes, and you can chose the requests with the authentication token. I built this example using also angular2-jwt: https://github.com/robisim74/AngularSPAWebAPI/tree/master/src/AngularSPAWebAPI/app The server is built with .NET Core, but it's the same. Basically you only need to store in LocalStorage the token, and add it to the header of the requests.

**Comment by robisim74** [comment]
@kazoooka I'm closing this issue. if you need, reopen it. Greetings
