### ISSUE TITLE
Translate word with '...'

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#112]
**I'm submitting a...**
```
[x ] bug report
[ ] feature request
[ ] support request
```

```javascript
placeholder="{{'Search...' | translate: lang }}"
```

**Expected behavior**
Should be translated.
**Actual behavior**
Not Translated

**Comment by robisim74** [comment]
The _dot_ (one or more) is used as key separator by default. If you want to use _dots_ in your keys, you have to configure a different separator for the composed keys, for example:

```
      this.translation.addConfiguration()
        ...
        .setComposedKeySeparator('-');
```
and use the new separator for composed keys.

Greetings,
Roberto

**Comment by johaven** [comment]
Thank you :)
