### ISSUE TITLE
Request: getBrowserLanguage public

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#113]
**I'm submitting a...**
```
[ ] bug report
[x ] feature request
[ ] support request
```

I would like to use the return value of this method when user have not defined his language or when he wants to set his language automatically.
Or if possible when setting current language with a null value, use automatically the browser value.

**Comment by robisim74** [comment]
That's already implemented.

Whether you use `defineLanguage`, the service tries to use:
- Stored language
- Browser language
- Default language

Whether you use `defineDefaultLocale`, the service tries to use:
- Stored locale
- Default locale, regardless of the browser locale (because not all the browsers return the locale)

**Comment by johaven** [comment]
At runtime i have this configuration (below) but it's the browser language which is always selected. I am not sure this is the normal behaviour but it is only a parenthesis.
```javascript
this.locale.addConfiguration()
            .addLanguages(['en', 'fr'])
            .defineLanguage('en')
            .useSessionStorage()
        this.locale.init()
```

I have this method to do the job (below), because the user can switch to defined language or to an automatic option which return an empty string. So i need to overwrite the sessionStorage. If there is a better way why not but i would need an example.
```javascript
setLanguage(language: string): void {
        if (!language) {
            language = navigator.language
        }
        if (language !== this.localeService.getCurrentLanguage()) {
            this.localeService.setCurrentLanguage(language)
            moment.locale(language)
        }
    }
```

**Comment by robisim74** [comment]
Do you have options that returns an _empty string_? In my opinion, you should disable those options. 

Anyway,  to get the browser language, this is the method of the library: https://github.com/robisim74/angular-l10n/blob/master/src/services/locale.service.ts#L255 that will remain private because it is useless to be public.

**Comment by johaven** [comment]
I send an empty string to my method _setLanguage_ (above) to understand when user want to use browser language (auto).
<img width="255" alt="capture d ecran 2017-07-30 a 21 30 44" src="https://user-images.githubusercontent.com/5459596/28756437-7ba9bef4-756e-11e7-819c-bc81ce76b5f4.png">

I would like know if there is a better way to switch between defined language and browser language, i did not find it in the doc.

That's why i proposed to use the language of the browser when we call _localeService.setCurrentLanguage_ with an empty string (for example).
Or to access private _getBrowserLanguage_ which is a shortcut to _navigator.language_ but it is more by convenience.

**Comment by robisim74** [comment]
You don't need to set an _auto_ option, because as said the first time the library already try to use the browser language.
So if the user sets _auto_, nothing changes.

**Comment by johaven** [comment]
It is difficult to explain the whole design, but if the user has selected a language (fr or en), the language is stored in database.
Subsequently, this preference is applied all the time.
If the user wants to go back to the browser language (without worrying about whether the language is available), with the auto parameter it is possible.

But hey, it works very well, it was an idea among others (good or not) :)
Anyway thanks for the reactivity and for the super job!

**Comment by robisim74** [comment]
@johaven About your requests:
- _When setting current language with a null value, use automatically the browser value_: I prefer to keep `setCurrentLanguage` method as it is, with a not nullable parameter
- _Make `getBrowserLanguage` public_: ok, that's possible. In the meantime, you have to implement your own method

**Comment by robisim74** [comment]
The `getBrowserLanguage ` method is public in the new major version 4.0.0 for Angular v5. Greetings
