### ISSUE TITLE
Question: Localization support for input type numbers

### ISSUE THREAD

**Issue by sundarcodes** [robisim74/angular-l10n#114]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ X] support request
```
Hi,
I am sorry if this question has already been answered. 
I have an input type field which accepts numbers. I couldn't find in the sample codes, how to add localization support for input fields.  Lets say I have a number with value 200000.65 If this is in italian locale (language - 'it'), should be displayed as 200.000,65 and in the US locale (en-US), it should be displayed as 200,000.65. My question is specific to input field as the user changes to this input should also be reflected properly in the screen based on the locale.

Please enlighten me on this also please feel free to correct me if I am missing something.

Thanks..

**Comment by robisim74** [comment]
For input fields this library provides number validation by locales: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#6. See also the live example: https://robisim74.github.io/angular-l10n-sample/#/validation

If you mean a replacement of the formatting as you type, like jquery-number, it is not supported.

Greetings

**Comment by sundarcodes** [comment]
Thank you for the directions and also for the library 👍 I have to admit that I didn't look at your live example - validation section.
Yes, formatting as we type is a good to have feature. I will try to implement it in my project and if possible 
 will send a PR if all works well :)
