### ISSUE TITLE
How to best support zh-Hant and zh-Hans

### ISSUE THREAD

**Issue by mrkvw** [robisim74/angular-l10n#115]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```
I am trying to add support for zh-Hans and zh-Hant to an Angular 4 application. Here is an example plunk: https://embed.plnkr.co/jQuHnbbmBf2kMuNjbwfD/

In app.module I've added zh-Hans:
`.addLanguages(['en', 'it', 'zh-Hans'])`

When the application loads, it is looking for locale-zh.json and dialog-zh.json and 404 errors are logged to the console. Despite this, the translation string in locale-zh-Hans.json and dialog-zh-Hans.json are successfully loaded. Is this the correct method to support Chinese (Simplified) and Chinese (Traditional)?

**Comment by robisim74** [comment]
No, it isn't the correct method. As explained in the docs: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.6 _language code_ is the ISO 639 _two-letter_ or _three-letter_ code of the language conforming to BCP47.

`Hans` and `Hant` are _script_ codes, that you use to build the default locale, and not the language.

So after the language has been stored, the parser reads `zh` as language and `Hans` as country code, and gets a 404 until you set the language at runtime.

As language codes for Chinese you could use the `three-letter` codes as in ISO 639-3. For the macrolanguage `zho` you have the following individual languages: http://www-01.sil.org/iso639-3/documentation.asp?id=zho

Greetings

**Comment by mrkvw** [comment]
Thanks for the reply! Is there a way to support script codes so that we can have different translation files for simplified and traditional Chinese, or are you suggesting we use one of the macrolanguage codes to differentiate between `Hans` and `Hant`?

**Comment by robisim74** [comment]
For now, the library supports only `languageCode-countryCode` as language, using the `useLocaleAsLanguage` method of `TranslationService`.
I was already thinking to add different combination like `languageCode-script`, but I have to do a breaking change, and I don't want release a new major version until Angular v5 will be released.

In the meantime, you have different solutions:
- Try to see if you could use macrolanguages to differentiate between `Hans` and `Hant`
- Adding `useLocaleAsLanguage` and using `Hans` and `Hant` as country codes: then you have to create a translation file for each country/script: `locale-en-US`, `locale-en-UK`, `locale-zh-Hant` etc. If you need to use `Hans` and `Hant` only for specific countries, you could avoid them and use directly the country codes: `locale-en-US`, `locale-zh-CN` etc. You can also customize this behavior, creating a custom provider: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4.4 to load only for Chinese the files with `languageCode-countryCode` as extension.

**Comment by mrkvw** [comment]
Thank you Roberto, that works perfectly!
