### ISSUE TITLE
Translated texts not displaying on @angular/cli on Safari iPad

### ISSUE THREAD

**Issue by nirav-upadhyay** [robisim74/angular-l10n#117]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```

**Expected behavior**
Display translated text using pipes or directive
**Actual behavior**
On safari on iPad the translated texts are not displaying either using pipes or directives. They display as a keywords stored in en.json file

**Steps to reproduce the behavior**
I have added 
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script> in index.html and even modified the polyfills.ts to import the intl
Plunker template: http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/

**Specifications: Angular version, library version, environment, browser**
angular/cli
Angular 4.3
Safari on iPad

**Comment by robisim74** [comment]
I'm looking at the sample app on Safari on IPad and it works: https://robisim74.github.io/angular-l10n-sample/#/home

Is your app running on other browsers?

Could you post your `AppModule` (with the configuration) and the `index.html` with the polyfills?

**Comment by nirav-upadhyay** [comment]
Yes my app is running properly on other browsers.

Index.html
```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Next</title>
    <base href="./">
    <meta http-equiv="X-UA-Compatible" content="IE=ie9+">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US,Intl.~locale.en-GB"></script>
</head>

<body>
    <app-root>Loading...</app-root>
</body>

</html>
```


App.Module
```
import { NgModule } from '@angular/core';
import { ErrorHandler } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { LocaleService, LocalizationModule, TranslationModule, TranslationService } from 'angular-l10n';
import { Logger, Options } from 'angular2-logger/core';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    ReactiveFormsModule,
    LocalizationModule.forRoot(),
    TranslationModule.forRoot()
  ],
  providers: [Logger, Options],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(public locale: LocaleService, public translation: TranslationService) {
    this.locale.addConfiguration()
      .setCookieExpiration(30)
      .defineDefaultLocale('en', 'US')
      .defineCurrency('USD');

    this.translation.addConfiguration().addProvider('assets/i18n/');

    this.translation.init();
  }
}
```
App.Component
```
export class AppComponent implements OnInit {

  constructor(private router: Router,
    private locale: LocaleService) {
    this.setCurrentLanguage();
  }

  setCurrentLanguage(): any {
    let userLang = 'en'
    this.locale.setCurrentLanguage(userLang);
  }
```

**Comment by robisim74** [comment]
About the Intl polyfill, it is not a problem: you need it only for dates & number and for older browsers, not for translating text. 

You are making a mix between two scenarios: please see the docs or the quickstart https://github.com/robisim74/angular-l10n/blob/master/doc/quick-start.md on how to work with this library (_you only need to translate texts_ or _you need to translate texts, dates & numbers_).

About the problem on Safari: I can't reproduce it:
- How are you doing to test your app on the iPad?
- Which version of Angular-CLI and Safari are you using? Is it compatible with Angular?
- Could you create a plunker with the problem?

Thanks

**Comment by nirav-upadhyay** [comment]
I am able to fix the issue by providing proper name to my json file. I was making small mistake on setting up the language in app.component
