### ISSUE TITLE
Request retry loading locale when failed

### ISSUE THREAD

**Issue by icharge** [robisim74/angular-l10n#118]
**I'm submitting a...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Features request**
 - Retry loading locale when http request failed

**Expected Behavior**
 - When provider trying to request locale (JSON file)  and failed with 404 or 500 status code. Then retry HTTP request for that

**Specifications: Angular version, library version, environment, browser**
angular: 4.1.3
angular-l10n: 3.5.0
Ionic Framework: ionic-angular 3.6.0

I just use this module with Ionic framework.

Sorry for my not good in English.

**Comment by icharge** [comment]
I'm found custom storage on https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#27-storage

**Comment by robisim74** [comment]
Hi @icharge,

what do you mean with _Retry loading locale when failed_? Can you provide more details or an example of the expected behavior?

**Comment by icharge** [comment]
@robisim74 Sorry for few detail.
**Expected Behavior**
- When provider trying to request locale (JSON file) and failed with 404 or 500 status code. Then retry HTTP request for that

And now I have idea. I just use **CustomTranslationProvider** to handle this by **Observable.retryWhen** right?

**Comment by robisim74** [comment]
Yes, using the [custom provider](https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4.4) you can set the logic you want (such as managing a 404).

**Comment by icharge** [comment]
@robisim74  Thank you. I'll try this.
