### ISSUE TITLE
Translations using translate pipe do not update dynamically

### ISSUE THREAD

**Issue by on3al** [robisim74/angular-l10n#119]
**I'm submitting a...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
When  
setCurrentLanguage is called on the applications LocaleService,
the locale of strings passed to the translate pipe should be localized in the new language

**Actual behavior**
When  
setCurrentLanguage is called on the applications LocaleService,
the locale of strings passed to the translate pipe are not localized. They maintain the langague the application was initialized in

**Steps to reproduce the behavior**

Createa  pipe like:
        <input type="text" class="form-control"  placeholder="{{'DEVICE_COMPONENT_SEARCH_PLACEHOLDER' | translate:lang}}" [(ngModel)]="deviceSearch" />

Change locale on LocaleService. See it does not change

Plunker template: http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/
    "@angular/common": "4.1.1",
    "@angular/compiler": "4.1.1",
    "@angular/core": "4.1.1",
    "@angular/forms": "4.1.1",
    "@angular/http": "4.1.1",
    "@angular/platform-browser": "4.1.1",
    "@angular/platform-browser-dynamic": "4.1.1",
    "@angular/router": "4.1.1",
  "angular-l10n": "^3.5.0",

**Comment by robisim74** [comment]
Please, provide the essential code or a plunker. However check if you are using correctly the pure pipes: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.1

**Comment by on3al** [comment]
Sorry. I hadn't taken a look at the documentation since about 3.1. 
Adding the   @Language() lang: string; to my components using the pipes resolved all the issues I was having.  Great work on this project.
