### ISSUE TITLE
How can I get the currency symbol, instead of the code?

### ISSUE THREAD

**Issue by maxmumford** [robisim74/angular-l10n#12]
Hi,

I'd like to be able to output the current locale's currency symbol, i.e. £, instead of GBP. There doesn't seem to be a way to do this with the standard service. 

Currently using the following but it's messy and there must be a better solution:

`{{  0 | localecurrency:defaultLocale:currency:true:'1.2-2' | slice: 0:1 }}`

Can you point me in the right direction?

Thanks
Max

**Comment by robisim74** [comment]
Hi @maxmumford,

the syntax is correct, but why do you use `SlicePipe?` If you want to display only the integer portion, you have to set `digitInfo` to `1.0-0`. See [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.2.4).
In any case, check that you have correctly defined the locale & currency:

```
this.locale.definePreferredLocale('en', 'GB');
this.locale.definePreferredCurrency('GBP');
```

See also the [source code](https://github.com/robisim74/angular2localization/tree/gh-pages) of sample app.

If it does not work, you should post the code that you use in components. Let me know

**Comment by robisim74** [comment]
Another reason might be because your browser does not support `Intl` (do you use Safari?), and polyfill of Intl.js was not added in `index.html`:

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-GB"></script>`.

See [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.2).

**Comment by maxmumford** [comment]
Hi @robisim74 ,

Thanks for your suggestions. Localisation is working fine, what I am trying to figure out is how to output just the currency symbol, depending on the user's localisation.

For example, if I have a user that is localised to en-GB, how do I output a "£"? Or en-US, how do I output a "$"?

The reason my temporary solution works is because I localise a number, then slice all but the first character, which happens to be the currency symbol (£ in my case). But there must be a cleaner way to do this?

Thanks
Max

**Comment by robisim74** [comment]
Now I understand. Unfortunately the `CurrencyPipe`needs the number to return the symbol. If you do not have many currencies, I would use something like this:

```
<div *ngIf="currency == 'EUR'">€</div>
...
```

**Comment by maxmumford** [comment]
Ok thanks for the solution. I think I'll stick to my current workaround because it's a bit more flexible and the overhead shouldn't be significant. 

Thanks again
Max
