### ISSUE TITLE
Use same instance of translation and localization in multiple feature modules

### ISSUE THREAD

**Issue by nirav-upadhyay** [robisim74/angular-l10n#120]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```

**Expected behavior**
Want to use the singleton translation service across the lazy loaded modules
**Actual behavior**
How can I create a single instance of translation service and use it across the different modules.
Should i have to use initialize translation service/module in shared module and 
The clarification is not clear that is given in https://github.com/robisim74/angular-l10n/issues/45 and https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5
Do you have any sample created with multiple modules?

**Steps to reproduce the behavior**

**Specifications: Angular version, library version, environment, browser**
All latest version of library, angular 4, angular/cli

**Comment by robisim74** [comment]
https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#52-shared-modules

Use `forRoot` method in _AppModule_, and translation / localization module without calling methods in the shared module.

**Comment by nirav-upadhyay** [comment]
Thanks
