### ISSUE TITLE
Angular l10n v4 for Angular v5

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-l10n#121]
Hi,

the new major version of the library for Angular v5 has a lot of new features and breaking changes. I'm reporting them here: https://github.com/robisim74/angular-l10n/releases (_starting from v4.0.0-beta.0_)

All the doc and the samples have been updated to the latest version. The doc for Angular v4 is still available here: https://github.com/robisim74/angular-l10n/tree/angular_v4

Greetings,
Roberto

**Comment by csentis** [comment]
Hi Roberto,

I am a huge fan of your work for which I would like to thank you!

In their release notes on 5.0.0-beta.5, the angular team mentions: "multiple bugs and browser inconsistencies"in intl API, which is why they "have dropped the intl api in favor of data exported from the Unicode Common Locale Data Repository (CLDR)".

Do you see any necessity to reflect that in your work?
Christian

**Comment by robisim74** [comment]
Hi Christian,

thank you for this question, because I have already thought about this, made a choice and updated the library.

To translate dates and numbers, this library provided wrappers of official pipes. Two years ago, Angular Team made a bold choice using Intl API because it was only supported by two browsers: two years later, Intl Api grew up, and natively supported by all browsers, the latest Safari (http://kangax.github.io/compat-table/esintl/). Now they have decided to go back to the old and safe CLDR: but you have to consider that the official pipes are not for translation but for localization in a specific location. Technically, CLDR data are the same of the polyfills, so I see no need to go back.

In the new version of this library for Angular v5, I saved Angular code for interfacing with the Intl API, extended it to all the features of the API and added the timezone: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes

And now that the official pipes also support the locale as a parameter, everyone is free to choose:
- using the pipes/directives of this library with Intl API
- using official pipes with CLDR passing the locale, which can always be handled with this library

Greetings,
Roberto

**Comment by csentis** [comment]
Fantastic, Roberto, thank you for this concise answer!

**Comment by robisim74** [comment]
_angular-l10 v4.0.0_ for Angular v5 is out: https://github.com/robisim74/angular-l10n/releases/tag/v4.0.0
