### ISSUE TITLE
Suggestion on how to handle not available translation key on startup (loading from API)

### ISSUE THREAD

**Issue by damirkusar** [robisim74/angular-l10n#122]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[x] support request
```

**Expected behavior**
We are loading the translations via the API: `this.translation.addConfiguration().addWebAPIProvider(`/api/localisations/json/`, 'json');`
This works actually pretty well. We just encountered that sometimes a user goes to the site, and our api / db / needs a second to render de received translations. 

So, we could chache that in files on the ui, so that it loads that first and updates it afterwards with changes form the api. 

Just saw you changed the way how to use it.. will change it. 

But, if I use loading of json files and api, does this work? is there a order how they are using it? do you have a feature which does that somehow and caches the api response into files? Or are you planning that?

Any other suggestions how we could solve that? What and how would you do it? Translations will stay in the DB. It is not a big problem, just not nice that the key is not translated for a half a second / second (roughly). 

Thanks

**Comment by robisim74** [comment]
Hi @damirkusar,

to solve the problem on startup, I suggest to use this configuration: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/quick-start.md#3 (for _angular-l10n v3.x_).

Also, if you are using _lazy loaded modules_, I suggest to use the `PreloadAllModules` as strategy. Here an example: https://github.com/robisim74/angular-l10n-sample/blob/master/src/app/app-routing.module.ts.

Latest version of the library has the `caching` setting (for static and Web API providers): but it doesn't solve this problem, It avoids that a request already made is performed again.

Greetings

**Comment by damirkusar** [comment]
Hi @robisim74 

thanks for the suggestion.. will take a look.. and let you know.. will close this issue for now, and maybe come back.. thanks for your great support all the time..

**Comment by robisim74** [comment]
See here for an explanation of the current versions: #121 and here for the changelog: https://github.com/robisim74/angular-l10n/releases
