### ISSUE TITLE
Decimal in string has wrong format

### ISSUE THREAD

**Issue by Neill83** [robisim74/angular-l10n#124]
**I'm submitting a...**
```
[ x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
`{{item.caption | translate:lang }}`

this is my string to translate... if it has no translation in json files it will be shown the text of "item.caption". But if there is a decimal at start of the string like:

`4.9 My Item`

the result is the following

` 4,9.9 My Item` 

**Specifications: Angular version, library version, environment, browser**

angular: 4.1.3
angular-l10n: 3.4.1

**Comment by robisim74** [comment]
@Neill83 If you have numbers in your keys, you should disable i18nPlural:

```
this.translation.addConfiguration()
    ...
    .disableI18nPlural();
```

**Comment by Neill83** [comment]
oh ok thanks, i'll try

**Comment by Neill83** [comment]
First try failed...

what is if the caption does not exist in a locale file? so instead of translating it, it shows the given text... but the result is

`4,9.9 My item` instead of `4.9 My Item`

This text is not being translated... because i get it from Server. I'm only displaying it through

`{{item.caption | translate:lang }}`

**Comment by Neill83** [comment]
Ok it works on second try... i disabled the i18nPlural in the wrong config.

thanks for your help @robisim74
