### ISSUE TITLE
Inlining resource json files

### ISSUE THREAD

**Issue by K3n4** [robisim74/angular-l10n#126]
I'm submitting a question
```
[ ] bug report
[ x] feature request
[ ] support request
```

Hi!
I'm using angular 4.3.3 on my project and i'm using webpack for bundling. I can import json files directly in angular components. 
Is there a possibilities to import these json files as resources for angular-l10n???

**Comment by robisim74** [comment]
@K3n4 I'm not sure that I understood. Please, can you provide further informations or a example?

However, are you sure you can not do it with existing methods? https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#2.4

**Comment by K3n4** [comment]
Thank you! https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#2.4.4 <- this helped me

I have another question. I'm using 'l10nTranslate' attribute to translate the text. When page is loaded, it first shows keys, and after a second it loads translations. Is it possible to hide keys before translations is loaded ????

**Comment by robisim74** [comment]
Yes, use these settings: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/quick-start.md#3

**Comment by K3n4** [comment]
Thank you!!!
