### ISSUE TITLE
localeDate pipe does not work for ionic production/aot builds

### ISSUE THREAD

**Issue by uloco** [robisim74/angular-l10n#127]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
localeDate pipe should also work on aot/Ionic production builds

**Actual behavior**
localeDate pipe has no output when building with ionic production or aot flag.

**Steps to reproduce the behavior**
When you use the localeDate Pipe on a normal debug build, everthing works fine.
But building with the --prod  or --aot flag (`ionic cordova run ios/android --prod`) the pipe doesn't do any output.

You can also build for browser with `npm run build --prod`, but don't run serve afterwards, this will build again in dev mode. Try with `npm install -g http-server` and run on `http-server www/`

I think the `@ionic/app-scripts` are the problem here. Since they updated to version 2.x.x they changed quite some stuff in their build pipline. In my opinion it has something to do with their aot compilation.

**Specifications: Angular version, library version, environment, browser**
    @ionic/cli-plugin-proxy : 1.4.6
    @ionic/cli-utils        : 1.9.2
    ionic (Ionic CLI)       : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    Node              : v8.4.0
    npm               : 5.3.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002

**Comment by robisim74** [comment]
Hi @uloco, I will do a test to verify. Because you say that the pipe does not work only in aot mode, could you test if the components are implementing the `ngOnInit` method, even if it is empty? (it is necessary for `decorators` in aot mode).

**Comment by uloco** [comment]
Holy crap, I totally forgot to add the Interface. You saved my day. Thank you!
