### ISSUE TITLE
Question: Localize anchor tag text in localized text.

### ISSUE THREAD

**Issue by feco93** [robisim74/angular-l10n#128]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x ] support request
```

**Expected behavior**

I would like to translate text that include an anchor tag with localized innerhtml.

For example:

<p>Click here to <a routerLink="/changepassword">change</a> your password.</p>

**Actual behavior**

I found an alternative way, but it's not good enough:

<div hidden="true">
    <a #link routerLink=''>{{'ForgotPassword' | translate:lang | uppercase}}</a>
</div>

<p [innerHTML]="'InvalidTokenMessage' | translate:lang:{ url: link.outerHTML} "> </p>

locale-..json:

"InvalidTokenMessage": "... {{url}} ..."

**Steps to reproduce the behavior**

https://plnkr.co/edit/aSwffcYubxbWctmOLd7I?p=preview

**Specifications: Angular version, library version, environment, browser**

**Comment by robisim74** [comment]
Hi @feco93,

anchor tag using _innerHtml_ works only if you use html elements: `routerLink` is an Angular directive, so you need to do your workaround.
Really, I don't understand why you need to put the anchor tag and the url as a parameter in your translation files.
I think it would be cleaner do a simple translation:

`<a [routerLink]="url">{{'ForgotPassword' | translate:lang | uppercase}}</a>`

and then manage the _url_ variable in the component class.

Greetings

**Comment by feco93** [comment]
I have to pass the url as an argument, because not the whole context supposed to be a link.

For example:

Click [http://google.com](here) to search...

I would like to translate the whole sentence, and "here" is a link, which text is also translated.

Thanks for reply

**Comment by robisim74** [comment]
For generic urls (using href) something like this should work:

`<p [innerHTML]="'Search' | translate:lang:{ url: 'http://google.com'}"> </p>`

json:

`"Search": "Click <a href={{url}}>here</a> to search"`

**Comment by feco93** [comment]
It's ok, but what is the best practice if I would like to use routerLink direcitve, because I don't want to refresh the whole page? As I mentioned I found an alternative way (https://plnkr.co/edit/aSwffcYubxbWctmOLd7I?p=preview), but I'm not sure it's the best solution to solve this problem. What do you think about it?

**Comment by robisim74** [comment]
Personally, I prefer to avoid html tags in translation, and split the translation.

**Comment by feco93** [comment]
Thanks for replying.
