### ISSUE TITLE
Executing pipe from .ts component & returning objects as values

### ISSUE THREAD

**Issue by Sluchik** [robisim74/angular-l10n#129]
Can we execut pipe  <h4 class="plan-item-holder-title">{{ 'CAPITAL' | translate:lang }}</h4>   from component
like

 ngOnInit() {
    this.chartCaptions = this.translatePipe.transform('CAPITAL', this.lang) ;
}

**Comment by robisim74** [comment]
Yes, see here: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#getting-the-translation-in-component-class

**Comment by Sluchik** [comment]
Thank You very much . It's nice possibility. And one more question. Can we return for example object with translated  key : value instead single value. It would be a good feature. Thanks

**Comment by robisim74** [comment]
Please, could you provide an example and the expected behaviour? Thanks.

**Comment by Sluchik** [comment]
For example i have 2 "json".
` "CAPITAL":{
    "title": "Capital",
    "addCapital": "Add Capital",
    "aveCartNames": ["Funding Amount", "Funding Interest", "Funding Repayment", "CapEx Volume", "Depreciation"],
    "keyMetrics": {
      "m1": "Funding Amount",
      "m2": "Funding Interest",
    },`
and i need return object ` "keyMetrics": {
      "m1": "Funding Amount",
      "m2": "Funding Interest",
    },` by  
`  getTranslation(): void {
        this.keyMetrics = this.translation.translate('CAPITAL.keyMetrics');
    }
`
Is it possible by module, or need find custom solution?

**Comment by robisim74** [comment]
Yes, you can. With the latest version of the library, remember to set `composedKeySeparator` during the configuration, e.g. to '.':

```
const l10nConfig: L10nConfig = {
    ...
    translation: {
        ...
        composedKeySeparator: '.'
    }
};
```

**Comment by Sluchik** [comment]
Hmm... Interesting. I have investigated the logic and discovered that currently the modul can't return the Object instead of value Currently it can return only single translated value. 
![image](https://user-images.githubusercontent.com/13663547/31184096-204c120e-a931-11e7-9d73-36de2d97d8e1.png)
version  "angular-l10n": "^3.5.1",

**Comment by robisim74** [comment]
Is not an _Object_ what I'm seeing in the image of your debug?

**Comment by AndriOsta** [comment]
@robisim74 Could you please provide an example how to return value by key in case if value is object.For example:
`"CAPITAL":{   
                    "keyMetrics": {
                                            "m1": "Funding Amount", 
                                            "m2": "Funding Interest"
                                           }
}

I want to get this object { "m1": "Funding Amount", "m2": "Funding Interest" } by key "keyMetrics".

**Comment by robisim74** [comment]
@AndriOsta See this plunker: https://plnkr.co/edit/r1TFsR1k0O5QBYlTejc3

Open the console and see the object.

**Comment by robisim74** [comment]
Ok, I found the problem: it works only if you don't use composed keys.

I'll try to fix it.

**Comment by robisim74** [comment]
Added support to objects as values also to composed keys in the latest pre-release.
