### ISSUE TITLE
Angular 4 pipe does not updete all of my components

### ISSUE THREAD

**Issue by Mightforanis1938** [robisim74/angular-l10n#131]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x ] support request
```

I am using lazy modules with the Language decorator and using the translation pipe 
`({{'UserGroup' | translate:lang}})`
When I set the current language not all my components change language, it works fine in Development mode but when i build with:
`ng build --target=production --env=staging --stats-json`
some of my copmnonents doesent change language just when the page is reloaded and it works when i subscribe to the translation changed event and set the lang property
```
this._translationService.translationChanged.subscribe(() => {
            this.lang = _translationService.getLanguage();
        });
```

in those components which doesen't change language.

**Specifications: Angular version, library version, environment, browser**
angular-l10n@3.5.1
@ angular/core@4.3.6
@ angular/cli: 1.3.2
Win10
Chrome 61

Thank you for any help.

**Comment by robisim74** [comment]
Hi @Mightforanis1938,

are you implementing the `ngOnInit` method in your components, even if it is empty? (it is necessary for decorators in aot mode).

**Comment by Mightforanis1938** [comment]
Thank you for your help, it solved my problem the implementation of ngOnInit.

**Comment by vvolodin** [comment]
Could you please mention this somewhere in the docs, I've just encountered this issue and only was able to fix it thanks to this issue.

**Comment by robisim74** [comment]
Already it is clearly written in the documentation: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes

![image](https://user-images.githubusercontent.com/14012361/35056358-d9a27d88-fbb1-11e7-98a6-0fc991b4bd92.png)

If you think it is not enough, feel free to contribute with a pr.

Greetings

**Comment by vvolodin** [comment]
Good stuff, I'd like to add it to the docs home, there's a point about AOT there.
Thanks for this great library!
EDIT: Argh, it doesn't really belong there, the home page is basically a simple library description. Well, I guess it's on users to read the docs more carefully than I did.

**Comment by robisim74** [comment]
Maybe I'll add it also in the quick-start: usually at least that's read ;)

**Comment by skorunka** [comment]
I had the same problem. Spent 12 hours until I got to this closed issue. Please, definitely put that note in to Quick Start. The AOT is enabled by default since Angular 5.

**Comment by robisim74** [comment]
Already added.

**Comment by skorunka** [comment]
Coo, thank you. For some reason I did not spot it there :)

**Comment by drmencos** [comment]
@robisim74, Could you clarify this, please?

> "... and to cancel subscriptions OnDestroy, even if they are empty."

I found no examples of this implementation.

I'm using both pipes with the `@Language` decorator and directives, and everything works fine, but I don't know if I have to unsubscribe from something.

**Comment by robisim74** [comment]
@drmencos `@Language` decorator uses an observable: if you implemet `OnDestroy` in your component (also if it is empty), automatically the decorator unsubscribe the observable when the component is destroied. So you have less memory usage.

A complete example:

```
export class HomeComponent implements OnInit, OnDestroy {

    @Language() lang: string;

    ngOnInit(): void { 
        // It can be empty
    }

    ngOnDestroy(): void { 
        // It can be empty
    }
}
```

**Comment by drmencos** [comment]
Thanks!
