### ISSUE TITLE
Issue with date pipe in IE

### ISSUE THREAD

**Issue by pamidivenkat** [robisim74/angular-l10n#132]
**I'm submitting a...**
```
[ *] bug report
[ ] feature request
[ ] support request

```
this._localeDatePipe.transform(t, this._defaultLocale, 'mm')

**Expected behavior**
Should return minutes in 2 digit format(ex: 25)

**Actual behavior**
![date-pipe](https://user-images.githubusercontent.com/7859972/31349149-a4caaaf6-ad3f-11e7-8250-3daa29c5ce94.PNG)

**Steps to reproduce the behavior**

**Specifications: Angular version, library version, environment, browser**

**Comment by robisim74** [comment]
Hi @pamidivenkat,

up to v3 this library provided only wrappers to the official Angular pipes, that used Intl API, just to change default locale at runtime. Try to change `LocaleDatePipe `with the official `DatePipe`: you will get the same problem.

The problem you are getting is specific for Intl in IE: it seems that it does not support the 'mm' alone.

Sorry, but I have to close this issue as unsolvable. If you really _need to translate only minutes_, do a little workaround, getting 'hh:mm' and using a slice.

Greetings
