### ISSUE TITLE
Localization for Hindi does not work

### ISSUE THREAD

**Issue by adv1** [robisim74/angular-l10n#133]
Hi.
Localization for Hindi does not work
The rest works fine.

constructor(public locale: LocaleService, public translation: TranslationService) {
  this.locale.addConfiguration()
    .addLanguages(['en', 'ru', 'id', 'hi', 'tr', 'ko', 'es', 'vi', 'ja'])
    .setCookieExpiration(30)
    .defineLanguage('en')
    .defineDefaultLocale('en', 'US');

  this.translation.addConfiguration()
    .addProvider('./assets/locale-');

  this.translation.init();

**Comment by robisim74** [comment]
Please, provide more info: what is not working for Hindi language? what errors are you getting? can you post the code that does not work? Thanks

**Comment by adv1** [comment]
.addLanguages(['en', 'ru', 'id', 'hi', 'tr', 'ko', 'es', 'vi', 'ja'])
all languages from this list work, (except Hindi) when switching between them everything is fine,
when switching to Hindi, shows all the words in English.
all languages are connected by the same template
No errors.

public languageList: Array<LanguageModel> = [
    { language: 'en', country: 'US' },
    { language: 'es', country: 'ES' },
    { language: 'hi', country: 'IN' },
    { language: 'id', country: 'ID' },
    { language: 'ja', country: 'JP' },
    { language: 'ko', country: 'KO' },
    { language: 'ru', country: 'RU' },
    { language: 'tr', country: 'TR' },
    { language: 'vi', country: 'VN' },
  ];

**Comment by robisim74** [comment]
The code of language is indifferent to get the translation file. Check if:
- `locale-hi.json` exists and that it has the correct translation
- your change language method is passing `hi` when you switch language

**Comment by adv1** [comment]
All files in folder 'src/assets/' 
locale-hi.json
     (in first screen shot)
http://prntscr.com/gzp6iu

Translation is correct 
{
"All": "सब",
  "At the stage of collection": "कलेक्शन के चरण पर",
  "Successfully completed": "सफलतापूर्वक पूरा किया गया",
  "Partially completed": " आंशिक रूप से पूरा किया गया",
  "investors": "निवेशक",
  "collected": "एकत्र किया गया",
  "days left": "दिन बचे हैं",
  "required": "आवश्यक",
  "invest": "निवेश करें",
  "About us": "हमारे बारे में",
}
 (in second screen shot)
http://prntscr.com/gzp7ua

And when I switch language method is sending 
 {language: "hi", country: "IN"} 
(in third screen shot)
http://prntscr.com/gzp6eh

The same template is used to connect the other languages and with exactly the same actions and they work well.

**Comment by robisim74** [comment]
See this plunker: https://plnkr.co/edit/tTt7EMcVT0x1W5jbUWRi

It works without problems: as I said, the language is indifferent for translation files (not for dates & numbers).

Try also to clean your browser cache: maybe you have a wrong cookie stored.

**Comment by adv1** [comment]
This is strange, because my application is downloaded to the test server and it also has a problem, if I open it from a phone or from another computer, then when I select the Hindi language, the same problem (does not translate words)

**Comment by robisim74** [comment]
Try to open the console, network tab: when you switch to hindi, do you get a 200 or a 400 status code?

**Comment by adv1** [comment]
status code is 200
https://prnt.sc/gzpubg

**Comment by adv1** [comment]
I took some files from applications that connect languages
https://plnkr.co/edit/uavAkUgQ2wPGwmcbIGub?p=preview
and once again I repeat that the other languages work perfectly

**Comment by robisim74** [comment]
Just a moment: what you are using to get the language? can you add to the plunker also an html file?

**Comment by adv1** [comment]
I updated plunker
https://plnkr.co/edit/uavAkUgQ2wPGwmcbIGub?p=preview

**Comment by robisim74** [comment]
I mean: a template file where you are getting the translation. With pipes & directives.

**Comment by adv1** [comment]
You mean it?
https://plnkr.co/edit/uavAkUgQ2wPGwmcbIGub?p=preview

**Comment by robisim74** [comment]
Yes. When you switch language to hindi, are you getting the english keys or the English translation?

**Comment by adv1** [comment]
I getting the english keys like this left side

"All": "सब",
  "At the stage of collection": "कलेक्शन के चरण पर",
  "Successfully completed": "सफलतापूर्वक पूरा किया गया",
  "Partially completed": " आंशिक रूप से पूरा किया गया",
  "investors": "निवेशक",
  "collected": "एकत्र किया गया",
  "days left": "दिन बचे हैं",
  "required": "आवश्यक",
  "invest": "निवेश करें",
  "About us": "हमारे बारे में",


Here is another language (Korean) and it works well when I swith to it
"All": "모든",
  "At the stage of collection": "수집 단계",
  "Successfully completed": "성공적으로 완료 됨",
  "Partially completed": "부분 완료",
  "investors": "투자자",
  "collected": "모은",
  "days left": "일 남음",
  "required": "필수",
  "invest": "사다",
  "About us": "회사 소개",

**Comment by robisim74** [comment]
Ok, this means that the keys are not found. Possible causes:
 - the keys in hindi translation file are not correct (TranslationService performes an hash access, and it is case sensitive)
- the response of the http request is not correct (check if the json file is well format)

If it does not work yet, you need to debug the library and see what happens when you load the translation file.

**Comment by adv1** [comment]
I took all the keys from the working language of Korea and put in Hindi, the problem remained.

**Comment by robisim74** [comment]
Got it! The example stopped working because I forgot a `"` in a new translation. Now it works again. So I think you have to check your file (it is rtl): it is sufficient that the double quotes are missing because it does not work.

**Comment by robisim74** [comment]
https://jsonlint.com/

**Comment by adv1** [comment]
Oh, of course, You're right, thank you very much, the problem really was in the " .

Thank you very much for your time.

**Comment by rmanikam** [comment]
hi. I am facing the problem of converting my file from english to hindi.
