### ISSUE TITLE
An issue with restoring countryCode

### ISSUE THREAD

**Issue by JTOne123** [robisim74/angular-l10n#134]
**I'm submitting a...**
```
[ x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
After press F5 have to initialize correct country code

**Actual behavior**
countryCode field is undefined

**Steps to reproduce the behavior**
1) disable location hash strategy, URL should be like this http://localhost/home
2) Press F5 or change query params and press F5

Plunker template: http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/

**Specifications: Angular version, library version, environment, browser**
angular 4, l10n - 3.5.1, reproduced in chrome and edge

I discovered for some reason defaultLocale.countryCode did not set after F5
I have written a workaround:

```
        this.locale.addConfiguration()
            .addLanguage('en', 'ltr')
            .addLanguage('ru', 'ltr')
            .addLanguage('uk', 'ltr')
            .setCookieExpiration(30)
            .defineDefaultLocale(defaultLang, this.versionConf.DefaultCountry)
            .defineCurrency(this.versionConf.DefaultCurrency);
        
        this.translation.addConfiguration()
            .addProvider('./src/assets/locale/locale-');

        return this.translation.init().then(() => {
/////////////////////////WORKAROUND
            if(!this.locale.getCurrentCountry()) {
                var defaultLocale = this.locale.getDefaultLocale();
                var language = defaultLocale.substr(0, 2);
                var country = defaultLocale.substr(3, 2);
                this.locale.setDefaultLocale(language, country);
            }
        });
```

**Comment by robisim74** [comment]
@JTOne123 I don't see any problem when the page is refreshed.

When you refresh the page, the library tries to retrieve from the storage the default locale _asynchronously_: this means that if you try to obtain the country code _before the action is completed_, it is empty.

If you need the country code to be instantly available when loading the application, you have two ways:
- use advanced initialization (I recommend using it in any case): https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/quick-start.md#3
- subscribe to the `defaultLocaleChanged` event:
```
        this.locale.defaultLocaleChanged.subscribe(() => {
            console.log(this.locale.getCurrentCountry());
        });
```

Hash location strategy has nothing to do with it.

Greetings

**Comment by JTOne123** [comment]
yep, the good remark about async, I missed it.

But anyway, I tried to subscribe to this.locale.defaultLocaleChanged, how you had recommended to me and nothing happen, it' does not help

**Comment by robisim74** [comment]
@JTOne123 Please provide a minimal repro, bacause as I said I don't see any issue here.

**Comment by robisim74** [comment]
Missing a repro I'm closing this issue. Greetings
