### ISSUE TITLE
Have translation on a array of object inside a ts file

### ISSUE THREAD

**Issue by orphen92** [robisim74/angular-l10n#135]
hi,
i have a little question about localisation of data inside a ts file.
in a component files, i have an data object like this:
[
    {
      'id': '21',
      'title': 'title',
      'content': 'content',
      'phone': 'phone nb',
      'email': 'email@email.com'
    }
...
]
How can i have translation on this array of object please?
thanks for your help

**Comment by robisim74** [comment]
To load the translation data from *.ts files you can use direct loading: https://robisim74.github.io/angular-l10n/spec/configuration/#loading-the-translation-data. You can use it for the whole app or only for a specific lazy loaded module.

To convert the array of object to a valid json, you can find a lot of example on StackOverflow. However, you could do something like this:

```
    const data: any[] = [
        {
            'id': '21',
            'title': 'title',
            'content': 'content',
            'phone': 'phone nb',
            'email': 'email@email.com'
        },
        {
            ...
        }
    ];

    var translationEN: any = {};

    data.forEach((obj: any) => {
        translationEN = {...translationEN, ...obj}; // TypeScript object spread.
    });
```
and then add the translation data to the configuration.

Greetings
