### ISSUE TITLE
angular-l10n for standalone library localization

### ISSUE THREAD

**Issue by User3290** [robisim74/angular-l10n#136]
I have developed a standalone library for angular and want to localize her by angular-l10n. How can it be done? Is it possible? I mean independent .json file with translation and configuration of angular-l10n in the module of library.

Angular 4, 
angular-l10n 3.5.1

**Comment by robisim74** [comment]
Never tried. It should be possible, but you could have these problems:
- json files are loaded asynchronously: you should manage when they are ready
- if you are using rollup to build your library, you'll get an error during the building process: this problem has been fixed in the latest release for Angular v5. If you are going to use the version for Angular v4, let me know, and I'll release a new version compatible

**Comment by robisim74** [comment]
I released a new version 3.5.2 for Angular v4 that could be used as dependencie of another library.

Greetings

**Comment by User3290** [comment]
Could you help me to configure angular-l10n from module of my library.

```
this.translation.addConfiguration()
      .addProvider(PATH);
```

What's PATH should be provided in this configuration? I have tried to configure by the next paths, but it doesn't help:
~LIBRARY/resources/localization/locale-
./resources/localization/locale-

**Comment by robisim74** [comment]
Where are your json files? Are they in your library, or in the host app?

Try to see in the console > network the request URL of the header, and adjust the path accordingly. If you need, you can also use an absolute path.

**Comment by User3290** [comment]
Json files are in my library and i try to configure l10n properly from module of library. The goal is to create independent library prepared to install to anywhere

**Comment by robisim74** [comment]
Json files are loaded throw an http request (Angular http.get method): therefore they must be identified by an URI.
If you are hardcoding your files, maybe you can create a barrel for them (that _requires_ the json files), and then you could use the Direct loading: https://robisim74.github.io/angular-l10n/spec/configuration/#loading-the-translation-data

**Comment by User3290** [comment]
Yes, it's acceptable. Is it possible in 3.5.2 version? L10nConfig isn't recognized here... And forRoot doesn't accept this..

**Comment by robisim74** [comment]
Yes, for v3.5.2 see here: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#2.4.1

**Comment by User3290** [comment]
Great! You have done perfect library for localization. Thanks!

**Comment by robisim74** [comment]
Thank you. Did you solve it?!

**Comment by User3290** [comment]
Yes! :)

**Comment by robisim74** [comment]
Ok, glad to know it.
