### ISSUE TITLE
Statistics mode to find unused translation

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#137]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```
It might be useful to determine if some translations was never used.
I regularly forget to delete some translations from the JSON file when I change or modify them in my code.
In many translators (babel etc ...) if the expression to translate no longer exists in the code, it is automatically deleted from the translation file. 
Here it is not possible to do this (and it makes sense) but I think it's possible to find another way.

A statistics mode (enabled on demand) that counts the number of times the word has been translated could very well help!

**Comment by robisim74** [comment]
Hi @johaven,

a _coverage_ of the translations is interesting, but I think it requires an additional library, to work only on dev environment.
Also, I think it requires that you build a _parser_ (of .ts & template files): so I think you could also create an extractor to build the basic json file.

If you want work on it, then I can support you and share it in this project.

**Comment by johaven** [comment]
Unfortunately I'm working on a project that is already taking all my time :(
I thought it would be easy to add a watcher to the translate function of the Translation service to increment results service. Too bad ... :(

**Comment by robisim74** [comment]
Closed due to inactivity
