### ISSUE TITLE
format no longer accepted

### ISSUE THREAD

**Issue by sante85** [robisim74/angular-l10n#138]
**I'm submitting a...**
```
[X ] bug report
[ ] feature request
[ ] support request
```

Format dd MMMM yyyy HH:mm:ss is no longer accepted

Expected
l10nDate:defaultLocale:'dd MMMM yyyy HH:mm:ss' -> 7 novembre 2017 11:00:00

**Actual behavior**
l10nDate:defaultLocale:'dd MMMM yyyy HH:mm:ss' output 7/11/2017

Specifications: Angular 5, library 4

**Comment by robisim74** [comment]
@sante85 In the v4 of the library there is a breaking change in custom formats for the dates for two reasons:
- Angular v5 no longer use Intl API
- the old custom format used by Angular was always shown the same format regardless of the localization

Now this library implements the Intl API interface itself, and so you can define the custom format in Intl way.

See the docs: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes > Dates & Numbers > Dates

**Comment by sante85** [comment]
Ok, you have an idea how to define custom format?

Thanks

**Comment by robisim74** [comment]
As I said, see the docs: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes

Below Dates & Numbers > Dates, you find the explanation & an example like this:

```
@Component({
    template: `
        <p>{{ today | l10nDate:defaultLocale:options }}</p>
    `
})
export class HomeComponent implements OnInit {

    @DefaultLocale() defaultLocale: string;

    today: Date = new Date();
    options: DateTimeOptions = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };

    ngOnInit(): void { }

}
```
