### ISSUE TITLE
"...toPromise is not a function at TranslationService..."

### ISSUE THREAD

**Issue by k-vekos** [robisim74/angular-l10n#139]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Translation messages to be loaded.

**Actual behavior**
Only currency/numbers are localized and getting error "TypeError: this.getTranslation(...).toPromise is not a function at TranslationService.<anonymous> (angular-l10n.js:1398)"

**Steps to reproduce the behavior**
Just following the quickstart guide.

**Specifications: Angular version, library version, environment, browser**
Angular v5, "angular-l10n": "^4.0.0", ASP.NET Core Angular template with webpack. Chrome.

**Comment by k-vekos** [comment]
Adding `import 'rxjs/add/operator/toPromise';` to `angular-l10n.js` (I added it to both versions) fixes the error and makes the message translation functionality work.

**Comment by k-vekos** [comment]
Updating my project's version of `rxjs` from `5.4.2` to `5.5.2` fixes it too.

**Comment by robisim74** [comment]
Yes, Angular v5 requires RxJS ^5.5.2, and so this library from v4.0.0, because they use lettable operators.
