### ISSUE TITLE
rc5 is released.

### ISSUE THREAD

**Issue by gcphost** [robisim74/angular-l10n#14]
Update to rc5?

**Comment by robisim74** [comment]
Hi, there are many changes in rc.5. I am evaluating them, and then I'll update.

**Comment by robisim74** [comment]
Version 0.8.10 compatible with rc.5 is out.

**Comment by robisim74** [comment]
I released the 0.9.0 version for rc.5 that allows you to import the library as modules. See [releases](https://github.com/robisim74/angular2localization/releases).
