### ISSUE TITLE
Server Side Rendering [question]

### ISSUE THREAD

**Issue by JTOne123** [robisim74/angular-l10n#140]
Hey there,

In the readme.md file wrote that this project is compatible with Server-Side Rendering.

Do you have an example to understand what I should do to implement it?

I'm interested in angular4 for aspnetcore.

Thank you!

**Comment by robisim74** [comment]
For Angular + ASP.NET Core I used this starter: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/README.md.
It is configured to use ngx-translate, so you need to remove it and add this library.
I didn't published an example (every starter is different...), but if you want to use it, later I can post how to configure this library

**Comment by JTOne123** [comment]
yep, I looked into this project and have had several issues
I don't know how to configure server.ts in webpack.conf
  // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverConfig = setTypeScriptAlias(require('./tsconfig.json'), {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './Client/bootstrap-server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./../AspCoreServer/Client/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ],
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './../AspCoreServer/Client/dist')
        },
        target: 'node',
        devtool: 'inline-source-map',

        node: {
            global: true,
            crypto: 'empty',
            process: true,
            module: false,
            clearImmediate: false,
            setImmediate: false
        }
    });

And I had an issue with vendor-manifest.json



It'd be great to see you example

**Comment by robisim74** [comment]
Why you are seeing in the server? And why you are seeing the config files of the starter? You don't need to change them to add the library.

**Comment by JTOne123** [comment]
I don't add the library. I want to try to adapt this solution to the MarkPieszak's approach.
I have two separated repos for angular(basically the same repo with you) and aspnetcore and I don't want to merge them.

**Comment by robisim74** [comment]
As I said, I can show you only how to add this library to the ClientApp of that starter: is it enough? is it ok for current version (using Angular v5)?

**Comment by JTOne123** [comment]
Thank you, it could be helpful

**Comment by robisim74** [comment]
Ok, the only important thing is the use of absolute urls when you define the providers for Json files. There are two way:
- Using absolute urls when you define the providers:
```
        providers: [
            { type: ProviderType.Static, prefix: 'http://localhost:5000/assets/i18n/' }
        ],
```
- Or using `ORIGIN_URL`  provided by nguniversal

I'll show this second option, because the first one does not need anything.

Steps:
- Remove ngx-translate everywhere (disclaimer...)
- Install angular-l10n
- Open ClientApp > app > **app.module.ts** and add the following configuration:

```
import { L10nConfig, L10nLoader, TranslationModule, StorageStrategy, ProviderType, TRANSLATION_CONFIG } from 'angular-l10n';

const l10nConfig: L10nConfig = {
    locale: {
        languages: [
            { code: 'en', dir: 'ltr' },
            { code: 'no', dir: 'ltr' }
        ],
        language: 'en',
        storage: StorageStrategy.Cookie
    },
    translation: {
        providers: [],
        caching: true,
        missingValue: 'No key'
    }
};
```
 Note that `providers` are not defined here (because `ORIGIN_URL` still does not exist.

Import the module:

`TranslationModule.forRoot(l10nConfig),`

and change the class in this way:

```
export class AppModuleShared {

    constructor(
        private l10nLoader: L10nLoader,
        @Inject(TRANSLATION_CONFIG) private configuration,
        @Inject(ORIGIN_URL) private originUrl: string) {

        this.configuration.providers = [
            { type: ProviderType.Static, prefix: `${this.originUrl}/assets/i18n/` }
        ];
        this.l10nLoader.load();
    }

}
```

The library is configured. Now you can change the components.

**home.component.ts**

```
...
import { LocaleService, Language } from 'angular-l10n';
...
export class HomeComponent implements OnInit {

    @Language() lang: string;

    ...

    // Use "constructor"s only for dependency injection
    constructor(
        public locale: LocaleService
    ) { }

    // Here you want to handle anything with @Input()'s @Output()'s
    // Data retrieval / etc - this is when the Component is "ready" and wired up
    ngOnInit() { }

    public setLanguage(lang) {
        this.locale.setCurrentLanguage(lang);
    }
}
```

**navmenu.component.ts**

```
...
import { Language } from 'angular-l10n';
...
export class NavMenuComponent {

    @Language() lang: string;

    ngOnInit(): void { }
    ...
}
```

Finally, rename in the html files `| translate` to `| translate:lang`.

**Comment by JTOne123** [comment]
thank you so much!

**Comment by freezy** [comment]
Sorry to hijack the thread, let me know if you prefer opening a new one.

I have a project based on the [universal-starter](https://github.com/angular/universal-starter) project, and I'm getting untranslated strings in the prerendered HTML page (`npm run build:prerender`). As soon as client side scripts take over, they are correctly replaced though.

I couldn't find any `ORIGIN_URL` (or `BASE_URL`, as it seems to be renamed) import for setting it up like you described. Anything I'm missing?

**Comment by robisim74** [comment]
In the example above `ORIGIN_URL` is imported from _aspnetcore-engine_ for ng universal. I don't know what you are using in your project, but it is only the base url of the app (something like `http://localhost:8080`).

**Comment by freezy** [comment]
I'm using simple static pre-rendering, so there is no host or anything I could refer to. 

Just so we're on the same page, a pre-rendered page should contain the *translated* string of the default language in the HTML code that is served to the client on first load, right? That would be the whole point, i.e. not seeing any `{{ translation_key }}` showing up between first render and application loaded when using universal?

**Comment by robisim74** [comment]
@freezy I tested the [universal starter](https://github.com/angular/universal-starter) and I didn't find any problems:

![image](https://user-images.githubusercontent.com/14012361/33495155-927bab98-d6c5-11e7-9333-2ad96fa6fbf6.png)

I tested all the commands:
- npm start
- npm run build:ssr && npm run serve:ssr
- npm run build:prerender && npm run serve:prerender

Also you don't need an absolute url as in the sample above (with a base url) in the providers, but you can use a default configuration, and also the advanced configuration: https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization

If you have still problems with it, please open a new issue e provide more info and steps to reproduce the problem.

Greetings

**Comment by freezy** [comment]
Thanks for testing this out!

Can you check what `index.html` contains after `npm run build:prerender`? In my test it still contains a placeholder for translated strings. Although the placeholders are replaced once the Javascript is loaded, they still are visible until then, which can be a while on mobile/slow network.

The goal would be to have them translated a *build time*. Do you think that's possible?

**Comment by robisim74** [comment]
@freezy This library is for translation at runtime. If you need the translated value in the html (for SEO reasons, I think) you should use Angular i18n native solution, that build an app for each language.

**Comment by freezy** [comment]
Yeah, that's what I figured, thanks!

Might worth noting that in the README. Reading "compatible with [...] Server Side Rendering" I would assume build time support, and yes, it's important for SEO but also for user experience.

Cheers!

**Comment by robisim74** [comment]
Compatible means that _it works with_, and not that _it is the best solution for_. Greetings

**Comment by freezy** [comment]
Well that's pretty subjective, isn't it. Why would you even mention it then.

I would even go as far as adding the build time aspect into your comparison chart, because it's a pretty important point nowadays...

**Comment by robisim74** [comment]
@freezy  This is a library, not a course on Angular. Unlike other libraries, it also provides comparison information because I think that's right. If you have other data, this is also an open source project, and feel free to contribute. See also here: https://github.com/robisim74/angular-l10n/issues/17

About the compatibility with the SSR, it was necessary to report it because many libraries are not (or were not compatible) with the SSR.

Greetings
