### ISSUE TITLE
Can't find nested json key by directive translation

### ISSUE THREAD

**Issue by r3st1k25** [robisim74/angular-l10n#142]
**I'm submitting a..**
[x ] bug report
[ ] feature request
[ ] support request

**Expected behavior**
Translation message to be loaded.

**Actual behavior**
Does not find the key

Not nested sample(works fine): http://embed.plnkr.co/UdKFunQFnD3TOkXp2v06/ (check json files)
Nested sample(not working): https://plnkr.co/edit/pCrQt6sEhEeuRIfuAhCO?p=preview

**Specifications: Angular 5, Angular-l10n 4.0.0**

**Comment by robisim74** [comment]
@r3st1k25 From v4.0.0, you must explicitly set each parameter you need:

```
    translation: {
        ...
        composedKeySeparator: '.',
        ...
    }
```

Greetings

**Comment by AHelper** [comment]
Although the spec includes _"There aren't default values: you must explicitly set each parameter you need."_ after describing `LocaleConfig` and `TranslationConfig`, the release notes may want to highlight this as a breaking change for those already using composed translation keys. 

(Yes, I know, the spec was linked to under breaking changes, RTFM, but just a thought)

**Comment by robisim74** [comment]
Thanks for the suggestion. I updated the release note: https://github.com/robisim74/angular-l10n/releases/tag/v4.0.0
