### ISSUE TITLE
In a JSON file, allow references to other keys

### ISSUE THREAD

**Issue by tw3** [robisim74/angular-l10n#145]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```

Today, we can only set strings and variables like {{myVar}}. It would be great to be able to include other existing keys (like a partial translation).

**Expected behavior**

```
{
  "Greetings": {
    "Hello": "Hi"
  },
  "text":"@:Greetings.Hello from Github!",
  "text2":"@:Greetings.Hello there!"
}
```

text = "Hi from Github!"
text2 = "Hi there!"

**Comment by robisim74** [comment]
Closed as it will not be implemented
