### ISSUE TITLE
Attributes not working in v4

### ISSUE THREAD

**Issue by PodaruDragos** [robisim74/angular-l10n#147]
**I'm submitting a...**
```
[ x ] bug report
```

**Expected behavior**
l10n-placeholder to properly translate text

**Actual behavior**
text is not translated and json keys are shown

**Specifications: Angular version, library version, environment, browser**
@angular - 5.0.2
angular-l10n -4.0.0,
#

Note: This worked with previous version. I know i can use a pipe for that as shown in the github example using material components

**Comment by robisim74** [comment]
Translation of attributes with directives are currently working, as in the plunker provided in the README.

Please create a plunker with the repro of the problem, or at least provide the code that are not working.

**Comment by PodaruDragos** [comment]
```
    <mat-form-field class="full-width-input">
      <input autocomplete="off" formControlName="email" l10nTranslate l10n-placeholder matInput placeholder="signin.form.fields.placeholders.email" type="email" />     
    </mat-form-field>
    <mat-form-field class="full-width-input">
      <input autocomplete="off" formControlName="firstName" l10nTranslate l10n-placeholder matInput placeholder="signin.form.fields.placeholders.firstName" type="text" />
    </mat-form-field>
```

this is what i am using, i checked the example and didn't see atribute directives for placeholder only pipes. If i missed that please point me in that direction and i will close this ticket

**Comment by robisim74** [comment]
As I said the plunker is in the README. I added an input with the placeholder attribute and it's working: http://plnkr.co/edit/vpqyPUvDJGOFTuoF7ySP

But I'm trying in a my app with Material and you are right: the placeholder is translated (as in the console), but not showed: it seems replaced by ng-reflect.

There weren't changes to the directives in this library: so I have to investigate what happens with Material.

**Comment by robisim74** [comment]
Maybe I found a solution: try to move `l10nTranslate` directive to the `mat-form-field` element:

```
    <mat-form-field class="full-width-input" l10nTranslate>
      <input autocomplete="off" formControlName="email" l10n-placeholder matInput placeholder="signin.form.fields.placeholders.email" type="email" />     
    </mat-form-field>
```

Just a question: are you sure that it worked before? with which version of Material & Angular?

**Comment by PodaruDragos** [comment]
I now checked it didn't work before with material, we used materialize and i thought it's material forms

**Comment by robisim74** [comment]
Ok, I confirm that the solution in the case of _placeholder_ attribute is to add only the `l10nTranslate` directive to the container form `mat-form-field`, and avoid the `l10n-placeholder` attribute:

```
    <mat-form-field class="full-width-input" l10nTranslate>
      <input formControlName="email" matInput placeholder="signin.form.fields.placeholders.email" type="email" />     
    </mat-form-field>
```

That for two reasons: `mat-form-field` is a container of the input element, and `l10nTranslate` directive try to use the `value` attribute for the input elements. However, I suggest you do not use the directives with the input tags.

Greetings
