### ISSUE TITLE
Needed and Not used translation keys. 

### ISSUE THREAD

**Issue by damirkusar** [robisim74/angular-l10n#148]
**I'm submitting a...**
```
[x] feature request
[x] question
```

Hi Rob,

First of all, thanks for this library. Great Job.

I have a question, respectively a feature request if not done :)

1. Is there a way to figure out which translation keys retrieved are not in use in the app?
2. Is there a way to log or tell which translation keys are missing which are used in the app, but are not in the language file or DB, for example a report per language?

Thank you very much
Damir

**Comment by robisim74** [comment]
Hi Damir,

no, you can only show missing keys in the templates. See #137 for the features you are requiring.

Greetings

**Comment by damirkusar** [comment]
Thanks Rob,

Greetings.
