### ISSUE TITLE
countryCode not seen for composedLanguage

### ISSUE THREAD

**Issue by tw3** [robisim74/angular-l10n#149]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**

If you specify a country for composedLanguage and rename the local JSON file, the sample app should behave the same as before.

**Actual behavior**

The sample app does not see countryCode, tries to fetch 'local-en-.json'

**Steps to reproduce the behavior**

1) Clone the angular-l10n-sample code.
2) Update l10nConfig with:
`composedLanguage: [ISOCode.Language, ISOCode.Country],`
3) Rename 'src/assets/locale-en.json' to 'src/assets/locale-en-US.json'

**Specifications: Angular version, library version, environment, browser**

Angular v5, angular-l10n v4.0.0, Windows, Chrome

**Comment by tw3** [comment]
Hmm...it works after clearing cookies.  So maybe a caching issue.

**Comment by robisim74** [comment]
Yes, the sample app stores the default locale in a cookie for 30 days, so you need to clean the cache if you change the configuration. During development tests, you can also remove the expiration of cookie, or set up a session storage.
