### ISSUE TITLE
Server Side Rendering error

### ISSUE THREAD

**Issue by Shiroh1ge** [robisim74/angular-l10n#154]
Greetings! I have been using this library for a while now, and decided to try out angular universal. I followed the angular-cli guide and after serving the app and opening it in the browse, the server crashes with this: https://i.imgur.com/uGL1ahS.png. I tracked it down to this method: https://i.imgur.com/5eUuQQr.png. Do you have any idea why this happens and is there a way to fix it?

**Comment by robisim74** [comment]
Thanks for reporting. It seems a problem with the translation of attributes. I'll fix it and I'll release a new version.

**Comment by robisim74** [comment]
Fixed in v4.1.1: https://github.com/robisim74/angular-l10n/releases

**Comment by Shiroh1ge** [comment]
Wow, that was quick! Thanks a lot, will be testing it in a bit. Gotta say, this is probably the most well maintained repo I've come across, and even by one person. Thanks for all the hard work!

**Comment by Shiroh1ge** [comment]
After updating, now I'm getting this: https://i.imgur.com/bvD34jI.png. Got narrowed down to 2 errors at least xD. Any ideas?

**Comment by robisim74** [comment]
I think that I have understand. Are using directives with some UI component, like Angular Material?

**Comment by Shiroh1ge** [comment]
We're not using Material, but I think we're using some UI slider components, I'm going to dig throughout the code and see if there's any weird usages of the directive.

**Comment by robisim74** [comment]
Ok. Later I'll do the fixing (it's the same as before, but this time for directives working on component UI). It's strange because they've been working without problems for a long time. Maybe something has changed in the new universal.

**Comment by robisim74** [comment]
@Shiroh1ge Please try v4.1.2 and let me know.

**Comment by Shiroh1ge** [comment]
I went into the source code and added the attr check inside the isValidNode() method and the issue was fixed. About the UI component, we were using a popup component that had translated text inside. It look liked this:
```
                <popper-content #subscriptionDateInfo>
                    <p class="additional-info" [translate]="{'expirationDate': periodEnd | date}">
                        expiration_date_text</p>
                </popper-content>
```

However, I commented it out and this still produced the same 2 errors.

**Comment by robisim74** [comment]
Did you try v4.1.2?

**Comment by Shiroh1ge** [comment]
Sorry, when you posted the above comment my page wasn't refreshed, so I didn't see it. Updating now.
edit: Updated to v4.1.2 and everything is fine! Thank you again for your time.

**Comment by robisim74** [comment]
Good to know! Thank you for collaborating. Greetings

**Comment by robisim74** [comment]
Just for info: I added an explanation of SSR with this library in the docs: https://robisim74.github.io/angular-l10n/quick-start/#appendix-d-using-angular-universal

I'm closing this issue. Open a new issue if you need. Greetings

**Comment by Shiroh1ge** [comment]
Thank you for this, I was looking for a solution for translating on the server side, because the translation were flashing unpleasantly when the client was loading, so I was looking at different solutions until I saw your comment, will try this out now!
