### ISSUE TITLE
The pipe 'translate' could not be found

### ISSUE THREAD

**Issue by tudor2004** [robisim74/angular-l10n#156]
```
[ ] bug report
[ ] feature request
[x ] support request
```

Translating string using `<span>{{'accommodations.list.columns.id' | translate:lang}}</span>` causes following exception *The pipe 'translate' could not be found*

Angular version 5.0.5, library version 4.1.2

**Comment by robisim74** [comment]
Are you importing `TranslationModule` or `LocalizationModule` in your module? https://robisim74.github.io/angular-l10n/spec/configuration/#configuration

**Comment by tudor2004** [comment]
No... that was it. I included the two modules in my SharedModule and now it works. Thanks a lot

**Comment by robisim74** [comment]
Just one: TranslationModule if you need to translate only texts, LocalizationModule if you need to translate texts, dates and numbers. Greetings
