### ISSUE TITLE
Provide version number for resource files

### ISSUE THREAD

**Issue by ashishmulaye** [robisim74/angular-l10n#157]
I have one question related to adding providers to translation service. Prior to 4.0.0 upgrade, I was using below code to add the providers to translation service. 

```
for (let i = 0; i < fileset.length; ++i) {
            let file: string = fileset[i];
            this.translationService.addConfiguration().addProvider(directory + file, 'json?' + versionMacro);
}
```
Here, 
directory = directory path which contains the resource files e.g. “folder1\folder2\”
file = file name e.g. “somefile.json”
versionMacro = some version number say 1

Now, as per 4.0.0 configuration, we can only provide type and the prefix. So i have modified my code as,
```
const providers: any = [];
        for (let i = 0; i < fileset.length; ++i) {
            const file: string = fileset[i];
            providers.push({ type: ProviderType.Static, prefix: directory + file });
}
```
However, we can only provide the prefix so I am not able to provide versioning to these resource files.
Is there any way we can add versioning to this?

I was debugging the code and I found that in HttpTranslationProvider.prototype.getTranslation, the url is formed using `url += args.prefix + language + ".json";`.
One possible solution would be to add a suffix/version property in provider and in getTranslation method append the suffix at the end of the url. `url += args.prefix + language + ".json" + suffix;`

**Comment by robisim74** [comment]
What you were doing was an unexpected side-effect. However, since the previous version, you can create a _Custom Provider_, and pass the parameters you need to build a custom path.

See https://robisim74.github.io/angular-l10n/spec/configuration/#loading-the-translation-data > **Using a custom provider**

**Comment by ashishmulaye** [comment]
I created a custom provider to build a path with versions. 

Thanks a lot @robisim74 !!!
