### ISSUE TITLE
[Question] how i use l10nPercent ?

### ISSUE THREAD

**Issue by sddania** [robisim74/angular-l10n#159]
**I'm submitting a...**
```
[ x ] support request
```
i'm trying to use the l10nPercent directive as showed below:
<p l10nPercent>89</p>

**Expected behavior**
i would see 89% into the p tag (with it locale)

**Actual behavior**
i see 8.900% (with it locale)

**Specifications: Angular version, library version, environment, browser**
angular-l10n: 4.1.3
@angular: 5.1.2

do you expect 1 as value expression for output 100% ?

**Comment by robisim74** [comment]
x% = x / 100 so if you want show 89%, your number should be 0.89

**Comment by sddania** [comment]
ok thanks
