### ISSUE TITLE
Extending Translation for ChangeDetectionStrategy.OnPush doesn't work in dev env

### ISSUE THREAD

**Issue by dhardtke** [robisim74/angular-l10n#160]
First of all: Thanks for this awesome library! I just recently switched from ngx-translate and this one has far exceeded my expectations. +1

**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
I am using JIT compilation in development and AOT compilation for our production builds.
Also, I have several components that use the OnPush ChangeDetectionStrategy.
I want to extend the Translation class, as mentioned [here](https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#onpush-changedetectionstrategy), but it does not work for dev builds.

**Actual behavior**
> ERROR TypeError: Class constructor Translation cannot be invoked without 'new'

I am exactly following the code from the manual:
```typescript
export abstract class MyAwesomeComponent extends Translation implements OnDestroy {
    constructor(public cdr: ChangeDetectorRef) {
        super(cdr);
    }
}
```
The class is abstract since more classes extend that Component.

In production (using AOT) everything works fine. This is why I think it might be related to the module format.

I use these two options for our dev environment:
```json
"target": "es5",
"module": "commonjs",
```

This is the prod config:

```json
"target": "es2015",
"module": "esnext",
```

**Steps to reproduce the behavior**

StackBlitz Template: https://stackblitz.com/edit/angular-l10n-scyjce?file=app%2Fapp.component.ts

I tried reproducing my issue on StackBlitz, but I could not reproduce it. I don't think there is any way to customize the way Angular and the rest of the application is loaded? (if it's esm2015, es5, etc.)

**Specifications: Angular version, library version, environment, browser**
Angular 5.1.3
angular-l10n 4.1.4

**Comment by robisim74** [comment]
Hi @dhardtke,

are you using Angular CLI or another starter? Could you post your _tsconfig.json_ for dev env?

**Comment by dhardtke** [comment]
I am not using any sort of starter (including Angular CLI).

My complete tsconfig.json looks like this:
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "rootDir": ".",
        "baseUrl": "./app",
        "lib": [
            "dom",
            "es5",
            "es2015",
            "es2016",
            "es2017.object"
        ]
    },
    "exclude": [
        "app/main-aot.ts",
        "node_modules"
    ]
}
```

**Comment by robisim74** [comment]
It's weird, I tried to recreate the problem without success: are you using webpack or systemjs?

**Comment by dhardtke** [comment]
webpack using the webpack-dev-server. Are you interested in my webpack config?

**Comment by robisim74** [comment]
which transpiler are you using with webpack? awesome-typescript-loader? ts-loader?

**Comment by dhardtke** [comment]
```js
{
    test: /\.ts$/,
    exclude: [/\.(spec|e2e)\.ts$/],
    use: [
        "cache-loader",
        {
            loader: "thread-loader",
            options: {
                workers: require("os").cpus().length - 1 // there should be 1 cpu for the fork-ts-checker-webpack-plugin
            },
        },
        {
            loader: "ts-loader",
            options: {
                transpileOnly: true, // disable type checker - we will use it in fork plugin
                happyPackMode: true // enable compatibility with the thread-loader
            }
        },
        "angular2-template-loader",
        "angular-router-loader"
    ]
}
```

**Comment by robisim74** [comment]
Are you using the same options for ts-loader also in prod?

**Comment by dhardtke** [comment]
In production I use `@ngtools/webpack`.
```js
{
    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
    use: [
        {
            loader: "@angular-devkit/build-optimizer/webpack-loader",
            options: {
                sourceMap: false
            }
        },
        {
            loader: "@ngtools/webpack",
            options: {
                sourceMap: false
            }
        }
    ]
}
```

**Comment by robisim74** [comment]
Ok, in fact with the Angular CLI tools it works. Could you try to remove "cache-loader", "thread-loader" and the options from ts-loader?

**Comment by robisim74** [comment]
Nothing, I tried your configuration and it works.

If you can, please create a simple version of the application that goes wrong, and push it on github.

**Comment by dhardtke** [comment]
Okay, I fixed it. Thank you for the trouble, though!

I am using ES5 and CommonJS modules in the dev env. My webpack config was wrong and loaded the ES2015 (ES6) bundle of angular-l10n, because I had a bug in my webpack config.

I will try to switch to ES2015 for development soon, but couldn't yet for some reason (parts of my app break).
