### ISSUE TITLE
How can i add a provider to the current providers and load that one?

### ISSUE THREAD

**Issue by Blar1975** [robisim74/angular-l10n#162]
Hi @robisim74 ,

**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```
I used the **addProvider** method to add a new locale file to the **Providers** in constructor of modules. It's worked in v4 like this
```
export class AuthoritiesModule {
    constructor(public translation: TranslationService) {
	this.translation.addConfiguration()
		.addProvider('./assets/locales/authorities/locale-');

	this.translation.init();
```
But now this method doesn't exist and when I call the `this.l10nLoader.load();` method in AppModule I cannot configure in other modules. So I cannot reload or something else.
Is It must define all providers in AppModule what i want to use in the application?

Thanks for your help.

**Specifications: Angular 5.1.3, Angular-l10n 4.1.3, Chrome**

**Comment by robisim74** [comment]
Hi @Blar1975,

try this:

```
export class AuthoritiesModule {

    constructor(
        public l10nLoader: L10nLoader,
        @Inject(TRANSLATION_CONFIG) private translationConfig: TranslationConfig
    ) {
        this.translationConfig.providers = [
            { type: ProviderType.Static, prefix: './assets/locales/authorities/locale-' }
        ];

        this.l10nLoader.load();
    }

}
```
You can find more info and examples in the docs: https://robisim74.github.io/angular-l10n/spec/configuration/#dynamic-settings
