### ISSUE TITLE
Can I request "first day of week" index?

### ISSUE THREAD

**Issue by k-vekos** [robisim74/angular-l10n#163]
Is there a way l10n can provide me with the index of the first day of the week depending on current locale? For example, if I have a custom calendar control I want a week to start on a Sunday if the index is `0` and on Monday if the index is `1`.

Thanks!

**Comment by robisim74** [comment]
Hi @k-vekos,

unfortunately not all calendars have a week of 7 days (https://en.wikipedia.org/wiki/List_of_calendars#Non-standard_weeks), so I do not think it is possible to create a method that receives an index as a parameter and returns the day of the week (at least for this library, which is not based on languages datasets).

But if you have a calendar, do you now the date? If you knew the date, it would be possible:

```
@Component({
    ...
    template: `
        <p>{{ weekDay }}</p>
    `
})
export class MyCalendar {

    options: DateTimeOptions = { weekday: 'long' };

    datePipe: L10nDatePipe = new L10nDatePipe();

    weekDay = this.datePipe.transform(new Date(), this.locale.getDefaultLocale(), this.options);

    constructor(public locale: LocaleService) {  }

    getWeekDay(day: Date): void {
        this.weekDay=  = this.datePipe.transform(day, this.locale.getDefaultLocale(), this.options);
    }

}
```

**Comment by k-vekos** [comment]
Thank you for the explaination. I am however confused about the second part of your reply. What does that code get me exactly?

**Comment by robisim74** [comment]
For example, passing today's date to `getWeekDay` method, it gets `Wednesday` if the current locale is` en-US`, and `Mercoledì` if it is `it-IT`. But of course, as I said, you must use a date.
