### ISSUE TITLE
Custom service consuming TranslationService?

### ISSUE THREAD

**Issue by k-vekos** [robisim74/angular-l10n#164]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x ] support request
```
I am trying to create a custom Angular Service that consumes TranslationService. This service provides convenience features such as returning localized form values for my app. I have an issue however where sometimes my Angular components are requesting translations from my CustomService before the TranslationService injected into my CustomService has finished loading. This results in the input keys being returned instead of properly localized text.

My question is: how can I manage this? I tried [Advanced Initialization](https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization) but now I'm getting an error:

```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[CustomService]: 
  StaticInjectorError[CustomService]: 
    NullInjectorError: No provider for CustomService!
```

Alternatively I found that I need to be using 

```
ngOnInit(): void {
        this.translation.translationChanged().subscribe(
            () => { this.title = this.translation.translate('Title'); }
        );
    }
```

But I don't know how to implement this inside my CustomService as I need to return *something* to the component.

Thanks in advance!

**Comment by robisim74** [comment]
Hi @k-vekos,

welcome to state management of an Angular app... 

Basically, you should implement something like this:

```
@Injectable() export class CustomService {

    public value: string;

    constructor(
        private translation: TranslationService
    ) {
        // You need to subscribe to the event if you need to update the value during initialization and when the language changes at runtime
        this.translation.translationChanged().subscribe((language: string) => {
            this.value = this.translation.translate(key);
        });
    }

    public getValue(key: string): void {
        // Gets the value when required.
        this.value = this.translation.translate(key);
    );

}
```

This is the logic. Then to update your component with the _value_, you have different way:
- using an EventEmitter (simple, and it can update directly your component)
- using RxJs BehaviorSubject (more structured, also for using with objects)
- using ngrx (for more complex scenarios)

But this does not depend on this library, and you can find a lot of explanations.

The problem with APP_INITIALIZER is weird: are you sure you are importing into _providers_ of the module your _CustomService_?

Greetings

**Comment by k-vekos** [comment]
@robisim74 I tried removing my `CustomService` to see if that was the cause of issues with the `APP_INITIALIZER` but the problem persists. Here is my `app.module.ts`:

```
import { NgModule, APP_INITIALIZER } from '@angular/core';
// ...
import { L10nConfig, L10nLoader, LocalizationModule, StorageStrategy, ProviderType } from 'angular-l10n';

const l10nConfig: L10nConfig = {
    locale: {
        languages: [
            { code: 'en', dir: 'ltr' },
            { code: 'de', dir: 'ltr' }
        ],
        defaultLocale: { languageCode: 'en', countryCode: 'US' },
        currency: 'USD',
        storage: StorageStrategy.Cookie
    },
    translation: {
        providers: [
            { type: ProviderType.Static, prefix: './assets/locale-' }
        ],
        caching: true,
        missingValue: 'No key'
    }
};

// Advanced initialization.
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load();
}

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        CommonModule,
        HttpModule,
        FormsModule,
        HttpClientModule,
        // ...
        LocalizationModule.forRoot(l10nConfig)
    ],
    providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: initL10n,
            deps: [L10nLoader],
            multi: true
        }
    ]
})
export class AppModuleShared {
    /* constructor(public l10nLoader: L10nLoader, ) {
        this.l10nLoader.load();
    } */
}
```

It seems to only throw the error when I view my component that uses TranslationService:

```
constructor(public translation: TranslationService) {}
```

**Comment by robisim74** [comment]
I don't see your `CustomService` in the list of `providers` of the module. Then you should use `APP_INITIALIZER` with the root `AppModule`.

**Comment by k-vekos** [comment]
I removed CustomService from my running code that's why it isn't in `providers`. How do I use `APP_INITIALIZER` with the root `AppModule`?

**Comment by robisim74** [comment]
Are you building an app or a library?

**Comment by k-vekos** [comment]
It's an app. Sorry, I forgot to mention that my project is based on a template which used SSR (which I disabled) so my app module is split up. Here is the "root":

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppModuleShared } from './app.module.shared';
import { AppComponent } from './components/app/app.component';

@NgModule({
    bootstrap: [ AppComponent ],
    imports: [
        BrowserModule,
        AppModuleShared
    ],
    providers: [
        { provide: 'BASE_URL', useFactory: getBaseUrl }
    ]
})
export class AppModule {
}

export function getBaseUrl() {
    return document.getElementsByTagName('base')[0].href;
}
```

Note the `AppModuleShared` in `imports`

**Comment by robisim74** [comment]
Why do you have an `AppSharedModule`? To get the `BaseUrl`? I have an app built with SSR, with the configuration of APP_INITIALIZER in `AppModule`, and the `AppServerModule` imports `AppModule`: it works.

However, I think the only reason for your error is the missing of `CustomService` in the list of your providers. Try to put it in `AppModule`.

**Comment by k-vekos** [comment]
The only reason I still have an `AppSharedModule` is because I disabled SSR but left the shared, server, and browser app.module.*.ts files. If I *really* wanted to I could combine `AppModuleShared` and `AppModule` but I haven't yet.

I tried adding `CustomService` to `providers` but I am still getting the error though.

**Comment by robisim74** [comment]
Try to inject the _TranslationService_ as _private_ into the component. Maybe it could be a problem of deps of your _CustomService_.

I'd need a repro to understand what happens.

**Comment by k-vekos** [comment]
Sorry, I found the source of the error it was a naming mixup with my providers and imports, etc.

Thanks!
