### ISSUE TITLE
getTranslation(language).toPromise is not a function

### ISSUE THREAD

**Issue by nopmania** [robisim74/angular-l10n#166]
After I include angular-l10n and run web, it has an error as follow:

TypeError: this.getTranslation(language).toPromise is not a function. (In 'this.getTranslation(language).toPromise()', 'this.getTranslation(language).toPromise' is undefined)
(anonymous function) — angular-l10n.js:1445
step — vendor.js:25971
(anonymous function) — vendor.js:25945
ZoneAwarePromise — vendor.js:86641
__awaiter — vendor.js:25941
(anonymous function) — angular-l10n.js:1270
step — vendor.js:25971
(anonymous function) — vendor.js:25945
ZoneAwarePromise — vendor.js:86641
__awaiter — vendor.js:25941
(anonymous function) — angular-l10n.js:1619
step — vendor.js:25971
fulfilled — vendor.js:25942
onInvoke — core.js:4733
run — vendor.js:85948
(anonymous function) — vendor.js:86625
onInvokeTask — core.js:4724
runTask — vendor.js:85998
drainMicroTaskQueue — vendor.js:86391
promiseReactionJob
defaultErrorLogger — core.js:1440
handleError — core.js:1501
run — vendor.js:85948
(anonymous function) — core.js:5676
onInvoke — core.js:4733
run — vendor.js:85948
(anonymous function) — vendor.js:86625
onInvokeTask — core.js:4724
runTask — vendor.js:85998
drainMicroTaskQueue — vendor.js:86391
promiseReactionJob
onUnhandledError — vendor.js:86450

**What am I doing wrong?**

```
[ ] bug report
[ ] feature request
[ /] support request
```

I use Angular 5 with angular-l10n version 4.1.4 with webpack,
IDE: Visual Studio Code
OS: MasOS 

Thank you,

**Comment by robisim74** [comment]
It's weird... which version of rxjs are you using?

**Comment by nopmania** [comment]
I use rxjs version 5.5.6.

**Comment by robisim74** [comment]
From rxjs 5.5.0 `toPromise` is a method of observable, so the error is weird if you are using 5.5.6 (did you recently update it? maybe a cache problem?)

Could you provide a way to reproduce the error?

Thanks

**Comment by nopmania** [comment]
I will create the project from ground-up again and let you know the result.

Thank you very much for your suggestion.

**Comment by nopmania** [comment]
I setup AspNetCore2 with Angular5 and integrate angular-l10n from ground up and everything smooth and i can with language.

I think, it have some conflicts in javascript packages, but I'm not sure which packages is the problem.

I install javascript packages from package.json (change package version and run npm install again and again)  until no warning anymore and start to include angular-l10n. 

Thank you very much.

**Comment by robisim74** [comment]
Hi @nopmania,

yes it is a known issue the caching of packages (especially in ASP.NET core projects). Next time you have the same problem, I suggest you:
- update npm to the latest version
- run `npm cache verify`
- remove manually `node_modules` & `package-lock.json`
- `npm install`

Thanks for reporting. Greetings
