### ISSUE TITLE
How can I use the currency, decimal in typescript 

### ISSUE THREAD

**Issue by nikhilsarvaiye** [robisim74/angular-l10n#167]
Hi I really liked this library.

I am still trying to find how to transpile/convert the currency, decimal in typescript/code using API.
Like we do for local string using Translation Service?

**Comment by robisim74** [comment]
Hi @nikhilsarvaiye,

do you mean this? https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#getting-the-translation-in-component-class > _DATES & NUMBERS_

**Comment by nikhilsarvaiye** [comment]
yes, i looked at like, its nice.
My question is if I have a value, 1234156.567
the currency pipe will transform it to $1,234,156.57
But If want like including thousand suffix, is there any way to do that?

so the output should look like this 
$1.2 M

**Comment by robisim74** [comment]
No, there isn't. You should do some manipulation, something like this:

```
let num: number = 1234156.567;

num = num / (1000000);

let value: string = this.pipe.transform(num, this.locale.getDefaultLocale(), '1.1-1') + " " + this.translation.translate('MILLION'); // MILLION will be M localized or other
```

Greetings

**Comment by nikhilsarvaiye** [comment]
anyway thnx, I extended this pipe to create own for thousand suffix, thnx for response
