### ISSUE TITLE
Possible to use pipes and params without lang parameter?

### ISSUE THREAD

**Issue by k-vekos** [robisim74/angular-l10n#168]
Is it possible to use a `translate` pipe _with_ parameters without having to provide the `lang` parameter?

In the user guide it gives this example:

```
{{ 'User notifications' | translate:lang:{ user: username, NoMessages: messages.length } }}
```

In my app I tried to use:

```
{{ 'User notifications' | translate:{ user: username, NoMessages: messages.length } }}
````

But it acts like my given translation key does not exist. Is this not an intended functionality?

**Comment by robisim74** [comment]
> Is it possible to use a translate pipe with parameters without having to provide the lang parameter?

No, it is not possible.

Greetings
