### ISSUE TITLE
[question] How to set currency in tag instead of using default one?

### ISSUE THREAD

**Issue by JTOne123** [robisim74/angular-l10n#169]
Hi there, I have a little question

Here is default currency by user locale
<span l10nCurrency="1.2-2" [symbol]="true">{{delivery.basePrice}}</span>

But I need for special cases insert predefined currency
<span l10nCurrency="1.2-2" [symbol]="true" [currency]="delivery.currencyCode">{{delivery.basePrice}}</span>

Is there available this feature?

**Comment by robisim74** [comment]
@JTOne123 You can't use a specific _defaultLocale_ or _currency_ with directives: you shoud use pipes, which accepts as arguments _defaultLocale_ and _currency_: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes

Alternatively, If you need only the currency symbol, you have also the following method of `LocaleService` class:

`getCurrencySymbol(currencyDisplay?: 'code' | 'symbol' | 'name', defaultLocale?: string, currency?: string): string`

**Comment by JTOne123** [comment]
thank you for your answer!

yep, getCurrencySymbol helps, but I prefer to use like pipes

***

And it doesn't clear for me, how to write it correctly

it does not work at all
{{ myvalue | l10nCurrency:defaultLocale:currency:'symbol':'1.2-2' }}

I need something

{{ myvalue | l10nCurrency:defaultLocale:'USD':'symbol':'1.2-2' }}

**Comment by robisim74** [comment]
Yes, the second one should do the trick: but keep in mind that the currency symbol is influenced by the `defaultLocale`. So for example, number 1000 will be shown:

in `en-US`:
`$1,000`
in `it-IT`:
`1.000 US$`

**Comment by JTOne123** [comment]
yes, it's ok, I know about it

But I don't know how to do make it works

What is here wrong?
{{ myvalue | l10nCurrency:defaultLocale:'USD':'symbol':'1.2-2' }}

```
compiler.es5.js:1694 Uncaught Error: Template parse errors:
The pipe 'l10nCurrency' could not be found ("


                        <td><span>{{[ERROR ->]detail.price  | l10nCurrency:defaultLocale:'USD':'symbol':'1.2-2'}}</span></td>
                    "): ng:///AppModule/OrdersComponent.html@44:36
```

**Comment by robisim74** [comment]
You have to import `LocalizationModule` (and not `TranslationModule`) in you module. You need to use also the `defaultLocale` decorator in your component.

**Comment by JTOne123** [comment]
In my app.module.ts already exists 

![image](https://user-images.githubusercontent.com/3457140/36142700-8822d420-10b1-11e8-88cd-13c2cd465ee9.png)

Also, I found this example https://github.com/robisim74/angular-l10n-sample/blob/57404b32076aae3c64623109dc5e8ff1f39c74eb/src/app/list/list.component.ts

Then I added  @DefaultLocale() defaultLocale: string;

But nothing works

**Comment by robisim74** [comment]
@JTOne123 Which versions of this library and Angular are you using? In your AppModule, the configuration is missing as in v3 of this library.

Configuration for latest version and Angular 5: https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization

Configuration for v3 and Angular 4: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/quick-start.md#3

**Comment by JTOne123** [comment]
I'm using Angular4 with the latest library

The v3 presents in my appmoudule
![image](https://user-images.githubusercontent.com/3457140/36143819-d38dc61a-10b4-11e8-9775-43f92a480da5.png)

**Comment by robisim74** [comment]
@JTOne123 you are using the v3 (old version) of this library: in any case that's not related to this issue. If you have problem to configure the library, please open a new issue following the instructions of the issue template and provide the versions you are using.

You can also find the links for the docs of each version in the README.
