### ISSUE TITLE
[Question] Best practice to implement browser language detection

### ISSUE THREAD

**Issue by tanandy** [robisim74/angular-l10n#172]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ x] support request
```

**Question**

Hello, can you provide more details about browser detection
https://robisim74.github.io/angular-l10n/spec/configuration/#getting-browser-language

I need to write a simple app that displays based on langage browser
if no langage found, i just set a default langage (i just need translation module not intl currently)
i succeed in writing some logical but i would like to know the better way to implement this

app.module.ts
```
const l10nConfig: L10nConfig = {
  locale: {
      languages: [
          { code: 'en', dir: 'ltr' },
          { code: 'fr', dir: 'ltr' }
      ],
      storage: StorageStrategy.Cookie
  },
  translation: {
      providers: [
          { type: ProviderType.Static, prefix: './assets/locale-' }
      ],
      caching: false,
      composedKeySeparator: '.',
      missingValue: 'No key',
      i18nPlural: true
  }
};`
````

app.component.ts
```
export class AppComponent implements OnInit, OnDestroy {
  title = 'app';

  constructor(public locale: LocaleService, public translation: TranslationService) { }

  ngOnInit(): void {
    const browserLang = this.locale.getBrowserLanguage();
    const acceptedLang = this.locale.getAvailableLanguages();

    if (acceptedLang.indexOf(browserLang) > -1) {
      this.locale.setCurrentLanguage(browserLang);
    } else {
      this.locale.setCurrentLanguage('fr');
    }
  }
  ngOnDestroy(): void { }

}
```

**Comment by robisim74** [comment]
@tanandy I added this explanation (https://robisim74.github.io/angular-l10n/spec/configuration/#getting-browser-language) to explain how the library works (see https://github.com/robisim74/angular-l10n/issues/170). You do not have to do anything: you just have to set up:

```
  locale: {
      languages: [
          { code: 'en', dir: 'ltr' },
          { code: 'fr', dir: 'ltr' }
      ],
      language: 'fr', // default language if the browser language is not found
      storage: StorageStrategy.Cookie
  },
```

and the _library_ will **automatically** try:

```
the library tries to get the language from the storage
or tries to get the language from the browser
or uses the language set in the configuration
```

Your `app.component.ts` is useless.

I hope it is clear.

Greetings

**Comment by tanandy** [comment]
Hello, 

yes, i knew that logic in my app was useless and forgot langage in that part of configuration since example was provided with defautlocale.
maybe you could provide more code samples as you did above in the doc even i recognize its really easy when its written.

Thanks a lot :+1:
