### ISSUE TITLE
Requesting help with usage in a reusable component package

### ISSUE THREAD

**Issue by nicovanbelle** [robisim74/angular-l10n#173]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```

Hi, I've built myself a reusable component library/package (_so separately packaged and present in node_modules of my parent application_) and I'm trying to get the translations to work using `directives` and/or `pipes`. The actual angular-l10n module configuration comes from the parent application. I only added your library as a peerDependency in this component module.

- If I use the `TranslationService` in my package, everything works like a charm.
- If I use a directive (e.g. `<h3 l10nTranslate>Title</h3>`), it does not do anything. 
- If I use a pipe (e.g. `<h3>{{ 'Title' | translate:lang }}</h3>`), it tells me; _Error: Template parse errors: The pipe 'translate' could not be found_

## Reusable component configuration

**Module**

```typescript
import {CommonModule} from '@angular/common';
import {ModuleWithProviders, NgModule} from '@angular/core';
import {InternalConfigurationComponent} from './internal-configuration.component';

@NgModule({
    imports: [
        CommonModule
    ],
    declarations: [
        InternalConfigurationComponent
    ],
    exports: [
        InternalConfigurationComponent
    ]
})
export class InternalConfigurationModule {

    static forRoot(): ModuleWithProviders {
        return {
            ngModule: InternalConfigurationModule,
            providers: []
        }
    }

}
```

**Component**

```typescript
import {Component, OnDestroy, OnInit, SkipSelf} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import {Language, LocaleService, TranslationService} from 'angular-l10n';
import {Subscription} from 'rxjs/Subscription';

@Component({
    templateUrl: './internal-configuration.component.html',
    styleUrls: ['./internal-configuration.component.less']
})
export class InternalConfigurationComponent implements OnDestroy {

    @Language() lang: string;

    private translationChangeSubscription: Subscription;

    constructor(public locale: LocaleService, public translation: TranslationService) {
    }

    selectLanguage(language: string): void {
        this.locale.setCurrentLanguage(language);
    }

    ngOnDestroy(): void {
        if (!this.translationChangeSubscription.closed) {
            this.translationChangeSubscription.unsubscribe();
        }
    }

}
```

## Parent application configuration

**Shared Module**

```typescript
const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      {code: 'en', dir: 'ltr'},
      {code: 'nl', dir: 'ltr'},
      {code: 'fr', dir: 'ltr'}
    ],
    language: 'en',
    storage: StorageStrategy.Session
  },
  translation: {
    providers: [
      {type: ProviderType.Static, prefix: './assets/locales/locale-'},
      {type: ProviderType.Static, prefix: './assets/locales/internal-config/locale-'}
    ],
    caching: true,
    missingValue: ((missing_key) => missing_key)
  }
};

@NgModule({
  imports: [
    CommonModule,
    TranslationModule.forRoot(l10nConfig), //<-- import angular-I10n module
  ],
  declarations: [],
  exports: [
    CommonModule,
    FormsModule
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class SharedModule {
  constructor(public l10nLoader: L10nLoader) {
    this.l10nLoader.load();
  }
}

```

**Config Module where component is used**

```typescript
@NgModule({
  imports: [
    SharedModule, //<-- import shared module where angular-I10n module is configured
    ConfigurationRoutes,
    InternalConfigurationModule.forRoot() //<-- import reusable component 
  ],
  declarations: [
    ConfigurationComponent
  ]
})
export class ConfigurationModule {
}

```

In a normal application, one would simply import the shared module into the component module and bob's your uncle. Unfortunately this is not possible and I'm not sure how to go from here. It's likely to be something very simple but I've come to a point where I must admit I need some help to get things working.. 

Kind regards,
Nico

**Comment by robisim74** [comment]
Hi @nicovanbelle,

when you create a `SharedModule`, you must import and export the modules. So you should change:

```
  exports: [
    CommonModule,
    FormsModule,
    TranslationModule // This re-export the pipes and the directives of the library
  ],
```

To understand how the library works see the `TranslationModule`: https://github.com/robisim74/angular-l10n/blob/master/src/modules/translation.module.ts

However, in my opinion, the logic you are using is not correct: if you set the configuration of this library in a shared module, every time you will call the shared module Angular will try to create a new instance of the classes of the library. So, I think, you shoud set up the configuration in root module, and in the shared module only import and export the `TranslationModule` without calling the `forRoot` method.

Working with modules in a package is not the same as working with modules in an app. Personally, I think that a package should only have root modules.

Hope this helps.

Greetings

**Comment by nicovanbelle** [comment]
Hi Roberto,

Let me first say, I really, really appreciate you take the time to help me.

And to put it in correct lexicon, I'm indeed trying to create (my very first) feature module. 
I took your advice and moved away from the shared library. It makes perfect sense that it was a bad idea. I now tried to get things to work in almost every single combination of imports/exports (using both `TranslationModule.forRoot(l10nConfig)` and plain `TranslationModule`) and forRoot/forChild module loaders. I just keep running into the very same issue over and over again.

As you put in the documentation that it's best for feature modules to use a separate service I now try to configure it with forChild. Unfortunately, no http requests are being fired to load the translations + directives and pipes still don't work. I think it is the way I load my component library into my parent application.

### Reusable component configuration

```typescript
import {CommonModule} from '@angular/common';
import {NgModule} from '@angular/core';
import {InternalConfigurationComponent} from './internal-configuration.component';
import {L10nConfig, L10nLoader, ProviderType, StorageStrategy, TranslationModule} from 'angular-l10n';

const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      {code: 'en', dir: 'ltr'},
      {code: 'nl', dir: 'ltr'},
      {code: 'fr', dir: 'ltr'}
    ],
    language: 'en',
    storage: StorageStrategy.Session
  },
  translation: {
    providers: [
      {type: ProviderType.Static, prefix: './assets/locales/internal-config/locale-'}
    ],
    missingValue: ((missing_key) => missing_key)
  }
};

@NgModule({
  imports: [
    CommonModule,
    TranslationModule.forChild(l10nConfig),
  ],
  declarations: [
    InternalConfigurationComponent
  ],
  exports: [
    InternalConfigurationComponent
  ]
})
export class InternalConfigurationModule {
  constructor(public l10nLoader: L10nLoader) {
    this.l10nLoader.load();
  }
}

```

The final packaged directory looks like this;
```
├── assets/
│   ├── locales/
│       ├── locale-en.json
│       ├── locale-fr.json
│       ├── locale-nl.json
│   ├── index.d.ts
│   ├── index.js
│   ├── internal-configuration.component.d.ts
│   ├── ngx-internal-config.d.ts
│   ├── ngx-internal-config.metadata.json
│   ├── ngx-internal-config.umd.js
│   ├── package.json
└── └── README.MD
```

### Parent Application

I've created [a dummy project here](https://stackblitz.com/edit/angular-l10n-sw9ljw) so it is more easy for you to gain insight in how my modules are loaded.

I think my error is in the way I load the feature module but unfortunately I cannot see the mistake I've made.

Thank you in advance,

Kind regards,
Nico

**Comment by robisim74** [comment]
@nicovanbelle Sorry, but I don't understand what you are trying to do:
- why do you have a configuration of this library in the package and also in the host app?
- how the library should load json files? to make an http request, there must be an address ... what is the address of the files inside the package? (see also this issue: https://github.com/robisim74/angular-l10n/issues/136)

There are a lot of way (and problems: see also https://github.com/robisim74/angular-l10n/issues/146) in implementing a library like this in another library.

If you have time to create a repo (simplified) of your library I can try to see a solution.

**Comment by robisim74** [comment]
I'm closing this issue due to lack of repro. Feel free to reopen if you need. Greetings
