### ISSUE TITLE
display of symbols for some currencies is different in different browsers.

### ISSUE THREAD

**Issue by harika13** [robisim74/angular-l10n#174]
**I'm submitting a...**
```
[ *] bug report
[ ] feature request
[ *] support request
```
I am trying with this to check the display of various currencies.

StackBlitz Template: https://stackblitz.com/edit/angular-l10n
with below data

<button (click)="selectLocale('cs', 'CZ', 'CZK', 'America/Los_Angeles');">1</button>
<button (click)="selectLocale('da', 'DK', 'DKK', 'Europe/London');">2</button>
<button (click)="selectLocale('il', 'IL', 'ILS', 'Europe/Rome');">3</button>
<button (click)="selectLocale('en', 'US', 'HKD', 'Europe/Rome');">4</button>
<button (click)="selectLocale('ja', 'JA', 'JPY', 'Europe/Rome');">5</button>
<button (click)="selectLocale('en', 'IN', 'INR', 'Europe/Rome');">6</button>
<button (click)="selectLocale('IT', 'IT', 'USD', 'Europe/Rome');">7</button>

The requirement is that the application default locale can be different from Currency Code. 
Ex: I am an user running the application from U.S but i wanted to see the currencies in INR.

1) Issue one 
Button 2 for IE - kr. 1.804,06   (places currency symbol on left hand side)
Button 2 for Chrome - 9.836,82 kr.  (places currency on right hand side)

2) Issue two
Button 4 for IE - $1,804.06  (HK$ is not displayed as in chrome - not consistent across browsers)
Button 4 for Chrome -  HK$9,836.82

3) Issue three
Button 7 for IE - $ 1.804,06
Button 7 for Chrome - 9.836,82 USD

Is A2L completely compatible with IE? Seems like Chrome is displaying correct symbols and formats.
 
Where can i find the information on which locale, language code and currency codes need to be passed and how the library works with it?

**Specifications: Angular version - 2.4.10, library version-2.0.11, environment, browser-IE, Chrome, Firefox**

**Comment by robisim74** [comment]
Hi @harika13,

- This library uses _Intl Apis_. Please see the docs: https://robisim74.github.io/angular-l10n/spec/configuration/#intl-api
- Stackblitz template doesn't have _polyfills_: so should try to use a local app to test real inconsistencies
- If you are using the old version of the library v2.0.11 for Angular v2, it used Intl APIs through Angular 2 official pipes
- From Angular v5, official Angular pipes use CLDR data to avoid inconsistencies, while this library continues to use Intl APIs

Greetings

**Comment by harika13** [comment]
Hi Roberto,
I have added polyfills and checked. Seems like in IE,  country default locale as Prefix doesn't seem to be displayed.
Ex: for HK$ it just gives $
for CN¥ it just give ¥
Is it known issue with Angular 2 version library?

**Comment by robisim74** [comment]
Yes, Angular team switched to CLDR data from Angular v5 also to avoid this kind of inconsistencies. I'm sorry, but I can not do anything about it. If viewing in IE is so important, you need to find custom solutions.
