### ISSUE TITLE
Remove suffix from WebAPI path

### ISSUE THREAD

**Issue by normandjulian** [robisim74/angular-l10n#177]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[*] support request
```

**Expected behavior**
I use a back-end service to get the translated values. Here is my configuration
```
const l10nConfig: L10nConfig = {
  locale: {
      ...
  },
  translation: {
      providers: [
          { 
            type: ProviderType.WebAPI,
            path: 'http://.../translations/'
          }
      ],
   ...
  }
};
```

To have the translations, I ask the uri '/translations' and with the user session, the service send me back the translations depending of the user language.
So I don't have to mind about adding the suffix (/en, /fr, ...). If I do add this suffix, the service send me back a 404 error.

**Actual behavior**
In this actual setup, the uri, are always ending with the language code : 

- /translations/en
- /translations/fr
- ...

So my API Service send me back a 404 error.

Is there a way to remove the suffix ? 

**Specifications: Angular version, library version, environment, browser**
I'm using :

- Angular 5.2.0
- l10n 4.1.5
- Angular CLI 1.7.0

**Comment by robisim74** [comment]
Hi @normandjulian,

yes, you can use a custom provider: https://robisim74.github.io/angular-l10n/spec/configuration/#using-a-custom-provider

Basically, you can copy the `TranslationProvider ` class (https://github.com/robisim74/angular-l10n/blob/master/src/services/translation-provider.ts) and change only this line:

```
case ProviderType.WebAPI:
                url += args.path + language;
```

removing the `language`.

Greetings

**Comment by normandjulian** [comment]
Hi @robisim74 ,

It works well, thank you.

For more informations, i created a provider called **translation-provider.ts** :
```
import ...

@Injectable() export class CustomTranslationProvider implements TranslationProvider {
   private cache: { [key: string]: Observable<any> } = {};
   constructor(
        @Inject(TRANSLATION_CONFIG) private configuration: TranslationConfig,
        private http: HttpClient) { }

    public getTranslation(language: string, args: any): Observable<any> {
        ... 
        switch (args.type) {
            case ProviderType.WebAPI:
                url += args.path;
                ...
        }
        ...
    }

    private caching(key: string, request: Observable<any>): Observable<any> {
        ...
    }
}
```

And in my module.ts :
```
@NgModule({
  ...
  imports: [
    ...
    TranslationModule.forRoot(
      l10nConfig,
      { translationProvider : CustomTranslationProvider}
    )
  ],
  ...
})
```

**Comment by robisim74** [comment]
Thanks for sharing. Greetings
