### ISSUE TITLE
Date and Time formats displaying different results in different browsers

### ISSUE THREAD

**Issue by harika13** [robisim74/angular-l10n#178]
**I'm submitting a...**
```
[* ] bug report
[ ] feature request
[ ] support request
```
Hi,
From sample app i observed different results for Date and time for 'es-US' and 'zh-CN' respectively with respect to IE browser.

When i passed these parameters

<button (click)="selectLocale('es', 'US', 'EUR', 'Europe/London');">United Kingdom</button>
<button (click)="selectLocale('zh', 'CN', 'YEN', 'Europe/Rome');">Italia</button>

IE 'és-US' : mar 08, 2018 3:18:14 PM    (not displayed in Spanish)
Chrome 'es-US' : 8 de marzo de 2018 3:17:36 p. m.

IE 'zh-CN' : 2018年3月月8日 15:19:30    (24 hour format returned)
Chrome: 'zh-CN' : 2018年3月8日 下午4:20:03

Am i passing incorrect parameters?

With currencies, 

does the translation locale should always be same as localization locale?
I have a scenario where my locale will be 'en-US' and application loads in 'English' but I need currencies to be displayed based on user selected value. If user selects currency in application as 'JPY' i need to display '￥' even though my application locale remains en-US. But inorder to display currency symbol we need to pass language code and countrycode along with currency code. If we set locale at this point to display right currency symbol my application reloads in Japanese language. This should not happen. 
How can we acheive displaying currency symbol just by passing currency code without effecting translations?

StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version 2, library version 2.0.11, environment, browser IE, IE Edge**

**Comment by robisim74** [comment]
Hi @harika13,

I already explained you (https://github.com/robisim74/angular-l10n/issues/174) that this library uses Intl API and that inconsistences across browsers are not related to this library. Then, you are using mixed locales, e.g. `'zh', 'CN', 'YEN', 'Europe/Rome'`: Chinese language, Japanese currency and Rome timezone (?), so the inconsistences are normal becuase it's not a standard.

About the currencies, you don't have to change the `DefaultLocale` if you don't need it:

```
selectCurrency(currency: string: void {
    this.locale.setCurrentCurrency(currency);
}
```

So the language and the format of numbers do not change: only the currency changes.

If you need, you have also the `getCurrencySymbol` method of `LocaleService`.

Greetings
