### ISSUE TITLE
APP_INITIALIZER is used incorrectly in the sample project

### ISSUE THREAD

**Issue by rbluethl** [robisim74/angular-l10n#179]
Hey!

This is not really an issue itself, but I would like to point out, that you should return a function that returns a Promise for the APP_INITIALIZER function. In your sample app, you return a synchronous function that can not be awaited by the APP_INITIALIZER process and thus, translations may not be loaded correctly.

So instead of
```
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load();
}
```

you should use
```
export function initL10n(l10nLoader: L10nLoader): () => Promise<void> {
  return (): Promise<void> => l10nLoader.load();
}
```

... so that the translations are loaded reliably. (It occurred to us, that translations were not loaded correctly and translation keys were shown all around the UI instead).

Wrong usage:
https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization

Reference:
https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e

Apart from that, we're successfully using your library. Very handy! Thanks.

**Comment by robisim74** [comment]
Hi @rbluethl,

I don't see any functional difference: you are only typing the function (ok, it's right), but it is always a function, and always `l10nLoader.load()` returns a Promise. Typing is lost during compilation.

**Comment by rbluethl** [comment]
Hey @robisim74 and thanks for your response.

I'm afraid it does make a difference.
I created a [sample ](http://www.typescriptlang.org/play/index.html#src=function%20initL10nSync()%3A%20Function%20%7B%0D%0A%20%20%20%20return%20()%20%3D%3E%20console.log(%22SYNC%22)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20initL10nAsync()%3A%20()%20%3D%3E%20Promise%3Cvoid%3E%20%7B%0D%0A%20%20%20%20return%20()%3A%20Promise%3Cvoid%3E%20%3D%3E%20%7B%20return%20new%20Promise(resolve%20%3D%3E%20console.log(%22ASYNC%22))%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isPromise(obj%3A%20any)%3A%20obj%20is%20Promise%3Cany%3E%20%7B%0D%0A%20%20%2F%2F%20allow%20any%20Promise%2FA%2B%20compliant%20thenable.%0D%0A%20%20%2F%2F%20It's%20up%20to%20the%20caller%20to%20ensure%20that%20obj.then%20conforms%20to%20the%20spec%0D%0A%20%20return%20!!obj%20%26%26%20typeof%20obj.then%20%3D%3D%3D%20'function'%3B%0D%0A%7D%0D%0A%0D%0Aconsole.log(%22IS%20PROMISE%20SYNC%22%2C%20isPromise(initL10nSync()()))%3B%0D%0Aconsole.log(%22IS%20PROMISE%20ASYNC%22%2C%20isPromise(initL10nAsync()()))%3B) where you can see that the "sync" approach won't be executed asynchronously.

The `isPromise` function is used by the Angular APP_INITIALIZER process to validate whether or not the given function returns a Promise.

References:
https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/src/application_init.ts
https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/src/util/lang.ts

Thanks for looking into it.

**Comment by robisim74** [comment]
@rbluethl,

in your sample, `initL10nSync` function is not returning a Promise, but a simple function: so it is normal that `isPromise` returns `false`.

Instead the following function:

```
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load();
}
```

returns a Promise, because `l10nLoader.load` method returns a Promise: https://github.com/robisim74/angular-l10n/blob/master/src/services/l10n-loader.ts#L22

You could also remove `Function` as type:

```
export function initL10n(l10nLoader: L10nLoader) {
    return () => l10nLoader.load();
}
```
because as you can see in your example, after the transpilation in JavaScript, types are lost.

**Comment by rbluethl** [comment]
Hey @robisim74,

you‘re right, I obviously got that wrong. Thanks for pointing me into the right direction. However, I‘m still wondering why the first approach caused troubles in our case. I‘ll have to look into that again.

Anyway, thanks for taking the time to review my mistake and keep up the good work.

Ronald

**Comment by robisim74** [comment]
No problem. Your proposal is correct, and adding types is a best practice. What i meant, it is weird that it causes troubles in your case. However I will keep it in mind.

Greetings
