### ISSUE TITLE
Angular RC6 released

### ISSUE THREAD

**Issue by AHelper** [robisim74/angular-l10n#18]
Another version just arrived. Can this get updated to RC6?

**Comment by bogomips** [comment]
+1

**Comment by robisim74** [comment]
Yes... I'm studying the changes, and then I'll update.

**Comment by robisim74** [comment]
I released v0.10.0 compatible with rc.6. Please see [releases](https://github.com/robisim74/angular2localization/releases) to know all the changes. Greetings!
