### ISSUE TITLE
shows the keys in some occasions [Chrome]

### ISSUE THREAD

**Issue by keyfu** [robisim74/angular-l10n#180]
I am using angular-l10n. Sometimes the translation does not load it and the browser (Chrome) shows the key. For example.

{
     "main": {
         "processing": "Por favor, espere ...."
     }
}

In my html:
<small l10nTranslate> main.processing </ small>

The browser shows main.processing, sometimes it shows it correctly.

My configuration:
`
// Advanced initialization.
@Injectable()
export class LocalizationConfig {

    constructor( public locale: LocaleService, public translation: TranslationService) { }

    load(): Promise<any> {
        this.locale.addConfiguration()
            .addLanguages(['en', 'es'])
            .setCookieExpiration(30)
            .defineLanguage('es')
            .defineDefaultLocale('es', 'CL')
            .defineCurrency(environment.currency.currency);
        this.locale.init();

        this.translation.addConfiguration()
            .addProvider('./assets/i18n/locale-');
         
        let promise: Promise<any> = new Promise((resolve: any) => {
            this.translation.translationChanged.subscribe(() => {
                resolve(true);
                
            });
        });
         this.translation.init();
        return promise;
    }
}

// AoT compilation requires a reference to an exported function.
export function initLocalization(localizationConfig: LocalizationConfig): Function {
    return () => localizationConfig.load();
}

@NgModule({
    bootstrap: [AppComponent],
    declarations: [
        ThemeComponent,
        AppComponent,
    ],
    imports: [
        BrowserModule,
        // HttpClientModule,
        CoreModule.forRoot(),
        LocalizationModule.forRoot(), // New instance of TranslationService.
        LayoutModule,
        AppRoutingModule,
        ThemeRoutingModule,
        AuthModule,
        NotFoundModule,
        InternalServerErrorModule,
        TagInputModule,
        BrowserAnimationsModule,
        FormsModule,
        ReactiveFormsModule,
    ],
    providers: [
        LocalizationConfig,
        { provide: LOCALE_ID, useValue: 'es-CL' },
        {
            provide: APP_INITIALIZER,
            useFactory: initLocalization,
            deps: [LocalizationConfig],
            multi: true
        },
        LoadaltairService,
    ],
    exports: [

    ]
})
export class AppModule {

}`

**Comment by robisim74** [comment]
Hi @keyfu,

please, format correctly the code in your issue, and provide all the info requested in the issue template, like the version of packages you are using.

**Comment by keyfu** [comment]
The question is not complicated. Is the next. I am using angular version 4 and angular-l10n version 3.5.2. Sometimes when I load my page the main.processing is shown, when the value of that key should be shown ("Please wait ..."). I read that Chrome loads the page first and then the json files. That is, when I call the method this.translation.init () it must wait for the json files to load and then display the page. You can tell me how to solve that problem. My English is not very good.

**Comment by robisim74** [comment]
Your configuration is for angular-l10n v2 and Angular v2. If you are using Angular v4, please see the correct branch and docs: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/quick-start.md#3

Greetings
