### ISSUE TITLE
override existing translation for a language with json object

### ISSUE THREAD

**Issue by hayha06** [robisim74/angular-l10n#185]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Specifications: Angular version, library version, environment, browser**
Angular 4.4.6  angular-l10n 3.5.2

Hello, 

I'm trying to override with a json object a translation for a specific language that was already loaded at app initialization.

Here's my configuration : 

app.module.shared.ts:
```javascript
export function initLocalization(localizationConfig: LocalizationConfig) {
    return () => localizationConfig.load();
}
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        CommonModule,
        HttpClientModule,
        HttpModule,
        WheelModule,
        LocalizationModule.forRoot(),
        RouterModule.forRoot([
            { path: '', component: AppComponent },
            { path: 'wheel', loadChildren: () => WheelModule }
        ]),
    ],
    providers: [LocalizationConfig,
        {
            provide: APP_INITIALIZER,
            useFactory: initLocalization,
            deps: [LocalizationConfig],
            multi: true
        }]
})
export class AppModuleShared {

}

```

localizationConfig.service.ts
```javascript
import { Injectable, Inject } from '@angular/core';
import { LocaleService, TranslationService } from 'angular-l10n';
import { LanguageService } from '../services/language.service';

@Injectable() export class LocalizationConfig {

    constructor( @Inject('BASE_URL') private originUrl: string, public locale: LocaleService, public translation: TranslationService, public languageService: LanguageService) { }

  async load(): Promise<void> {
    this.locale.addConfiguration()
      .addLanguages(['en', 'fr'])
      .setCookieExpiration(30)
          .defineDefaultLocale('en', 'US');
      this.locale.init();

    this.translation.addConfiguration()
      .addProvider(`${this.originUrl}assets/i18n/`);

      let promise: Promise<any> = new Promise((resolve: any) => {
          this.translation.translationChanged.subscribe(() => {
              resolve(true);
          });
      });

      this.translation.init();

      return promise;
  }

}
```

wheel.module.ts
```javascript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { LocalizationModule } from 'angular-l10n';
import { WheelComponent } from '../components/wheel/wheel.component';

@NgModule({
    declarations: [
        WheelComponent,
    ],
    imports: [
        CommonModule,
        LocalizationModule.forChild(),
        RouterModule.forChild([
            { path: 'wheel', component: WheelComponent }
        ])
    ]
})
export class WheelModule {
}
```

wheel.component.ts
```javascript
import {Component, OnInit} from '@angular/core';
import { Language, LocaleService, TranslationService } from 'angular-l10n';

@Component({
    selector: 'app-wheel',
    templateUrl: './wheel.component.html',
    styleUrls: ['./wheel.component.css'],
})
export class WheelComponent implements OnInit {
    @Language() lang: string;

    constructor(public localeService: LocaleService,public translationService: TranslationService) {
    }

    ngOnInit() {
        // I get jsonData from API here

        // So i try this to load the new translation for english but don't work
        this.translationService.addConfiguration()
            .addTranslation("en", jsonData);
        this.translationService.init();

    }
}
```

So I try to use the addTranslation method, but I think it works only on configuration, not after.
I also try to extend LocalizationService to have a new instance so I'm able to load a new translation but only from the construction and I don't have my data at this stage.
Currently I don't know what to try next, or if it's just possible to change translation data for one language after configuration.
Support will be apprecied, thank you

**Comment by robisim74** [comment]
Hi @hayha06,

basically you can't add a new translation after the configuration.

However, we need to know the purpose of what you are trying to do. I explain: your `WheelModule ` is lazy loaded, right? And you are creating a new instance of `LocalizationService`: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#5.1

The point is: the translation data of this new instance are empty: I don't think that you `jsonData` is loaded when you add it (`addTranslation("en", jsonData)`) if you are retrieving it from an API. You should add it using an `addWebAPIProvider`: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#2.4.3

In this way you will have a new instance of `LocalizationService` with the new translation data when your lazy loaded module will be loaded.

But keep in mind that you can't change another time the translation data if you don't change language.

I hope this helps.

Greetings

**Comment by hayha06** [comment]
Hi @robisim74, and thank you for your quick answer.

I tryied to lazy loaded the module but I was able to have a new instance of translationService only when I extends `Localization ` and add the `provider: [TranslationService]`  to the component. After that I was able to load a different translation but only in the constructor and not in the init method. But I need it to be initialized in the init method as I know what translation used only after a call to backend and I can't use a webApiProvider as the url is never the same.

In fact, what I'm trying to do is to have different configuration on the same module regarding the parameter used to access it : 

Let's imagine, I access the component with different parameter so I use this parameter to ask a backend api if I have custom json or not. And so depending on the result, I initialize the translation dynamically.

See this pseudo code : 
wheel.component.ts
```javascript
import {Component, OnInit} from '@angular/core';
import { Language, LocaleService, TranslationService } from 'angular-l10n';

@Component({
    selector: 'app-wheel',
    templateUrl: './wheel.component.html',
    styleUrls: ['./wheel.component.css'],
})
export class WheelComponent implements OnInit {
    @Language() lang: string;

    constructor(public localeService: LocaleService,public translationService: TranslationService) {
    }

    ngOnInit() {
		this.activatedRoute.queryParams.subscribe((params: Params) => {
			this.service.getService(params['serviceId']).subscribe(async (data) => {
				//Depending on data result :
				
				//service 1 has a custom json for english
				// --> en : use custom json
				// --> fr : use root json
				
				this.translationService.addConfiguration()
					.addTranslation("en", jsonData)
					.addProvider(`${this.originUrl}assets/i18n/`);
				this.translationService.init();
				
				//service 2 has a custom json for french
				// --> en : use root json
				// --> fr : use custom json
				
				this.translationService.addConfiguration()
					.addTranslation("fr", jsonData)
					.addProvider(`${this.originUrl}assets/i18n/`);
				this.translationService.init();
				
				//service 3 has not custom json
				// --> en : use root json
				// --> fr : use root json

				this.translationService.addConfiguration()
					.addProvider(`${this.originUrl}assets/i18n/`);
				this.translationService.init();				
			});
		
		});
    }
}
```

Also it would be great if a custom json has missing keys so the key value from the root json will be used.

I hope you understand my use case better now, if not, don't hesitate to ask me more detail.

Thank you again for your help on this.

**Comment by robisim74** [comment]
Hi @hayha06,

there are some things I do not understand:

- If you use `LocalizationModule.forChild()` you should have a new instance of the service, and you don't need to extend it: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#5.1
- There should be no difference between _constructor_ and _OnInit_ method

Said this, you can't use at the same time Direct Loading (`addTranslation`) and Asynchronous Loading (`addProvider`): Asynchronous Loading wins. So I think you shoud use a custom provider to call the API: https://github.com/robisim74/angular-l10n/blob/angular_v4/doc/spec.md#2.4.4

However, also if you solve this problem (and I think it should work), it will work only the first time you load the sub-module: next times you need to change language to get it works: the library is built in this way because it uses pure pipes.

**Comment by hayha06** [comment]
Hi @robisim74,

After more research, I find out that my module was not really lazy loaded. That why I got unexpected behavior.

After fixing the lazy loading, I got the behavior you explain and I'm now able to load different translation on the init method using a custom provider.

Thank you for your time spent to help me, I'm closing this issue now as the initial question was answered.

Just as extra information, here's how I fix the lazy loading : 

app.module.shared.ts
```javascript
export function initLocalization(localizationConfig: LocalizationConfig) {
    return () => localizationConfig.load();
}
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        CommonModule,
        HttpClientModule,
        HttpModule,
        WheelModule, // <-- remove this
        LocalizationModule.forRoot(),
        RouterModule.forRoot([
            { path: '', component: AppComponent },
            { path: 'wheel', loadChildren: () => WheelModule } // <-- change this 
            { path: 'wheel', loadChildren: './modules/wheel.module#WheelModule' } // <-- with this 
        ]),
    ],
    providers: [LocalizationConfig,
        {
            provide: APP_INITIALIZER,
            useFactory: initLocalization,
            deps: [LocalizationConfig],
            multi: true
        }]
})
export class AppModuleShared {

}
```

**Comment by daotoad** [comment]
FWIW, I am working on a project where we sometimes need to override translation based on a parameter other than language, such as `user_id`.  I'm using a custom TranslationProvider to request information from a special configuration service, then if needed apply any transformations to the existing lexicons.  

Of course I am not trying to change one or two components' translations, I am changing translation throughout the entire application.
