### ISSUE TITLE
json translations are not parsed correctly anymore?

### ISSUE THREAD

**Issue by pieterdegraeuwe** [robisim74/angular-l10n#186]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
translate a key 'foo.bar' which is defined in json as 
{
  "foo" : {
       "bar" : "some foobar translation"
   }
}

should return "some foobar translation"

**Actual behavior**
it returns 'No Key' (see plunkr)

**Steps to reproduce the behavior**
see plunker https://plnkr.co/edit/hHYIY0wkCwYqo4XSt0cf?p=preview
(I've added a foo.bar translation at the bottom)

**Comment by robisim74** [comment]
Hi @pieterdegraeuwe,

from v4 you must set the _composedKeySeparator_ you are using:

```
    translation: {
        ...
        composedKeySeparator: '.'
    }
```

See #184 #144 #142 

Greetings

**Comment by pieterdegraeuwe** [comment]
Indeed, it's working now. Pity I did'nt find the other related issues.
Thanks !
