### ISSUE TITLE
angular-l10n in angular v5 not changing text in browser

### ISSUE THREAD

**Issue by ishwaryanair** [robisim74/angular-l10n#187]
I am using  "angular-l10n": "^4.1.3" in my project and loaded the same way it is mentioned here https://stackblitz.com/edit/angular-l10n. But i am not seeing the change of text in UI, for example,

This is my html tag:
`<div l10nTranslate >
              Topogram
            </div>` 
in translation file, i have
`export const translationFR: any = {  
    "Topogram": "Topogramme"
}`
And my selected language is 'fr' loaded this way in app.module.ts,
import {HttpClientModule} from '@angular/common/http';
import { L10nConfig, L10nLoader, LocalizationModule, StorageStrategy, ProviderType } from 'angular-l10n';
import { translationEN, translationFR } from '../assets/i18n/i10n';

const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      { code: 'en', dir: 'ltr' },
      { code: 'fr', dir: 'ltr' }      
    ],
    defaultLocale: { languageCode: 'en', countryCode: 'US' },
    currency: 'USD',
    timezone: 'America/Los_Angeles',
    storage: StorageStrategy.Cookie
  },
  translation: {
    translationData: [
      { languageCode: 'en', data: translationEN },
      { languageCode: 'fr', data: translationFR }
    ],
    caching: true,
    missingValue: 'No key'
  }
};
export function initL10n(l10nLoader: L10nLoader): Function {
  console.log("i m here in L10nLoader");
  return () => l10nLoader.load();
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    LocalizationModule.forRoot(l10nConfig), 
    routing,
    CoreServicesModule.forRoot(backendConnectionConfig),
    FeaturesModule
  ],
   providers: [
    {
        provide: APP_INITIALIZER,
        useFactory: initL10n,
        deps: [L10nLoader],
        multi: true
    }],
  bootstrap: [AppComponent]
})
export class AppModule{
 }
In ui i still see Topogram only but i am expecting Topogramme. Please let me know if this issue is due to routing or something else?

**Comment by ishwaryanair** [comment]
I got the above issue sorted by using html tag with `<div> {{translation.translate('Topogram')}}</div>`

**Comment by robisim74** [comment]
@ishwaryanair That does not make sense: the `translate` method is intedend to be used in component, and not in the template, and it will call the method every change detection cycle.

Please follow the documentation, and try to compare your code with the provided samples in this repository.

If you have problems with the basic features of the library, please provide a repro.
