### ISSUE TITLE
Callback for switching language with webAPI

### ISSUE THREAD

**Issue by normandjulian** [robisim74/angular-l10n#189]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[*] support request
```
Hi, 
I'm stuck with a list displaying languages.
When the user change the language, the pipe **| translate** seems to be broken.
I think, it's because i'm using the WEBAPI provider and the new translations aren't reached yet.

Here is my HTML code
`{{'CVLanguageIso.' + language.locale | translate }}`

Here is my TS code when the user change the language in the list
`
// locale === 'fr' or 'it' ...
this.localeService.setDefaultLocale(locale);
`

Before switching language, I have the well translated value 'Français', 'English' ...

**Expected behavior**
The user select 'French', and I should have the result : **Français**

**Actual behavior**
Actually, I got the name of the key : **CVLanguageIso.fr**

**How I hot fixed it**
I put a **setTimeout** and redraw the component to display the language, but as I don't really know how long will take the request, i can't be sure of the time.

I tried to use the **defaultLocaleChanged** :
`
this.localeService.defaultLocaleChanged.subscribe(
      (res) => console.log(res);
    );
`
But it's triggered when the language is changed directly and not when the request is over.
So it doesn't fit to me.

Is there something like **defaultLocaleChanged** but to catch when the request is over ?

**Specifications: Angular version, library version, environment, browser**
**Angular** 5.2.0
**l10n** : 4.1.5

Thank you.

**Comment by robisim74** [comment]
Hi @normandjulian,

are you using the `translate `pipe correctly? The correct syntax is: `{{ 'Title' | translate:lang }}`, using the `@Language` decorator: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

To know when the request has been completed, you have the following method: `translationChanged(): Observable<string> `: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#getting-the-translation-in-component-class

I hope this helps.

**Comment by normandjulian** [comment]
Nice, that is definetly what I need.

> To know when the request has been completed, you have the following method: translationChanged(): Observable<string>: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#getting-the-translation-in-component-class

Thank you.

I do not use **lang**, but it look to use the defaultLanguage, and it's fine for me.
> are you using the translatepipe correctly? The correct syntax is: {{ 'Title' | translate:lang }}, using the @Language decorator: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages
