### ISSUE TITLE
Parameterized translations

### ISSUE THREAD

**Issue by AHelper** [robisim74/angular-l10n#19]
It would be beneficial to allow translations that require some dynamic values in them to be directly used with the `TranslatePipe` and `TranslateService`.  Looking around at what other projects offer, ng2-translation allows parameters to be used as substitutions in the translate pipe and RC6's i18n will use placeholders.

A proposed usage would be:

_en.json:_

```
{
  "UserNotifications": "{{ user }}, you have {{ numMessages }} new messages"
}
```

_HTML:_

```
<div>{{ "UserNotifications" | translate:lang:{ user: username, numMessages: messages.length } }}</div>
```

_Typescript:_

```
const params = {
  user: username,
  numMessages: messages.length
};
const translated = this.localizationService.translate("UserNotifications", params);
```

**Comment by robisim74** [comment]
Ok, thanks for the suggestion. I will implement this feature as soon as possible.

**Comment by robisim74** [comment]
I added the commit that allows you to use parameters.
If you want to test it, you can do so:
- Uninstall this library from your application
- Download this repository
- Follow the instructions of the README file to build the library and install it in your application

You can use:

```
<div>{{ "UserNotifications" | translate:lang:{ user: username, NoMessages: messages.length } }}</div>
```

and if you need, even the nested localization:

```
<div>{{ "UserNotifications" | translate:lang:{ user: username | translate:lang, NoMessages: messages.length | localeDecimal:defaultLocale:'1.2-2' } }}</div>
```

Please let me know if it works as you expect.

**Comment by AHelper** [comment]
Sorry for the delay, I finally got a chance to test this on a separate project.  This works as expected, thanks!

**Comment by robisim74** [comment]
Hi,

I have included this feature in the new version compatible with rc.7.

Greetings
