### ISSUE TITLE
Add fallback mechanism also for direct translation data

### ISSUE THREAD

**Issue by IlCallo** [robisim74/angular-l10n#190]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Expected behavior**
Fallback option for direct translation data

**Actual behavior**
No fallback feature is present

**Steps to reproduce the behavior**
For a really small library (a small Authentication GUI) I'd like to add direct data translation.
There is also the need to store and display the list of supported languages (with the language name, not the code).
With async translations it's possible to use the fallback provider and make it point to a "general.json" file with all strings which must be the same for all the languages (or the majority of them) but with direct data this option is not available.

Is it possible to add it?
Something like this

```typescript
translation: {
    translationData: [
        { languageCode: 'en', data: translationEN },
        { languageCode: 'it', data: translationIT },
        { fallback: translationFallback },
    ]
}
```

**Comment by robisim74** [comment]
Hi @IlCallo,

if you use Direct loading, the translation data are already merged in order. So just use a reverse order during the configuration:

```
translation: {
    translationData: [
        { languageCode: 'en', data: fallbackTranslation },
        { languageCode: 'en', data: translationEN },
        { languageCode: 'it', data: fallbackTranslation },
        { languageCode: 'it', data: translationIT }
    ]
}
```

The service merges the data in order: so if it doesn't find a key in `translationEN `or `translationIT`, it should use the key of `fallbackTranslation`.

**Comment by IlCallo** [comment]
Worked like a charm, thank you 😄
Even if having to duplicate the fallback declaration for every language can be bothersome after a while (like, 4+ languages supported).
Is it possible to add a wildcard selector in the languageCode for this kind of scenario?
something like
```
translation: {
    translationData: [
        { languageCode: '*', data: fallbackTranslation },
        { languageCode: 'en', data: translationEN },
        { languageCode: 'it', data: translationIT }
    ]
}
```

**Comment by robisim74** [comment]
I see.

The library is developed to make an associative access by the language code (for better performances): in the asynchronous loading the problem does not arise, because the data translation of a language are loaded one at a time, while in direct loading you have to repeat it.

At the moment, it's not planned to change this behavior.

**Comment by IlCallo** [comment]
Well, that settles it I guess :)
I was thinking about creating a '*' entry in the associative array and checking there if the language-specific translation is not present, but I'm not sure to have understood correctly what you tryed to explain, so I'll just repeat the fallback line.
Ty anyway for the package!
