### ISSUE TITLE
Not working on PRODUCTION build

### ISSUE THREAD

**Issue by antl3x** [robisim74/angular-l10n#192]
**I'm submitting a...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Work in production.

**Actual behavior**
None of the configurations are loaded in production.

**Steps to reproduce the behavior**
`ng build --prod --build-optimizer=false --aot --base-href "/"`

**Specifications: Angular version, library version, environment, browser**
Angular version: 6.0.0
Library version: 5.0.0

When we run `console.log(this._translation.getConfiguration());` to debug.

In our `ng serve` environment we see the configuration loaded and all the translation working, but when we build for production `ng build --prod --build-optimizer=false --aot --base-href "/"` we see an empty `{}` json for the console.log output.

**Comment by robisim74** [comment]
Hi @aasmm7x,

there isn't a known bug with AoT. See the sample app: https://github.com/robisim74/angular-l10n-sample

Are you sure that in prod mode you are passing the configuration to `forRoot` method? where is the configuration? into some environment variable?

**Comment by henriquecustodia** [comment]
I think I have a related problem

When I try use the `l10nDate` and `l10nCurrency` pipes inside a expression, on AoT build the expressions doesn't show the result but expressions using `translate` pipe show the result correctly. Using directives everything works fine on AoT build.  

On dev build all pipes and diretives works fine.

The sample app uses just  directives to format numbers and dates, so I can't see it  working in an app...  


AppModule Config

```ts
const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      { code: 'en', dir: 'ltr' },
      { code: 'pt', dir: 'ltr' }
    ],
    defaultLocale: { languageCode: 'pt', countryCode: 'BR' },
    currency: 'BRL',

  },
  translation: {
    providers: [
      { type: ProviderType.Static, prefix: './assets/i18n/' }
    ],
    caching: true,
    missingValue: 'No key',
    composedKeySeparator: '.',
  }
};
@NgModule({
  imports: [
    ...
    LocalizationModule.forRoot(l10nConfig)
  ]
})
export class AppModule {
  constructor(l10nLoader: L10nLoader) {
    l10nLoader.load();
  }
}
```


```
@angular/*": "^6.0.3 
angular-l10n": "^5.0.0
```

EDIT
I forgot to add the `ngOnInit` and `ngOnDestroy` lifecycles like is explained [here](https://robisim74.github.io/angular-l10n/quick-start/) :

> To use AoT compilation you have to implement OnInit, and to cancel subscriptions OnDestroy, even if they are empty. 

After adding the lifecycles, everything works fine :smile: 

Thanks!

**Comment by robisim74** [comment]
@henriquecustodia Yes, it's correct. But the problem of @aasmm7x seems different, because he gets an empty configuration.

**Comment by antl3x** [comment]
Hey @robisim74 we solved our problem.

We have the configuration object (L10nConfig) in an separate file called `l10n.config.ts` and we import the object to `app.module.ts`. 

For some weird reason, this work normally when we do `ng serve` but when we build the project, it stop working.

So to solve our problem we hard coded the configuration object in the `app.module.ts` directly and we do not use anymore an external file to hold the configuration object.
