### ISSUE TITLE
missingValue?: string | ((path: string) => string);

### ISSUE THREAD

**Issue by nm-a** [robisim74/angular-l10n#195]
**I'm submitting a...**
```
[* ] bug report
[ ] feature request
[ ] support request
```

Hi,
When I try to to use "function" for "missingValue", getting below error with -aot enabled build.

Error:
Consider changing the function expression into an exported function

can we fix this issue, this is very useful to deal initial resource file load issue.

thank you

**Comment by robisim74** [comment]
Hi,

this a common scenario with AoT: you have to use exported function. This works:

```
export const l10nConfig: L10nConfig = {
   ...
    translation: {
       ...
        missingValue: miss
    }
};

export function miss(path: string): string {
    return path + ' is missing';
}
```

**Comment by nm-a** [comment]
thank @robisim74 , it is fine now. In my case I am getting all resource values from the json files, initially it is returning keys instead of values. This could be because of ServiceState = "isReady" initially.

I am following lazy loading steps to load the files in advance.

```
{
      provide: APP_INITIALIZER,
      useFactory: initL10n,
      deps: [L10nLoader, TranslationService, LocaleService],
      multi: true
    }
```

Can you please recommend is there any other approach to handle this.

**Comment by robisim74** [comment]
The suggested way can be found in the documentation: https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization

Moreover, I suggest to use a preloading strategy for lazy loaded modules.

Greetings

**Comment by nm-a** [comment]
thank you @robisim74 , I will try this.
