### ISSUE TITLE
Detect error in loading translation file

### ISSUE THREAD

**Issue by TheShanMan** [robisim74/angular-l10n#196]
I had a bug submitted against my project for failing to load 2 languages. As it turns out our l10n team had unescaped quotes in their json. angular-l10n silently fell back to english since that's what I configured it to do. However, it would've been nice to at least see a console log message about the faulty json file, generate an event that I could handle, or be able to detect the correct locale in l10nloader.load's onfulfilled handler (the locale state seems to reflect the specified locale, not the fallback locale). This would help in more quickly pointing the problem at our l10n team rather than my project. It might also make it possible to write some automation to try to load each locale and verify that such a console log message isn't present. Then whenever they check in new translated strings, we'd know right away if they checked in any faulty json.
```
[ ] bug report
[x ] feature request
[ ] support request
```

**Expected behavior**
Provide some means to detect that fallback has occurred
**Actual behavior**
Can't find a way to detect fallback
**Steps to reproduce the behavior**
Create a json with unescaped quotes (invalid json) and try to use that string bundle in your page that is configured to fall back to another locale
StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version, library version, environment, browser**
Angular 6.0.5, angular-l10n 5.0.0, windows, chrome

**Comment by robisim74** [comment]
Hi,

Translation files are loaded only a runtime, when they are required  by the user.

However, an event fired on a loading error already exist: `translationError` of `TranslationService`. It was thought for errors during the http requests to web APIs, but it should be fired also for an invalid json. Here an example: https://robisim74.github.io/angular-l10n/spec/configuration/#asynchronous-loading-through-a-web-api

Then you have to manage by yourself the state of locale: locale and translation are two different services. With the current behaviour, locale is updated in any case, but translation remains in previous state: there is no one fallback.

**Comment by TheShanMan** [comment]
I didn't find a way to handle this while looking through the docs so thank you for pointing out this feature!
