### ISSUE TITLE
expression | translate:lang is not translating 

### ISSUE THREAD

**Issue by josephjelaskar** [robisim74/angular-l10n#197]
My application uses the angular version 6.0.2 and angular-l10n is 5.0.0. The problem i experience is that the expression in HTML is not getting translated but when i have the below code inside the ngOnInit() of the corresponding component is working.

 this.strCasingsInPendingCollection = this.translation.translate('CasingsInPendingCollection'); 

but No expression in the template (HTML ) is translated as a result the key is shown. our application loads the translation data through WebAPI

this.translationConfig.providers = [
            {
                type: ProviderType.WebAPI, path: this.urlConstants.Translate
            }];

Kindly help me on this.

**Comment by robisim74** [comment]
Hi,

are you implementing `Language` decorator in your components? https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

Otherwise post the code of your component and the configuration used for the library. Thanks.

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

Yes. I have implemented as per the documentation. Please find the below snippet

**From app.module.ts**

import {
    LocalizationModule, LocaleService, TranslationService, LocaleValidationModule, TranslationModule,
    L10nConfig, L10nLoader, ProviderType, StorageStrategy, TranslationConfig, LocaleConfig,
    LOCALE_CONFIG, TRANSLATION_CONFIG
} from 'angular-l10n';

const l10nConfig: L10nConfig = {
    translation: {
        missingValue: 'No Value',
        missingKey: 'No Key',
        caching: true,
        providers: []
    },
    locale: {
        defaultLocale: { languageCode: 'en-us', countryCode: 'US' },
        storage: StorageStrategy.Disabled
    }
}

@NgModule({

    bootstrap: [AppComponent],
    imports: [
        ....,
       ....,
        TranslationModule.forRoot(l10nConfig),
        LocalizationModule.forRoot(l10nConfig),
        LocaleValidationModule.forRoot()
],
providers:[
         ....,
       TranslationUtility,
        {
            provide: APP_INITIALIZER, 
            useFactory: initLocalization,
            deps: [TranslationUtility],
            multi: true
        },
]
});

export class AppModule {}


**From Dashboard Component**

import {  Language, DefaultLocale } from 'angular-l10n';

@Component({
    selector: 'dashboard',
    templateUrl: './dashboard.component.html',
    providers: [DashboardService, CommonService]
    
})
export class DashboardComponent extends BaseComponent implements OnInit {
    @Language() lang: string;
    @DefaultLocale() defaultLocale: string;

ngOnInit(): void {
this.strCasingsInPendingCollection = this.translation.translate('CasingsInPendingCollection');
}
}

**From the Template**

<span class="dashboard-widgetAText">
                            {{'CasingsInPendingCollection' | translate:lang}}
   </span>

**From BaseComonent**

export class BaseComponent extends Localization implements OnDestroy {
 constructor(){
      super();
}

ngOnDestroy(): void {
        if (this.subscription)
            this.subscription.unsubscribe();
    }
}

Thanks....

**Comment by robisim74** [comment]
The correct syntax for the decorators is uppercase:

```
@Language() lang: string;
@DefaultLocale() defaultLocale: string;
```

Then, you don't need to extends also the `Localization `class in your `BaseComponent`: are you using a different change detection strategy (like OnPush)?

**Comment by josephjelaskar** [comment]
Hi @robisim74,

The syntax is in uppercase in fact. copy & paste it here has turned that to be lower case.
 I am not using different change direction strategy. Even before ,I have also tried removing the Localization form basecomponent , but no luck so far.

Thanks..

**Comment by robisim74** [comment]
Ok, try to correct also:
- Remove the import of `TranslationModule`: `LocalizationModule` is enough
- Correct `defaultLocale: { languageCode: 'en-us', countryCode: 'US' },` to `defaultLocale: { languageCode: 'en', countryCode: 'US' }`: if you need to load composed languages (`/en-us` path in your url), see here: https://robisim74.github.io/angular-l10n/spec/configuration/#using-a-composed-language
- If your `DashboardComponent `is in a submodule (or a lazy loaded module) make sure you are importing there `LocalizationModule`
- Clean the browser cache and try again

If it still won't work and you can't create a repro, compare with the sample app: https://github.com/robisim74/angular-l10n-sample

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

Personally, Thank you very much for your response and support.

Removed the import of TranslationModule.
The changes regarding the country code is done and composed language set up is also done.
The DashboardComponent is not in submodule .

Significantly , when i happened to debug the TranslatePipe  i have noticed that  the "ServiceState" inside the translate function is in "isWaiting" state and the Key is returned as it is.At the same time, the below given code of the corresponding component returns translated value but not consistently

this.translation.translate('CasingsInPendingCollection');

i guess the async loading of Web API translation set up is not ready. Please feel free to correct me in case i am wrong.  is there any set up to make the file loading synchronous? or is there any technique to make sure that the file and set up is ready before the actual translation happens?. I like to have your guidance on these.


Thanks..

**Comment by robisim74** [comment]
I see that the provider is added in your _TranslationUtility_: could you post its code?

See also here: https://robisim74.github.io/angular-l10n/spec/configuration/#dynamic-settings To load synchronously right way is APP_INITIALIZER.

In any case, after the loading the pipes should be updated also asynchronously.

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

As i have shared with you already ,we in fact load the translation using APP_INITIALIZER  following the "Advanced Initialization".

export function initLocalization(localizationConfig: TranslationUtility): Function {
    return () => {

        localizationConfig.load();
    };
}

@Injectable()
export class TranslationUtility {

    private languageCodes = Array<Language>();

    constructor(
        public l10nLoader: L10nLoader,
        public locale: LocaleService,
        public translation: TranslationService,
        private injector: Injector,
        @Inject(TRANSLATION_CONFIG) private translationConfig: TranslationConfig,
        @Inject(LOCALE_CONFIG) private localeConfig: LocaleConfig,
        @Inject(AppService) public appService: AppService,
        @Inject(CommonService) public commonService: CommonService,
        private urlConstants: HttpUrl

    ) { }
load(): Promise<any> {
        return new Promise((resolve: any) => {
        console.log("Loading Languages and its translation context");
            if (this.localeConfig.languages == undefined) {
                this.commonService.GetLanguageCodeList().subscribe(
                    data => {
                        data.forEach((item, index) => {
                            //This is use to let localization know languages that it needs to support
                            var s = this.languageCodes.find(x => x.code == item.Id);
                            if (s == null || s === undefined) {
                                this.languageCodes.push({ code: item.Id, dir: 'ltr' });
                            }

                        });
                        this.localeConfig.languages = this.languageCodes;
                    });
            }
		//Reading the UserContext via WebAPI to know the user Preference Language
			this.appService.getUserContext().
			subscribe(user=>{			
				if (user as UserContext) {
					this.translationConfig.providers = [
					{
						type: ProviderType.WebAPI, path: this.urlConstants.Translate
					}];
					this.translationConfig.composedLanguage = [ ISOCode.Language, ISOCode.Country ];
					if (user.LanguageCode.includes('-')) {
                       var userLanguageCodeWithCountryCode: string[] = user.LanguageCode.split('-');
                    this.locale.setDefaultLocale(userLanguageCodeWithCountryCode[0], userLanguageCodeWithCountryCode[1]);
                                 this.locale.setCurrentLanguage(userLanguageCodeWithCountryCode[0]);
					}
					else
					{
					   this.locale.setDefaultLocale(userLanguageCodeWithCountryCode[0], '');
                       this.locale.setCurrentLanguage(userLanguageCodeWithCountryCode[0]);
					}
					return this.l10nLoader.load();
				}		
			});
		});
}
}


Thanks..

**Comment by robisim74** [comment]
Unfortunately I can test your code, but:
- you should check that the _load_ method works as expected: if the ServiceState is in isWaiting state means that _load_ method of l10nLoader has not been called. You have a subscription inside the promise, maybe it is the problem. Your promise must be resolved
- you should avoid to call setDefaultLocale (and also setCurrentLanguage) during the configuration, because they will try to load the translations but they are not ready. Use localeConfig instead

**Comment by josephjelaskar** [comment]
HI @robisim74 ,

you want me to make the changes like

this.translationConfig.providers = [
                {
                    type: ProviderType.WebAPI, path: this.urlConstants.Translate
                }];
            this.translationConfig.composedLanguage = [ ISOCode.Language, ISOCode.Country ];

this.localeConfig.defaultLocale = {
                languageCode: 'en', countryCode:'US'
            };
            this.localeConfig.language = 'en';
          this.translationConfig.caching = true;
        this.translationConfig.missingValue = 'No Value';
        this.translationConfig.composedLanguage = [ISOCode.Language, ISOCode.Country];
        return this.l10nLoader.load();


can i make the initial configuration Empty? I mean the configuration what i have inside app.module.ts

Thanks...

**Comment by robisim74** [comment]
Yes, you can use an empty object (just with locale and translation keys). But you must complete the configuration before calling l10nLoader.load method.

BTW I suggest you to try a simple solution until the translation works. Then add your logic during the configuration.

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

Once again thank you very much for your guidance. I will try to change those to get it worked and will let you know.

Regards..

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

I have an interesting update for you..Typically After making all the changes you have suggested, i have written my Custom Pipe calling the same function **translation.translate(key)**  as the built in translate pipe ( | translate:lang) does. The code is as given below

import { Pipe, PipeTransform } from '@angular/core';
import { Localization, LocaleService, TranslationService, Language } from 'angular-l10n';

@Pipe({ name: 'customTranslate' })


export class customTranslatePipe extends Localization implements PipeTransform {
    constructor() { super(); }
    transform(value: string): string {
        return this.translation.translate(value);
    }
}

I have used both my custom pipe ( | customTranslate) and built in translate pipe ( | translate:lang) altenatively in a same HTML a couple of times. When the custome pipe calls the function the service state is in "isReady" state and when the built in pipe calls the function the serviceState still in "isWaiting" state unfortunately. both the pipes are called again and again the serviceState behaves the same as mentioned above.  I am confused here. Please let me know what should be the problem..


Thanks..

**Comment by robisim74** [comment]
Sorry, but I don't understand what you are trying to do.

The library and pipes work as intended if you follow the docs.

Greetings

**Comment by josephjelaskar** [comment]
Hi @robisim74 ,

Personally , Thanking you for your continues support and guidance. Please accept my apologies that the mistake falls on my implementation which has been rectified and now the translation works fine. The problem is that "TranslationService" has been added in the  Providers section of both Appmodule and AppComponent. Removing it from the providers array of Appcomponent tuned the translation working..

Regards...
