### ISSUE TITLE
Web api translation throwing an error as Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by HemaVSitaram** [robisim74/angular-l10n#199]
Hi,

I have added following code in app.module:

const l10nConfig: L10nConfig = {
  translation: {
    providers: [{
      type: ProviderType.WebAPI,
       path: environment.baseUrl + '/translations/getTranslations?module=dashboards&locale='
        }]
    caching: true,
    composedKeySeparator: '.',
    missingValue: 'No key',
     i18nPlural: true
  }
};

@NgModule({
  imports: [
    StoreModule.forRoot(reducers, { metaReducers }),
    EffectsModule.forRoot(effects),
    NgxPermissionsModule.forRoot(),
    CoreModule.forRoot(),
    AppRoutingModule,
    AuthModule,
    StoreRouterConnectingModule.forRoot({
      stateKey: 'router'
    }),
    LocalizationModule.forRoot(l10nConfig),
    LocaleValidationModule.forRoot()
  ],
  providers: [
    { provide: RouterStateSerializer, useClass: CustomSerializer },
    AppCommonService
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule {
  constructor(public l10nLoader: L10nLoader) {
    this.l10nLoader.load();
  }

By-default, im not applying any translation. But, when i select an option to convert(provided a drop down to change language). im calling the following code.

this.localeService.setDefaultLocale(this.languageCode, this.countryCode, "'', 'latn');

For which, im getting following error:

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
> TypeError: Cannot read property 'apply' of undefined
>     at Observable.eval [as _subscribe] (angular-l10n.js:1468)
>     at Observable._trySubscribe (Observable.js:172)
>     at Observable.subscribe (Observable.js:160)
>     at eval (Observable.js:286)
>     at new ZoneAwarePromise (zone.js:891)
>     at Observable.toPromise (Observable.js:284)
>     at TranslationService.eval (angular-l10n.js:1398)
>     at step (tslib.es6.js:91)
>     at Object.eval [as next] (tslib.es6.js:72)
>     at eval (tslib.es6.js:65)
>     at Observable.eval [as _subscribe] (angular-l10n.js:1468)
>     at Observable._trySubscribe (Observable.js:172)
>     at Observable.subscribe (Observable.js:160)
>     at eval (Observable.js:286)
>     at new ZoneAwarePromise (zone.js:891)
>     at Observable.toPromise (Observable.js:284)
>     at TranslationService.eval (angular-l10n.js:1398)
>     at step (tslib.es6.js:91)
>     at Object.eval [as next] (tslib.es6.js:72)
>     at eval (tslib.es6.js:65)
>     at resolvePromise (zone.js:814)
>     at eval (zone.js:724)
>     at rejected (tslib.es6.js:63)
>     at ZoneDelegate.invoke (zone.js:388)
>     at Object.onInvoke (core.js:4760)
>     at ZoneDelegate.invoke (zone.js:387)
>     at Zone.run (zone.js:138)
>     at eval (zone.js:872)
>     at ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:4751)
> 

and i can see in the network tab of chrome debug window, this api is not getting called.

I'm using:
Angular: 5.2.8
l10n: 5.0.0
rxjs: 5.5.2

**Comment by robisim74** [comment]
Hi,

I think the problem is the versions: with Angular v5 and rxjs 5 you should use angular-l10n 4.1.5: https://github.com/robisim74/angular-l10n/releases

However, missing `Locale `in the configuration could break the library.

**Comment by HemaVSitaram** [comment]
Thanks, it worked after changing the version.
