### ISSUE TITLE
special chars Rx problem

### ISSUE THREAD

**Issue by damienbod** [robisim74/angular-l10n#2]
Hi, thanks for this package. When I use special characters in the resource files, the Localization service throws an  invalid character exception due to the 'Actualités' => é

Any ideas how to fix this?

``` javascript

{
    "HELLO": "Bonjour {{value}}",
    "NAV_MENU_HOME": "Actualités",
    "NAV_MENU_SHOP": "Boutique"
}
```

Error:

``` javascript
Localization service: SyntaxError: Invalid character
   "Localization service:"
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at Json.parse (http://localhost:8186/libs/angular2.dev.js:390:7)
   at Response.prototype.json (http://localhost:8186/libs/http.dev.js:296:9)
   at Anonymous function (http://localhost:8186/libs/angular2localization.js:58:13)
   at MapSubscriber.prototype._next (http://localhost:8186/libs/Rx.js:5039:9)
   at Subscriber.prototype.next (http://localhost:8186/libs/Rx.js:10667:9)
   at onLoad (http://localhost:8186/libs/http.dev.js:672:13)
   at ZoneDelegate.prototype.invokeTask (http://localhost:8186/libs/angular2-polyfills.js:380:18)
   at onInvokeTask (http://localhost:8186/libs/angular2.dev.js:2177:15)
   at ZoneDelegate.prototype.invokeTask (http://localhost:8186/libs/angular2-polyfills.js:380:18)
   at Zone.prototype.runTask (http://localhost:8186/libs/angular2-polyfills.js:282:22)"
   }

```

greetings Damien

**Comment by robisim74** [comment]
Hi Why do you use '{{value}}' in the message? However accented characters are not considered special characters, and work normally: see [here](https://github.com/robisim74/angular2localization/tree/gh-pages) for a sample. Can you add the code snippets that uses in the view and in the component?

**Comment by damienbod** [comment]
Hi I don't use {{value}}, was just testing, this is not the problem, have removed it. The chars should be ok, valid json, but the Rx throws the invalid char exception. 

src:

https://github.com/damienbod/Angular2LocalizationAspNetCore/tree/dev/src/Angular2LocalizationAspNetCore/wwwroot

Greetings Damien

**Comment by robisim74** [comment]
Yes, the json is valid. I also work with ASP.NET Core. I try to see myself because JSON.parse generates that error.

**Comment by damienbod** [comment]
strange, thanks

**Comment by robisim74** [comment]
<img width="1080" alt="2016-04-26" src="https://cloud.githubusercontent.com/assets/14012361/14834719/4c29f716-0c06-11e6-833c-7e33484de803.png">

I do not see the error, if not in the encoding of accented characters.

**Comment by robisim74** [comment]
See [here](http://stackoverflow.com/questions/36627655/special-characters-in-utf-8-using-renderbody). This should solve your problem.

<img width="1080" alt="2016-04-26 1" src="https://cloud.githubusercontent.com/assets/14012361/14835002/ccf79230-0c07-11e6-9174-625e517beb2a.png">

**Comment by damienbod** [comment]
Hi @robisim74 

Thanks for your answer, and the link  It only crashes in IE 11. Firefox and chrome displays it but the chars incorrectly. It seems the resource file http request is not returned in the correct format. I will try changing this.

Greetings Damien

**Comment by robisim74** [comment]
Hi @damienbod. The problem is only in the character encoding. I saved your json files in Unicode (UTF-8), and I cleaned the browser cache. Also in IE 11 I see everything correctly.
<img width="1080" alt="2016-04-27" src="https://cloud.githubusercontent.com/assets/14012361/14847392/af01020a-0c68-11e6-83f7-1bbd779adcb1.png">

**Comment by damienbod** [comment]
Hi @robisim74 

When I save the files in UTF-8, everything works fine. Thanks.
I'll do a blog about this, thanks again for your help.

Greetings Damien

**Comment by robisim74** [comment]
On Windows the encoding is always a problem ... Good luck for your project.
