### ISSUE TITLE
Suppressing @Language() when using translate pipe ?

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#201]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```
Hello,

Would it be possible to help to explain why do we need to use the @Language when using translate pipe ? What's the purpose, and if there's any possibility to suppress it ?

`
@Language() lang: string;
<p>{{ 'hello.world' | translate: lang }}</p>
`

Thanks.

**Comment by robisim74** [comment]
For better performance, this library uses `pure pipes` to achieve the translation: https://angular.io/guide/pipes#pure-and-impure-pipes

`Language ` decorator is the way used to pass the language parameter.

Alternatively you can use the directives: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#directives

**Comment by dsuwirya** [comment]
OK, but the question is more why do we need to mandate the application to explicitly declare and pass it instead of the current "lang" value being 'figured out' automatically within the angular-l10n library itself? Just trying to see if there's a way to even streamline this further, and minimize further what the application side has to do.

Thanks much.

**Comment by robisim74** [comment]
`Pure pipes` provide better performance because the Angular Change detection mechanism fires them _only_ when the key or an external parameter changes. So there isn't a way to update them internally (such as using directives).

**Comment by robisim74** [comment]
Closed due to inactivity.
