### ISSUE TITLE
Text not being translated using pipe in production only

### ISSUE THREAD

**Issue by elmentecato** [robisim74/angular-l10n#203]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
`<a routerLink="apps">{{ 'appsLabel' | translage:lang }}</a>
`
should display "Applications" text in the anchor which is the value for "en" locale in my json file.

**Actual behavior**
I see "appsLabel" instead

**Steps to reproduce the behavior**
My setup follows the documentation as best as I can tell. I know that the server reads successfully the json file with the strings and if I call translation.translate('appsLabel'), I do get the correct translated string (even in production). Cannot provide way to reproduce, because this works in dev mode. Only stops working when compiled with production flag and deployed to a server.

Project was created with CLI and I use this to compile (in case base-href matters, but as I said, the json file is found fine):
ng build --prod --base-href=/portal/

**Specifications: Angular version, library version, environment, browser**
Angular 6.1.0
angular-l10n 5.1.0
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Mac OS 10.13.6

Please help. I searched for this issue online, and couldn't find anything. I don't know what else to check, as everything runs fine until I deploy. And even in production works fine in typescript. Just not in the html templates using pipe (translate:lang). Thanks.

**Comment by robisim74** [comment]
Hi @elmentecato,

are you implementing the `ngOnInit` method in your components, even if it is empty? (it is necessary for decorators in aot mode). See: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

**Comment by elmentecato** [comment]
Thanks @robisim74 
That was it!
