### ISSUE TITLE
Need of 'cache buster' mechanism for .json file

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#204]
We're experiencing problem where the application is taking the .json file from browser cache, eventhough there's newer 'version' of .json file available. 

In order to resolve this, we need to apply common cache buster mechanism by appending query parameter at the end of the URL, e.g. http://www.myserver.com/locale-en.json?v1.0.1.

But currently, the only way to achieve that is by overriding HttpTranslationProvider > getTranslation(). It would be great if you can provide a way for us to achieve this without the need to override it. Or, if you can help to suggest a better way to resolve this caching problem would be even better.

Thanks much!

**Comment by robisim74** [comment]
Hi @dsuwirya,

I was already thinking about a solution for this browser behavior: I like your idea.

**Comment by robisim74** [comment]
I made a commit (https://github.com/robisim74/angular-l10n/commit/b4ddd7bcb19ebb7f559e1807b7d01465a8c7d67d) that adds two options to the configuration: `version `and `timeout `(related to this other your request: #181 ).

Let me know your opinion before I release a new version of the library.

**Comment by dsuwirya** [comment]
Looks great ! Thank you very much ! Will these changes be available on v4.x as well or only on v5.x ?

**Comment by robisim74** [comment]
Hi @dsuwirya,

I released the new version of the library for Angular v6: https://github.com/robisim74/angular-l10n/releases

I usually release updates for previous versions of Angular just for bug fixes, and not for new features.

However, in v4.x, you can implement the `CustomTranslationProvider` as in the new version. Then you can pass the new settings in the `args` parameter:

```
providers: [
    { type: ProviderType.WebAPI, path: 'https://www.myserver.com/i18n/', version: '1.0', timeout: 2000 }
]
```

and get the values `args.version`  and `args.timeout` in the `getTranslation` method.

Greetings

**Comment by dsuwirya** [comment]
Sounds reasonable, thanks much !

**Comment by tiho2** [comment]
> I made a commit ([b4ddd7b](https://github.com/robisim74/angular-l10n/commit/b4ddd7bcb19ebb7f559e1807b7d01465a8c7d67d)) that adds two options to the configuration: `version `and `timeout `(related to this other your request: #181 ).
> 
> Let me know your opinion before I release a new version of the library.

Great!
Can one see this feature in G. Chrome's Developer Tools? I have added new properties to configuration, but I don't see them as Request Headers as expected. (So, not sure if my config is ignored.)
