### ISSUE TITLE
angular-l10n with <ng-content> ?

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#205]
Hi @robisim74,

May I know what's the proper way to translate text for reusable component that is using `<ng-content>` ?

From what I observe so far, directive and pipe don't work in this case, and only translate() works.

I'm always trying to avoid using translate() as much as I can due to verboseness of the approach.

ref. 
- https://blog.angular-university.io/angular-ng-content/
- https://medium.com/claritydesignsystem/ng-content-the-hidden-docs-96a29d70d11b

`<ng-content> does not “produce” content, it simply projects existing content. Think of it as some variation of node.appendChild(el) or the well-known JQuery version $(node).append(el): with these methods, the node is not cloned, it is simply moved to its new location. Because of this the lifecycle of the projected content is bound to where it is declared, not where it is displayed.
`

Thank you.

**Comment by robisim74** [comment]
Hi @dsuwirya,

please, could you create a [Stackblitz](https://stackblitz.com/edit/angular-l10n) sample?

**Comment by dsuwirya** [comment]
Hi @robisim74,

I'm so sorry. I think it's more a mistake on my part. Please ignore this question / concern. There should be no issue using angular-l10n directive and pipe even in content projection `<ng-content>` scenario.

Thanks again!
