### ISSUE TITLE
How 'inject' styling in the middle of translated text ?

### ISSUE THREAD

**Issue by dsuwirya** [robisim74/angular-l10n#206]
Hi @robisim74,

I have a few cases where I need to translate a long text, where I need to make some words in the middle of that text bold, italic, etc. 

e.g. "This is a long text with **bold** and _italic_ that I have to translate". 

Is there anyway we can achieve this in an elegant way? Currently, the only way I can think of is by breaking down the sentence into several chunks and concat them ( - which is not necessary will always result to a correct concatenation for all languages ).

Thanks.

**Comment by robisim74** [comment]
https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#using-html-tags-in-translation

**Comment by dsuwirya** [comment]
Thanks for the above pointer! I completely missed that!

How about for the situation where there is `<a></a>` in the middle - any suggestion, please?
e.g. `<p>On this <a (click)="onClick()">link</a>, hello world</p>`

Thanks!

**Comment by robisim74** [comment]
Angular doesn't process HTML added by `innerHTML `(except sanitization). See for example: https://stackoverflow.com/a/37676847/6067476

The easiest way is to split the translation:
```
<p>
    {{ 'begin' | translate:lang }}
    <a (click)="onClick()" l10nTranslate>link</a>
    {{ 'end' | translate:lang }}
</p>
```

**Comment by SvenBudak** [comment]
@dsuwirya Your request will never work in the angular world i think. the latest response from @robisim74 is the only way to solve your problem correctly. if your link contains normal urls then you can place it directly into the translate string.

Voted 4 Close ;)

**Comment by robisim74** [comment]
Closed due to inactivity.
