### ISSUE TITLE
Placeholder not behaving as expected

### ISSUE THREAD

**Issue by madhumlr** [robisim74/angular-l10n#207]
**I'm submitting a...**
```
[ X] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Change placeholder text based on the language selected.

**Actual behavior**
Placeholder text does not change when language is changed

**Steps to reproduce the behavior**
In my page I have a simple textbox
<input type='text' placeholder="{{'my-key' | translate:lang}}" />. When page loads placeholder has English text.

When I change the language to French, placeholder does not get updated to french text. 
Sample: https://stackblitz.com/edit/angular-l10n-czlvmp?embed=1&file=app/home.component.ts

My framework:
Angular 5
Angular-l10n: 4.2.0 version

Can you please suggest me if there are any workaround to fix this issue?

**Comment by robisim74** [comment]
Hi @madhumlr,

the following code works without problems:

`<input matInput type="text" formControlName="company" placeholder="{{ 'company' | translate:lang }}">`

**Comment by madhumlr** [comment]
Does not seems to be working for me:
Sample here: https://stackblitz.com/edit/angular-l10n-czlvmp?embed=1&file=app/home.component.ts

My Framework:
Angular 5
Angular-l10n: 4.2.0 version

**Comment by robisim74** [comment]
To work with translate pipe, you have to add the `Language `decorator in the component:

`@Language() lang: string;`

https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

Greetings

**Comment by madhumlr** [comment]
Thanks @robisim74, its working fine after adding @Language().
I did not import @Language at child component in angular. This was causing the issue.

Marking it as "Closed"
