### ISSUE TITLE
Namespaces for keys

### ISSUE THREAD

**Issue by Etchelon** [robisim74/angular-l10n#21]
Ciao Roberto,
really good job, I like your library a lot! I was trying to understand which is better: this or ng2-translate, and I decided I'll give this a try, especially because I like the api more and your pipes are pure, and although I'm just starting with a new project, I know it'll become big, with a lot of translations in page. I can't assess the impact of impure pipes, but if the angular team itself discourages their use... :)

Anyway, I seem to understand that your library doesn't support namespaced keys like ng2-translate does e.g.:
{
  "HOME": {
    "TITLE": "Homepage",
    "FOOTER": "Text in the footer"
  },
  "HELP": {
    "TITLE": "Help page
  }
}

I think it would be very useful to implement. Medium to big projects will certainly be split into multiple components which will need the same key, but with a namespace (like "TITLE", many components might use this key). Ofc we could use a prefix but we'd lose the nesting in the json file.

What do you think?

Once again good job, and kind regards.

Andrea

**Comment by robisim74** [comment]
Ciao Andrea,

I was already planning to implement this feature, and because you have confirmed that it would be helpful, I will try to do it as soon as possible.

Thanks!

**Comment by robisim74** [comment]
Ciao Andrea,

I added this feature in the latest version of the library compatible with Angular 2.0.0 Final Release.

I'm working to the other feature.

Saluti

**Comment by Etchelon** [comment]
Thanks man, that was quick! :)

**Comment by jhwegener** [comment]
Is there an option to get rid of this feature in my project?
I have a notation like this in my files:

{
    "my.key":"my.value",
    "my.next.key":"my.next.value"
}

That's why this feature brakes my translation files!

**Comment by robisim74** [comment]
No, there isn't.

Do you really need this option? I'll evaluate an alternative and let you know.

**Comment by jhwegener** [comment]
Yes an option would be great. Otherwise I had to change my complete translation file (>1000 keys).

**Comment by robisim74** [comment]
Ok. I see.

**Comment by robisim74** [comment]
Hi @jhwegener,

I added a commit that implements the option. By default, the feature is still present, but if you want to disable it, when you initialize the `LocalizationService`, you can invoke the following method before the `updateTranslation` method:

`this.localization.setComposedKey(false);`

If you don't want giving up the feature, but simply you want to use a different separator from the point, you can pass it to the method. For example:

`this.localization.setComposedKey(true, "-");`

If you want to test it, or use it immediately, you must remove the library from your node_modules, clone this project, and follow the instruction to build and install the library in README file.

I think I'll release a new version of the library when Angular 2.3.0 will be realeased.

Greetings,

Roberto

**Comment by jhwegener** [comment]
Hi Roberto,

this works like a charm! 
Thx for this quick response and implementation!

Greetings

Henning
