### ISSUE TITLE
Dynamic label name 

### ISSUE THREAD

**Issue by rberkovi** [robisim74/angular-l10n#210]
**I'm submitting a question**
```
[ ] bug report
[ ] feature request
[ X] support request
```
We developing application that required multi brand support and intertionalization
We have components that shared between the brands, but display label can be different base on brand.

Is their is way to dynamically resolve this? We would not wanted to create new component just for different label.

For example in java locale their is notion of variant. Locale has country, language and third attribute can be anything (variant) 

**Expected behavior**

**Actual behavior**

**Steps to reproduce the behavior**

StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version, library version, environment, browser**

**Comment by robisim74** [comment]
Hi @rberkovi,

I see, but in this library the _locale_ is built according to the rules of internationalization, to be able to work also with public APIs like Intl.

However, the translation data are simple objects, and you have many ways to implement it, for example it would be enough to add a prefix to all translations::

```
@Component({
  selector: 'app-brand',
  template: `<p>
    {{ (brand + '.name') | translate:lang }}
  </p>`
})
export class BrandComponent implements OnInit {
  @Language() lang: string;
  @Input() brand: string;
  ...
}
```

Then you can pass it the brand:
```
<app-brand brand="brandA"></app-brand>

<app-brand brand="brandB"></app-brand>
```

and create translation data like this:
```
{
    "brandA": {
        "name": "Angular"
    },
    "brandB": {
        "name": "TypeScript"
    }
}
```

You could also create a custom pipe to add the prefix before the translation and so on.

I hope this can give you some ideas.

Greetings

P.S. Another thing: in component class you can get the object of translations for a specific _variant_, like in java:
```
const res = this.translation.translate("brandA");
console.log(res["name"]);
```

**Comment by rberkovi** [comment]
thank you, you can close it
