### ISSUE TITLE
Localized routing for SEO

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-l10n#211]
Hi,

since version 6.1.2 the library provides support for localized routing: [docs](https://robisim74.github.io/angular-l10n/spec/configuration/#localized-routing-for-seo) & [demo](https://robisim74.github.io/angular-l10n-sample)

This is an option to be activated explicitly during configuration. I ask who will try it, to leave here any comments or feedbacks about the behavior.

Thanks!

**Comment by havran** [comment]
Hi, it is possible use default page language without language prefix? 

For example: i have page wit default language DE and translated version with EN - then i want show german (default) content on path / (without prefix) and english (translated) content on prefixed URL /en

Thanks.

**Comment by robisim74** [comment]
@havran do you mean this?

```
https://example.com/home (for default language)
https://example.com/it/home (for other languages)
```

No at the moment. But I could easily add an option to do it.

The question is: is this a best practice? also for SEO?

**Comment by havran** [comment]
> @havran do you mean this?
> 
> ```
> https://example.com/home (for default language)
> https://example.com/it/home (for other languages)
> ```
> No at the moment. But I could easily add an option to do it.
> 
> The question is: is this a best practice? also for SEO?

Exactly like this. About SEO - I'm not sure, but definitely this is option which is used on many sites (I primary work with Drupal CMS and here is possibility use both variant for default language - configurable). 

And if i want use benefits (localize dates.numbers) from this library for site with one language (for example DE) and decide add second language later, then I want use non prefixed URLs for old pages and use prefixed url only for translated pages.

**Comment by robisim74** [comment]
I see. I will do some tests and let you know when the option will be available.

**Comment by havran** [comment]
> I see. I will do some tests and let you know when the option will be available.

Thank you!

**Comment by robisim74** [comment]
@havran from version 6.4.0 is available the option for default routing: https://robisim74.github.io/angular-l10n/spec/configuration/#options

If you will try it, please let here a feedback.

**Comment by havran** [comment]
Thank you.

**Comment by havran** [comment]
Hello again. I'm trying implement l10n-angular to our project. Localized routing work but i have small problem.
We have menus and content loaded from external CMS (Drupal8) which use same concept (language prefix) for selecting translated content.

For example we have two languges:
en - default (without prefix)
sk - (with prefix /sk)

Language switching work perfectly.

I have menu loaded from CMS - then i have page with URL /sk/page. 

I need for loading content from CMS whole url - with prefix but localized routing, after click, remove prefix /sk from route.url. It's possible get whole URL (with /sk part) in my resolver?

Thanks.

**Comment by robisim74** [comment]
@havran I'm not sure I understand what you mean: if you need to get the url you could use the instance of Angular Location class:

`const path: string = this.location.path();`

or the router. Please, If this does not solve your problem, open a new issue with a more detailed explanation.

**Comment by havran** [comment]
Hello again, i think i solve part with getting original clicked path with small service:

```typescript
import { Injectable } from '@angular/core';
import { NavigationStart, PRIMARY_OUTLET, Router, UrlSegment, UrlTree } from '@angular/router';
import { filter } from 'rxjs/operators';
import { Location } from '@angular/common';

@Injectable()
export class PathService {

  private url: string;

  constructor(
    private router: Router,
    private location: Location,
  ) {
    this.url = this.location.path();
    this.router.events.pipe(
      filter((event: any) => event instanceof NavigationStart)
    ).subscribe((data: NavigationStart) => {
      this.url = data.url;
    });
  }

  get currentUrl(): UrlSegment[] {
    const parsedUrl: UrlTree = this.router.parseUrl(this.url);
    return parsedUrl.root.children[PRIMARY_OUTLET] ? parsedUrl.root.children[PRIMARY_OUTLET].segments : [];
  }
}
```

One remains thing is switch language from URL (which work for URL with prefix), but if i use configuration with:

```typescript
    localizedRouting: [ISOCode.Language],
    localizedRoutingOptions: {
      defaultRouting: true
    },
```
then links from CMS without prefix do not switch language. My content resolver still can get correct content (because i get content by path). I see private method LocalizedRouting.parsePath which seems to do set locales by url language prefix in loading time (from location). 

I think i need manually set locales like parsePath() method, I'm right? Thanks.

**Comment by robisim74** [comment]
Yes. I do not think that I will make public methods as parsePath, because they were built for the default behavior of the library, and may not always be good in other cases.

**Comment by havran** [comment]
Thank you very much.

**Comment by robisim74** [comment]
From v7.0.0 there is a complete support for SEO by locales: https://robisim74.github.io/angular-l10n/spec/seo/

**Comment by ihor-zinchenko** [comment]
@robisim74 hi! can you provide an example how to localizate Title and description?

**Comment by robisim74** [comment]
@ihor-zinchenko With angular-l10n v10, you could create a custom class like this:

```
import { Injectable, Inject } from "@angular/core";
import { DOCUMENT } from '@angular/common';
import { Title, Meta } from "@angular/platform-browser";

import { L10N_CONFIG, L10nConfig, L10nTranslationService } from "angular-l10n";

/**
 * Manages the translation of page 'title' and meta tags.
 */
@Injectable({
    providedIn: 'root'
})
export class SearchService {

    constructor(
        @Inject(DOCUMENT) private document: Document,
        @Inject(L10N_CONFIG) private l10nConfig: L10nConfig,
        private translation: L10nTranslationService,
        private title: Title,
        private meta: Meta
    ) { }

    /**
     * Translates the 'title' of the page and the provided meta tags.
     * @param page The key path of the page
     */
    public updateHead(page: string): void {
        const metaTags = ['description', 'keywords'];

        this.translation.onChange().subscribe({
            next: () => {
                this.setTitle(page);
                if (metaTags.length > 0) {
                    for (const name of metaTags) {
                        this.updateTag(name, page);
                    }
                }
            }
        });
    }

    public setLang(language: string): void {
        this.document.documentElement.lang = language;
    }

    private setTitle(page: string): void {
        this.title.setTitle(this.translation.translate(page + (this.l10nConfig.keySeparator || '') + 'title'));
    }

    private updateTag(name: string, page: string): void {
        this.meta.updateTag(
            {
                name: name,
                content: this.translation.translate(page + (this.l10nConfig.keySeparator || '') + name)
            }
        );
    }

}
```
Then just call the `updateHead` in `ngOnInit` of routes component, for example: `this.search.updateHead('home');`

**Comment by ihor-zinchenko** [comment]
@robisim74 thanks!)
