### ISSUE TITLE
Translations using `translate` pipe are sometimes not evaluated.

### ISSUE THREAD

**Issue by mahmoudajawad** [robisim74/angular-l10n#212]
**I'm submitting a...**
```
[*] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
The `translate` pipe to work every time it's being used.

**Actual behavior**
On the first load of the application to any page, all `translate` pipe variables in the template fail to load, however after navigating back and forth it works.

For instance, following login page is what is shown on first load:
![Screenshot_2018-11-01-Athr.png](http://prtsc.ca/images/2018/11/01/Screenshot_2018-11-01-Athr.png)
And, following is what shows after logging-in and out again to go back to the same page:
![Screenshot_2018-11-01-Athr837837ef0c3a747b.png](http://prtsc.ca/images/2018/11/01/Screenshot_2018-11-01-Athr837837ef0c3a747b.png)

**Steps to reproduce the behavior**
Use following deps:
```
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "angular-l10n": "^6.0.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "file-saver": "^2.0.0-rc.4",
    "ngx-cookie": "^4.0.2",
    "rxjs": "^6.0.0",
    "zone.js": "~0.8.26"
```
and the behaviour would would be the same. Previous versions of Angular and Angular-l10n are not having this issue.

**Specifications: Angular version, library version, environment, browser**
Angular-l10n: 6.0.0.
Angular: 7.0.0.
All browsers. Tested on mobile phones and Windows 10 devices.

**Comment by robisim74** [comment]
@AjawadMahmoud 

Please do these checks:
- in the network tab that data is correctly loaded when the app starts
- the correct implementation of the translate pipe: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

If these checks are successful, please post the code of the initialization of this library and the login component.

**Comment by mahmoudajawad** [comment]
@robisim74, sorry for replying late.
Now, two things:
1) My bad! Firefox wasn't showing some error message. Although I can't remember seeing it in Chrome before, however, today when I was fiddling little with the code before updating the issue I found that chrome is reporting the following error:
```
// Chrome console
ERROR TypeError: Cannot read property 'dir' of undefined
    at LocaleService.push../node_modules/angular-l10n/fesm5/angular-l10n.js.LocaleService.getLanguageDirection (angular-l10n.js:583)
```
2) I don't get it, I have the exact same implementation on another project and it's working fine:
```
// app.component.ts
import { Component, OnInit } from '@angular/core';

import { TranslationService, LocaleService } from 'angular-l10n';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

	title: string = 'athr';
	dir: any = 'rtl';

	constructor(private translation: TranslationService, private locale: LocaleService) { }

	ngOnInit() {
		this.translation.translationChanged().subscribe(
			() => {
				this.dir = this.locale.getLanguageDirection();
				this.title = this.translation.translate('app.title');
			}
		);
	}
}
```

I was sure the issue wasn't related to `login` component alone as I had the same behaviour on any page that I access it for first time before routing to another page.

**Comment by robisim74** [comment]
Check in your configuration that you have added the supported languages:

```
const l10nConfig: L10nConfig = {
    locale: {
        languages: [
            { code: 'en', dir: 'ltr' },
            { code: 'it', dir: 'ltr' },
            { code: 'ar', dir: 'rtl' }
        ],
        ...
    },
    ...
};
```

Then check also if you are using the latest version of the library v6.1.2, because recently I fixed the `getLanguageDirection ` method to avoid the error in any case.

**Comment by mahmoudajawad** [comment]
This is my `L10nConfig`:
```
const l10nConfig: L10nConfig = {
	locale: {
		languages: [
			{ code: 'ar', dir: 'rtl' },
			{ code: 'en', dir: 'ltr' }
		],
		defaultLocale: { languageCode: 'ar', countryCode: 'AE', numberingSystem: 'latn' },
		currency: 'AED',
		storage: StorageStrategy.Cookie
	},
	translation: {
		providers: [
			{ type: ProviderType.Static, prefix: './assets/l10n/locale-' }
		],
		caching: true,
		composedKeySeparator: '.'
	}
};
```
And, yes I just updated to `6.1.2` with the same issue.
UPDATE: I actually forgot to mention that after updating to `6.1.2` the error relater to `getLanguageDirection` is gone. The console on both chrome and firefox is now clear.

**Comment by robisim74** [comment]
So it works? or is not it getting the direction anyway?

**Comment by mahmoudajawad** [comment]
The direction is getting set correctly. I can know that because a `sidenav` in the other pages is set to show either left or right based on the `dir` of the page.
I actually never had any problems with `dir` at all. The problem was and is still that at first run of the app, any page of it, any term using the `translate` pipe wouldn't work, however `L10nTranslate` directive would work.

**Comment by robisim74** [comment]
Please, post the code of a component that's not working, and other info about the initialization.

**Comment by mahmoudajawad** [comment]
I choose `login` because it's not container-ised as such done to other pages nor it's bound to any `AuthGuard`, making it more test-worthy.
```
//login.page.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { AuthService } from '../../shared/auth.service';


@Component({
	selector: 'app-login',
	templateUrl: './login.page.html',
	styleUrls: ['./login.page.scss']
})
export class LoginPage implements OnInit {

	form: FormGroup = this.fb.group({
		email: ['', Validators.required],
		password: ['', Validators.required]
	});
	email!: string;
	password!: string;

	constructor(private auth: AuthService, private fb: FormBuilder) { }

	ngOnInit() {}

	login(): void {
		this.auth.login(this.email, this.password, ['/']);
	}

}
```
```
//login.page.html
<div class="login-container text-center">
	<form class="login-form" ngNativeValidate>
		<img class="mb-4" src="/assets/img/logo.png" alt="" width="72" height="72">
		<h1 class="h3 mb-3 font-weight-normal" l10nTranslate>login.login_note</h1>
		<label for="inputEmail" class="sr-only" l10nTranslate>login.email</label>
		<input type="email" id="inputEmail" class="form-control" placeholder="{{'login.email' | translate}}" [(ngModel)]="email" [ngModelOptions]="{standalone: true}" required autofocus>
		<label for="inputPassword" class="sr-only" l10nTranslate>login.password</label>
		<input type="password" id="inputPassword" class="form-control" placeholder="{{'login.password' | translate}}" [(ngModel)]="password" [ngModelOptions]="{standalone: true}" required>
		<!-- <div class="checkbox mb-3">
			<label>
				<input type="checkbox" value="remember-me"> Remember me
			</label>
		</div> -->
		<button class="btn btn-lg btn-primary btn-block" type="submit" (click)="login()" l10nTranslate>login.login</button>
		<p class="mt-5 mb-3 text-muted">&copy; 2018</p>
	</form>
</div>
```
You didn't ask for it, but here it's anyway:
```
//app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

import { L10nConfig, L10nLoader, LocalizationModule, StorageStrategy, ProviderType } from 'angular-l10n';

import { AppRoutingModule, pages } from './app-routing.module';
import { AppComponent } from './app.component';
import { CookieModule } from 'ngx-cookie';
import { KeysPipe, ValuesPipe } from './shared/object.pipe';
import { CapitalisePipe, SplitPipe } from './shared/string.pipe';
import { HttpClientModule } from '@angular/common/http';

const l10nConfig: L10nConfig = {
	locale: {
		languages: [
			{ code: 'ar', dir: 'rtl' },
			{ code: 'en', dir: 'ltr' }
		],
		defaultLocale: { languageCode: 'ar', countryCode: 'AE', numberingSystem: 'latn' },
		currency: 'AED',
		storage: StorageStrategy.Cookie
	},
	translation: {
		providers: [
			{ type: ProviderType.Static, prefix: './assets/l10n/locale-' }
		],
		caching: true,
		composedKeySeparator: '.'
	}
};

@NgModule({
	declarations: [
		KeysPipe,
		ValuesPipe,
		CapitalisePipe,
		SplitPipe,

		AppComponent,
		...pages
	],
	imports: [
		HttpModule,
		HttpClientModule,
		BrowserModule,
		FormsModule,
		ReactiveFormsModule,
		NgbModule,
		AppRoutingModule,
		CookieModule.forRoot(),
		LocalizationModule.forRoot(l10nConfig)
	],
	providers: [],
	bootstrap: [AppComponent]
})
export class AppModule {
	constructor(public l10nLoader: L10nLoader) {
        this.l10nLoader.load();
    }
}
```

UPDATE: Corrected `login.page.html` file name.

**Comment by robisim74** [comment]
As I suggested above, to use translate pipe see here: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

You have to use: `{{'login.password' | translate:lang}}` and then add the `Language `decorator in the component: `@Language() lang: string;`

That's because it is a _pure pipe_.

Also I suggest you to use advanced initialization: https://robisim74.github.io/angular-l10n/quick-start/#advanced-initialization

**Comment by mahmoudajawad** [comment]
Alright. This is really weird. Advanced initilisation has resolved the problem. I don't get it as I didn't have to do this on another project. Could this be related to Angular version?
For now, I'm fine. Your suggestion for advance initialisation is perfect!

**Comment by robisim74** [comment]
Ok, don't forget to use translate pipe in the correct way, otherwise it won't work when you change language.

Please close the issue if it solved.

**Comment by mahmoudajawad** [comment]
Thanks also for the suggestion in regards of the `translate` pipe. I usually force an app refresh as I set the language based on the API results. That's why I don't use the `lang` attribute which you always advise to use.
Thanks for your time. You are always a great supporter!
