### ISSUE TITLE
Support for OnPush change detection strategy breaks application

### ISSUE THREAD

**Issue by dhardtke** [robisim74/angular-l10n#213]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
The application should work without an exception.

**Actual behavior**
I get an exception when using the translate pipe.

**Steps to reproduce the behavior**
I couldn't reproduce it in a stackblitz but this happens:
I get a `TypeError` in the line `const cdr = Object.keys(this).find((key) => this[key]['markForCheck'] !== undefined);` because (for some reason) some class members are uninitialized (i.e., `undefined`).

Changing the line to `const cdr = Object.keys(this).find((key) => this[key] && this[key]['markForCheck'] !== undefined);` fixes that.

I will create a PR to fix this issue.

**Specifications: Angular version, library version, environment, browser**
Angular 7.0.3, latest angular-l10n, Windows 10 NodeJS 11 and Firefox (latest stable).

**Comment by robisim74** [comment]
I was not able to reproduce the error either. However, the additional check is correct.

I released the new version: https://github.com/robisim74/angular-l10n/releases/tag/v6.3.1

Greetings
