### ISSUE TITLE
Valid number with "-" using parseNumber

### ISSUE THREAD

**Issue by skyfremen** [robisim74/angular-l10n#215]
Would like to understand why "2-1" is a valid number using parseNumber.

Expected result
returns NaN

Acutal result 
returns 2

Stackblitz
[https://stackblitz.com/edit/angular-l10n-x4hhov](https://stackblitz.com/edit/angular-l10n-x4hhov)

**Comment by robisim74** [comment]
After the conversion, `parseNumber `method uses `parseFloat`:

![image](https://user-images.githubusercontent.com/14012361/48334006-8a34e400-e659-11e8-8062-81e27e14a329.png)

It would be interesting to understand if it is a bug of `parseFloat `or if it is the expected behavior.

**Comment by skyfremen** [comment]
Assuming parseNumber = parseFloat.

```
parseFloat("2~1") = 2
parseNumber ("2~1") = NaN
```

Why are these 2 having different result then?
https://stackblitz.com/edit/angular-l10n-x4hhov

![image](https://user-images.githubusercontent.com/22805288/48334616-3d233300-e696-11e8-9bfd-c8ab7b027b04.png)

**Comment by robisim74** [comment]
Because before applying `parseFloat`, the string is converted to English from the original language: _tilde_ is not an accepted sign and then NaN is returned directly in the conversion phase (only numbers, minus sign, decimal & thousand separtors are accepted).
Here the code: https://github.com/robisim74/angular-l10n/blob/master/src/services/locale-validation.ts#L26-L50

**Comment by skyfremen** [comment]
ok it makes sense to include minus sign for negative number. 
However minus sign that is not in the first position doesn't make sense.
eg 
"-21" valid negative number
"2-1" invalid number

**Comment by robisim74** [comment]
The problem should not be there, because the method should be used together with the `l10nValidateNumber `directive, which verifies the first position of minus sign:

![image](https://user-images.githubusercontent.com/14012361/48335709-d5052a80-e65e-11e8-924a-eff4b71c0b6c.png)

**Comment by robisim74** [comment]
@skyfremen Is it ok for you or do you need more information?

**Comment by skyfremen** [comment]
No additional information needed. Personally I feel that parseNumber can be used individually and should not be tied to l10nValidateNumber. 

In cases where I just use parseNumber method in .ts

**Comment by robisim74** [comment]
Ok, I will consider whether to add control even in the method. Thank you
