### ISSUE TITLE
feature: add optional LanguageInterceptor

### ISSUE THREAD

**Issue by IlCallo** [robisim74/angular-l10n#216]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Expected behavior**
When a request is sent to the server, the current locale/language **may** be inserted as `Accept-Language` or similar to let the server know current language of the client.
This can be useful if the server returns an error or some kind of message and wants to return only the translated string for the client to display.

**Actual behavior**
Not present AFAIK

**Possible implementation**
```typescript
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { LocaleService } from 'angular-l10n';
import { isUndefined } from 'lodash-es';
import { Observable } from 'rxjs';

@Injectable()
export class LanguageInterceptor implements HttpInterceptor {
  constructor(public localeService: LocaleService) {}

  public intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (!isUndefined(this.localeService.getCurrentLanguage())) {
      request = request.clone({ setHeaders: { 'Accept-Language': this.localeService.getCurrentLanguage() } });
    }
    return next.handle(request);
  }
}
```

**Comment by robisim74** [comment]
Sounds reasonable: but an interceptor is not necessary: just add the header here: https://github.com/robisim74/angular-l10n/blob/master/src/services/translation-provider.ts#L31

Example:
`const headers: HttpHeaders = new HttpHeaders({ 'Content-Type': 'application/json', 'Accept-Language': language });`

I will add this feature in the next version, but you could also implement your custom provider: https://robisim74.github.io/angular-l10n/spec/configuration/#using-a-custom-provider

**Comment by IlCallo** [comment]
I think you misunderstood, I meant **all** requests done by the application, not just the ones generated by this library :)

That's why an interceptor: it could be useful if this library provide an option to automatically attach the header to all outgoing requests and this complexity is hidden to the user via some configuration options, the interceptor would be registered by the library and activated based on this option.

**Comment by robisim74** [comment]
I see. Ok I will evaluate an option for this. But keep in mind that it is outside the scope of this library. So I think it would be appropriate to make a separate module imported only in case of need, so that it does not go to weight the library if not used.

**Comment by IlCallo** [comment]
Yeah, that seem a good idea.

Mine is just a suggestion, I'm already good  injector I defined, I just thought that it could be a common use case scenario when using this library

**Comment by robisim74** [comment]
Ok, thanks for the suggestion. Let you know.

**Comment by robisim74** [comment]
@IlCallo 

The feature is available with the latest version of the library: https://robisim74.github.io/angular-l10n/spec/configuration/#setting-the-locale-in-accept-language-header-on-outgoing-requests

Thanks again for the advice. If you will try it, please let here your feedback.

Greetings

**Comment by IlCallo** [comment]
Seems to work fine, ty!

**Comment by Lempkin** [comment]
Hi,

I've tried to set this out but it doesn't seems to work for me.
My config : 

```
const l10nConfig: L10nConfig = {
  locale: {
    localeInterceptor: [ISOCode.Language, ISOCode.Script, ISOCode.Country],
    languages: [{ code: 'en', dir: 'ltr' }, { code: 'fr', dir: 'ltr' }],
    defaultLocale: { languageCode: 'en', countryCode: 'EN' },
    currency: 'EUR',
    storage: StorageStrategy.Cookie,
  },
  translation: {
    providers: [{ type: ProviderType.Static, prefix: './assets/locale-' }],
    caching: true,
    missingValue: 'No key',
    composedKeySeparator: '.',
  },
};
```

I've added LocaleInterceptorModule in the app.module.ts imports. But for every request that I send to the API, "Accept-Language" header is still "fr". No matter if I set defaultLocale to "en", no matter if I switch lang with

`this.localizationService.switchLocale(event.value);`

Do I miss something?
Many thx!

**Comment by robisim74** [comment]
@Lempkin You are saying to the interceptor to use _scriptCode_:

`localeInterceptor: [ISOCode.Language, ISOCode.Script, ISOCode.Country],`

but you are only using `languageCode` & `countryCode`:

`defaultLocale: { languageCode: 'en', countryCode: 'EN' },`

Then, what is `this.localizationService.switchLocale` method?

Finally, when you send the requests? When the app starts? Make sure the library is ready (for example trying to call `getCurrentLanguage` in `LocaleService`).

**Comment by Lempkin** [comment]
Sry I forgot things, here the switchLocale : 

```
 public localeInfo = [
    new LocalizationInfo('fr-FR', 'FR', 'fr', 'EUR'),
    new LocalizationInfo('en-US', 'US', 'en', 'USD'),
  ];
constructor(public locale: LocaleService) {}

public switchLocale(localeInfo: LocalizationInfo) {
    this.locale.setDefaultLocale(localeInfo.language, localeInfo.country);
    this.locale.setCurrentCurrency(localeInfo.currency);
  }
```

I tried with 
`localeInterceptor: [ISOCode.Language /*, ISOCode.Script, ISOCode.Country*/],`

as in your example in the doc, but still the same.

I send request when I click on some buttons, and I'm sure that service is ready cause I use : 
```
export function initL10n(l10nLoader: L10nLoader): Function {
  return () => l10nLoader.load();
}
```

**Comment by robisim74** [comment]
1) Make sure `localeInfo.language` has a correct value when you call `switchLocale`
2) Are you using another interceptor? Is it possible that something else is overriding the `Accept-Language` header?

**Comment by Lempkin** [comment]
Oops my bad, indeed we had another interceptor which overrides headers... #shame 
Working perfectly now :)
Thx and sry :)
