### ISSUE TITLE
accessibility support

### ISSUE THREAD

**Issue by chrislingxiao** [robisim74/angular-l10n#218]
**I'm submitting a...**
```
[ ] bug report
[x ] feature request
[x ] support request
```

I need to add translated text to aria-label or other accessibility attribute like this:
attr.aria-label="{{ 'xxxxxxxx' | translate:lang}}", but seems like it doesnt support it.

**Comment by robisim74** [comment]
@chrislingxiao 

I do not find any problem with the use of air-label attribute:

`<button attr.aria-label="{{ 'Title' | translate:lang }}">Text</button>`

or:

`<button aria-label="Title" l10n-aria-label l10nTranslate>Text</button>`

Could you explain what kind of problem you get and provide a reproduction?

**Comment by chrislingxiao** [comment]
it was my bad. I forgot to add @Language. Ill close this issue.
