### ISSUE TITLE
[Question] why are you forcing the usage of decorators?

### ISSUE THREAD

**Issue by FabienDehopre** [robisim74/angular-l10n#219]
I'm not sure that forcing the usage of decorator to set the language, default locale and the currency is a good solution just yet.
I read a comment by one of the maintainers of the TypeScript infrastructure at Google about the usage of the decorators in the NGRX Effects package and it seems that the use of decorators is not recommended.
Here is the link to the comment in the NGRX platform repo: https://github.com/ngrx/platform/issues/1368#issuecomment-430096161

The decorators will probably be a good idea once the spec is stable.

**Comment by robisim74** [comment]
The proposal in ngrx you refer to is a proposal that relates to that library and that's it.

Decorators are included not only in TypeScript compiler, but also in the Angular compiler.

However, you're right: decorators are not yet stable, but considered experimental.

The point is: even the decorators included in this library in future could be used as simple functions (because that are).

I have marked the `Translation` and `Localization` classes as deprecated because they are currently a duplication of code. The intention would be to remove them, but if you tell me that you also feel comfortable working with the extension of the classes, we can certainly leave them.

**Comment by FabienDehopre** [comment]
I think that since the class that extends either the `Translation` or the `Localization` class don't need to provide the services (see #90), it's not a problem to use them.

**Comment by robisim74** [comment]
Glad to hear it.

Ok, in the next major release I will present them again as an alternative to decorators, but I would like to present them restyled.

In particular, I don't like the unsubscriptions of params (https://github.com/robisim74/angular-l10n/blob/master/src/services/translation.ts#L35): I'd like to happen automatically.

Every idea or suggestion is welcome.

**Comment by robisim74** [comment]
Note: it would be possible to unsubscribe by implementing a function like this: https://github.com/NetanelBasal/ngx-take-until-destroy/blob/master/src/take-until-destroy.ts

**Comment by FabienDehopre** [comment]
Indeed. That's exactly the solution I had in mind.

```ts
import { MonoTypeOperatorFunction, Observable, ReplaySubject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

/**
 * Une interface qui requiert la méthode `ngOnDestroy`.
 */
export interface WithOnDestroy {
  ngOnDestroy(): void;
  [key: string]: any;
}

/**
 * Patch the component with unsubscribe behavior.
 *
 * @param component The component class (`this` conttext)
 * @return An observable representing the unsubscribe event
 */
export function componentDestroyed(component: WithOnDestroy): Observable<true> {
  if (component.componentDestroyed$) {
    return component.componentDestroyed$;
  }

  const originalNgOnDestroy: () => void | undefined = component.ngOnDestroy;
  const stop$ = new ReplaySubject<true>();

  component.ngOnDestroy = () => {
    // istanbul ignore else
    if (originalNgOnDestroy) {
      originalNgOnDestroy.apply(component);
    }

    stop$.next(true);
    stop$.complete();
  };

  return (component.componentDestroyed = stop$.asObservable());
}

/**
 * Un opérateur RxJS qui stop la souscription quand le composant est détruit (`ngOnDestroy`)
 *
 * @param component La classe du composant (`this`).
 */
export function untilComponentDestroyed<T>(component: WithOnDestroy): MonoTypeOperatorFunction<T> {
  return (source: Observable<T>) => source.pipe(takeUntil(componentDestroyed(component)));
}
```
and the spec
```ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { fakeAsync, tick } from '@angular/core/testing';
import { interval, Subscription } from 'rxjs';

import { untilComponentDestroyed } from './until-component-destroyed';

// tslint:disable:max-classes-per-file

@Component({
  template: ``,
})
class TestHostComponent implements OnDestroy, OnInit {
  stub = jasmine.createSpy('stub');
  myInterval!: Subscription;

  ngOnInit() {
    this.myInterval = interval(200)
      .pipe(untilComponentDestroyed(this))
      .subscribe((v: number) => {
        this.stub(v);
      });
  }

  ngOnDestroy() {}
}

@Component({
  template: ``,
})
class TestHostDoubleComponent implements OnDestroy, OnInit {
  stub1 = jasmine.createSpy('stub1');
  stub2 = jasmine.createSpy('stub2');
  myInterval!: Subscription;
  mySecondInterval!: Subscription;

  ngOnInit() {
    this.myInterval = interval(200)
      .pipe(untilComponentDestroyed(this))
      .subscribe((v: number) => {
        this.stub1(v);
      });
    this.mySecondInterval = interval(200)
      .pipe(untilComponentDestroyed(this))
      .subscribe((v: number) => {
        this.stub2(v);
      });
  }

  ngOnDestroy() {}
}

describe(`untilComponentDestroyed`, () => {
  it(`should cancel an observable stream during the destroy cycle`, fakeAsync(() => {
    const testComponent = new TestHostComponent();

    testComponent.ngOnInit();
    tick(610);

    testComponent.ngOnDestroy();
    tick(1000);

    expect(testComponent.stub).toHaveBeenCalledTimes(3);
  }));

  it(`should cancel an observable stream during the destroy cycle`, fakeAsync(() => {
    const testComponent = new TestHostDoubleComponent();

    testComponent.ngOnInit();
    tick(610);

    testComponent.ngOnDestroy();
    tick(1000);

    expect(testComponent.stub1).toHaveBeenCalledTimes(3);
    expect(testComponent.stub2).toHaveBeenCalledTimes(3);
  }));
});
```

That's the implementation I use in my code.

**Comment by robisim74** [comment]
Great!

Yes, I was thinking that I could use the same function also to cancel subscriptions in the decorators (and avoid duplicate code).

I will try to implement it: if I can avoid breaking changes I will release the new classes with a minor version.

**Comment by robisim74** [comment]
I have simplified the function like this:

```
import { MonoTypeOperatorFunction, Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

export function takeUntilDestroyed(target: any): MonoTypeOperatorFunction<any> {
    const destroy: Subject<boolean> = new Subject<boolean>();
    const targetNgOnDestroy: Function = target.ngOnDestroy;

    function ngOnDestroy(this: any): void {
        destroy.next(true);
        destroy.complete();

        if (targetNgOnDestroy) {
            targetNgOnDestroy.apply(this);
        }
    }
    target.ngOnDestroy = ngOnDestroy;

    return takeUntil(destroy);
}
```

**Comment by robisim74** [comment]
Commit: https://github.com/robisim74/angular-l10n/commit/c8b202509d43fdca1225a8dabe8707cbc5b84418

**Comment by FabienDehopre** [comment]
In the `Translation` and `Localization` classes, can't you add an empty `ngOnDestroy` method that will be overridden if the component implements the `OnDestroy` interface? 
It's just as a fallback in case the component does not implement the `OnDestroy` interface.

**Comment by FabienDehopre** [comment]
Otherwise, that's look a lot cleaner with the `takeUntilDestroyed` operator :)

**Comment by robisim74** [comment]
Good idea! I do it right away.

Fabien, do you think I should immediately remove the method (https://github.com/robisim74/angular-l10n/blob/master/src/services/extensions.ts#L34)? It would be a breaking change...

**Comment by FabienDehopre** [comment]
I think you can leave the method until the next major release. Just mark it as deprecated with a message indicating that the method will be removed on the next major release.

**Comment by robisim74** [comment]
@FabienDehopre I started with this and I refactored the whole library: https://github.com/robisim74/angular-l10n/releases/tag/v7.0.0

Thanks again.
