### ISSUE TITLE
Extract json to translate 

### ISSUE THREAD

**Issue by jesusvallez** [robisim74/angular-l10n#220]
Hi guys! 

I'm trying to export all my project with the names of directives as keys with their strings as values, but I do not know how I can do it with any tool to do it easy.

There is this tool to extract ngx-translate (https://github.com/ngx-translate/core, https://github.com/flavienb/ngx-translate-extract) but I can not find anything for this package.

How could I do it?

Thanks for all @robisim74

**Comment by robisim74** [comment]
Hi @jesusvallez,

AFAIK there is no key extractor for this library, and it's not planned on my part.

**Comment by jesusvallez** [comment]
Oh, thanks for your response. I like this library but if I have to do it myself it's a bit tedious

**Comment by DaSchTour** [comment]
So there is no chance to get translations into a translation tool like poedit like it is possible with translations from angular official i18n?

**Comment by robisim74** [comment]
This project was not designed to work with the _gettext_ logic, like the old _angular-gettext_ for angular.js e the official i18n for angular.

So it is not easy to create a parser for all translation keys (which can be in different ways both in html files and in ts files): even there may not be, as in the new features for SEO.

Similar attempts, such as the one created for ngx-translate, have a lot of issues...

Maybe you can adapt a gettext extractor for javascript, create _po_ files and convert them to json ... but I have never tried.

With Angular, if you want to work with that logic, in my opinion you should use the official i18n.

However, I reopen this issue, to listen to other opinions as well.

**Comment by DaSchTour** [comment]
Well, for me the important part is not parsing the keys from html or ts files but having translations in a file format that can be edited in widely used tools like poedit which allows editing xlf files and has tooling for suggesting translations through translation services. Which allows me to translate angular applications with hundrets of keys in minutes. So as keys are not extract there just needs to be some logic to create XLF files with needed keys and parse them back. So maybe a JSON to XLF converter would be enough.

**Comment by robisim74** [comment]
Ok, there is some converter:
- json to xliff: [Okapi](http://okapiframework.org/) / http://okapiframework.org/wiki/index.php?title=JSON_Filter
- json to po: [Translate Toolkit](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/index.html) / http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/json2po.html

But actually I never tried.

**Comment by DaSchTour** [comment]
I tested json to po. And it works fine when converting json to po file. But the direction back doesn't work with composed keys 😞

**Comment by xcash** [comment]
For those seeking a quick way to extract all the words matching the template pattern ` 'word' | translate:lang ` here is a one-liner:

    echo "{"; grep -r -o -E "'\w+'\s*\|\s* translate:\w+" src/app/* | sed -E "s/.*'(\w+)'.+/\"\1\":\"\1\",/g"; echo "}"

**Comment by xcash** [comment]
And this is a small Python tool to extract labels from `.ts` and `.html` files and merge `language-XY.json` files:

https://gist.github.com/xcash/35be65bd2d23650536db3879ad813a5d

Note: Python 3.x

**Comment by robisim74** [comment]
@xcash Fantastic! Thank you so much for sharing!

**Comment by robisim74** [comment]
Closed due to inactivity
