### ISSUE TITLE
Formbuilder - How to format numbers before patchValue?

### ISSUE THREAD

**Issue by xcash** [robisim74/angular-l10n#221]
**I'm submitting a...**
```
[ ] bug report
[X] feature request
[X] support request
```

**Expected behavior**
I've managed how to validate field in a FormBuilder form but i am missing a way to do the opposite. When I need to populate the form I have raw data. Ho to localize it in the ts before calling `patchValue'?
Only way I found is directly using the pipe (approach derived by looking in the test files.. :) ) but it doen't seem too elegant. :)

Am I missing something in the docs?
Thanks a lot :)

**Comment by robisim74** [comment]
Do you mean this? https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#getting-the-translation-in-component-class

**Comment by xcash** [comment]
Yes I ended up doing exactly like that. But more specifically i mean if is there a better way instead of specifying the formatting two times. 
In my form definition I write:

```
    this.exampleForm = this.fb.group({
      weight: ['', [ l10nValidateNumber('1.0-1') ]],
      height: ['', [ l10nValidateNumber('1.0-0', 50, 260), Validators.required ]],
    });

```
And when loading data i need to specify it again:

```
      const formvalues = {
        weight: this.decimalPipe.transform(weight, this.defaultLocale, '1.0-1'),
        height: this.decimalPipe.transform(height, this.defaultLocale, '1.0-0'),
      }
      this.exampleForm.patchValue(formvalues);

```

Since formbuilder is an abstraction over a full form, it would be awesome to abstract all the localization within it. i.e. talking to the form by raw numbers and it autonomously localizing by the parameters specified in initialization (or in the markup of the fields, like the ngModel localization/validation). 
Probably I should submit this separately as a feature request. :)

**Comment by robisim74** [comment]
@xcash 

About the use of the` transform` method of the pipes to translate dates & numbers in the components, you are right: it's time to create public methods in `LocaleService` class: will do.

**Comment by robisim74** [comment]
About you second request, we can now continue here.

I know the problem, for having found it in my apps.

About the repetition of the format, in my opinion it is not a problem: when you patch values, you can use a format that takes into account the maximum number of decimals, for example:

`this.decimalPipe.transform(weight, this.defaultLocale, '1.0-4')`

Personally I find it more annoying to have to convert all the numbers every time. For this reason in my app I have created custom methods like these:
```

    transformNumber(value: number): string {
        return this.pipe.transform(value, this.locale.getDefaultLocale(), '1.0-4');
    }

    transformNumbers(data: any): any {
        let transformedData = deepClone(data);

        if (typeof data === 'object') {
            if (data instanceof Array) {
                transformedData = transformedData.map(value => this.transformNumbers(value));
            }
            Object.keys(transformedData).forEach((key: string) => {
                if (typeof transformedData[key] === 'number') {
                    if (this.stringData.includes(key)) {
                        transformedData[key] = this.transformNumber(transformedData[key]);
                    }
                } else if (typeof transformedData[key] === 'object') {
                    transformedData[key] = this.transformNumbers(transformedData[key]);
                }
            });
        }
        return transformedData;
    }
```

However, I'm not sure I understood the solution you're recommending for the library. Please try to explain with some examples.

**Comment by xcash** [comment]
@robisim74 thanks for the replies :)

In your code sample you're formatting numbers using same precision. In my code sample, and in a lot of real cases, you may need to use different decimals for different fields.

My proposal is to delegate the full formatting and parsing to the field itself (using directive).
Now for each field the flow is: format raw number -> user uses the form -> parse localized back to raw number.
A solution would be to always use raw numbers with `patchValue` and retrieve raw numbers with `form.values`. Markup side you could specify the formatting directives like you do when using ngModel. 
Or, even better, using the validators used to create the controls respecting the formbuilder goal of keeping all the validation in the code instead of the markup.

I don't know angular internals so I don't know if what I'm proposing is even possible. :/

**Comment by robisim74** [comment]
In my example I am using a variable format, and the numbers will be formatted according to the precision in which they were saved:
1.23 => 1,23
1.2 => 1,2
and so on.

About you proposal:
- validation required _text_ field
- even if you could format the values in the input fields of the template (which I do not recommend) inside the `value` property of `FormGroup` there will always be a text field that needs to be transformed.

**Comment by xcash** [comment]
> In my example I am using a variable format, and the numbers will be formatted according to the precision in which they were saved:

I see but it's not always the case. It depends on underlying data structure. You might have automatically calculated floats, or for some field you might want to force 2 decimals even if it's an integer.
But it's not the point. :)

Yes I forgot that validator requires strings... :(
Then if we cannot use the FormControl to abstract the localization it seems we must live with this approach of format and parse.

**Comment by robisim74** [comment]
@xcash The methods to format dates & numbers in component class have been added in the latest release: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#dates-numbers_2

Greetings

**Comment by xcash** [comment]
@robisim74 Great!!! I will check it out soon! :)
Thanks!!
