### ISSUE TITLE
Angular Material tooltip not being translated when using parameters.

### ISSUE THREAD

**Issue by derckie** [robisim74/angular-l10n#224]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ x ] support request
```

**Expected behavior**
When using a parameter in the translation for a matTooltip the parameter needs to be taken from the variable.

Example :  {{ 'TXT_TO_TRANSLATE' | translate: lang:{ username: this.accountService.currentUser.name } }}

**Actual behavior**
The translation is done except for the parameter which remains  {{ username }}. Other translations with parameters outside of the matTooltip on the same page are correct.

**Comment by robisim74** [comment]
@derckie 

I am currently using `matTooltip` with the parameters in the translation in my app, and it works correctly.

Could you provide a reproduction?

**Comment by derckie** [comment]
@robisim74 

I was apparently to quick with my question. I had to restart my app completely in order to get it working.  Saving my code and compiling while ng serve was running didn't picked it up.

It  works now as expected. Thanks for this very nice translation module !

**Comment by robisim74** [comment]
Ok!
