### ISSUE TITLE
Translation provider locale json never loads

### ISSUE THREAD

**Issue by banderberg** [robisim74/angular-l10n#227]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ x] support request
```

**Expected behavior**

All my locale-en.json files load.

**Actual behavior**

All but ONE load.

***
What possible cause might there be to explain why only ONE of my locale-en.json files FAILS to load?  I have five different modules and they all load the assets except one.  I have spent two days inspecting code and I can see no differences between the one not working and the others that are.

I upgraded to v7 of angular-l10n turned on logging and still get no indication of why this is happening.

Thoughts or ideas or pretty much anything to help me figure this out would be appreciated.

Thanks

**Comment by robisim74** [comment]
Could you provide the _l10nConfig_ of the module that is not working? Are you getting an error 400 in console > network > xhr? Or only the translation in the module is not working?

**Comment by banderberg** [comment]
`export const l10nConfigReporting: L10nConfig = {
    locale: {
        languages: [],
        storage: StorageStrategy.Cookie
    },
    translation: {
        providers: [],
        caching: true
    },
    logger: {
        level: LogLevel.Log
    }
};`

In Network > Xhr, I see the other locale-en.json files load but this one in particular just never shows up.  I don't see any 400.

That config above is identical to all of my other modules.

**Comment by robisim74** [comment]
Are you providing an empty configuration?

Then if you are using lazy loaded modules, you should not provide also the _locale_ configuration, because it will override the root configuration.

**Comment by robisim74** [comment]
Moreover if you are using _caching: true_ you should see the _locale-en.json_ loaded only once.

Here the docs and an example:
https://robisim74.github.io/angular-l10n/spec/lazy-loading/
https://github.com/robisim74/angular-l10n-sample/blob/master/src/app/list/list.module.ts

Without more detailed information or a repro it is not possible to provide help.

**Comment by robisim74** [comment]
I'm closing it for lack of information.
