### ISSUE TITLE
Bug: Validator digits "1.0-0" is interpreted as "1.0-3"

### ISSUE THREAD

**Issue by sahrmann** [robisim74/angular-l10n#228]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```
Although documentation proposes the validator `height: ['', [ l10nValidateNumber('1.0-0', 50, 260) ]]` (supposedly to only accept numbers without any fraction digits), this validator does not work. It accepts numbers with 0 to 3 fraction digits, instead of only integer numbers. The reason seems to be line 72 in src/services/locale-validation.ts:

```
const maxFraction: number = options.maximumFractionDigits || 3;
```

The expression `0 || 3` evaluates to 3, so if maximumFractionsDigits is set to 0, it will be changed to 3.

**Comment by robisim74** [comment]
@sahrmann 

Thanks for reporting.

Fixed in latest version 7.0.2

Greetings
