### ISSUE TITLE
TRANSLATION_CONFIG missing

### ISSUE THREAD

**Issue by vasicvuk** [robisim74/angular-l10n#229]
I am updating from Angular 5 to Angular 7.  I used @Inject(TRANSLATION_CONFIG) in Angular 5 and now i get error:
```
'angular-l10n"' has no exported member 'TRANSLATION_CONFIG'
```

What can i use to inject Translation config in Angular 7 ?

Is this L10N_CONFIG now ?
```
[ ] bug report
[ ] feature request
[X ] support request
```

**Comment by robisim74** [comment]
Yes, now there is only the `L10N_CONFIG` token: https://robisim74.github.io/angular-l10n/spec/configuration/#configuration-token, which has the `translation` property.

See also the changelog: https://github.com/robisim74/angular-l10n/releases/tag/v7.0.0

**Comment by vasicvuk** [comment]
Thanks, I am closing the issue.
