### ISSUE TITLE
Is this module ready for AOT?

### ISSUE THREAD

**Issue by bogomips** [robisim74/angular-l10n#23]
I've made few tests but I  got errors.
did someone succeed?

**Comment by robisim74** [comment]
Please provide at least the rollup configuration, the import mode of the library and the errors you get. Thank you.

**Comment by robisim74** [comment]
Ok, I have found the mistake. Angular 2 has again changed the compilation options for the destination src folder. I'll update and publish a new release. Thanks for the feedback.

**Comment by bogomips** [comment]
I did not even answer and you are already going to fix it :)
I will give it a try as soon as you release the new version and I'll leave a feedback in case of errors.
Thanks!

**Comment by robisim74** [comment]
Hi,

I have released the new version, which fixes the AoT compilation. See [here](https://github.com/robisim74/angular2localization/releases) for more information.

There are however still many problems with the AoT compilation. Follow [this thread](https://github.com/angular/angular/issues/11262) for example.

Greetings

P.S. I have switched the [sample app](http://robisim74.github.io/angular2localization) to AoT compilation.
