### ISSUE TITLE
How to add translation data to the service

### ISSUE THREAD

**Issue by Etchelon** [robisim74/angular-l10n#230]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```

Hi, I'm trying to achieve the following:
have a singleton service that manages translations in my Angular app. The service provides a method like the following:
`getTranslations(languageCode: string, moduleName: string) {}`
What I want to do is load chunks of translations, grouped by moduleName, on demand. For example when loading a lazy module but no only, another example might be when rendering a custom form loaded from database, where its labels are also translated.
In case of loading translations for a lazy module, the built in approach of importing TranslationModule.forChild could work fine, but there's no such mechanism to handle form translations (or anything else than a NgModule). Is that correct?
So I was thinking to do the following: create a service which calls an HTTP endpoint with the language and obtains the chunk of translation data, and then adds it to the dictionary (translationData member in TranslationService). How can I achieve this, besides the obvious javascript powered hack of doing
`(this.translationService as any).addData()` on the private-but-still-there method of TranslationService? If that method were protected I could inherit the default implementation of the service...

Is it maybe possible to modify the configuration object in order to add direct translation data (L10nConfigRef) and rerun load on the L10nLoader?

**Comment by robisim74** [comment]
Yes, you don't need to access to `addData `method:  you can modify the config object adding the new data and then call the load or the `init `method of `TranslationService`. 

But keep in mind that the translations on the html will not work without reloading the page or changing language (see also #200)

**Comment by Etchelon** [comment]
That's what I ended up doing while waiting for your response, actually I'm calling the private function loadTranslation because init also subscribes to race(...) and there's no need to duplicate a listener on language/locale changes... by the way, isn't that a problem? Semantically, init should be called only once but since you can call it multiple times that subscription should not be duplicated.

Also, I noticed that using addData was wrong because at every language change the translationData dictionary was reinitialized from the dictionary in the config object, so that is what must actually be enriched.

**Comment by robisim74** [comment]
You are right: calling `init `again should create a duplicate listener (not a problem, but not perfect).

Better to make the `loadTranslation `method public (but the logic won't change).

**Comment by robisim74** [comment]
@Etchelon From version 7.1.0 `loadTranslation `method is public. Greetings

**Comment by Etchelon** [comment]
Thanks a lot!
