### ISSUE TITLE
Problems upgrading to 7.0

### ISSUE THREAD

**Issue by othenos** [robisim74/angular-l10n#231]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[ X] support request
```
I'm upgrading from Angular 6 to 7 and encountering issues with the component translation. I know I'm providing minimal information but will be happy to provide a lot more if you need it. I suspect this is a simple configuration mistake on my part.

**Expected behavior**
In component, the translate function on the TranslateService should provide translation based on key provided.

**Html pipes DO translate properly.**

**Actual behavior**
Key is not found. For some reason the Json files are not available to the TranslationService.

**Steps to reproduce the behavior**
TranslationService is loaded in the constructor of the component.
this.translation.translate('defaultWeight'); returns 'No Key'

StackBlitz Template: https://stackblitz.com/edit/angular-l10n

**Specifications: Angular version, library version, environment, browser**
7.2.0, 7.0.2, OS X, Chrome

**Comment by othenos** [comment]
Closing this. Apparently, I had just not re-compiled properly and was using an older version.

**Comment by robisim74** [comment]
Ok! Thanks for reporting.
