### ISSUE TITLE
Allow TranslationProvider to run without HttpClientModule

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#232]
```
[ ] bug report
[ X] feature request
[ ] support request
```
Ii use standalone app based on electron and i don't need HttpClientModule, i would like to avoid this kind of error:
```js
StaticInjectorError(AppModule)[TranslationProvider -> HttpClient]
```
Would it be possible to make this HttpClientModule dependency optional? Only in case we use queries to get the translations?

**Comment by robisim74** [comment]
Hi @johaven,

it's not a problem add the `@Optional` decorator to the injection of HttpClient in the service, but then if another dev which instead needs it forget to import HttpClientModule, he won't get any error or warning...

**Comment by johaven** [comment]
_staticInjectError_ is raised when i import TranslationModule in app.module (not in my services).
I think it would be better to make optional the module httpclient in angular l10n especially if we do not use the possibilities to request translations.

**Comment by robisim74** [comment]
You get _staticInjectError_ because you are not importing HttpClientModule in your AppModule.

As I said, I can avoid the error, marking as `@Optional` the injection of _HttpClient_ in the _TranslationProvider_ service.

But then how do I solve the problem of lack of error when other users of the library use it but forget to import it?

**Comment by johaven** [comment]
I don't know how to check if module is loaded inside Angular (i searched with no results).

Inside TranslationProvider service, i think @Optional return null if no module is injected (i did not test), you can probably raise on error when user try to request without HttpClientModule.

**Comment by robisim74** [comment]
I tested `@Optional` and it works.

I should check if the HttpClient service exists when the providers are inserted ... It can be done.

However I do not know if this will bring a benefit: I don't think that `HttpClientModule` will not be included in the bundle for example.

I will evaluate this change. In the meantime it is necessary to always import `HttpClientModule`, even if not used.

**Comment by johaven** [comment]
It's as you want, I personally like to lighten my builds (especially with a desktop application) but I think most people use your library in a context of web server.

I will understand if you do not integrate :)

**Comment by robisim74** [comment]
@johaven From version 7.1.0 `HttpClientModule` is optional. Greetings

**Comment by johaven** [comment]
@robisim74 Thank you for this and for the work done on this lib. I use it on all my projects.
