### ISSUE TITLE
Route name localization

### ISSUE THREAD

**Issue by 6matko** [robisim74/angular-l10n#233]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Expected behavior**
Feature to localize/translate route names in different languages. Example:
I have a route named **news** and url: **website.com/en/news**
If I change language then location url and appropriate routerLink url's become to **website.com/ru/novosti**.
This functionality is actually achieved in **localize-router** library, but there were several other problems. Basically there was a Pipe that was localizing routes.

**Actual behavior**
Currently only locale is changing in URL and I have to do such workaround for routerLinks: `routerLink="{{lang}}/{{news.url}}"` which becomes to (based on current language):
website.com/en/news
website.com/ru/news
Also there is no way to change name of route after locale to appropriate name in specific language.

**Steps to reproduce the behavior**
-

**Specifications: Angular version, library version, environment, browser**
Angular: 7.2.1
Angular-l10n: 7.2.0

**Comment by robisim74** [comment]
Hi @6matko,

`LocalizedRouting` class of this library works differently from `localized-router` library:

- route name is not localized, because in my opinion the language of the URIs is English, and not a mix of English and other languages 
- you don't need a workaround for `routerLink`: you can use it normally: `routerLink="/news"` and the class will replace the path adding the current locale

Greetings

**Comment by 6matko** [comment]
@robisim74 Hello, thanks for your reply.
My confuse is SEO. AFAIK crawlers will look up for URI from HTML which will be **news** aka single language. The same goes for public urls that may appear on website. Maybe you can give me your advice on how to achieve my goal with translatable route names ?

**Comment by robisim74** [comment]
See here: https://support.google.com/webmasters/answer/182192?hl=en&ref_topic=2370587 Crawlers need a localized route (URLs with locale), not a translated route (translated route name).

However, if you need, I think you can implement your own routing translation: just subscribe to `router.events`, translate the segment and replace it, in the same way that is done in the class to add the locale: https://github.com/robisim74/angular-l10n/blob/8d22a657295c9bd22ae4112af134cdebe7072cc6/src/models/localized-routing.ts#L35

**Comment by 6matko** [comment]
Thank you, will be looking forward into it.

**Comment by ihor-zinchenko** [comment]
@robisim74 hi! can u provide an example for the latest version of your lib to show me how I can localize the router path?

**Comment by robisim74** [comment]
@IhorVimmi There is no example of translation of the route. The updated link of the comment above is the following: https://github.com/robisim74/angular-l10n/blob/7260edfa76a5a5fba50a84f05ae7433c192889d6/projects/angular-l10n/src/lib/services/l10n-routing.service.ts#L39
