### ISSUE TITLE
Use fallback translation if WebAPI provider not responding

### ISSUE THREAD

**Issue by 6matko** [robisim74/angular-l10n#234]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
If WebAPI is unable to get translations, fallback translations should be used. Maybe I am missing something, but I didn't find information on how manually set which translations to use (fallback) when I handle error via `translationError` Observable.

**Actual behavior**
Library requests translations via WebAPI provider and in case if server is offline (throws error), fallback provider is not using fallback translations but hangs up whole app.

**Steps to reproduce the behavior**
Set WebAPI Provider to server that is offline.

**Specifications: Angular version, library version, environment, browser**
Angular: 7.2.0
Angular-l10n: 7.1.0

**Comment by robisim74** [comment]
Hi @6matko,

in this library, [fallback providers](https://robisim74.github.io/angular-l10n/spec/configuration/#using-fallback-providers) and [error handling](https://robisim74.github.io/angular-l10n/spec/configuration/#error-handling-of-data-loading) when obtaining translation files are two different concepts.
Please, post the configuration you are using and explain what behavior you want to achieve.

**Comment by 6matko** [comment]
Its very possible that I misunderstood the concept.
```
      providers: [
         { type: ProviderType.WebAPI, path: `${environment.apiUrl}/translations/public/` },
      ],
```
With provider I request translations (JSON) from my API based on provided language. If my server doesn't respond for any reason, my app gets hang up with following error:

> ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"http://localhost:14019/api/translations/public/en","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:14019/api/translations/public/en: 0 Unknown Error","error":{"isTrusted":true}}
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)

My expected behavior is that I want to show translations from local JSON which will act as a fallback if server returns error.

**Comment by robisim74** [comment]
First of all, you have to handle the error (to avoid the app breaking):

```
this.l10nLoader.load()
            .catch(err => console.error(err));
```

Then it depends on the strategy you want to adopt, for example:

- if you have a local json for each translation, you can add them as fallback providers: https://robisim74.github.io/angular-l10n/spec/configuration/#using-fallback-providers
- you can change the configuration, and force the reloading of the translation

Please provide more details if you need a solution.

**Comment by rbluethl** [comment]
Hey @robisim74 and @6matko,

I think I have the same problem.
It can happen that some JSON files are not available on our server (for example because the translation of a specific language is not done yet). In this case, the l10nLoader.load() function runs into 404 errors (which is ok). However, our application stops working in this case.

I also tried catching errors like @robisim74 suggested:
```javascript
this.l10nLoader.load().catch(err => console.error(err));
```

What I would like to achieve is the following:
* The library tries to fetch the translation file of a specific language (./assets/locale/module1/module1-es.json)
* The file can not be found for whatever reason (404)
* A fallback language for the same file is used (./assets/locale/module1/module1-en.json)
* Errors are handled gracefully

Is this possible? Also, why does my app stop working even if I handle errors as stated above?

Thanks already!

Ronald

**Comment by robisim74** [comment]
@rbluethl Are you using `APP_INITIALIZER`? It breaks the app if you don't catch the error in the exported function:

```
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load().catch(()=> console.log("catch"));
}
```

Then, if you get the error when the app starts, and you want to set a fallback language:
```
export function initL10n(l10nLoader: L10nLoader, locale: LocaleService): Function {
    return () => l10nLoader.load().catch(()=> {
        locale.setCurrentLanguage('en');
    });
}
```
In this case, you should have a safe fallback 'en'  translation, so I recommend adding it as direct loading:

```
const l10nConfig: L10nConfig = {
    ...
    translation: {
        translationData: [{
            languageCode: 'en', data: {
                "app": {
                    "title": "Angular localization",
                    "subtitle": "It's a small world"
                }
            }
        }],
        providers: [
            { type: ProviderType.Static, prefix: './assets/locale-' }
        ],
        ...
        rollbackOnError: false,
        composedKeySeparator: '.'
    }
};
```
(An alternative to direct loading is to use fallback providers: https://robisim74.github.io/angular-l10n/spec/configuration/#using-fallback-providers).
Please note that I have disabled `rollbackOnError` to make it works, so you will also need to handle any error even when the user changes language.

**Comment by 6matko** [comment]
For me, error handling helped with app being hanged up:
```
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load().catch(()=> console.log("catch"));
}
```
And fallback also worked for me with following providers:
```
         { type: ProviderType.Fallback, prefix: './assets/translations/fallback', fallbackLanguage: [] },
         { type: ProviderType.WebAPI, path: `${environment.apiUrl}/translations/public/` },
```
I had to turn off `rollbackOnError` in order to make it work. So in current behavior I have error catching to prevent app from hanging up and if translation could not be received from server, `fallback.json` is used to translate my app. `rollbackOnError` should be turned off.

My case is resolved, big thanks @robisim74. Great library and great support, you helped me once again :) For now I don't want to close this issue because I don't know if **rbluethl** found a solution so feel free to close it when you need to.

**Comment by rbluethl** [comment]
@robisim74 yes you were right, I'm using APP_INITIALIZER and I didn't catch the error properly.

Using
```
export function initL10n(l10nLoader: L10nLoader): Function {
    return () => l10nLoader.load().catch(()=> console.log("catch"));
}
```
did the trick. Thanks a lot for the help.

@6matko thanks for waiting, I guess the issue is resolved then. 😃
