### ISSUE TITLE
Different translation and Datetime/number configuration

### ISSUE THREAD

**Issue by SchneiterT** [robisim74/angular-l10n#235]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
I need to be able to set the translation of strings completely separate to the localization of dates and numbers. 
This should be similar to how windows handles translation and formats. You can select English as your language for translations but use a totally different datetime/number format like German. 
So for example i would like to have English (en) as the translation for strings and German (de-DE) as the datetime/number format (Montag, 25. März, 2019). Is it possible to configure the module like this?

**Actual behavior**
I tried using the setDefaultLocale with values like (en, DE) for the example above but this seems to set the date/number localization to (en-US?). I did not find a way to set them separately.

**Comment by robisim74** [comment]
Hi @hrschoch, no It's not possible. If you don't like the mix _en-de_ provided by Intl API, you should manage a different locale by yourself,  and pass it to the date/number pipes. You could also use the official Angular pipes and its _locale_id_.
