### ISSUE TITLE
Browser history navigation issue

### ISSUE THREAD

**Issue by alexandrkrucheniuk** [robisim74/angular-l10n#236]
**Browser history navigation issue**

Issue reprodusing while **localizedRouting** usage. Location history is replacing instead of saving to 

```
const l10nConfig: L10nConfig = {
  logger: {
    level: environment.production ? LogLevel.Off : LogLevel.Warn
  },
  locale: {
    languages: [
      {code: 'ar', dir: 'rtl'},
      {code: 'en', dir: 'ltr'}
    ],
    defaultLocale: {
      languageCode: 'ar'
    },
    language: 'ar',
    storage: StorageStrategy.Cookie,
    cookieExpiration: 30,
  },
  localizedRouting: {
    format: [ISOCode.Language, /* ISOCode.Script, */ /* ISOCode.Country */]
  },
  translation: {
    providers: [
      {type: ProviderType.Static, prefix: './assets/localization/locale-'}
    ],
    caching: true,
    composedKeySeparator: '.',
    missingValue: 'Translation missed'
  }
};
```

**Expected behavior**
User can use browser navigation buttons.

**Actual behavior**
User can't use browser navigation buttons. 

**Steps to reproduce the behavior**
1. Join home page
2. Navigate to 1+ pages
3. Try to use back browser button
4. You will forwarded back to home page

**Specifications: Angular version, library version, environment, browser**
Angular 7.2.9
angular-l10n 7.1.0

All browsers.

**Comment by ihor-zinchenko** [comment]
+1

**Comment by maximhavr** [comment]
+1

**Comment by robisim74** [comment]
@alexandrkrucheniuk Please could explain "Navigate to 1+ pages"?

If in the [sample app](https://robisim74.github.io/angular-l10n-sample) I navigate to other pages, then I can use the back button without any problem.
If I change language, the url is replaced without adding it to browser history to avoid an inconsistent state.

**Comment by alexandrkrucheniuk** [comment]
@robisim74 I meant that when you navigate somewhere multiple time you can't forward back. 
Thanks for the answer! I found the issue in our code. 
We have used our custom routing **:lang/page/:pagePath**, requirements changed and I've switched to use Localized routing. Before we had added in every component router link to **:lang/page/:pagePath** , when requirement chaged we just removed **/page** from the routerLink so our pathes are **:lang/:pagePath**. Issue is that [localized-routing](https://github.com/robisim74/angular-l10n/blob/master/src/models/localized-routing.ts) probably doesn't recognize such path correctly. 


So, we just shouldn't include localizedRouting.format inside our router Links. Path should contain only path to route that marked in _app-routing.module.ts_ .

**Comment by robisim74** [comment]
It's correct. You don't need to include _lang_ in router links.

**Comment by alexandrkrucheniuk** [comment]
@robisim74 can you advice good way how to exclude route from the usage of SEO routing? I mean allow few routes to don't have _lang_ in the URL.

**Comment by robisim74** [comment]
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0
