### ISSUE TITLE
Allow cookie name to pass in the configuraton

### ISSUE THREAD

**Issue by nmarkapuram** [robisim74/angular-l10n#238]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```
Hi,

First of all - Thanks to the author & contributors of this library. It is very much useful.

When I set the storage strategy as a cookie, there is no way to set our own cookie name. I see that the cookie name (defaultLocale) is hardcoded in many places in the library.

Is it possible for you to make the cookie name as a configurable option?

Thanks in advance.

Regards.

**Comment by robisim74** [comment]
Hi @nmarkapuram,

it shouldn't be a big problem to do it.

**Comment by robisim74** [comment]
@nmarkapuram 

I did the commit. The feature will be available in the next release.

If you need the feature right away, you can implement your own custom storage: https://robisim74.github.io/angular-l10n/spec/configuration/#storage

Greetings

**Comment by nmarkapuram** [comment]
Thanks a lot @robisim74.
May I know when you are targeting next release? Also, is there any plan to update the configuration docs along with release?

**Comment by robisim74** [comment]
@nmarkapuram I just released the new version: https://github.com/robisim74/angular-l10n/releases/tag/v7.2.0

You can use the new config option `storageNames` for _defaultLocale_ (and also for _currency_ and _timezone_ yet): https://robisim74.github.io/angular-l10n/spec/configuration/#l10nconfig
 
Greetings

**Comment by nmarkapuram** [comment]
Thanks @robisim74, It's working great!!

One more small request. Can we configure domain as well?

The reason is, I have to set the cookie at the domain and not sub-domain. Currently, the cookie is set at the domain in the URL.

Ex:- abc.com is the domain and "x.abc.com" is my app domain. I want to set the cookie at ".abc.com" instead of "x.abc.com"

(Or) Can you please provide a way to extend setCookie function?

Thanks in advance.

**Comment by robisim74** [comment]
@nmarkapuram That's another issue. Since it is a specific need, as I said, you can implement your own custom storage: https://robisim74.github.io/angular-l10n/spec/configuration/#storage with a custom `setCookie `function.

**Comment by nmarkapuram** [comment]
Thanks @robisim74 for the suggestion.
