### ISSUE TITLE
Providing just translation file in lazy loaded module config

### ISSUE THREAD

**Issue by bogacg** [robisim74/angular-l10n#239]
I've added configuration settings in App Module as described in Quick Start guide with options like `caching`, `missingValue`  etc. and json file for app level used translations.

In my lazy loaded module I'm setting just **prefix** for json files location as such:

```
const l10nConfig: L10nConfig = {
  translation: {
      providers: [
        { type: ProviderType.Static, prefix: './assets/locale-lazy-' }
      ]
  }
};
```
I didn't define any options described in App Module. `logger` or `translation.caching`..etc.

It seems to work, but before I deep dive further I wanted to ask, lazy loaded module translation service instance gets other settings from App level one? Or do I have to define all same settings in lazy loaded module's config as well?

Thanks for your work by the way, loved using this library so far.

**Comment by robisim74** [comment]
Hi @bogacg,

if you are using lazy loaded modules creating a new instance of `TranslationService`, you must provide a new configuration with all the settings. See here for more details: https://robisim74.github.io/angular-l10n/spec/lazy-loading/

Greetings
