### ISSUE TITLE
missed functionality

### ISSUE THREAD

**Issue by shurfa** [robisim74/angular-l10n#24]
for the Arabic languages, different countries has different settings, we want angular2localization to trigger on different countries for the same language eg. 
ar-LY -> local-ar-LY.json should be loaded and updateTranslate
ar-SA -> local-ar-SA.json should be loaded and updateTranslate
ar-SR -> local-ar-SR.json should be loaded and updateTranslate
ar-EG -> local-ar-EG.json should be loaded and updateTranslate
and so on.
BTW. the same for English language (locale-en-US.json for the united state) & (locale-en-UK.json for United Kingdom).

**Comment by robisim74** [comment]
I understand. However the language (en) is not the _locale_ (en-US): the _locale_ is used for localization of dates and numbers. If we consider the _locale_ as the language, we force everyone to create a file for each country.
I have to consider whether I can add it as an option.

Meantime, consider whether the three-letter code of ISO 639 may be useful (unfortunately not all the codes are supported by Intl API for localization of dates and numbers).

Instead, if you do not need to localize dates and numbers, you can create your own tags for the language (avoid only the hyphen), for example: `arLY`, `arSA` etc.

**Comment by shurfa** [comment]
I' would like to thank you for every effort you did to make this work success, please go on to support the world, it is awesome work you did. it it is exactly as you recommend i did try last night with the same result (missed the locale info for numbers and dates which was a shame). So is there any how to have both for the same language though ? e.g.
for the English language we have two different English spelling as shown below, the same for arabic language there will be many expressions differences.

language--------resource-------------ex------------currency----------------date------------
enUS -------- locale-enUS --- locali**z**ation -----   $  --- Saturday, September 24, 2016
enUK -------- locale-enUK --- locali**s**ation -----   £  --- Saturday, 24 September 2016

**Comment by robisim74** [comment]
Maybe I have an idea to solve the problem in a simple way (using an ad hoc convention in the language code). Tonight I try to implement it and let you know.

**Comment by shurfa** [comment]
Great, many thanks. you will be the hero for the Localization then. (Bravo).

**Comment by robisim74** [comment]
Finally I was able to add the feature. Just call the method `useLocaleAsLanguage` at initialization of the `LocalizationService`:

```
this.locale.addLanguages(['en', 'it', 'ar']);
this.locale.definePreferredLocale('en', 'US', 30);

this.localization.translationProvider('./resources/locale-');

this.localization.useLocaleAsLanguage(); // Enables the feature.

this.localization.updateTranslation();
```

and create the json files as:

```
locale-en-US.json
locale-en-GB.json
locale-it-IT.json
locale-ar-SA.json
...
```

I added the commit that allows you to use this feature.
If you want to test it, you can do so:
- Uninstall this library from your application
- Download this repository
- Follow the instructions of the README file to build the library and install it in your application

Please let me know if it works as you expect.

Greetings

**Comment by shurfa** [comment]
well done rob,
i will do. 
BR.

**Comment by shurfa** [comment]
OK, congratulations ! . well done rob, it works as a charm exactly as we expect with the exception of the following 2 points:
1- the numbers system used by some Arabian countries is hendu i.e. (ر.س.‏ ٨٬٨١٥٫٦٦) as in Saudi Arabia and Egypt while the rest e.g. LIBYA use Arabic system i.e.(80815,66). if you follow windows system locale you may find some thing to check.
2- what about the locale-list-en.json does it need to change that too ? i.e. it did not change accordingly.

Best regards.

**Comment by robisim74** [comment]
Hi,

1- This library supports the numbering systems as included in [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) and in [cldr](http://www.unicode.org/cldr/charts/latest/by_type/core_data.numbering_systems.html). For using see [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#4).
2- Do you have a new instance of the LocalizationService? Remember to call `useLocaleAsLanguage`  method at the new initialization (I have not declared it as _static_, because each module can have a different logic).

Greetings

**Comment by shurfa** [comment]
Dear rob, while I continue test the last changes a new issue raised, please take care of.
#Issue:
when you browse the sample site and change to any RTL language then exit the browser. then open the browser again you will get the right translation for that language  but the wrong direction (LTR) the default.
BR.

**Comment by robisim74** [comment]
Sorry, but I don't see this error in the [sample site](http://robisim74.github.io/angular2localization/#/home). Or you're talking about your site? In this case, remember to check the current language in the AppComponent: `ar`, and not `ar-SA` etc. like [this](https://github.com/robisim74/angular2localization/blob/gh-pages/app/app.component.ts).

**Comment by shurfa** [comment]
you are right, It was my mistake, the problem was the condition test as you expect.
the final thing Rob, i found that it is not possible to provide the eastern Arabic numbers system ( ٣٫١٤١٥٩) as an input to the Validation form unless you copy it from e.g. Home Page (PI: 3.14159). what you thing might be the cause of this problem ?
i did change the default windows locale to Arabic SA as provided, and the numbering system, the keyboard layout etc., with no success.
![image](https://cloud.githubusercontent.com/assets/4338912/18881517/ebb890f0-84db-11e6-94fa-bebb67d4d5c5.png)

![image](https://cloud.githubusercontent.com/assets/4338912/18881572/24393614-84dc-11e6-81bb-bedd9fcabbe3.png)

BR.

**Comment by robisim74** [comment]
Why do you want to change all system settings? Try to use a keyboard on line, like [this](http://www.arabic-keyboard.org), or download a virtual keyboard.

**Comment by shurfa** [comment]
OK. Rob, i may miss explain it. all i need is to make google chrome or any other web browser recognize the numbering system as i change the web site language e.g. when i select en-UK it accepts 3.14 as an input without intervention, and when we select ar-SA it accepts ٣٫١٤ and then you validate appropriately according to the selected locale.
Is that clear ?
Thanks.

**Comment by robisim74** [comment]
Ok, that's another question.
- If you want the browser to ricognize the number, you have to change the language in the browser, add the attribute `type="number"` in your input tag, and remove `validateLocaleNumber`.
- If you want the app to ricognize the number, let the browser as it is, don't put the attribute and use the `validateLocaleNumber` (this validator requires that the input is in text format, in order to evaluate the signs of all languages).

I suggest using this second mode, because not all browsers support this control, and especially because a user can have a browser language, but view the app in another language.

**Comment by shurfa** [comment]
Sorry Rob, the issue is a bit complicated and i will summarize it as follows:
1- i did test your sample site with different Browsers and i get a different result from the validator as below.
**on IE 11 as:**

![image](https://cloud.githubusercontent.com/assets/4338912/18962756/c28fd648-867a-11e6-8c93-f0fc91865518.png)

**and on google chrome as** 
![image](https://cloud.githubusercontent.com/assets/4338912/18962640/5de730b0-867a-11e6-80b8-3c4255d2e544.png)

2- I still can't input the numbers as i type in the proper locale format i.e (٣٫١٤), may be it is a browser problem.

BR.

**Comment by robisim74** [comment]
Ok, I fixed the problem with IE and Edge.

Please, next time, go to different issue, so that other users can be updated.

In the coming days, I will publish the updated version of the library and sample app.

Greetings

**Comment by shurfa** [comment]
Thanks Rob, excellent ! keep going.

**Comment by robisim74** [comment]
I released the new version. Greetings
