### ISSUE TITLE
SEO Service to provide attribute type selection for meta tags

### ISSUE THREAD

**Issue by bogacg** [robisim74/angular-l10n#240]
**I'm submitting a...**
```
[] bug report
[X] feature request
[ ] support request
```

**Expected behavior**
SEO Service to have selection weather to add `name` or `property` attribute for **meta tags**. [Facebook Open Graph](https://developers.facebook.com/docs/sharing/webmasters/#markup) uses `property` attribute for meta tag.

**Actual behavior**
Right now it only adds/updates `name` attributes.

**Steps to reproduce the behavior**
Follow same steps described in [SEO by locales](https://robisim74.github.io/angular-l10n/spec/seo/) document and add to your JSON properties like:

```
    "home": {
        "title": "Home Title",
        "description": "Home description.",
        "og:title": "Home Title",
        "og:description": "Home description."
    },
```
all above gets injected to header in form `<meta name="og:description"...` but we need some (for Facebook case) in `<meta property="og:description"` format

Side note:

I see on Stackoverflow questions related to Open Graph validity, some people wrote using `name` attribute gives a warning on Facebook side but still validates and uses.

**Comment by robisim74** [comment]
@bogacg I see: but I prefer to follow only the HTML5 spec (see also this SO question: https://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property)

In any case, starting from the [SearchService](https://github.com/robisim74/angular-l10n/blob/master/src/services/search.service.ts) class, you can easily create your custom class that uses _property_, or different combinations.
