### ISSUE TITLE
Angular v8 update

### ISSUE THREAD

**Issue by bogacg** [robisim74/angular-l10n#244]
Angular v.8 is expected week of May 22. Upgrading projects from previous version shouldn't be difficult yet there are new concepts (such as **differential loading**) that might require used libraries to be on the same page in terms of dependencies to work properly.

At the moment I'm porting a project to Angular v.8 (rc.4) and while it works fine in dev mode, AoT build does not. I can trace back to a **zone.js** error, and since v8 release candidate upgraded its depended version, I'm thinking **angular-l10n** might have to as well at some point.

**Comment by robisim74** [comment]
I tried updating my apps to Angular v8 and I didn't get any errors. `zone.js` is just a devDep for the library, what kind of error you got?

However, when Angular v8 is released, a new version for Angular v8 of this library will be released as soon as possible.

**Comment by bogacg** [comment]
This is the error I'm getting on the console when I publish:
```
Uncaught Error: In this configuration Angular requires Zone.js
 at Object.6dTf (polyfills-es2015.630faf
```

**Comment by robisim74** [comment]
That's weird. I only have two polyfills: `polyfills` and `polyfills-es5`. The first is always loaded, while the second only if I open IE. Why do you have `polyfills-es2015`?

**Comment by bogacg** [comment]
I'm trying out Angular 8 with CLI rc-4 now and this is the output for `ng build --prod` on a basic project (with Material & Service Worker libs added). However build output was same in previous rc as well.

```
Date: 2019-05-24T13:09:06.921Z
Hash: 8501619cc276d4a555ad
Time: 28232ms
chunk {0} runtime-es5.741402d1d47331ce975c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.f7d66caa470011a6978b.js (main) 353 kB [initial] [rendered]
chunk {2} polyfills-es5.943113ac054b16d954ae.js (polyfills) 111 kB [initial] [rendered]
chunk {3} styles.fc478d4fa80f7a6ac0ef.css (styles) 61.5 kB [initial] [rendered]

Date: 2019-05-24T13:09:29.004Z
Hash: 895162ad818bd0edc0a6
Time: 22041ms
chunk {0} runtime-es2015.858f8dd898b75fe86926.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.256be0ae2f08b452d7de.js (main) 308 kB [initial] [rendered]
chunk {2} polyfills-es2015.e954256595c973372414.js (polyfills) 36.8 kB [initial] [rendered]
chunk {3} styles.fc478d4fa80f7a6ac0ef.css (styles) 61.5 kB [initial] [rendered]
```

**Comment by robisim74** [comment]
You're right: I was still using the `es5` target. Now I get the error.

Also in reference to your pr (#245 ), have you already verified that updating the dependencies the error disappears?

**Comment by bogacg** [comment]
I'll tell when I get back home (I did that work on my desk computer), I really forgot what was the outcome because there is a [breaking change](https://next.angular.io/guide/static-query-migration) in rc-5 published last night, which affected another UI library I'm using. It's all a mess now. I'll get back to you.

**Comment by robisim74** [comment]
Ok, np. But I think I found the reason: if I remove `import 'web-animations-js';` from `polyfills.ts` in my app, then it works without problems.
Therefore it is not a problem of this library. I think we should open an issue in angular-cli repo.

**Comment by robisim74** [comment]
I opened an issue on angular-cli repo: https://github.com/angular/angular-cli/issues/14518

**Comment by robisim74** [comment]
The solution is the angular-cli repo. I'm closing this.
