### ISSUE TITLE
LocalizedRouter initialization 

### ISSUE THREAD

**Issue by havran** [robisim74/angular-l10n#247]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[*] support request
```

Hi. As i wrote in #246, i want configure locale (and probably localizedRouting or other parts of l10n configuration)  dynamically - per hostname used. This work but i have problem with my configuration, which is loaded by APP_INITIALIZER and return observable.

In my LocalizationConfig, i need for getting current siteId, read information from configuration and then from my SiteService. This works but one small problem remains.

Seems LocalizedRouting is initialized too late and then subscription to routing events miss InitialNavigation event on first page loading https://github.com/robisim74/angular-l10n/blob/b07d11cfe1bbd947fc204dad37327180c6fa5ee0/src/models/localized-routing.ts#L29-L34 

Then  logic which remove language prefix from URL and redirect routing to URL remainder is not fired and subscription to routing event NavigationEnd incorrectly add language prefix to URL.

I think this is because initialNavigation in my router is set to 'enabled' and navigation is started in APP_INITIALIZER. I can't (or don't want) use initialNavigation='disabled' (and then router.initialNavigation() in app.component), because this cause screen blink on SSR page load.

Any idea how to solve this problem? Thanks.

**Comment by robisim74** [comment]
Hi @havran,

unfortunately it is not easy to understand what is happening in your app without a repro.

However: are you sure that the _NavigationStart_ event is not fired on first page loading? In #246 I see that the _locale_ configuration is empty, so it does not even contain the list of available languages. The method `redirectToPath` indeed, called when NavigationStart event is fired, does nothing without the list of available languages.

I think `LocalizedRouting` is not initialized _too late_, but too soon, before the configuration settings are evaluated.

Make sure that your `SetConfig` method to be completed before the `load` method of `l10nloader` is invoked.

**Comment by havran** [comment]
Hi, i create repository which demonstrate problem which i have.

https://github.com/havran/async-problems-l10n

**Comment by robisim74** [comment]
Ok, thanks for the repro. There are two problems:
- `initialNavigation: 'enabled'`: are you sure you need it?
- a workaround is to subscribe to the event in your app (i.e. in `app-rounting`):

```
  constructor(private router: Router, private lr: LocalizedRouting) {
    this.router.events.pipe(
      filter((event: any) => event instanceof NavigationStart)
    ).subscribe((data: NavigationStart) => {
      (<any>this.lr).redirectToPath(data.url);
    });
  }
```
I could also make _public_ `redirectToPath` method in the next release. But you should still provide the list of available languages during configuration:

```
  locale: {
    languages: [
      { code: 'en', dir: 'ltr' },
      { code: 'sk', dir: 'ltr' },
      { code: 'sv', dir: 'ltr' },
    ],
  },
```

**Comment by havran** [comment]
Thank you for answer. `initialNavigation: 'enabled';` should prevent page blink if is page loaded from SSR, then we don't want use `'disabled'` here. This can be set dynamic way, i can try if this solve problem on both sides (SSR and local development).

Part of trick is provide locales dynamically, by hostname (app should serve different content for different hostname - there are different backends per hostname and every site locales can be configured differently).

Anyway, thank you again.
