### ISSUE TITLE
Latest version is not published to NPM

### ISSUE THREAD

**Issue by bogacg** [robisim74/angular-l10n#248]
Latest commit does not have a tag for new version, maybe also because **package.json** has `"private": true` set, bottom line latest version is not published to NPM.

Thanks

**Comment by robisim74** [comment]
I have not published a new version to npm because at the moment does not seem to need it. The current version seems to work well with Angular v8. Greetings

**Comment by bogacg** [comment]
I did not have any errors using 7.2.0 either but when I saw latest commit I thought it wasn't intentional not to publish it. 👌 All good then
