### ISSUE TITLE
translation changes only in components extend the locale

### ISSUE THREAD

**Issue by dansenzhou** [robisim74/angular-l10n#25]
Hi, I am wondering if I did something wrong or it was implemented like this:

when I want to change the locale by selector/button. Only those labels/messages in the components which extends Locale will change, labels in other components still keeps the original localization.

**Comment by robisim74** [comment]
Yes, it's correct. Because the pipes are pure, each component must update the `lang` parameter of its pipes. Extend the `Locale` class does it.
