### ISSUE TITLE
Nothing translated after update from v4 to v7

### ISSUE THREAD

**Issue by Neill83** [robisim74/angular-l10n#250]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```

**Expected behavior**
Translations to be working as intended.

**Actual behavior**
First of all, I updated from v4.1.5 to v7.2.0.
I have two languages, german and english. German is the fallback. If I switch to english, the fallback is translated and not the english version, the l10nConfig seems to be OK.

**Specifications: Angular version, library version, environment, browser**
Angular 7.2.15
l10n 7.2.0
Chrome
in development mode

Maybe you can help me.

Thanks a lot

**Comment by Neill83** [comment]
it's loading the wrong json

![image](https://user-images.githubusercontent.com/9987324/58933954-34489a80-8769-11e9-8251-59ecddf9e948.png)

The status is 200
![image](https://user-images.githubusercontent.com/9987324/58934018-6d810a80-8769-11e9-8b2a-8bdb0f1e7a72.png)

The l10nConfig seems to be OK
![image](https://user-images.githubusercontent.com/9987324/58934082-bb960e00-8769-11e9-9871-c8bddbdad900.png)

but it translates into german instead of english because of the wrong loaded json

**Comment by robisim74** [comment]
Please, post the code of l10n config.

**Comment by Neill83** [comment]
```
let defaultLocale:DefaultLocale =
        lang === 'de' ? { languageCode: 'de', countryCode:  'DE' } : { languageCode: 'en', countryCode:  'GB' };

    let currency:string = lang === 'de' ? 'EUR' : 'GBP';

{
        logger:      {
            level: logLevel
        },
        locale:      {
            languages:     [
                {
                    code: 'en',
                    dir:  'ltr'
                },
                {
                    code: 'de',
                    dir:  'ltr'
                }
            ],
            language:      lang,
            defaultLocale: defaultLocale,
            currency:      currency,
            storage:       StorageStrategy.Disabled
        },
        translation: {
            providers:            [
                {
                    type:   ProviderType.Static,
                    prefix: localePrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: pluginPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: crmPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: dataHistoryPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: cmsPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: plentyBasePrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: processesPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: printHistroyPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: terraComponentsLocalePrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: feedbackPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: propertiesPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: systemPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: logPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: warehousePrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: orderPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: boardsPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: catalogsPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: elasticSyncPrefix
                },
                {
                    type:   ProviderType.Static,
                    prefix: reportPrefix
                }
            ],
            caching:              true,
            composedKeySeparator: '.',
            i18nPlural:           false
        }
    }

```


I am getting the language from localStorage since I have an "external" login where I can select the language.

So until here it works fine, but then the wrong language files are being loaded.

**Comment by robisim74** [comment]
If the problem is when the app is loaded, try to see in which order the language is set: https://robisim74.github.io/angular-l10n/spec/configuration/#how-the-language-is-defined-at-the-first-loading

If the problem is when you change language, maybe for some reason you are still passing `de` and not `en`. What is the code to change language? are you sure it's passing the correct _lang_ value?

**Comment by Neill83** [comment]
![image](https://user-images.githubusercontent.com/9987324/58937151-e2584280-8771-11e9-90bd-60003f1bd945.png)
The question is... it tries to get the language from the browser before trying to get it from the config?

if it is that way... that is bad

**Comment by Neill83** [comment]
```
let langInLocalStorage:string = localStorage.getItem('my_lang');
    let lang:string = null;

    if(!isNull(langInLocalStorage))
    {
        lang = langInLocalStorage;
    }
    else
    {
        lang = navigator.language.slice(0, 2).toLocaleLowerCase();

        if(lang !== 'de' && lang !== 'en')
        {
            lang = 'en';
        }

        localStorage.setItem('my_lang', lang);

        let date:any = moment(new Date());
        date.add('30', 'days');
        date.format();

        document.cookie = 'my_lang = ' + lang + '_' + lang.toUpperCase() + ';path=/;expires=' + date.toString();
    }

```

But that is not relevant i think. My selected language is English and i get German because of your configuration as i said above?

**AND** it is almost the same config as it was for v4.2.5. We only added the defaultLocale and currency stuff.

**Comment by robisim74** [comment]
Yes, the browser language wins. If you want force the language when the app start, you should call `setLanguage` or `setDefaultLocale` after the initialization.

From v4 to v7 there aren't big breaking changes. Make sure you are using rxjs > 6, and for _DefaultLocale_ and _Currency_  you are using `LocalizationModule` and not `TranslationModule` as well (you should also remove _lang_ from the config).

**Comment by robisim74** [comment]
Please, see also the second scenario: https://robisim74.github.io/angular-l10n/spec/configuration/#second-scenario-you-need-to-translate-messages-dates-numbers
