### ISSUE TITLE
Error when compiling with Ivy

### ISSUE THREAD

**Issue by magnattic** [robisim74/angular-l10n#253]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Compiles with `"enableIvy": true`.

**Actual behavior**

`ERROR in node_modules/angular-l10n/src/models/base-directive.d.ts(36,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).`

**Specifications: Angular version, library version, environment, browser**
```
Angular CLI: 8.1.0-beta.2
Node: 11.14.0
OS: linux x64
Angular: 8.1.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0-beta.2
@angular-devkit/build-angular              0.801.0-beta.2
@angular-devkit/build-ng-packagr           0.801.0-beta.2
@angular-devkit/build-optimizer            0.801.0-beta.2
@angular-devkit/build-webpack              0.801.0-beta.2
@angular-devkit/core                       8.1.0-beta.2
@angular-devkit/schematics                 8.1.0-beta.2
@angular/cdk                               8.0.1
@angular/cli                               8.1.0-beta.2
@angular/material                          8.0.1
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.1.0-beta.2
@nguniversal/express-engine                8.0.0-rc.1
@nguniversal/module-map-ngfactory-loader   8.0.0-rc.1
@schematics/angular                        8.1.0-beta.2
@schematics/update                         0.801.0-beta.2
ng-packagr                                 5.3.0
rxjs                                       6.5.2
typescript                                 3.6.0-dev.20190618
webpack                                    4.34.0
```

**Comment by robisim74** [comment]
@magnattic In Angular v8, Ivy is still in preview (see https://blog.angular.io/a-plan-for-version-8-0-and-ivy-b3318dfc19f7). Many problems are still possible, but they do not depend either on apps or libraries, because there must be full backwards compatibility.

However, I did a test by enabling Ivy in the example app (angular 8.0.0 and angular-l10n 8.0.0) and I see no compilation errors: some things still don't work (like innerHtml or the Material menu).

Of course, when Ivy is finally released, if something needs to be corrected even in this library to be supported, it will be done.

Meanwhile, this is an open source project, and if you want to contribute to anticipate this support, every contribution is welcome.

**Comment by magnattic** [comment]
> However, I did a test by enabling Ivy in the example app (angular 8.0.0 and angular-l10n 8.0.0) and I see no compilation errors: some things still don't work (like innerHtml or the Material menu).

Did you use the `translate` Directive? I suspect that the problem is that it inherits from BaseDirective, which has `@Input`s, but is not a `@Directive` itself. This doesn't seem to work with Ivy (yet). I hope they fix it soon.

A workaround might be to add dummy directive metadata to BaseDirective, like

``` 
@Directive({ selector: 'thisWillNeverBeUsed' })
export abstract class BaseDirective implements AfterViewInit, OnChanges, OnDestroy {
   ...
}
```

But I haven't tested yet if that actually works...

**Comment by robisim74** [comment]
I tried updating the sample app: https://github.com/robisim74/angular-l10n-sample, adding:

```
  "angularCompilerOptions": {
    "enableIvy": true
  }
```

It uses all the features of this library.

**Comment by magnattic** [comment]
Seems this is a regression. I updated the sample app to 8.1.0-next.3 and got the error I am seeing above.

Here is the issue in the angular repo: https://github.com/angular/angular/issues/31160

**Comment by robisim74** [comment]
Thanks for reporting

**Comment by robisim74** [comment]
It should be solved through https://github.com/angular/angular/commit/eb6281f5b471e55d5c761065e17ab2a293690d29
