### ISSUE TITLE
[params] has the wrong type!

### ISSUE THREAD

**Issue by magnattic** [robisim74/angular-l10n#255]
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
A JSON object can be assigned to the [params] Attribute of the translate pipe.

As per the documentation:

``` 
<p [params]="{ user: username, NoMessages: messages.length }" l10nTranslate>userNotifications</p>`
```

**Actual behavior**
The params property is of type string.
This leads to errors when compiling with the new Ivy renderer when using `fullTemplateTypeCheck: true` in the tsconfig.json.

> ```
> ERROR in __ng_typecheck__.ts:1800:30 - error TS2322: Type '{ "min": number; "max": number; }' is not assignable to type 'string'.
> 
> 1800         var _t28 = _ctor44({ params: {
>                                   ~~~~~~
> 
>   node_modules/angular-l10n/src/directives/translate.directive.d.ts:11:5
>     11     params: string;
>            ~~~~~~
>     The expected type comes from property 'params' which is declared here on type 'Partial<Pick<TranslateDirective, "l10nTranslate" | "params" | "translate">>'
> ```

**Steps to reproduce the behavior**
Compile a angular-l10n project with the most recent angular versions and 
``` 
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
``` 

**Specifications: Angular version, library version, environment, browser**

> Angular CLI: 8.1.0-rc.0
> Node: 11.14.0
> OS: linux x64
> Angular: 8.2.0-next.0
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... platform-server, router
> 
> Package                                    Version
> --------------------------------------------------------------------
> @angular-devkit/architect                  0.801.0
> @angular-devkit/build-angular              0.801.0
> @angular-devkit/build-ng-packagr           0.801.0
> @angular-devkit/build-optimizer            0.801.0
> @angular-devkit/build-webpack              0.801.0
> @angular-devkit/core                       8.1.0
> @angular-devkit/schematics                 8.1.0-rc.0
> @angular/cdk                               8.0.1
> @angular/cli                               8.1.0-rc.0
> @angular/material                          8.0.1
> @ngtools/json-schema                       1.1.0
> @ngtools/webpack                           8.1.0
> @nguniversal/express-engine                8.0.0-rc.1
> @nguniversal/module-map-ngfactory-loader   8.0.0-rc.1
> @schematics/angular                        8.1.0-rc.0
> @schematics/update                         0.801.0-rc.0
> ng-packagr                                 5.3.0
> rxjs                                       6.5.2
> typescript                                 3.5.2
> webpack                                    4.35.2

**Comment by robisim74** [comment]
Fixed in v8.1.0.

Thanks for reporting.

Greetings
