### ISSUE TITLE
Decorators not working with AoT and Ivy

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-l10n#257]
https://github.com/angular/angular/issues/31495

**Comment by robisim74** [comment]
This problem occurs up to version 8 of angular-l10n with Ivy enabled.

**Comment by vvolodin** [comment]
So this is why the new docs are not using @Language anymore? I'm a bit confused, because I've recently upgraded to Angular 9, enabled both AoT and Ivy and angular-l10n v. 8.1.2 seems to work fine, perhaps I'm missing something...

**Comment by robisim74** [comment]
@vvolodin  Yes, the new version of the library (v9) doesn't use decorators like `@Language` because they don't work with Ivy (the Angular issue is still open).
The old version of the library (v8) should work with Ivy if:
- you don't use pipes
- you use pipes but you reload the app when language changes

**Comment by vvolodin** [comment]
Ah, thanks for clarification. Indeed, my app was reloading the page after language change so I didn't notice anything.

**Comment by robisim74** [comment]
After over a year this issue was fixed in [Angular v10.0.5](https://github.com/angular/angular/blob/master/CHANGELOG.md#1005-2020-07-22). So also the v8 of the library works with Ivy.
