### ISSUE TITLE
Expose method on TranslationService to know if a key is missing

### ISSUE THREAD

**Issue by Etchelon** [robisim74/angular-l10n#258]
**I'm submitting a...**
```
[ ] bug report
[X] feature request
[X] support request
```
Hi again Roberto,
I'm wondering if it's possible to know if a translation is present in the TranslationService's data. I need this because I'm implementing a custom fallback mechanism in a piece of my application.
During development everything was fine: we compared the return value of translationService.translate with the key. If equal, the translation is missing and we do the fallback.
Problem is: in production, the missingValue function is not _.identity but something else, so the comparison fails and we return that instead of the fallback value.
I have worked around the issue by doing the following:
```
const missingValueSentence = this.translationService.getConfiguration().missingValue(key);
const translation = this.translationService.translate(key);
if (translation === missingValueSentence) {
  // Do the fallback
}

```
But it would be nicer to just do:
```
const translation = this.translationService.hasKey(key)) { // or this.translationService.has(key)
    ? this.translationService.translate(key)
    : *the fallback*;
```
What do you think about it?

**Comment by robisim74** [comment]
Hi Andrea,

ok, it can be useful.

**Comment by robisim74** [comment]
Added in v8.1.0.

Greetings
