### ISSUE TITLE
How to apply localization in Primeng <p-tabView> header attribute to disply header on different language.

### ISSUE THREAD

**Issue by maulikta** [robisim74/angular-l10n#259]
I want to apply angular-l10n on below PrimeNG component.
```
<p-tabView>
        <p-tabPanel header="Header1">
           Content 1
        </p-tabPanel>
        <p-tabPanel header="HeaderSecond" >
            Content 2
        </p-tabPanel>
        <p-tabPanel  header="Header3">
            Content 3
        </p-tabPanel>
    </p-tabView>
```
I have tried below code for one of header :

 **`<p-tabPanel l10n-header header="headertext" l10nTranslate>`**

But its not `working...`

My locale json file is like below:
locale-en.json
{ 
"Header1":"Header1_en",
    "HeaderSecond":"Header2_en",
    "Header3":"Header3_en"
}

locale-it.json
{ 
"Header1":"Header1_IT",
    "HeaderSecond":"Header2_IT",
    "Header3":"Header3_IT"
}

.Is there any solution for above case....

**Comment by robisim74** [comment]
Hi @maulikta,

`header` in PrimeNg TabView component is rendered in a different position of the DOM (not in the subtree): in cases like this, the only way is to use the translate pipe (see also #194).

Greetings

**Comment by maulikta** [comment]
Thanks for your support....
