### ISSUE TITLE
Text is not being translated in typescript

### ISSUE THREAD

**Issue by Neill83** [robisim74/angular-l10n#26]
Hi,

I'm using Angular 2.0.1 with Router 3.0.1

My problem is that i have a login page where i translate the text to english or german. In html my text is being translated:

`<label>{{'language' | translate:lang}}:</label>`

This works fine for me.

But now i'm trying to translate my text in `ngOnInit` like:

```

ngOnInit()
    {
        this.languages.push({
                                value:   'default',
                                caption: this.localization.translate('default')
                            },
                            {
                                value:   'de',
                                caption: this.localization.translate('german')
                            },
                            {
                                value:   'en',
                                caption: this.localization.translate('english')
                            });

        this.localization.updateTranslation();
    }


```

Now im calling the Component directly by url

`localhost:4200/login`

and my text won't be updated. If i navigate through router (on response of a rest-call), it works fine.

Thanks

**Comment by robisim74** [comment]
Hi, you have to call _updateTranslation_ method only when you initialize the service. To update the translations in the components, you must subscribe _translationChanged_ event. See [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.5).

**Comment by Neill83** [comment]
Hi again, maybe i didn't explain it that good. I mean that the translation is not done. I'm getting the i18n-keys as result

![bildschirmfoto 2016-10-11 um 10 24 55](https://cloud.githubusercontent.com/assets/9987324/19263513/fc878956-8f9c-11e6-9ba0-8621b2434389.png)

and this is what i expect when i call `localhost:4200/login` directly:

![bildschirmfoto 2016-10-11 um 10 26 16](https://cloud.githubusercontent.com/assets/9987324/19263558/2e6f09b2-8f9d-11e6-9795-d0f8107acfd2.png)

(this is what i get when i navigate to login through router and that is what i want by routing directly)

Thanks

**Comment by robisim74** [comment]
This happens because you load values before the http get of the translation files has been completed. As said, the only way is to subscribe to the _translationChanged_ event. See also #16. If this doesn't work, please post the code of login.component, router and app.component, so I can try it tonight.

**Comment by Neill83** [comment]
So you don't provide a resolver for this to load a component after resolver is done?

Or maybe should be provided a function which is fired on http 200 response

**Comment by robisim74** [comment]
As said, the library already provides the event _translationChanged_ (fired on response) to update translations: if you want to reload a component, you must implement it in your code. But it is not necessary, if you initialize the variables to be translated in the constructor of the component as indicated.

**Comment by Neill83** [comment]
We found the solution:

```

this.localization.translationChanged.subscribe(
          () => {
              this.languages.forEach((lang:SelectBoxValue) => {
                  switch(lang.value)
                  {
                      case 'de':
                          lang.caption = this.localization.translate('german');
                          break;
                      case 'en':
                          lang.caption = this.localization.translate('english');
                          break;
                      case 'default':
                          lang.caption = this.localization.translate('default');
                          break;
                  }
              });
          }
        );

```

Thanks for your help!

Regards
