### ISSUE TITLE
TypeError: Cannot read property 'get' of null TypeError: Cannot read property 'get' of null at L10nTranslationProvider.getRequest

### ISSUE THREAD

**Issue by jaroslawmajdzinski** [robisim74/angular-l10n#263]
**I'm submitting a...**
[ ] feature request
[x ] support request
```

**Expected behavior**

**Actual behavior**

TypeError: Cannot read property 'get' of null TypeError: Cannot read property 'get' of null at L10nTranslationProvider.getRequest

**Steps to reproduce the behavior**

StackBlitz Template: https://stackblitz.com/edit/angular-l10n

Angular 8.2.4
rxjs 6.5.2.

Hi! First time when I'm asking for support then please forgive me.

**Comment by robisim74** [comment]
Hi, are you importing Angular `HttpClientModule` in your AppModule?

**Comment by jaroslawmajdzinski** [comment]
Hi !

Thanks, Roberto, for your answer.
Yes, you are right - I didn't do,
then after I added HttpClientModule everything is alright.
I missed this small thing.


Jarek

pt., 6 wrz 2019 o 15:08 Roberto Simonetti <notifications@github.com>
napisał(a):
