### ISSUE TITLE
Add Transloco to comparison table

### ISSUE THREAD

**Issue by IlCallo** [robisim74/angular-l10n#264]
**I'm submitting a...**
```
[ ] bug report
[x] feature request
[ ] support request
```

**Expected behavior**

More or less a month ago a new i18n library was revealed: https://github.com/ngneat/transloco.
It would be interesting to see how does it places with respect to this library, which is pretty mature and feature complete.

Twin issue on their repo: https://github.com/ngneat/transloco/issues/81

**Actual behavior**

Comparison is missing from the table.

**Comment by robisim74** [comment]
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0
