### ISSUE TITLE
Browser history not working when using lang in routerLink

### ISSUE THREAD

**Issue by 6matko** [robisim74/angular-l10n#265]
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[X] support request
```

**Expected behavior**
When routerLink has language added, browser history should be recorded (working) - Back button works correctly.
**Actual behavior**
For SEO purposes (Using SSR) we add lang to our routerLink in order for crawlers to get correct url with language. We are doing it because we have dynamic pages with dynamic menu which means we define our menu navigation via Admin panel and Admin is setting routes as simple string. For example, we have route `news` so Admin types URL: `news`
Menu items are rendered via Angular and routerLink will be `news`. With this behavior everything is working fine and angular-l10n is adding language to location, back button (browser history) is also working fine, BUT if we inspect html then we see that rendered anchor is "https://website.com/news" instead of "https://website.com/en/news". So to solve this we are adding following code: 
```
<a class="nav-link" routerLink="{{lang}}/{{item.url}}">{{item.title}}</a>
```
{{lang}} =
```
@Language() lang;
```
And with this solution browser history is not working. Navigation is not recording. From some chatting with my colleagues we came to idea that Angular routing is not happening correctly and therefore there is a following bug.
**Steps to reproduce the behavior**
1. Add language to routerLink
2. Navigate to different routes (that contain language in routerLink)
3. Try to use browser BACK button

**Specifications: Angular version, library version, environment, browser**
Angular 7.2.0
Angular-l10n 7.1.0

**UPDATE:**
Maybe there is some kind of way to include language into routerLink / rendered href ?
P.S. Looks like this is what causes it: https://github.com/robisim74/angular-l10n/blob/master/src/models/localized-routing.ts#L113
But If I change it to "true" then it records route twice and I have to press "back" twice 🤔

**Comment by robisim74** [comment]
Hi @6matko,

this behavior has already been seen here: #236.

The routing of l10n was designed to navigate without adding _lang_ to each link. So if you add the _lang_ it executes these lines: https://github.com/robisim74/angular-l10n/blob/8d22a657295c9bd22ae4112af134cdebe7072cc6/src/models/localized-routing.ts#L110-L114 as you noticed. The segment with the language, in fact, is only expected during the first bootstrap of the app (therefore from external links)

Changing this behavior is a new feature: maybe I'll add it to a new version, but not to a past one as v7.

**Comment by 6matko** [comment]
Had to create custom routerLink directive which adds href with current language on <a> and on click navigates through router.navigate and therefore closing this. Thanks for response.
