### ISSUE TITLE
Search Service in new architecture?

### ISSUE THREAD

**Issue by bogacg** [robisim74/angular-l10n#268]
I can't see Search Service in new documentation. We won't have it in new version?
Any suggestion for an alternative?

I like the leaner new way of new architecture though I had to make changes in my project. 👍
Thank you

**Comment by robisim74** [comment]
The logic of the new architecture is to provide only the essential classes and methods to be lighter and more customizable.
Therefore the Search Service was excluded, but you can take it from the previous version (https://github.com/robisim74/angular-l10n/blob/angular_v8/src/services/search.service.ts), updating methods.
