### ISSUE TITLE
Thanks a lot for pr! Yes it is only an environmental problem: this library has in the `tsconfig` `"noImplicitAny": true`

### ISSUE THREAD

**Issue by ravipatel3482** [robisim74/angular-l10n#269]
Thanks a lot for pr! Yes it is only an environmental problem: this library has in the `tsconfig` `"noImplicitAny": true`

_Originally posted by @robisim74 in https://github.com/robisim74/angular-l10n/issues/9#issuecomment-220242510_
Still Not Work  
I have Code Like 
 getEmployeeByCode(empCode: string): Observable<IEmployee> {
        return this._http.get('https://localhost:44300/api/employees/' + empCode)
            .map((response: Response) => <IEmployee>response.json()).catch(this.handleError);
    }
    // Notice the method return type is Observable<IEmployee[]>
    getEmployees(): Observable<IEmployee[]> {

        return this._http.get('https://localhost:44300/api/employees')
            .map((response: Response) => <IEmployee[]>response.json()).catch(this.handleError);
    }
    
I Getting Broblem For Obsrvable<IEmployee[]> vs Observable<Iemployee>
I employee is Interface Class Declare In another Ts File

**Comment by robisim74** [comment]
@Raviniki You are referring to an issue over three years ago. Also I don't see the use of angular-l10n library in your code. So I'm closing this issue.

**Comment by ravipatel3482** [comment]
Never mind I get a solution
