### ISSUE TITLE
Country or Language localization

### ISSUE THREAD

**Issue by EmmanuelFRANCOIS** [robisim74/angular-l10n#27]
@robisim74 Very nice module!
I try to implement it in my new Ionic 2 app (rc0), and I'm facing a fondamental problem:
My app relies heavily on financial calculations and planning.
So I need to display dates and numbers in the right format according to the user country, not the user language.
Indeed, for example, a date is written differently in US than in UK:
- US: MM/DD/YYYY
- UK: DD/MM/YYYY

even if the language code for these two countries are the same : "en".
Same for numbers and currencies.
So my question is: is it possible to format dates, numbers, percents and currencies localized by country instead of language?

**Comment by robisim74** [comment]
Hi @EmmanuelFRANCOIS,

yes, you are in the [Third scenario](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#3.3). See also [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.2).

The [sample app](http://robisim74.github.io/angular2localization/#/home) is built in this way: if you change the country, from the United States to the United Kingdom, you will see change the format of dates and numbers.

Greetings

**Comment by EmmanuelFRANCOIS** [comment]
Ah ok!
Didn't see this.
Thanks for your help!
