### ISSUE TITLE
Readme with configuration wrong

### ISSUE THREAD

**Issue by ruisilva450** [robisim74/angular-l10n#270]
Hi,

I was trying to configure the advanced initialization and got saw that the main readme states:
```
export function initL10n(l10nLoader: L10nLoader): () => Promise<void> {
    return () => l10nLoader.init();
}
```
But ```L10nLoader``` doesn't even have the ```init()``` function... 

What it has is the ```load()```.

Am I missing something?

**Comment by robisim74** [comment]
The current Readme is for Angular v9 and Angular l10n 9.0.0-rc.0 See https://github.com/robisim74/angular-l10n/releases

If you are using previous versions, please see https://github.com/robisim74/angular-l10n#previous-versions

**Comment by ruisilva450** [comment]
Totally got it wrong.
Sorry about that.
