### ISSUE TITLE
Pipes are not working: L10N_LOCALE & L10nLocale not found.

### ISSUE THREAD

**Issue by mike-pixel** [robisim74/angular-l10n#274]
I followed your instructions regarding the pipes. I want to format and translate a few dates in one of my component html template.

I tried adding the following `@Inject` as specified in the documentation (because otherwise I would get the "pipe not found" error):
```
export class AppComponent {
    constructor(@Inject(L10N_LOCALE) public locale: L10nLocale) { }
}
```
However I get these errors:
Module '"../node_modules/angular-l10n/angular-l10n"' has no exported member 'L10N_LOCALE'.
Module '"../node_modules/angular-l10n/angular-l10n"' has no exported member 'L10nLocale'. Did you mean 'L10nLoader'?

There might be something missing in the documentation.
I'm using version 8.1.2.

I've been trying to make it work for 2 hours and for now I think I'll just print the date in small format without using any translation.

**Comment by robisim74** [comment]
Hi @mike-pixel,

at the end of the Readme, you can find the link to the doc for Angular v8 (https://github.com/robisim74/angular-l10n/tree/angular_v8/docs).

The current doc is for the latest version of the library for Angular v9 (https://github.com/robisim74/angular-l10n/releases)
