### ISSUE TITLE
HTTP Failure - During parsing chinese and french text

### ISSUE THREAD

**Issue by tarun-nagpal-github** [robisim74/angular-l10n#275]
Hey,

I am able to translate English and German. But I am getting the attached Error on chinese and french  text.

After searching I found the issue is with string parsing ' or "" etc. 

I am attaching the error and the translated code can be found here.

![image](https://user-images.githubusercontent.com/4689167/72717076-604e4a00-3b99-11ea-933b-12fedfe91dfd.png)

https://gist.github.com/tarun-nagpal-github/f593106df3f82e6d5adc207bab4405fd

**Comment by robisim74** [comment]
Hi @tarun-nagpal-github,

did you try to validate your json files? (for example using https://jsonlint.com/)

If your json are valid, please provide more information:

- Angular & angular-l10n versions
- Explain: _After searching I found the issue is with string parsing ' or "" etc._

**Comment by tarun-nagpal-github** [comment]
@robisim74 

Thanks for the reply. The JSON is valid and the versions is ""angular-l10n": "^7.0.0",".

 After searching I found the issue is with string parsing ' or "" etc. 

When I replace all the Chinese text and English it works .

**Comment by tarun-nagpal-github** [comment]
@robisim74 

I got a temporary solution. 

Actual Problem 

I was converting the following text from English to Chinese and it has space when converted into Chinese.

    "passportPan" : "(Passport, driving license, PAN card)",
    "billAndRc" : "(Electricity bill, vehicle registration certificate)",
    "expAndSalarySlip" : "(Previous experience letter, relieving letter, salary slips)",

Solution 

I trimmed the values and tried. It worked

Suggestions

It should accept special characters and spaces as a first letter
