### ISSUE TITLE
Lazy modules management on v9

### ISSUE THREAD

**Issue by sddania** [robisim74/angular-l10n#282]
I don't understand the new l10n configuration;
now we can set some provider with a name like 'app' and 'lazy' (see the application demo on this repo).
Now on my production application i have several Json where i placed the translations, and sometimes i can load more than one Json per module.

The config will loads the translations into modules with name by convention? Can i specify more than one asset per provider?

**Comment by robisim74** [comment]
Hi @sddania,

you can add all the assets you need, and the `name` is only the identifier used internally by the library.

If you have lazy loaded modules, which pass new configurations and json files via the `forChild` method, this is no longer natively supported: in the new version you should centralize them in the main module and in the main assets like the demo app.

**Comment by danielcollettepb** [comment]
If I understand correctly, if I have 10 lazy modules, all strings files for the 10 modules will load when the app starts up. There is no way to dynamically load them when a module is loaded? (like we used to with the `forChild`)

**Comment by nickroberts** [comment]
Ideally, we should be able to lazily load these translation files, just like the modules are lazy loaded.

It you have fallback enabled (which we do), then for each module, there are 2 network requests (e.g. en-US.json and en.json).

For the example mentioned before for 10 modules, that quickly turns into 20 requests for translations.

That being said, I wasn't a huge fan of how it was handled in the previous version, as for each lazy loaded module, we had to load the main translations, along with the lazy module translations. I'm not sure if that was some misconfiguration on our end, or not, but It was a bit of a pain.

**Comment by robisim74** [comment]
@nickroberts I agree: how lazy loading was managed in the previous version was not optimal (even using the cache), and for this reason that support has been removed.

@danielcollettepb The ability to dynamically load the translation files is still present: simply add them to the providers in the configuration and call the `loadTranslation `method, as in this example: https://github.com/robisim74/angular-l10n/blob/6eca9185b6204bddac66990e51a535ba434bd361/projects/angular-l10n/src/tests/l10n-translation.service.spec.ts#L361-L367

But since lazy loaded modules don't yet have some sort of _module initializer_ (see https://github.com/angular/angular/issues/17606), translation will not work on the first load in all situations (for example if you use pure pipes or asynchronous loading of translations).

**Comment by robisim74** [comment]
However it seems that an Angular [Resolver](https://angular.io/api/router/Resolve) works.

Create the resolver for lazy loaded module:

```
@Injectable({
    providedIn: 'root'
})
export class L10nLazyResolver implements Resolve<Promise<any>> {

    constructor(@Inject(L10N_CONFIG) private config: L10nConfig, private translation: L10nTranslationService) { }

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<any> {
        this.config.providers = [
            ...this.config.providers,
            { name: 'lazy', asset: './assets/i18n/lazy', options: { version: '9.0.0' } }
        ];
        return this.translation.loadTranslation();
    }
}
```
Add it to the router:
```
    {
        path: 'lazy', loadChildren: () => import('./lazy/lazy.module').then(m => m.LazyModule), resolve: { l10n: L10nLazyResolver }
    },
```

Guys: could you also try in your apps if it works correctly? And if it works correctly, what do you think? Should I add it in the example app and as a suggested way for lazy loading?

**Comment by nickroberts** [comment]
That seems pretty cool. I will test it out later today when I get the chance.

Thanks again for the great module! It seems much better than having to generate X number of bundles for translations like they expect you to do with the built-in internationalization.

**Comment by danielcollettepb** [comment]
@robisim74 I was going to ask if you thought resolvers would work, you beat me to it.

Tested in my app locally and it works. I changed it slightly so I can define the providers in the route data as an array:

```
{
    path: 'sample',
    loadChildren: () => import('./sample/sample.module').then(m => m.SampleModule),
    resolve: { l10n: L10nLazyResolver },
    data: {
      l10nProviders: [{ name: '', asset: './assets/i18n/sample' }]
    }
  }
```

and get the `route.data.l10nProviders` in the Resolver:

```
@Injectable({
  providedIn: 'root'
})
export class L10nLazyResolver implements Resolve<Promise<any>> {
  constructor(@Inject(L10N_CONFIG) private config: L10nConfig, private translation: L10nTranslationService) {}

  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<any> {

    this.config.providers = [
      ...this.config.providers,
      ...route.data.l10nProviders
    ];

    return this.translation.loadTranslation();
  }
}
```

thoughts or suggestions?

Would be great if this resolver could be added to the library and yes, sample code/documentation would definitely be helpful.

**Comment by danielcollettepb** [comment]
Only potential issue is that files are loaded multiple times, on app load I see my `app` and `home` json files loaded, then see them again when the `sample` module is lazy loaded:

![image](https://user-images.githubusercontent.com/6116867/75584292-6b6c8380-5a3d-11ea-8c29-c1a6da78762e.png)

**Comment by robisim74** [comment]
@danielcollettepb I like your idea! And yes, it could be added to the library, again as a hackable class.

If you enable caching in the configuration, it shouldn't happen that the files are reloaded.

**Comment by danielcollettepb** [comment]
Tested the cache and it works, I had it set to false.

Thanks for the quick support and feedback... much appreciated!

**Comment by nickroberts** [comment]
It works! Thanks @robisim74 & @danielcollettepb! Much appreciated!

**Comment by robisim74** [comment]
Thank you all for your contribution!

In the examples above, we should also avoid that providers are added multiple times if the module is loaded multiple times:

```
@Injectable({
    providedIn: 'root'
})
export class L10nResolver implements Resolve<Promise<void>> {

    constructor(
        @Inject(L10N_CONFIG) private config: L10nConfig,
        private translation: L10nTranslationService
    ) { }

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<void> {
        this.config.providers = [...new Set([...this.config.providers, ...route.data.l10nProviders])];

        return this.translation.loadTranslation();
    }
}
```

**Comment by robisim74** [comment]
Hi,

with the commits above, I added native support to lazy loading:
- New signature for the `loadTranslation` method: now also accepts partial loading of the providers
- New caching system: in addition to http requests, translation data are not re-evaluated
- A `L10nResolver`: https://github.com/robisim74/angular-l10n/blob/master/projects/angular-l10n/src/lib/services/l10n-resolver.ts

No breaking changes.

Before releasing a new minor version of the library, I'd like to know your opinion.

**Comment by danielcollettepb** [comment]
All looks good to me.

**Comment by nickroberts** [comment]
Looks great! Nice work, and keep up the great work!

**Comment by robisim74** [comment]
New version is out: https://github.com/robisim74/angular-l10n/releases/tag/v9.1.0

Thanks again!

**Comment by sddania** [comment]
Thanks you all!
