### ISSUE TITLE
Is lazy loaded module supported?

### ISSUE THREAD

**Issue by m-sadegh-sh** [robisim74/angular-l10n#283]
Recently I decided to upgrade from V7 to V9 and I noticed that maybe lazy loaded modules are not supported yet. Because I can't find any explanation about this feature in documentations.

If this is not supported, what would be your option to be able to use V9 in a project with dozens of lazy loaded modules? Do you recommend us to upgrade at all?

**Comment by m-sadegh-sh** [comment]
As I saw issue #282, Now it's clear to me that latest version supports lazy loaded modules with a bit of hacks.

**Comment by robisim74** [comment]
@m-sadegh-sh Support for lazy loading has been added with version 9.1.0: https://github.com/robisim74/angular-l10n#lazy-loading

Greetings
