### ISSUE TITLE
ILocaleService equivalent

### ISSUE THREAD

**Issue by hamzapoly** [robisim74/angular-l10n#284]
Hello team,

I've been using the version 5.1.0 and there's been the very useful service ILocaleService. 
Though with angular 8 and L10n last version it doesn't exist anymore.
What's the story behind ?
Thanks

**Comment by robisim74** [comment]
@hamzapoly The last version of this library is for Angular v9: https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0

`LocaleService `is no longer available: the translation methods are in [L10nTranslationService](https://robisim74.github.io/angular-l10n/injectables/L10nTranslationService.html), while the methods for dates, numbers and other Intl APIs are in [L10nIntlService](https://robisim74.github.io/angular-l10n/injectables/L10nIntlService.html)

**Comment by robisim74** [comment]
I'm closing for lack of response.
