### ISSUE TITLE
How to force latin numerics with v9?

### ISSUE THREAD

**Issue by mahmoudajawad** [robisim74/angular-l10n#285]
Hello.

After the upgrade to angular-l10n v9 I lost the ability to force latin numerics which was introduced few versions back by the team based on #161. How to achieve the same with v9?

**Comment by robisim74** [comment]
Hi @mahmoudajawad ,

just add the `u` extensions to your languages, for example: `language: 'en-US-u-nu-latn'`

References:
- https://github.com/robisim74/angular-l10n#types
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

**Comment by mahmoudajawad** [comment]
hello,

thanks for your response, @robisim74.
I'm still unable to force Arabic with latin numerics. Have a look at the following sample `app-comp`:
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ng9-hw';

  today: Date = new Date();
  value: number = 1500.50;

  locales: { [key: string]: L10nLocale; } = {
    en: {
      language: 'en-AE-u-ca-gregory-nu-latn',
      currency: 'AED',
      timeZone: 'asia/dubai'
    },
    ar: {
      language: 'ar-AE-u-ca-gregory-nu-latn',
      currency: 'AED',
      timeZone: 'asia/dubai'
    }
  };

  constructor(@Inject(L10N_LOCALE) public locale: L10nLocale, public translate: L10nTranslationService, public intl: L10nIntlService) { }

  setLocale(locale: string): void {
    this.translate.setLocale(this.locales[locale]);
  }

}
```

If you test it by adding buttons that trigger `setLocale` method you would see that it's always hindu-arabic numerics not latin (arabic) numerics when `setLocale('ar')`. I set the following for `app-module`:
```
const i18nAsset = {};

export const l10nConfig: L10nConfig = {
  format: 'language-script-region',
  providers: [
    { name: 'app', asset: i18nAsset }
  ],
  cache: true,
  keySeparator: '.',
  defaultLocale: { language: 'en-AE', currency: 'AED' },
  schema: [
    { locale: { language: 'en-AE', currency: 'AED' }, dir: 'ltr', text: 'English' },
    { locale: { language: 'ar-AE', currency: 'AED' }, dir: 'rtl', text: 'Arabic' }
  ]
};

export function initL10n(l10nLoader: L10nLoader): () => Promise<void> {
  return () => l10nLoader.init();
}
```

**Comment by robisim74** [comment]
In the sample app, it works: https://stackblitz.com/edit/angular-l10n-7jvtvu

**Comment by mahmoudajawad** [comment]
Dude! This is the most ridiculous thing I've ever missed!

Sorry, My bad. You were right. It's working. It was cached data that was getting the hindu-arabic numerics instead of latin (arabic) numerics. Thanks, @robisim74, you are great help always.
