### ISSUE TITLE
Number and Dates Not Translated v9

### ISSUE THREAD

**Issue by Voodooman36** [robisim74/angular-l10n#286]
I have recently upgraded a project to Angular 9 and v9 of Angular-L10n. Translations work fine except for Dates and numbers.

**Comment by Voodooman36** [comment]
I also see this error when running the application

node_modules/angular-l10n/lib/services/l10n-intl.service.d.ts:51:42 - error TS2694: Namespace 'Intl' has no exported member 'PluralRulesOptions'.

**Comment by robisim74** [comment]
Regarding the first request, it is not possible to understand what is happening in your app, without code or error messages. Try to compare with the [example app](https://stackblitz.com/edit/angular-l10n), and be careful that the date and number _options_ now inherit from Intl's interfaces.

About the second request, check you TypeScript version, and in `tsconfig` the `lib `property:
```
    "lib": [
      "es2018",
      "dom"
    ],
```

**Comment by Voodooman36** [comment]
Changing from es2017 to es2018 resolved the second issue.

On the first issue, here is the markup

{{ 'MonthlyAccrual' | translate:locale.language}}: {{ accrual | l10nNumber:locale.language:{ digits: '1.2-2' } }}

The MonthlyAccrual text is translated according, but the number is still showing in English, regardless of language. In this case af-ZA was used.

**Comment by robisim74** [comment]
It seems that the _af-ZA_ locale is not supported by Chrome:

```
console.log(Intl.NumberFormat.supportedLocalesOf("af-ZA"))
// []
```

but works for example in Firefox.

I can't do anythink. You should try:
- using a polyfill or use another language for that country (with the same number notation)
- also opening an issue on Chrome

**Comment by Voodooman36** [comment]
Thanks. For now I am using the built-in formatting for numbers and dates which is working.
