### ISSUE TITLE
Is there a way to lazy load the locale .json file?

### ISSUE THREAD

**Issue by Mak006** [robisim74/angular-l10n#29]
Right now, we have sub-components that essentially have their own translation files (using .addProvider).  However, when these components are loaded dynamically (via routing), the translation file never gets added.  Calling updateTranslation does nothing since the language is still the same.  

Any help or suggestions would be appreciated!

**Comment by robisim74** [comment]
Hi,

you can find the explanation of how the lazy loading works [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#5).

Also the sample app is built in this way: see [list.module.ts](https://github.com/robisim74/angular2localization/blob/gh-pages/app/list.module.ts) and [list.component.ts](https://github.com/robisim74/angular2localization/blob/gh-pages/app/list.component.ts).

Basically, you have an instance of the classes _LocaleService_ and _LocalizationService_  at the beginning for the whole app and a new instance of the _LocalizationService_ class for all the components that you want to have their own translation data. There are two cases:
- Lazy loading of modules

In this case, yuo have something like this:

```
@NgModule({
    imports: [
        ...
        LocaleModule, // LocaleService is singleton.
        LocalizationModule.forChild() // New instance of LocalizationService.
    ],
    declarations: [ListComponent]
})
```

and the new initialization of the _LocalizationService_ in the component.
- Lazy loading of components

In this case, to create a new instance of _LocalizationService_, you have to inject it in the component:

```
@Component({
    ...
    providers: [LocalizationService] // New instance of LocalizationService.
})

export class ListComponent extends Locale {
    constructor(public locale: LocaleService, public localization: LocalizationService) {
        super(locale, localization);

        // Initializes LocalizationService for this component and for its descendants.
        this.localization.translationProvider('./resources/locale-list-'); // Required: initializes the translation provider with the given path prefix.
        this.localization.updateTranslation(); // Need to update the translation.
    }
}
```

The main difference between these two ways of doing it is in the way they are loaded: in the first case, all the child modules are loaded when needed (if you see the _dist_ folder in the sample app, you find a _chunk_ - the app has also activated the _preloading_ in background). In the second case, the child component is performed at the time of the request, but it's loaded at the bootstrap of the app.

If you have still problems, post your code.

Greetings
