### ISSUE TITLE
Equivalent to localeService.getAvailableLanguages()

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#291]
Hi,
is there a method that replaces this since the new version (9.x.x) ?

**Comment by robisim74** [comment]
Hi @johaven ,

no there isn't. Do you think is it still useful?

Just access to `schema `property of `L10nConfig`.

**Comment by johaven** [comment]
Yes but it's not an array :)

**Comment by robisim74** [comment]
Ok, it will be added.

**Comment by robisim74** [comment]
Added in the latest version: https://github.com/robisim74/angular-l10n/releases/tag/v9.2.0

Greetings
