### ISSUE TITLE
error NG8004: No pipe found with name 'translate' when using with lazy loading

### ISSUE THREAD

**Issue by samnanglorn** [robisim74/angular-l10n#292]
Hi guys!

I'm using angular v9.0.6 and angular-l10n v9.1.0. When I use it with lazy loading in my project, it always return error that unknown pipe 'translate' but if I use it normal (without lazy load) it work fine.

Before when I use it with angular v8 and angular-l10n v8, I can use it by put TranslationService to providers: [] in app.module but in v9 can not.
How could I do it with lazy load in v9?

Thanks for all @robisim74

**Comment by robisim74** [comment]
Hi @samnanglorn ,

new way for lazy loading: https://github.com/robisim74/angular-l10n#lazy-loading

Then the logic for pipes, directives and components is always the same: you have to import `L10nTranslationModule `back into your module for translate pipe or directive, and `L10nIntlModule `for other pipes and directives: https://github.com/robisim74/angular-l10n/blob/master/projects/angular-l10n-app/src/app/lazy/lazy.module.ts#L11-L16

**Comment by samnanglorn** [comment]
> Hi @samnanglorn ,
> 
> new way for lazy loading: https://github.com/robisim74/angular-l10n#lazy-loading
> 
> Then the logic for pipes, directives and components is always the same: you have to import `L10nTranslationModule `back into your module for translate pipe or directive, and `L10nIntlModule `for other pipes and directives: https://github.com/robisim74/angular-l10n/blob/master/projects/angular-l10n-app/src/app/lazy/lazy.module.ts#L11-L16

Thanks, @robisim74 that work fine
