### ISSUE TITLE
Question: override translation file used in Angular Library from Angular Application

### ISSUE THREAD

**Issue by danielcollettepb** [robisim74/angular-l10n#296]
We maintain an [Angular Library](https://angular.io/guide/creating-libraries) internal to our company for common components and would like to provide a default translation file in the library (for english).

Is it possible to override the translation file path loaded in the library with a new one from the Angular application that consumes the library? We would need to pass the new translation file path to the library.

**Comment by robisim74** [comment]
@danielcollettepb I'm not sure I understand what your goal is. I need a more detailed description or example, and I need to know where angular-l10n is used (in your library and/or in the app that consumes it).

**Comment by danielcollettepb** [comment]
We've decided to pass translated strings into the library components as inputs, rather than having the library having a dependency on angular-l10n, mainly because of issues with versioning.
