### ISSUE TITLE
l10n-placeholder definitively removed ?

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#297]
Just a question, because migration doc doesn't mention anything about it.

**Comment by robisim74** [comment]
What do you mean by `10n-placeholder`?

If you mean the ability to translate attributes like the _placeholder_, this is still valid:

`<input type="text" l10n-placeholder placeholder="someKey" l10nTranslate/>`

**Comment by johaven** [comment]
yes about **l10n-placeholder**, i ask this for 2 reasons:

- I did not see the directive in the documentation (maybe I missed it)

- This kind of binding seems to no longer working now:

`<input type="text" l10n-placeholder [placeholder]="someKeyAsVar" l10nTranslate/>`

**Comment by robisim74** [comment]
Translate directive is one of the few things that has not changed: and in the doc the attribute is shown in the example: https://github.com/robisim74/angular-l10n#directives

I just tried it in my app, and it works. Could you recreate the situation where it doesn't work?

**Comment by johaven** [comment]
In the doc, l10n-title is mentionned for me. The usage of l10n-*attribute is not explicit enough in my opinion :)

The value is only translated the first time, it is when the value is modified by events that it is not subsequently translated, before the last version i didn't have this problem.

For example:
```html
<div class="sidebar-form">
  <div class="input-group">
    <input type="text" name="search" [(ngModel)]="searchText" class="form-control" l10n-placeholder [placeholder]="placeholder" (keyup.enter)="goSearch()" (keyup.escape)="clearSearch()" (focus)="onFocus()" (blur)="onBlur()" autocomplete="new-password" l10nTranslate>
<!--    <input type="text" name="search" [(ngModel)]="searchText" class="form-control" [placeholder]="placeholder|translate:locale.language" (keyup.enter)="goSearch()" (keyup.escape)="clearSearch()" (focus)="onFocus()" (blur)="onBlur()" autocomplete="new-password">-->
    <span class="input-group-btn">
      <button (click)="dispatchClick()" role="button" type="button" name="search" id="search-btn" class="btn btn-sm" [ngSwitch]="searchText">
        <i *ngSwitchDefault class="fas fa-times"></i>
        <i *ngSwitchCase="false" class="fas fa-search"></i>
      </button>
    </span>
  </div>
</div>
```

```javascript
    onFocus() {
        this.searchService.focusSearch()
        if (this.searchService.lastUrl) {
            this.placeholder = 'Escape key to exit'
        }
    }

    onBlur() {
        this.placeholder = this.originalPlaceHolder
    }

    dispatchClick() {
        if (this.searchText) {
            this.clearSearch()
        } else {
            this.onFocus()
        }
    }

    clearSearch() {
        this.placeholder = this.originalPlaceHolder
        this.searchService.stopSearch()
    }
```

**Comment by robisim74** [comment]
Even in the previous version it was not possible to dynamically change the value of the expression in the attribute.

https://github.com/robisim74/angular-l10n/blob/angular_v8/docs/spec/getting-the-translation.md#attributes

I will specify it again in the new doc.

**Comment by johaven** [comment]
You are right sorry for the time lost, i loaded my old branch and i used this:

```javascript
[placeholder]="placeholder|translate:lang"
```
and not the directive ...

thank you for your patience 👍
