### ISSUE TITLE
How do I use the translate out of the template, in Service, or Component code?

### ISSUE THREAD

**Issue by pedrolvr** [robisim74/angular-l10n#3]

**Comment by robisim74** [comment]
Hello. Usually the translation is used in templates. `Service` does not exist in object-orienting languages: there are classes and also the components are classes.
However, this library has the `LocalizationService` class, which provides the translation service. After it has been initialized in the main component, you can take advantage of the dependency injection in all children components or classes that recall it.
It has a `translate` method of Observable type, you can invoke it by RX to get the translation of the desired key, something like this:

``` TypeScript
    constructor(public localization: LocalizationService) {

        var translatedTitle: string;

        this.localization.translate("TITLE").forEach(

            // Next.
            (value: string) => {

                translatedTitle = value;

            }, null

        ).then(() => console.log(translatedTitle));

    }
```

**Comment by pedrolvr** [comment]
Great!

2016-04-27 17:13 GMT-03:00 Roberto Simonetti notifications@github.com:

**Comment by robisim74** [comment]
I update and close this answer: Now you have two methods of `LocalizationService` to call in the component:
- `translate` of string type;
- `translateAsync` of Observable type.

Greetings.
