### ISSUE TITLE
timing issue with intitial translation 

### ISSUE THREAD

**Issue by JanEggers** [robisim74/angular-l10n#30]
hi i have a timing issue in my app with initial translation in my component (template). when changing the current language later on it works as expected.

i see one call to translate pipe that is aborted because the state of the localization service is not ready.
After this initial call there are no further calls to the translate pipe.

i subscribed to translationchange in my component and triggered an app.tick(), i debugged into changedetection and the translate is not called because lang and key did not change.

so root problem seems to be that current language is set before the providers are added!?

if i add additional code after adding a provider i can workaround the issue:
1. localization.addProvider('url');
2. (<any>this.localization).getTranslation(language); //because this.localization.updateTranslation(language); does nothing because languagecode is the same

3. component.lang = "";

as a sidenote: the TranslatePipe returns "" if the localization service is not ready, i would prefere that it returns the key to be consistent with lacalizationService.translate calls

**Comment by robisim74** [comment]
Hi,

I have removed the return of the key from `TranslatePipe` because you were likely to see the key in the template during loading.

As explained [here](https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.4), and as you can see in the [app.component.ts](https://github.com/robisim74/angular2localization/blob/gh-pages/app/app.component.ts) of the sample app, when you subscribe to the `translationChanged` in the bootstrap component, you have to call `updateTranslation` method after the subscription.

However in these days I'm preparing an alternative solution to load the translation files before the app is rendered. I should publish it tonight.

Greetings

**Comment by robisim74** [comment]
Ok, if you prefer another solution, I've updated the [quick-start](https://github.com/robisim74/angular2localization/blob/master/doc/quick-start.md) with an appendix that explains how to load the translation file before the app is rendered.

Also the [sample app](https://github.com/robisim74/angular2localization/tree/gh-pages) is updated.

Keep in mind, however, that when you want to get the translation in a component, you still have to do it in this way:

```
@Component({
    ...
    template: '<h1>{{ title }}</h1>'
})
export class HomeComponent {

    // Initializes the variable 'title' with the current translation at the time of the component loading.
    public title: string = this.localization.translate('TITLE');

    constructor(public localization: LocalizationService) {

        this.localization.translationChanged.subscribe(

            // Refreshes the variable 'title' with the new translation when the selected language changes.
            () => { this.title = this.localization.translate('TITLE'); }

        );

    }

}
```

To work with asynchronous loadings in the components, remember that `translationChanged` is fired only when the loading of file is completed, but you must have already subscribed it.

Greetings

**Comment by JanEggers** [comment]
sorry that didnt work for me either, i have one translation file per component
and each component loaded after initial language assign does not translate.

i refactored the code like adviced in quick-start but added a translation[] to the initialize function.
i export one translation per component and my initialize now looks like:

home.component.ts 

```
export class HomeComponentTranslation extends Translation {
    constructor() {
        super('home.component');
    }
}


@Component({
    moduleId: module.id.toString(),
    selector: 'home',
    templateUrl: 'home.component.html',
    styleUrls: []
})
@Injectable()
export class HomeComponent extends Locale implements OnInit {
    constructor(locale: LocaleService, localization: LocalizationService) {
        super(locale, localization);
    }

    ngOnInit() { }
}
```

Initializer

```
export class Translation {
    constructor(public name: string) {
    }
}

export class Initializer {
   ....
    initialize(translations: Translation[]) {
        var lang = localStorage.getItem(languageKey);
        if (!lang) {
            lang = 'en';
        }

        var promise: Promise<any> = new Promise((resolve: any) => {
            this.localization.translationChanged.subscribe(() => {
                resolve(true);
            });
        });

        this.locale.addLanguages(this.languages);

//1. this must be done first
        translations.forEach((t) => {
            this.localization.addProvider(t.name);
        });

//2. this has to be delayed after all providers are provided
        this.locale.setCurrentLanguage(lang);
        this.localization.updateTranslation(lang);

        return promise;
    }
}

```

app.module

```
        {
            provide: Translation,
            useClass: HomeComponentTranslation,
            multi: true
        },
        {
            provide: Translation,
            useClass: LoginComponentTranslation,
            multi: true
        },
...
        {
            provide: APP_INITIALIZER,
            useFactory: (translation: TranslationServiceBase, translations) => () =>  initializer.initialize(translations),
            deps: [TranslationServiceBase, Translation],
            multi: true
        }
```

**Comment by robisim74** [comment]
Hi,

there are things I don't understand in your code:
- why do you inject the components?
- you don't define your preferred language
- you get the language from locale storage, but you don't use `useLocalStorage` method of the library
- I don't see where you get the translation

I think you should start more easily and then customize.

However, the correct way to intialize the services in your case is something like this:

```
export class Initializer {
   ....
    initialize(translations: Translation[]) {
        // 1
        this.locale.addLanguages(this.languages);
        // 2
        this.locale.definePreferredLanguage('en');
        // 3 (OPTIONAL)
        this.locale.useLocalStorage();
        // 4
        translations.forEach((t) => {
            this.localization.addProvider(t.name);
        });
        // 5
        var promise: Promise<any> = new Promise((resolve: any) => {
            this.localization.translationChanged.subscribe(() => {
                resolve(true);
            });
        });
        // 6
        this.localization.updateTranslation(); // Need to update the translation.

        return promise;
    }
}
```

And _really important_, if you do not use the pipes, you get the translation in the component in this way:

```
@Component({
    ...
    template: '<h1>{{ title }}</h1>'
})
export class HomeComponent {

    // Initializes the variable 'title' with the current translation at the time of the component loading.
    public title: string = this.localization.translate('TITLE');

    constructor(public localization: LocalizationService) {

        this.localization.translationChanged.subscribe(

            // Refreshes the variable 'title' with the new translation when the selected language changes.
            () => { this.title = this.localization.translate('TITLE'); }

        );

    }

}
```

If you don't do this: `public title: string = this.localization.translate('TITLE');` before the subscription, you don't get the value, because `translationChanged` has been already fired (by `updateTranslation`) and it will be fired only when the language changes.

Let me know.
