### ISSUE TITLE
Double language after reloading page using fragment

### ISSUE THREAD

**Issue by ihor-zinchenko** [robisim74/angular-l10n#303]
Hi! I add link to the fragment and after reloading page l10n double lanuage
Before reloading: http://localhost:4200/en#system
After reloading: http://localhost:4200/en/en#system
Please help) 

`<a
  [routerLink]="['/']"
  [fragment]="item.fragment"
>
  {{ item.text | translate:locale.language }}
</a>`

**Comment by robisim74** [comment]
@IhorVimmi Please follow the issue template, or provide at least essential information such as the versions you are using.

In the sample app (https://github.com/robisim74/angular-l10n/tree/master/projects/angular-l10n-app), adding fragments seems works.

**Comment by IhorVimmi** [comment]
@robisim74 where i can clone your sample?

**Comment by robisim74** [comment]
I'm closing due to lack of response.
