### ISSUE TITLE
ERROR in Directive L10nDirective in /node_modules/angular-l10n/angular-l10n.d.ts has no selector, please add it!

### ISSUE THREAD

**Issue by mohitmadras** [robisim74/angular-l10n#313]
Describe the bug
ng build --prod are failing with the error:
ERROR in Directive L10nDirective in/node_modules/angular-l10n/angular-l10n.d.ts has no selector, please add it!
Cannot determine the module for class L10nDirective in /node_modules/angular-l10n/angular-l10n.d.ts! Add L10nDirective to the NgModule to fix it.

package json:
{
  "name": "msk-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test --code-coverage --watch=false",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "npx compodoc -p tsconfig.json -w -s"
  },
  "private": true,
  "dependencies": {
    "-": "0.0.1",
    "@angular/animations": "^8.2.14",
    "@angular/common": "~8.2.3",
    "@angular/compiler": "~8.2.3",
    "@angular/core": "~8.2.3",
    "@angular/forms": "~8.2.3",
    "@angular/platform-browser": "~8.2.3",
    "@angular/platform-browser-dynamic": "~8.2.3",
    "@angular/router": "~8.2.3",
    "@ng-bootstrap/ng-bootstrap": "^5.1.4",
    "@ngrx/store": "^8.0.0",
    "@swimlane/ngx-datatable": "^16.0.2",
    "angular-l10n": "^10.0.2",
    "bootstrap": "^4.4.1",
    "g": "^2.0.1",
    "localforage": "^1.7.3",
    "ngx-toastr": "^11.2.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.0",
    "@angular/cli": "^8.3.29",
    "@angular/compiler-cli": "~8.2.3",
    "@angular/language-service": "~8.2.3",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by robisim74** [comment]
@mohitmadras angular-l10n v10 requires angular v10, as in [release](https://github.com/robisim74/angular-l10n/releases)

You can find previous versions here: https://github.com/robisim74/angular-l10n#previous-versions

**Comment by mohitmadras** [comment]
Thank you, It is working
