### ISSUE TITLE
Why I am getting this error ?? I did npm install then ng serve but every time get the same result

### ISSUE THREAD

**Issue by harsh599** [robisim74/angular-l10n#315]
![image](https://user-images.githubusercontent.com/31313683/95237442-d973f700-0825-11eb-83bf-8293fab864f9.png)

**Comment by robisim74** [comment]
As in [Readme](https://github.com/robisim74/angular-l10n#contributing), first you need to build the library:

```
npm install
npm run build
```

and then `npm start`

In an Angular workspace, you build libraries first, then run apps.

Greetings
