### ISSUE TITLE
problem when loading the .json

### ISSUE THREAD

**Issue by ihabZhaika** [robisim74/angular-l10n#32]
Hi,
i followed the setup guide , i am using webpack , when i run the server i get
`GET http://localhost:8080/assets/locale-en.json 404 (Not Found)`
``
`        this.localization.translationProvider('../../../assets/locale-'); // Required: initializes the translation provider with the given path prefix.
`
is there any thing i have to add to webpack config file to let it work ?

**Comment by robisim74** [comment]
Hi,

I don't know if it depends on webpack. But you should have this:

`this.localization.translationProvider('./assets/locale-');`

You have to provide the path from root (where is the _index.html_). What's the path of your json files?

Let me know.

**Comment by ihabZhaika** [comment]
check the image , i tired path from root , same probelm
https://s18.postimg.org/k3zyxl7nt/path.png

**Comment by robisim74** [comment]
I don't see the bundle file built with webpack.

You should have _index.html_, _bundle_ and _assets_ in the same root folder. Do you serve the app from _src_ folder?

Try to see the structure of the [sample app](https://github.com/robisim74/angular2localization/tree/gh-pages) if it can help.

**Comment by ihabZhaika** [comment]
hi,
i use npm script as the following     "serve": "webpack-dev-server --inline --progress  "
full project structure in the image below
https://s11.postimg.org/umgjwn8c3/path1.png

in addition , i tied to run your demo app , when doing npm install i get
`npm ERR! peerinvalid The package webpack@2.1.0-beta.25 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sass-loader@4.0.2 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
`
so it need update

**Comment by robisim74** [comment]
Ok, I think you have to:
- change _output_ in _webpack.config.js_:

```
        output: {
            path: __dirname,
            filename: "dist/app.bundle.js",
        },
```
- move _assets_ folder from _src_ in the same folder of _webpack.config.js_, because webpack creates _index.html_ and _dist_ folder in its folder.

Then, you can use:

`this.localization.translationProvider('./assets/locale-');`

Instead, if you want to publish the app in the _dist_ folder, you must change in _webpack.config.js_:

```
var CopyWebpackPlugin = require('copy-webpack-plugin'); // You have to install copy-webpack-plugin

...
    output: {
        path: "./dist/",
        filename: 'app.bundle.js'
    },
    ...
    plugins: [
        ...
        new CopyWebpackPlugin([
            { from: './src/assets/*.*', to: "assets/" }
        ])
    ]
...
```

The logic is always the same: you need to have _index.html_, _bundle_ and _assets_ in the same folder.

For the error on install, try to see if you have the latest version of node & npm.

**Comment by ihabZhaika** [comment]
i tired, for some reason still get the same error , if i build for production the file get copied , but if i am using webpack-dev-server the same problem
can you update the starter demo ('fails on npm install') , i will try to follow
Project download url , if you want to give a look : npm install , then npm run serve
https://drive.google.com/open?id=0B_AFMME1kY1oRVdsMkE1Nnlob2M

**Comment by robisim74** [comment]
Ok, I try to look it. 

For the sample app, the only reason for the fails on install is the updating of npm: `npm install npm@latest -g`

**Comment by robisim74** [comment]
Ok,

unfortunately there is a compatibility problem between `copy-webpack-plugin` and `webpack-dev-server`: webpack-dev-server has many problems, and indeed I prefer to use --watch.

However, you can solve in this way:
- Move `assets` folder in root folder (IMPORTANT: this is the problem of webpack-dev-server)
- `webpack.config.js` :

```
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    entry: './src/main.ts',
    output: {
        path: "dist",
        filename: 'app.bundle.js'
    },
    ...
    plugins: [
        ...
        new CopyWebpackPlugin([
            {
                from: 'assets',
                to: 'assets',
                flatten: true
            }
        ])
    ],
    devServer: {
        historyApiFallback: true,
        stats: 'minimal',
        outputPath: path.join(__dirname, 'dist')
    },
    ...
};
```

This solution works with npm run serve and npm run build (you will see your app published in dist folder):

![cattura di schermata 6](https://cloud.githubusercontent.com/assets/14012361/20013432/6400ede2-a2b3-11e6-861b-499f818cac68.png)

Certainly there are other solutions to copy static files.

Greetings

**Comment by ihabZhaika** [comment]
great, it works
thanx for you effort,
last question
which dev-server you would recommend , bcz i am new to this world :)

**Comment by robisim74** [comment]
Honestly, I don't know other dev-server for webpack. At the end, I have chosen to use the simple `--watch` offered by webpack and use a server like _http-server_ or _lite-server_ (or IIS, because I develop server-side in .NET).

Is it slower? Yes. Do you have to refresh the browser? Yes, but I have these reasons:
- You have to configure the config file only for webpack, and not also for the dev-server;
- I'm sure the result I get during the development will be the same in production.

Greetings,

Roberto

**Comment by ihabZhaika** [comment]
ok thanks :+1:
