### ISSUE TITLE
 Function calls are not supported in decorators but 'L10nTranslationModule' was called

### ISSUE THREAD

**Issue by benzhuo** [robisim74/angular-l10n#326]
I'v run into an error when build my project in product mode.
**ERROR in Error during template compile of 'BzadmModule'
  Function calls are not supported in decorators but 'L10nTranslationModule' was called**

the code in NgModule  like 

  imports: [
    L10nTranslationModule.forRoot(
      l10nConfig,
      {
        translationLoader: HttpTranslationLoader
      }
    )
 }

I am using angular-l10n@9.0.0

Is there anyone know how to solve this ?

**Comment by robisim74** [comment]
@benzhuo Please provide more details or a reproduction.

**Comment by robisim74** [comment]
Closed due to inactivity
