### ISSUE TITLE
Release a version with peerDependencies compatible with RxJS v7

### ISSUE THREAD

**Issue by coyoteecd** [robisim74/angular-l10n#330]
**Describe the bug**
Most recent versions of Angular 12 accept upgrading to RxJS v7. The [peerDependencies entry in package.json](https://github.com/robisim74/angular-l10n/blob/e50ec7af3834b12966018f50d01577fda7b8521d/projects/angular-l10n/package.json#L30) of angular-l10n should account for this scenario.

At the moment, I see the following warning at npm install:
```npm WARN angular-l10n@12.0.0 requires a peer of rxjs@^6.5.4 but none is installed. You must install peer dependencies yourself.```

**Comment by robisim74** [comment]
Thanks for reporting. I will release a patch to fix it as soon as I have verified that the library is compatible with both version 6 and 7.

**Comment by robisim74** [comment]
Just released a new version: https://github.com/robisim74/angular-l10n/releases

I had already removed the deprecated stuff in rxjs v6, and the library seems compatible. Any feedback is however appreciated.

**Comment by coyoteecd** [comment]
Updated both my projects with no visible issues. Thanks.
