### ISSUE TITLE
[Question] Differences / Benefits vs ngx-translate?

### ISSUE THREAD

**Issue by Zeratoxx** [robisim74/angular-l10n#333]
Hi,

I just found your project in my research for a translation package. This project seems well documented. 
I wonder:

1. What was the initial inspiration for this project while [`ngx-translate`](https://github.com/ngx-translate/core) is so popular?
2. What are the main differences and/or benefits comparing to [`ngx-translate`](https://github.com/ngx-translate/core)?

Thanks, have a great day :)

**Comment by robisim74** [comment]
Hi @Zeratoxx,

1) This project (like _ngx-translate_) was born when Angular v2 was still in alpha release and it didn't have an official solution to handle the translation, a while ago...  At the time, they were called _angular2localization_ and _ng2-translate_, and you can find the initial differences in this old post: https://stackoverflow.com/a/39118307/6067476

2) More than evaluating the benefits between these libraries, I think you should ask yourself which of these solutions (or others, such as the official i18n solution provided by Angular) is best suited to your project, reading the doc, looking at the examples, and the support offered.

Greetings

**Comment by Zeratoxx** [comment]
Thank you very much for your quick and helpful answer! :)

**Comment by robisim74** [comment]
Closed due to inactivity
