### ISSUE TITLE
possibility to configure PARSE_DATE_STYLE const. Configure full, long,medium,short options

### ISSUE THREAD

**Issue by hschindler** [robisim74/angular-l10n#339]
**Is your feature request related to a problem? Please describe.**
I need to chage the date format for short. I want to use 2-digits for das and month.

**Describe the solution you'd like**
It should be possible to customize the dateStyle

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by robisim74** [comment]
You can use [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) options, i.e.

`<p>{{ today | l10nDate:locale.language:{ day: '2-digit', month: '2-digit', year: 'numeric' } }}</p>`

`03/07/2023`

**Comment by hschindler** [comment]
Oh, that works. Thanks for your help!
