### ISSUE TITLE
I encountered this problem: Unexpected value 'TranslateModule' imported by the module 'SharedModule'. Please add an @NgModule annotation.

### ISSUE THREAD

**Issue by CandyDD** [robisim74/angular-l10n#343]
This problem occurred after I upgraded angular from 15 to 16. The following is my version situation:

angular-l10n：v8.1.2
angular/core: v16.2.12
typescript: v4.9.5

**Comment by robisim74** [comment]
I'm surprised that version v8 of this library worked up to Angular v15.

Generally, this library has a version for each major version of Angular, and you shoud upgrade also libraries.

By the way, this library has no `TranslateModule`.

Please at least post the complete error log.

**Comment by CandyDD** [comment]
As a last resort, I had to upgrade angular-l10n to the latest version
