### ISSUE TITLE
Will there be an Angular 18 release?

### ISSUE THREAD

**Issue by jonmarozick** [robisim74/angular-l10n#348]
I saw a commit for Angular 17 but no release. I was just wondering if there will be a release for Angular 17 and/or 18. Please forgive me if this is not the right place to ask.

**Comment by robisim74** [comment]
Why do you need a release for Angular v17 and v18? Current release is not working for you?

A major version of this library is only released if there are new features or breaking changes or compatibility issues.

**Comment by jonmarozick** [comment]
I don't need a release. The current release is working for me. I was just curious, and the commit made me wonder. Thanks for the reply.
