### ISSUE TITLE
Localization not working on refresh using translate method

### ISSUE THREAD

**Issue by Nikhil-Pahwa** [robisim74/angular-l10n#35]
I am using the translation pipe in html as well as the translate method of LocalizationService. 
The translation pipe is working properly. But when i use translate method in my component, it works fine when i route from another page . But when i refresh the page the translation don't work and it shows the key.
Here is my sample code for my component.

`constructor(public locale: LocaleService, public localization: LocalizationService) {
        super(locale, localization);
    }

    getDefaultTimeRanges() {
        let dStr: string = this.localization.translate('D');
}`

Here from the above code i have translate the key 'D'. But it doesnot translate when i refresh the page. Also i have tried Advanced initialization but the issue remain the same.
Please guide me if i am missing anything. Thanks in advance.

**Comment by robisim74** [comment]
Hi,

when you get the translation in the component, you don't know when the http get of translation file has been completed. So you have to initialize your variable and also subscribe to the `translationChanged` event:

https://github.com/robisim74/angular2localization/blob/master/doc/spec.md#2.4

See also these issues: #26 #16

**Comment by Nikhil-Pahwa** [comment]
thanks this seems to be working now. Hence i am closing this issue
