### ISSUE TITLE
Translation is not working in initialization.

### ISSUE THREAD

**Issue by tsukasa521** [robisim74/angular-l10n#37]
Hi,

I have two component, app and dashboard component. The app is home component and dashboard is normal component.
I use router like this:
 { path: 'home',  component: DashboardComponent }.

I found if access localhost:8080/home, translation will be not working in dashboard component(app component is fine). I mean translation is not working when run app component and dashboard component at the same time.

Could you give me a suggestion? thanks.

**Comment by robisim74** [comment]
Hi @tsukasa521,

sorry, but I don't understand what you mean. Please, post at least the essential code.

Greetings,

Roberto

**Comment by tsukasa521** [comment]
Sorry for my bad english. And I found solution in your sample, good sample!!!

**Comment by robisim74** [comment]
@tsukasa521 English is not a problem: without seeing the code is difficult to see what happens. Greetings
