### ISSUE TITLE
Trying to use localized labels/text while unit testing component, however, no label for test is seen 

### ISSUE THREAD

**Issue by kapoorruchi** [robisim74/angular-l10n#39]
Hi Team,

I'm unit testing a component, while the test case is running fine, I could not show labels for the text fields.
Issue : The component's HTML file contain labels for text fields with 'translate:lang' pipe, however, it is not able to pick keys from locale files while unit testing. 

Below is my code :
```
beforeEach(async(() => {
            TestBed.configureTestingModule({
                imports: [FormsModule, ValidatorsModule, ReactiveFormsModule, LocaleModule, LocalizationModule.forChild(),
                    Ng2Bs3ModalModule, UserManagementModule, HttpModule],
                declarations: [TestComponent],
                providers: [
                    MockUserService,
                    LocaleService,
                    LocalizationService,
                    { provide: HttpService, useClass: MockHttpService },
                    { provide: UserService, useClass: MockUserService },
                    SpinnerService,
                    CustomNotificationService,
                    NotificationsService,
                    {
                        provide: Router, useClass: RouterStub
                    },
                    MockBackend,
                    BaseRequestOptions,
                    EventsService,
                    {
                        provide:
                        Http,

                        useFactory: (backend: any, defaultOptions: any) => {
                            return new Http(backend, defaultOptions);
                        },
                        deps: [MockBackend, BaseRequestOptions]
                    }
                ]
            }).overrideComponent(CreateUserComponent, {
                set: {
                    templateUrl: 'create-user.component.spec.html',
                    providers: [
                        { provide: UserService, useClass: MockUserService }
                    ]
                }
            });

            TestBed.compileComponents();
            console.log('Test bed for create user spec created');
        }));

fit('should create user',
            async(inject([UserService, LocaleService, LocalizationService],
                (mockUserService: UserService, locale: LocaleService, localization: LocalizationService) => {
                    TestBed
                        .compileComponents()
                        .then(() => {
                            let fixture = TestBed.createComponent(TestComponent);
                            let createUserInstance = fixture.debugElement.children[0].componentInstance;
                            let user: User = new User(0, 'user', 'created', 'successfully', 'admin', true, 'Test@123', 'Test@123', '');
                            let spy: jasmine.Spy = spyOn(createUserInstance, 'createUser');
                            createUserInstance.setModel(user);
                            createUserInstance.createUser();
                            expect(spy.calls.any()).toBe(true, 'into create user function of create user component success');
                            fixture.whenStable().then(() => {
                                fixture.detectChanges();
                                let de: DebugElement[] = fixture.debugElement.queryAll(By.css('input'));
                                expect(de.length).toBe(6);
                            });
                        });
                })));
```

```
@Component({
    selector: 'test-cmp',
    template: '<create-user></create-user>'
})
class TestComponent extends Locale {
    constructor(public locale: LocaleService, public localization: LocalizationService) {
        super(null, localization);
        this.locale.addLanguage('en');
        this.locale.addLanguage('ru');
        // Required: default language
        this.locale.definePreferredLocale('en', 'US', 30);
        // Required: initializes the translation provider with the given path prefix.              
        this.localization.translationProvider('../../translations/locale-');
        // Need to update the translation.
        this.localization.updateTranslation();
        this.locale.setCurrentLocale('en', 'US');
    }
}
```

Above is the code that shows following points  :
1. TestBed for unit test case. with required dependencies including LocaleService and LocalizationService.
2. Unit test case injecting dependencies for LocaleService and LocalizationService. So, when the component instance is created at line `let createUserInstance = fixture.debugElement.children[0].componentInstance;` , it goes to component's constructor where localeservice and localizationService objects are referenced.
3. Test component for the unit test case which initializes fields for localeService and localizationService references.

Please help, this is urgent.

**Comment by robisim74** [comment]
Sorry, but without all the code I can not reproduce the problem, which in any case can not depend on this library.

Links:
https://vsavkin.com/three-ways-to-test-angular-2-components-dcea8e90bd8d#.hf59z3u9c
https://medium.com/google-developer-experts/angular-2-testing-guide-a485b6cb1ef0#.4qy0xtjjf

Here you can find an example of how to test this library: https://github.com/robisim74/angular2localization/blob/master/test/pipes/translate.pipe.spec.ts

**Comment by robisim74** [comment]
I added a test to the sample app: https://github.com/robisim74/angular2localization/blob/gh-pages/test/home.component.spec.ts

Configuration:
https://github.com/robisim74/angular2localization/blob/gh-pages/karma.conf.js
https://github.com/robisim74/angular2localization/blob/gh-pages/spec.bundle.js

**Comment by kapoorruchi** [comment]
Thanks Robisim. 
I will use above references to figure out the solution for the problem.
I will update you accordingly.

**Comment by kapoorruchi** [comment]
Hi,

I'm using version - "ng2-validators": "^1.5.2".
I tried using localization in my test case as you have shown in the below link  :
https://github.com/robisim74/angular2localization/blob/gh-pages/test/home.component.spec.ts
I 'm getting error undefined.enableCookie is not a function for statement :
`locale.enableCookie = false;`

Is it due to version issue ?

**Comment by robisim74** [comment]
_ng2-validators_ is another library.

If you get this error, `locale` is not a valid instance of `LocaleService `class.

**Comment by kapoorruchi** [comment]
Apologies for the wrong library.
"angular2localization": "^1.1.0"

**Comment by robisim74** [comment]
Finally, do you have solved?

**Comment by robisim74** [comment]
I'm closing this issue. If you need, open a new issue. Greetings

**Comment by kapoorruchi** [comment]
Ok.

Regards,
Ruchi
