### ISSUE TITLE
Cyclic dependency with advanced initialization 

### ISSUE THREAD

**Issue by emilio-simoes** [robisim74/angular-l10n#42]
I'm having a cyclic dependency error when using the advanced initialization and a custom Http provider:

`Cannot instantiate cyclic dependency! ApplicationRef_: in NgModule AppModule in ./AppModule`

Bellow is the providers section of the module, note that if I remove any of the two providers the application will compile and run with each of them individually. Only when I try to use both of them together the error occurs:

```
providers: [
  {
    provide: APP_INITIALIZER,
    useFactory: initLocalization,
    deps: [LocalizationConfig],
    multi: true
  },
  {
    provide: Http,
    useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions, router: Router) => {
      return new HttpInterceptor(xhrBackend, requestOptions, router);
    },
    deps: [XHRBackend, RequestOptions, Router]
  }
]
```

Full error stack trace:

`Unhandled Promise rejection: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef_: in NgModule AppModule in ./AppModule ; Zone: <root> ; Task: Promise.then ; Value: Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef_: in NgModule AppModule in ./AppModule
Stack trace:
NgModuleProviderAnalyzer</NgModuleProviderAnalyzer.prototype.parse@http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:9916:21 [<root>]
NgModuleCompiler</NgModuleCompiler.prototype.compile@http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:18498:11 [<root>]
JitCompiler</JitCompiler.prototype._compileModule@http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:26572:52 [<root>]
JitCompiler</JitCompiler.prototype._compileModuleAndComponents/createResult@http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:26514:22 [<root>]
Zone.prototype.run@http://localhost:5555/node_modules/zone.js/dist/zone.js?1482335873252:113:24 [<root> => <root>]
scheduleResolveOrReject/<@http://localhost:5555/node_modules/zone.js/dist/zone.js?1482335873252:520:52 [<root>]
Zone.prototype.runTask@http://localhost:5555/node_modules/zone.js/dist/zone.js?1482335873252:151:28 [<root> => <root>]
drainMicroTaskQueue@http://localhost:5555/node_modules/zone.js/dist/zone.js?1482335873252:418:25 [<root>]
ZoneTask/this.invoke@http://localhost:5555/node_modules/zone.js/dist/zone.js?1482335873252:349:25 [<root>]`

**Comment by robisim74** [comment]
Did you see this question? http://stackoverflow.com/questions/39767019/app-initializer-raises-cannot-instantiate-cyclic-dependency-applicationref-w

**Comment by emilio-simoes** [comment]
Yep, that definitely fixes the problem.
I didn't associated with it because the custom Http provider was working standalone and the error message was referring the ApplicationRef_ and not the Router, but using the injector to get the router works fine.

@robisim74 thanks

Closing the issue.

**Comment by robisim74** [comment]
Thank you for reporting. Greetings
