### ISSUE TITLE
Format date of md-input

### ISSUE THREAD

**Issue by jo55** [robisim74/angular-l10n#44]
Hi,

I'm struggling with formatting a date in a md-input field. Placeholder is not working as it is in your example for digits as I need to show a text like Start Date first. 
When a date is entered and I change the language (culture) the error "Invalid argument .... for pipe 'DatePipe' appears and the application stops.

Thank's in advance for your support

**Comment by robisim74** [comment]
Hi @jo55,

if I understand correctly, you're trying to do something like this:

`<md-input type="date" [(ngModel)]="today" placeholder="{{ today | localeDate:defaultLocale:'mediumDate' }}"></md-input>`

and in the constructor of the component there is the initialization of `today `:

`this.today = Date.now();`

It works:

![image](https://cloud.githubusercontent.com/assets/14012361/21700510/0ed70ca6-d3a1-11e6-9397-4a02c6deff46.png)

After selecting the date and change language:

![image](https://cloud.githubusercontent.com/assets/14012361/21700546/4a0ea482-d3a1-11e6-96dc-f1d211807c9f.png)

**Comment by jo55** [comment]
Hi robisim74,

this is what I have at the moment
`<md-input type="text" class="form-control" id="startDate" required [(ngModel)]="model.startDate" name="startDate" placeholder="Start date"></md-input>`

I would like to keep Start date as I'll need some other date fields (e.g. End date, etc.)

![image](https://cloud.githubusercontent.com/assets/22825072/21714704/b307f0f6-d400-11e6-9995-4e32042f93f9.png)

I tried this which is showing the correct format but with the error by changing the language

`<md-input type="text" class="form-control" id="startDate" required [(ngModel)]="model.startDate" name="startDate" placeholder="Start date" value="{{ model.startDate | localeDate:defaultLocale:'fullDate' }}"></md-input>`

![image](https://cloud.githubusercontent.com/assets/22825072/21714740/dd3a75b0-d400-11e6-90c5-6c3b4f403ede.png)

In the component is imported the Baseload class
`export class Baseload {
    constructor(
        public startDate?: Date,
        public megawatts?: number
    ) { }
}`

and in the constractor is
`model = new Baseload();`

`<p>` tag it is working fine

![image](https://cloud.githubusercontent.com/assets/22825072/21714994/39e164f8-d402-11e6-89e8-67edee689d5a.png)


![image](https://cloud.githubusercontent.com/assets/22825072/21714812/42a7e590-d401-11e6-81d2-c13773f8df2b.png)

![image](https://cloud.githubusercontent.com/assets/22825072/21714842/68c57120-d401-11e6-979f-f2282e185dac.png)

![image](https://cloud.githubusercontent.com/assets/22825072/21714860/78c1710a-d401-11e6-8547-ba2c560ab533.png)

![image](https://cloud.githubusercontent.com/assets/22825072/21714868/83475b1c-d401-11e6-9057-3f81872b80ee.png)

**Comment by robisim74** [comment]
Ok, I see. The problem is that when you change language, the format of _model.startDate_ is not a valid entry format for the pipe. You have to transform it with a custom pipe or a function before, or use another variable with the correct format (date, number or string).

**Comment by jo55** [comment]
ok. Thank you for the quick replay ...

... and thanks a lot for sharing your work 👍
