### ISSUE TITLE
Add output EventEmitters for changed language, country, currency in the locale.service

### ISSUE THREAD

**Issue by damienbod** [robisim74/angular-l10n#5]
It would make it easy when using localized data from a server api.

If you want to implement this feature, I could also implement this as a  pull request.

What do you think?

Greetings Damien

**Comment by robisim74** [comment]
It seems like a good idea: more features, more easy. Thanks!

**Comment by damienbod** [comment]
cool, thanks for merging, any chance of a npm release?

greetings Damien

**Comment by robisim74** [comment]
Thank you. Yes, now I compile the library and I publish the new release.

**Comment by robisim74** [comment]
v0.5.2 is out.

**Comment by damienbod** [comment]
great thanks
