### ISSUE TITLE
Traslate html or component attributes?

### ISSUE THREAD

**Issue by RicardoJBarrios** [robisim74/angular-l10n#52]
I'm using primeNG, and some components rely on attributes to display data, like the button:

` <button pButton type="submit" label="Submit"></button>`

I've tried with `translate`, but it raise an `Cannot read property 'nodeValue' of undefined` error. Also could be interesting to be able to translate attributes like `alt`, without the need of extend from `Locale`.

**Comment by robisim74** [comment]
Next major release will include support for `value` attribute (https://github.com/robisim74/angular2localization/issues/48), and some other features for nested nodes, but not for other attributes. This library basically provides pipes to translate everything, and directives are only for static template, where pipes are useless.
To work only with the attributes, there is already Angular i18n native solution. I think you should consider moving to it if you want work only on the template.

**Comment by RicardoJBarrios** [comment]
Ok, thanks for your answer.

**Comment by robisim74** [comment]
If you're still interested, you can now translate attributes this way:

`<button pButton type="submit" l10n-label label="Submit" l10nTranslate></button>`

Greetings
