### ISSUE TITLE
It's just Angular l10n

### ISSUE THREAD

**Issue by robisim74** [robisim74/angular-l10n#53]
Because _it's just Angular_, I renamed the library (_Angular localization_ is already taken by an AngularJS library...), and because only a new name is useless, I made a code refactoring, with a lot of breaking changes.

This project started only with one injectable class for translation at the beginning of Angular 2 (it was its name), and it has grown to become heavy, but I think that _clean code_ is important to manage the project.

I also tried to make it more beautiful and simple to use, and especially to optimize performance and size (thinking about tree shaking), so that you can only import the modules and classes that are used.

All the documentation is updated.

Greetings,

Roberto

**Comment by hgoebl** [comment]
Hi @robisim74 nice work! The next time you introduce breaking changes, you might consider using `doSomething()` method names instead of the C# `DoSomething()` names which are really _very_ unusual in JavaScript and TypeScript.

**Comment by robisim74** [comment]
Hi @hgoebl, yes, I know. All the methods of the library use `doSomething()`: I chose the `DoSomething()` sintax only for the methods of the initial configuration, for these reasons:
- to highlight that it is a configuration
- because it is built with a fluent API

But you are right: it is a C# technique. Thanks for the tip!
