### ISSUE TITLE
Setting default via definePreferredLocale not working

### ISSUE THREAD

**Issue by AmmarCSE** [robisim74/angular-l10n#55]
If you try to set the default like:

        this.locale.definePreferredLocale('it', 'IT', 30);

it doesnt work.

Stepping through, before that method is called the defaults are empty. After, it is always set to 'en-US' regardless. This happens in demo repo itself.

**Comment by robisim74** [comment]
You are using the old way to configure the library. Please see the breaking changes from v2.0.0: https://github.com/robisim74/angular-l10n/releases

**Comment by AmmarCSE** [comment]
Ah ok, thanks.

For  those who did not update their version, the issue is if you previously set the default, it is stored in a cookie and changing it afterwards will not work. You will have to clear the cookie.

Thanks for the awesome library @robisim74

**Comment by robisim74** [comment]
@AmmarCSE  I'm closing this issue. If you need, open a new issue. Greetings
