### ISSUE TITLE
Validation non-required input

### ISSUE THREAD

**Issue by pavelsvehla** [robisim74/angular-l10n#56]
I would like to use `validateLocaleNumber` validation for a form field that is optional. That means both empty string or correctly formatted number are valid values.

Currently, an empty string does not pass the validation resulting into an invalid field. Is there any workaround to validate non-required inputs?

**Comment by robisim74** [comment]
You are right: at the moment an empty or null string is considered invalid, but actually it is not correct, because the only workaround is initializing the field with a value as 0, or hiding the error, but the form is invalid.

So tonight I will fix it and I will release a new version immediately.

**Comment by robisim74** [comment]
Fixed in v2.0.2: https://github.com/robisim74/angular-l10n/releases

**Comment by pavelsvehla** [comment]
Great, thanks!

**Comment by robisim74** [comment]
@reyze I'm closing this issue. If you need, open a new issue. Greetings
