### ISSUE TITLE
TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by melvas** [robisim74/angular-l10n#57]
Hi Roberto,

I've faced this error trying to run my project with **angular-l10n**. But this error is arrears just when I use minified version of @angular/core (*.umd.min.js). When I use non-minified version (*.umd.js) it works as expected. I use gulp in my project. 

Any help or advice is appreciated.

See snippet of my System.config below:

```
 map: {
            // our app is within the app folder
            app: 'client/dst',
            // angular bundles
            '@angular/core': 'lib:@angular/core/bundles/core.umd.min.js',
            '@angular/common': 'lib:@angular/common/bundles/common.umd.min.js',
            '@angular/compiler': 'lib:@angular/compiler/bundles/compiler.umd.min.js',
            '@angular/platform-browser': 'lib:@angular/platform-browser/bundles/platform-browser.umd.min.js',
            '@angular/platform-browser-dynamic': 'lib:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.min.js',
            '@angular/http': 'lib:@angular/http/bundles/http.umd.min.js',
            '@angular/router': 'lib:@angular/router/bundles/router.umd.min.js',
            '@angular/forms': 'lib:@angular/forms/bundles/forms.umd.min.js',
            // other libraries
            'rxjs': 'lib:rxjs',
            'angular-l10n': 'lib:angular-l10n/bundles/angular-l10n.umd.min.js'
        }
```

Thanks

**Comment by robisim74** [comment]
Hi Vasyl,

unfortunately, I'm not able to reproduce this problem. If you search on Google this error, always it seems related to an incorrect version of the installed packages. So my advice is this: remove the _node_modules_, use the latest version of the Angular packages, do a new fresh install, and verify that there are no requests from libraries of different versions of Angular.

Greetings

**Comment by melvas** [comment]
Thanks for quick response, but I've already done this many times and the problem is still here...

**Comment by robisim74** [comment]
It's weird... Can you post your _tsconfig.json_ and your _package.json_ (only the packages)?
Are you using gulp-typescript to compile your app?

**Comment by melvas** [comment]
Sure.

**_tsconfig.json:_**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "outFile": "client/dst/client-app.js",
    "lib": [ "es6", "es2015.promise", "dom" ]
  },
  "compileOnSave": true,
  "exclude": [
    "bin",
    "obj",
    "node_modules",
    "client/lib",
    "client/map-src"
  ]
}
```

and **_packages:_**
```
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/compiler-cli": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/platform-server": "2.4.5",
    "@angular/router": "3.4.5",
    "@angular/upgrade": "2.4.5",

    "es6-promise": "4.0.5",

    "angular-l10n": "2.0.0",

    "jquery": "3.1.0",
    "systemjs": "0.19.27",
    "core-js": "2.4.1",
    "reflect-metadata": "0.1.9",
    "rxjs": "5.0.3",
    "zone.js": "0.7.6",

    "bootstrap": "3.3.7",
    "spectrum-colorpicker": "1.8.0",
    "moment": "2.17.0",
    "chart.js": "2.4.0",
    "malihu-custom-scrollbar-plugin": "3.1.5"
  },
  "devDependencies": {
    "typescript": "2.1.5",
    "typings": "2.1.0",

    "gulp": "3.9.1",
    "merge-stream": "1.0.0",
    "rimraf": "2.5.4",
    "gulp-concat": "2.6.0",
    "gulp-rename": "1.2.2",
    "gulp-uglify": "2.0.0",
    "gulp-sourcemaps": "1.6.0",
    "gulp-angular-embed-templates": "2.3.0",
    "gulp-rev": "7.1.2",
    "gulp-clean-css": "2.0.12",
    "gulp-sass": "2.3.2"
  }
```

> Are you using gulp-typescript to compile your app?

Just common gulp I guess.

**Comment by robisim74** [comment]
OK, thanks. Later I will try to recreate the problem. I'll let you know.

**Comment by melvas** [comment]
Thanks a lot for your help

**Comment by robisim74** [comment]
I tried your configuration, and it works. But I have a doubt: are you using Visual Studio (I see that you exclude bin and obj folders)? Because in Visual Studio, it happened that previous versions of packages remain even after being uninstalled. So try to remove _node_modules_ outside VS, and from command line try to update your npm version (`npm install npm@latest -g`), and then run `npm install`.

**Comment by melvas** [comment]
Yup, I use VS2015. But before I deleted _node_modules_, I had closed VS and removed it with console command _rimraf node_modules_. 

But I'm not surre that I've updated npm version, Thanks for your advice, I'll do all these steps again and let you know the result.

**Comment by robisim74** [comment]
Ok, in Visual Studio I suggest also to use these settings: https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/

**Comment by melvas** [comment]
Roberto, thank you for your advices! Error dissapeared after I've updated npm version and reinstalled all modules. Thanks a lot!
