### ISSUE TITLE
Translation async provider fallback

### ISSUE THREAD

**Issue by davguij** [robisim74/angular-l10n#58]
I'm using the module into a project, loading the JSON files asynchronously from an external web API.

It would be nice having a fallback when the API doesn't respond for any reason. At this moment, the `LocalizationService` just prints an error to the console on the `getTranslation()` method, but the method itself returns `void` so there's no way of telling whether the async load was successful or not.

Maybe returning an Observable<boolean> would allow to define a fallback static object on loading error?

What do you think? Would you find this useful? What would be your preferred way of implementing this? I can try to put together a PR if you want me to.

Thanks and regards.

**Comment by robisim74** [comment]
You can't return an Observable, because `getTranslation` method is not public: at runtime (when you change language) it's invoked by an event. But you are right: at the moment there is only a `console.error`: I think we could fire an event when there is an error on the loading, that you can subscribe as an observable to perform a custom action.
What do you think?

**Comment by IDisposable** [comment]
That would be ideal, also looking for a way to merge multiple localization sources into one package (we've got microservices that each offer up some localizable content), so eventing on even success would be helpful.

**Comment by davguij** [comment]
@robisim74 Sounds good. Either way, the point is being able to notify subscribers of a possible HTTP error.
I'll fork and try to come up with something later today / tomorrow and will let you know.

**Comment by robisim74** [comment]
I made a commit https://github.com/robisim74/angular-l10n/commit/823e0091de562a7e8d6c917f1a7a2b39d939f8e5 to add a `translationError` event and to add a new `AddWebAPIProvider` method to the configuration.

I'm going to release a new version by Monday.

Greetings,

Roberto

**Comment by davguij** [comment]
Sorry I really couldn't find the time to get to code on it :(

Anyway, good job, @robisim74!

**Comment by robisim74** [comment]
Hi,

no problem: thanks for suggesting this improvement.

I released the new version: see [releases](https://github.com/robisim74/angular-l10n/releases).

I suggest to subscribe the `translationError` event before calling the `init` method:

```
this.translation.translationError.subscribe((error: any) => console.log(error));

this.translation.init();
```

Greetings,

Roberto

**Comment by davguij** [comment]
Just updated from 1.4.1 and the new `translationError` event works like a charm.

I'm taking the liberty of closing the issue now.

Once again, great job!
