### ISSUE TITLE
Separate JSON translation files

### ISSUE THREAD

**Issue by melvas** [robisim74/angular-l10n#59]
Hi Roberto,

I want to use different translation files for each module (component). Is there any way to do this?

Thanks

**Comment by robisim74** [comment]
Hi @melvas,

https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#5

Also the List module/component of the [sample](https://github.com/robisim74/angular-l10n-sample) is built in this way.

Greetings,

Roberto

**Comment by melvas** [comment]
Thank you for quick response. I thought that this functionality is for additional translation files loading. Looks like I misunderstand you or my question was unclear. 

Let's say that I have two different variants of translation for one term in different files:

**locale-en.json:**
`{
   "term": "translation 1"
}`

**locale-test-module-en.json:**
`{
   "term": "translation 2"
}`

**test-module-main.component.ts:**
`<span translate>term</span>`

And my goal is to use _locale-test-module-en.json_ translation variant for _TestModule_ and ignore other one.

Thanks

**Comment by robisim74** [comment]
It isn't _for additional translation files loading_: you can usually add more than one translation file using `AddProvider` method.

Please read the documentation and see the sample app: with Lazy loading you can create a new instance of the service _with its own translation data for every lazy loaded module/component_.

**Comment by melvas** [comment]
Ok, I will read and try it again. Thanks.

**Comment by melvas** [comment]
I've tried to do this in the same way as in your sample. Please look to excerpts of my code below:

**app.module.ts:**

         `import { NgModule, APP_INITIALIZER, Injectable } from '@angular/core';
          ...
          import { LocalizationModule, LocaleValidationModule, LocaleService, TranslationService } from 'angular-l10n';
          ...
          //Base components
          import { AppComponent } from './app.component';
          import { NavigationComponent } from './spot-rt-manager-app/navigation/components/navigation.component';

          @Injectable()
          export class LocalizationConfig {
              constructor(public locale: LocaleService, public translation: TranslationService) { }

              load(): Promise<any> {
                  this.locale.AddConfiguration()
                      .AddLanguage('en')
                      .AddLanguage('sp')
                      .SetCookieExpiration(30)
                      .DefineDefaultLocale('en', 'US')
                      .DefineCurrency('USD');
                  this.locale.init();

                  this.translation.AddConfiguration()
                      .AddProvider('./assets/locale-');

                  let promise: Promise<any> = new Promise((resolve: any) => {
                      this.translation.translationChanged.subscribe(() => {
                          resolve(true);
                      });
                  });

                  this.translation.init();

                  return promise;
              }
          }

          // AoT compilation requires a reference to an exported function.
          export function initLocalization(localizationConfig: LocalizationConfig): Function {
              return () => localizationConfig.load();
          }

          // APP_INITIALIZER will execute the function when the app is initialized and delay what it provides.
          @NgModule({
              imports: [
                  ...
                  LocalizationModule.forRoot(), // New instance of LocaleService & TranslationService.
                  LocaleValidationModule.forRoot(),
                  ...
              ],
              declarations: [...],
              providers: [
                  LocalizationConfig,
                  {
                      provide: APP_INITIALIZER,
                      useFactory: initLocalization,
                      deps: [LocalizationConfig],
                      multi: true
                  }
              ],
              bootstrap: [AppComponent]
          })

          export class AppModule { }`

**customer.module.ts:**

          `import { LocalizationModule } from 'angular-l10n';
          ...

          @NgModule({
              imports: [
                  ...
                  LocalizationModule.forChild(),
                  ...
              ]
              ...
          })`

**customer.component.ts:**

         `import { Localization, LocaleService, TranslationService } from 'angular-l10n';
           ...
         
         @Component({
             selector: 'customer-block',
             templateUrl: 'customer.component.html',
             encapsulation: ViewEncapsulation.None
         })
         
         export class CustomerComponent extends Localization implements OnInit, OnDestroy {
             ...
             constructor(public locale: LocaleService, public translation: TranslationService) {
                 super(locale, translation);
         
                 this.translation.AddConfiguration()
                     .AddProvider('./assets/locale/customer-');
                 this.translation.init();
             }
         }

**locale-es.json:**

        `{
           ...
           "Customer": "Cliente 'locale-es.json'"
           ...
        }`

**customer-es.json:**

        `{
           ...
           "Customer": "Cliente 'customer-es.json'"
           ...
        }`

This is part of my app: blue header is _navigation.component_ from _app.module_ and grid is _customer.component_ from _customer.module_:
![image](https://cloud.githubusercontent.com/assets/1480027/23165327/3d2ce220-f844-11e6-846c-5b9f52b0b759.png)

When I choose Spanish language it uses translation of 'customer' from _customer-es.json_ for both components:
![image](https://cloud.githubusercontent.com/assets/1480027/23165424/ba7acb98-f844-11e6-8125-cea650893099.png)

This is what I want to prevent. Can you give me any advice how to achieve this please?

Also I noticed that when I refresh page it doest'n load _customer-es.json_ file (see screenshot below). Maybe I have forgot something?
![image](https://cloud.githubusercontent.com/assets/1480027/23165657/ea8f1766-f845-11e6-9b99-8e2c6ce4993d.png)

Thank you

**Comment by robisim74** [comment]
>  it uses translation of 'customer' from customer-es.json for both components

Do both components belong to the `customer` module?

About the problem on the refresh, make sure that cookies are not disabled, and try to clear the cache.

**Comment by melvas** [comment]
> Do both components belong to the customer module?

No, they belong to different modules.

> make sure that cookies are not disabled, and try to clear the cache.

Cookies are enabled and I cleared cache several times
![image](https://cloud.githubusercontent.com/assets/1480027/23166514/98de383a-f849-11e6-8317-bc8be4cf12a0.png)

**Comment by robisim74** [comment]
> .AddLanguage('sp')

Try to correct it: `.AddLanguage('es')`.

Please check also the codes when you set a new language.

**Comment by melvas** [comment]
OMG, sorry! My mistake. 

> Please check also the codes when you set a new language.

It was only one place with such mistake. Thanks

I've fixed it, rebuilt all bundles and cleared cache but nothing is changed for me :(

**Comment by robisim74** [comment]
Because the configuration seems correct, I need to know how are built components and modules, with the configuration of the router. As said, there is an example without these problems.

**Comment by melvas** [comment]
> I need to know how are built components and modules, with the configuration of the router

There is an `app.module` - main module of my project, `customer.module` which is imported to the main module and  `customer-stops.module` which  is imported to `customer-stops.module` and exports `customer-stops.component`. `navigation.component` (blue bar with tabs) belongs to `app.module`. `customer-stops.component_ (grid) belongs to _customer-stops.module_.

Please see code excerpts below:

**app.module:**

     `import { AppRoutingModule } from './app-routing.module';
     ...
     import { CustomerModule } from './spot-rt-manager-app/customer/customer.module';
     
     //Base components
     import { AppComponent } from './app.component';
     import { NavigationComponent } from './spot-rt-manager-app/navigation/components/navigation.component';    

     @NgModule({
         imports: [
             ...
             AppRoutingModule,
     
             LocalizationModule.forRoot(), // New instance of LocaleService & TranslationService.
             LocaleValidationModule.forRoot(),

             CustomerModule,
         ],
         declarations: [
             AppComponent,     
             NavigationComponent
         ],
         providers: [...],
         bootstrap: [AppComponent]
     })
     
     export class AppModule { }`

**app-routing.module:**

     `import { NgModule } from '@angular/core';
     import { Routes, RouterModule } from '@angular/router';
     
     const appRoutes: Routes = [
     ];
     
     @NgModule({
         imports: [
             RouterModule.forRoot(appRoutes)
         ],
         exports: [
             RouterModule
         ]
     })
     
     export class AppRoutingModule { }`

**customer.module:**

     `import { CustomerRoutingModule } from './customer-routing.module';     
     import { RouterModule } from '@angular/router';
     
     import { CustomerStopsModule} from './modules/stops/customer-stops.module';
     ...
     
     @NgModule({
         imports: [
             CustomerRoutingModule,
             RouterModule,
             ...
             CustomerStopsModule
         ],
         ...
     })
     
     export class CustomerModule {  }`

**customer-routing.module:**

     `import { Routes, RouterModule } from '@angular/router';
      ...
     import { CustomerComponent } from './components/customer.component';
     import { CustomerStopsComponent } from './modules/stops/components/customer-stops.component';
     
     const customerRoutes: Routes = [
         {
             path: 'customer',
             component: CustomerComponent,
             canActivate: [LoggedInGuard],
             children: [
                 ...
                 {
                     path: '',
                     component: CustomerStopsComponent
                 }
             ]
         }
     ];
     
     @NgModule({
         imports: [
             RouterModule.forChild(customerRoutes)
         ],
         exports: [
             RouterModule
         ]
     })
     
     export class CustomerRoutingModule { }`

**customer-stops.module:**

     `import { RouterModule } from '@angular/router';
     
     import { CustomerStopsComponent } from './components/customer-stops.component';
     ...
     
     @NgModule({
         imports: [     
             LocalizationModule.forChild()
         ],
         declarations: [
             CustomerStopsComponent,
         ],
         exports: [
             CustomerStopsComponent
         ]
     })
     
     export class CustomerStopsModule {  }`

**customer-stops.component:**

     `import { ActivatedRoute } from '@angular/router';
     
     import { Localization, LocaleService, TranslationService } from 'angular-l10n';
     ...
     
     @Component({
         selector: 'customer-stops-block',
         templateUrl: '../src/spot-rt-manager-app/customer/modules/stops/templates/customer-stops.component.html',
         encapsulation: ViewEncapsulation.None
     })
     
     export class CustomerStopsComponent extends Localization implements OnInit, OnDestroy {
         constructor(private route: ActivatedRoute, public locale: LocaleService, public translation: TranslationService) {
             super(locale, translation);
     
             this.translation.AddConfiguration()
                 .AddProvider('./assets/locale/customer-stops-');
             this.translation.init();
         }
     }`

I hope it will be useful.

Thank you

**Comment by robisim74** [comment]
Your modules are not lazy loaded, that's the problem. So you have always one instance of the service.

**Comment by robisim74** [comment]
I try to explain better: you have multiple routers and modules in cascade: that way you're writing a lot of code but it's like you are in the app module yet: _Angular doesn't create new instances of the classes in this case_: you will have the same problem when you will try to inject your own services.

Obviously there is a way to force a new instance: just use `providers` in the `customer-stops.component`:

```
 @Component({
     selector: 'customer-stops-block',
     providers: [TranslationService],
     ...
 })
```

In this way, the new instance with its translation file will be used by the component and by its descendants (not the modules).

But keep in mind that all the modules, the components and the json files will be loaded at the boostrap of the app, so I think you should consider to simply add more than one provider in the app module.

Instead, if you want to deepen the lazy loading, I suggest you these articles:
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load
https://vsavkin.com/angular-router-declarative-lazy-loading-7071d1f203ee#.tassoed85
and if you use webpack:
https://damienbod.com/2017/01/14/angular-2-lazy-loading-with-webpack-2/

Greetings,

Roberto

**Comment by melvas** [comment]
Thanks, I've tried to add providers and it is works for me now. 

And also thank you for the articles, but I will have to bundle my app into one file by some reasons that's why I will cannot use lazy loading I guess. 

I think it would be nice to have ability to force directive (pipe) to use specific translation file, added in app.module,  via parameter etc:

`<span translate translationContext="customer-stops-">Customer</span>`
`<span>{{'Customer' | translate:lang:'customer-stops-'}}</span>`

But it's just my suggestion. What do you think about this?

**Comment by robisim74** [comment]
One file for directive/pipe means one translation service for directive/pipe: it would downgrade memory & performance. Sorry, but I think is not possible.

Greetings

**Comment by melvas** [comment]
In this case yes, you are right...

Thank you for your help and guidance.
