### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by melvas** [robisim74/angular-l10n#60]
Hi @robisim74,

Is there is any ability to change time zone according to locale in _angular-l10n_?

Thank you

**Comment by robisim74** [comment]
Hi @melvas,

you can use the timezone component in the format, as the official Angular DatePipe: 
https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html

Both use Intl.DateTimeFormat:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

Greetings,

Roberto

**Comment by melvas** [comment]
Yes, I can do this, but I couldn't **set** timezone. Let's say I have UTC date from server and I need to convert it to current locale. 

Official A2 DatePipe cannot do this: https://github.com/angular/angular/issues/9324

Thanks

**Comment by robisim74** [comment]
In Intl doc I find:
```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

// formats below assume the local time zone of the locale;
console.log(new Intl.DateTimeFormat('en-US').format(date));
...
```

Can you post an example of input, and the expected output?

Edit. Official Angular DatePipe has the problem that you can't change the default locale at runtime, as this library allows. So you should not need to set time zone, because it is set according to the default locale.

**Comment by melvas** [comment]
This example looks pretty close to what I want: http://jsfiddle.net/uq99udc9/4/

**Comment by robisim74** [comment]
Ok, I see. No, you can't do that. Pipes/directives are used to format the values, not as an interpreter: you have to still use specific libraries for that.

However, now Chrome supports Timezone options in Intl API, and I want to test this new polyfill: https://github.com/yahoo/date-time-format-timezone

But I have not yet planned this change.

Greetings,

Roberto

**Comment by melvas** [comment]
Ok, I will use `moment.js` for this now. Thank you. But I have else one question to you. Can I ask it here or I have to create new issue instance?

Thanks,

Vasiliy

**Comment by robisim74** [comment]
New question, new issue.

**Comment by melvas** [comment]
Got it, thank you.

Vasiliy
