### ISSUE TITLE
navigator is not defined when using it with ASP.NET Core PreRendering

### ISSUE THREAD

**Issue by damirkusar** [robisim74/angular-l10n#61]
Hi @robisim74, 

first of all, great job with this library. Really like it.. but I am running into a problem when using it with pre-rendering in a .net core app. When doing the pre-rendering, it does not allow or now DOM specific things.. So I am getting the following error (part of it):
`...navigator is not defined ... node_modules\angular-l10n\bundles\angular-l10n.umd.js:259:33)`

this is the following line in the above mentioned file:
`this.hasCookie = typeof navigator.cookieEnabled !== "undefined" && navigator.cookieEnabled;`

When removing this line or commenting it out, PreRendering works. But because it is in your lib, it does not persist :)

What can we do here to have a permanent solution?

I have a project where you can reproduce it here: [https://github.com/damirkusar/AngularMeetsNetCore](https://github.com/damirkusar/AngularMeetsNetCore)

You will have to enable Pre-Rendering in the index.cshtml file under Views/Home by adding this to the app tag:
`asp-prerender-module="ClientApp/dist/main-server"`

Thank you very much
Damir

**Comment by robisim74** [comment]
Hi @damirkusar,

interesting question. During PreRendering, browser is not supported. I'll try your app, and I'll try a solution.

Let you know as soon as possible.

Greetings,

Roberto

**Comment by damirkusar** [comment]
Hey @robisim74,

Thank you.. will also play more on that :)

**Comment by robisim74** [comment]
As Steve Sanderson wrote in this article http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/:

>There are limitations with server-side rendering. Notably, your application code can’t just assume it always runs in a browser. If you try to reference the browser’s DOM directly, you’ll get an error like window is undefined when it runs server-side.

Unfortunately, the problem is not only `navigator`:  I can remove this control on it, but also `directives` will give you an error using prerendering, because they reference the browser's DOM directly.

So I think you have to renounce to prerendering if you want to use this library as-is (or you have to renounce to this library if you want to use prerendering).

**Comment by robisim74** [comment]
Edit. The night brings counsel... I'll try to remove all the references to the DOM (without lose functionalities).

Let you know.

**Comment by damirkusar** [comment]
Good Morning,

this sounds great :) thank you.. looking forward to hear from you again..

EDIT:
Maybe not the nicest solution, but as a workaround we could add a new test if navigator, browser or window is definded as well:
`this.hasCookie = typeof navigator !== "undefined" && typeof navigator.cookieEnabled !== "undefined" && navigator.cookieEnabled;`

This could help that when it renders on server that this is ignored, but in the browser, it will / shoule work

**Comment by robisim74** [comment]
Hi @damirkusar,

yes, I fixed `navigator` in this way. Regard to directives, I found the solution renouncing the methods on DOM elements, and using the properties: this is an interesting aspect, which I hope to deepen.

If you want to test the commit, you have to uninstall the library and follow the instruction in README file to build and install the library. Please note that I made a little breaking change by another commit, and you have to use `AddWebAPIProvider` method in configuration.

However, by Monday, I'm going to release a new version of the library.

Have a nice Sunday,

Roberto

**Comment by robisim74** [comment]
Hi @damirkusar,

I released the new version of the library that supports prerendering: see [releases](https://github.com/robisim74/angular-l10n/releases).

Greetings,

Roberto

**Comment by damirkusar** [comment]
Good Morning @robisim74 

Thanks for the Realease and quick fix. Using 2.0.4 now it can not find the AddWebApiProvider nor the translationError

```
this.translation.AddConfiguration().AddWebAPIProvider('/api/localisations/', 'json', true);
this.translation.translationError.subscribe((error: any) => console.log(error));
```

**Comment by damirkusar** [comment]
Hi @robisim74,

thanks for the update, it works great.. thank you.. 

I think you should add to your README that you are supporting now Pre-Rendering, as one additional selling point :) 

Great work.. thanks again
Damir
