### ISSUE TITLE
Translations not working in case of Lazy loaded modules with ChangeDetection set to OnPush

### ISSUE THREAD

**Issue by anilchinnu21** [robisim74/angular-l10n#63]
Tried using 'translate' pipe along with 'aync' pipe in a child module. It just shows key name as it is.

**Comment by robisim74** [comment]
See #47. `With ChangeDetectionStrategy.OnPush` you have to pass also `ChangeDetectorRef`:

```
constructor(public locale: LocaleService, public translation: TranslationService, public cd: ChangeDetectorRef) {
        super(locale, translation, cd);
}
```

Greetings,

Roberto

**Comment by anilchinnu21** [comment]
Ok.

Do I need to do this in each component? or is there a way to set this at module level?

**Comment by robisim74** [comment]
You have to use `ChangeDetectorRef` only into the components that use `OnPush` and that extend `Translation` or `Localization` class. It isn't possible in the module.

**Comment by anilchinnu21** [comment]
Ok. Thank you.

I will close this ticket.
