### ISSUE TITLE
TranslationConfig.addTranslation instead just sets translations

### ISSUE THREAD

**Issue by AHelper** [robisim74/angular-l10n#66]
It seems like 2.x regressed on #22 where `TranslationConfig.addTranslation` overwrites instead of adds translations.  Was this intentional?  If so, the name isn't clear that it actually overwrites.  Otherwise, could the previous behavior be restored?

**Comment by robisim74** [comment]
Yes, it was removed from v2.0.0. But are you using _direct loading_ instead of _json_ files? Do you need it for Angular v2 or Angular v4?

**Comment by AHelper** [comment]
Direct (by json, I assume you mean async loading json files with multiple providers). In my particular case, I'm importing a set of json files depending on module. These are bundled together with the app with SystemJS builder, so no requests are made for translations and I immediately have js objects with the translations.

I can easily handle merging these together on my end, just came up when (finally) migrating off of 1.x and caught me off guard as it did before.

**Comment by robisim74** [comment]
Ok, np. You are right: it's a regression. I can immediately release a new version: do you need it only for Angular 4 or even for Angular 2?

**Comment by AHelper** [comment]
I'm on 2.x right now (Angular 2.4.x).

**Comment by robisim74** [comment]
Ok, I'll release v2.0.8 (you need Angular ^2.4.5) and v3.0.1 (Angular ^4.0.0) tonight.

**Comment by AHelper** [comment]
Thanks a bunch!

**Comment by robisim74** [comment]
Hi @AHelper,

I released v2.0.8 for Angular v2 and v3.0.1 for Angular v4 with the fixes: https://github.com/robisim74/angular-l10n/releases

If you are migrating from _angular2localization_ to _angular-l10n_, you can see the changes here: https://github.com/robisim74/angular-l10n/releases/tag/v2.0.0

Greetings

**Comment by AHelper** [comment]
@robisim74 Finally got this pulled down, works like a charm, thanks!

**Comment by robisim74** [comment]
Well! Thanks for reporting. Greetings
