### ISSUE TITLE
DefineDefaultLocale & UseLocaleAsLanguage not translating

### ISSUE THREAD

**Issue by skyfremen** [robisim74/angular-l10n#68]
this.locale.AddConfiguration().DefineDefaultLocale('ja', ''); // not working
this.locale.setDefaultLocale('ja', ''); //working
this.translation.AddConfiguration().UseLocaleAsLanguage();

If i set the configuration to use UseLocaleAsLanguage while using DefineDefaultLocale('ja', '') it will pass 'undefined' to the WebAPI. 
However when using this.locale.setDefaultLocale('ja', ''); it will be working.
Please help, thanks.

**Comment by robisim74** [comment]
- You are using `DefineDefaultLocale` without setting the _countryCode_, that is required.
If you need only the translation of texts, you should use only `defineLanguage`.
- `UseLocaleAsLanguage` _sets the use of locale (languageCode-countryCode) as language_, that means you should have more translation files for each language, for example:` en-US`, `en-GB` and so on. So it works only if you set also the required _countryCode_.
If you don't have more translation files for each language, you should not use `UseLocaleAsLanguage`.
