### ISSUE TITLE
Translation not working in case of lazy loading

### ISSUE THREAD

**Issue by anilchinnu21** [robisim74/angular-l10n#69]
Translation doesnt work in case of lazy loaded module. 
I have set the configuration in my component class as described in documentation.
`this._translationService.AddConfiguration()
            .AddProvider('./assets/translate/employee-');
        this._translationService.init();`

Translate pipe works fine but translate method call within component class doesnt work.
`ngOnInit() {
this.text = this._translationService.translate('HELLO');
}`

**Comment by robisim74** [comment]
https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.3

```
ngOnInit() { 
    this.text = this._translationService.translate('HELLO');

    this.translation.translationChanged.subscribe(
            () => { this.text = this._translationService.translate('HELLO'); }
    );
}

```
