### ISSUE TITLE
LocaleDecimalPipe transform error with minIntegerDigits and maxFractionDigits

### ISSUE THREAD

**Issue by skyfremen** [robisim74/angular-l10n#70]
I have a problem when transforming Decimals, I have set minIntegerDigits = 1, minFractionDigits = 0 and maxFractionDigits = 9. However when I increase the integer value, the maxFractionDigits seems to decrease.

var numberValue: number = 111111111.1234567;
var stringValue= this.localeDecimalPipe.transform(111111111.1234567, 'en-US', '1.0-9');

**Expected** 
stringValue = "111,111,111.1234567"

**Actual** 
stringValue = "111,111,111.123457"

**Comment by robisim74** [comment]
`localeDecimalPipe` uses Angular `DecimalPipe`, that uses `Intl.NumberFormat` API: the standard defines 20 as max value for `maximumFractionDigits`, but browsers seem to use max 15 digits (integer + fraction). In fact, if I do this:

`Intl.NumberFormat('en-US', {minimumIntegerDigits: 1, minimumFractionDigits: 0, maximumFractionDigits: 20}).format(123456789.1234567);`

I get your same result.

So if you really need more than 15 digits, I think you can't use `localeDecimalPipe` and Angular `DecimalPipe`. You have to build your own custom filter.

Greetings
