### ISSUE TITLE
[Question] Best practice for long and formatted text

### ISSUE THREAD

**Issue by mscudlik** [robisim74/angular-l10n#73]
I am not a very experienced web developer so i'm kind of asking myself what is the best practive for long static texts (not coming from a backend service) in combination with formatting, text placeholders and localization (not just some labels).  

Currently i luckily don't yet have a lot of these larger texts block so i basically split them in multiple blocks,
which is in my opinion not so nice and i guess there is a better way to archive this.

Do i need a CMS for this and include the pages usng iframes or something or is there a better solution?

This question is not restricted to angular-l10n but as i'm using it and i think others might have struggled with the same thing.

Thanks for any tips and tricks,
Matthias

**Comment by SvenBudak** [comment]
Just use any Translation Tool like https://www.codeandweb.com/babeledit
This will solve your problem...

**Comment by Pasqualle** [comment]
It depends how much text you have.
It is quite easy to pull (multilingual) content from a CMS (via REST or graphQL). Here is one (non-angular) example: https://using-drupal.gatsbyjs.org/ source code link in the footer.

**Comment by robisim74** [comment]
Closed due to inactivity
