### ISSUE TITLE
Server-Side Renderer: MutationObserver

### ISSUE THREAD

**Issue by SpiffyJr-Envisage** [robisim74/angular-l10n#74]
Hi there,

In your docs I noticed your library said it's both AoT and server-side compatible. Trying it on the server gives me the following error:

```Listening on: http://localhost:8000
ERROR { ReferenceError: MutationObserver is not defined
    at TranslateDirective.BaseDirective.addTextListener
```

**Comment by robisim74** [comment]
Thanks for reporting. Will be fixed in the next release.

The feature has been introduced in v2.0.6, so if you need to work you should use v.2.0.5 in the meantime: https://github.com/robisim74/angular-l10n/releases (if you are using Angular 4 you'll get warnings, but it is compatible).

Greetings

**Comment by robisim74** [comment]
Fixed in the latest release. Greetings
