### ISSUE TITLE
Support for parsing and validating dates, percentages and currencies?

### ISSUE THREAD

**Issue by surfspiders** [robisim74/angular-l10n#75]
This is a very nice API...
Do you also support parsing and validating date and percentage strings? Or do you have something like this planned in the future?

For example do you have a similar function like the parseNumber method of LocaleValidation (for example: parsePercentage or parseDate)? Or  I need a similar method like validateLocaleNumber for validation of percentage or date fields. 

Or do you perhaps know an alternative?

**Comment by robisim74** [comment]
For numbers, percentages and currencies, the number format is the same: so you can validate & parse with that API (but if you have strings that contain symbols, you must remove them before parsing).
Dates are the real question: initially I thought to use the same algorithm. I already created the classes for this scope. But then I stopped, for two reasons:
- You should create an algorithm for each calendar (and each date format)
- Usually you use the _datepicker_ in web apps, particularly if multilingual

So I don't think I add other functions, unless someone proposes some interesting ideas or wants to contribute.

**Comment by robisim74** [comment]
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0
