### ISSUE TITLE
Typescript support for translations of Currencies and Decimals

### ISSUE THREAD

**Issue by thormentor** [robisim74/angular-l10n#76]
How can I use l10n to format currencies and decimals in typescript? 
I can't manage to find any documentation on this subject.

**Comment by robisim74** [comment]
With _TypeScript support_, do you mean how to get translation of decimals and so on in classes?

If yes, you have the `getDefaultLocale` method of `LocaleService`, and the `defaultLocaleChanged` event to know when _defaultLocale_ changes. Then you can use the `tranform` method of pipes like in Angular to get the translation, but you could use also the _Intl_ APIs directly (or also use other specific libraries).
So you can do something like this:

```
constructor(public locale: LocaleService,) {
    let pipe = new LocaleDecimalPipe();
    let translatedValue = pipe.transform(1234.5, this.locale.getDefaultLocale(), '1.2-2');
    
    // You need to subscribe to the following event if you want get the new value when defaultLocale changes because you are in the constructor.
    this.locale.defaultLocaleChanged.subscribe(
        () => {
            translatedValue = pipe.transform(1234.5, this.locale.getDefaultLocale(), '1.2-2');
        }
    );
}
```
The logic is the same of the translation of texts: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#33-getting-the-translation-in-component-class

**Comment by thormentor** [comment]
Thanks @robisim74, this is just what I need.

**Comment by robisim74** [comment]
Ok, np. I'll update the docs. Greetings
