### ISSUE TITLE
HTML tags in translation

### ISSUE THREAD

**Issue by hruslowkirill** [robisim74/angular-l10n#77]
When putting html tags in locale json, they are outputted as text.
`"name" : "Hello, my name is <strong>John</strong>"`

So when I use 
`<p translate>name</p>`
I see <strong> tags instead of word John actually being bold. Does your library support HTML tags?

**Comment by robisim74** [comment]
Using pipes:
 
`<p [innerHTML]="'name' | translate:lang"></p>`

Regarding use of directives, I'm evaluating if translate _innerHTML_ property: maybe in the next release you will do this:

`<p [innerHTML]="'name'" translate></p>`

**Comment by robisim74** [comment]
In the latest release, I added support also to directives for using Html tags in translation.

Greetings
