### ISSUE TITLE
JSON keys issue

### ISSUE THREAD

**Issue by melvas** [robisim74/angular-l10n#78]
Hi Roberto,

I've faced strange behavior of `translate` directive/pipe: when I'm trying to use '.' (dot) symbol in JSON key seems like the lib trims it by dot and returns just last part of the key (see screenshots below please). Also there is some problem with translation when key starts with numbers. 
 
![image](https://cloud.githubusercontent.com/assets/1480027/24911498/d26f4d36-1ed3-11e7-9a40-6af45dced42b.png)

![image](https://cloud.githubusercontent.com/assets/1480027/24911416/82c3b93e-1ed3-11e7-8af1-be6b62d048a6.png)

![image](https://cloud.githubusercontent.com/assets/1480027/24911464/ad6ce7be-1ed3-11e7-8024-247147fb1691.png)

Maybe there are some rules for JSON keys?

Thank you,

Vasiliy

**Comment by robisim74** [comment]
Hi Vasiliy,

regarding the dot, yes it is used by default for composed keys: you can choose another symbol during the configuration, calling `setComposedKeySeparator` method of `TranslationService`.

By default, the service tries to translate the keys that start with a number: this feature is used during the pluralization. For now, you can't avoid it: the service uses only the string after the number as a key.
I can add a method to disable this feature, but you should wait for the next release.

**Comment by IDisposable** [comment]
Should probably be using keys that make it clear this string hasn't been localized (e.g. `YearlyPieces`) and _always_ putting in the translation _even_ for English (e.g. `12-Month Pieces`) ... this sets a standard for localization that is much easier to ensure things get localized and also makes the selection of _keys_ independent of the content, and thus easier to work around the automatic features of the library such as dot and number conventions.

**Comment by melvas** [comment]
Got it, thank you, @robisim74 .

P.S. @IDisposable, thank you for your advice, this way I've already choose today evening :)
