### ISSUE TITLE
Localization 0.7.1 not working

### ISSUE THREAD

**Issue by damienbod** [robisim74/angular-l10n#8]
Hi Roberto

I updated to version 0.7.1, and the localization no longer works. Empty strings are returned from the pipe.

https://github.com/damienbod/Angular2LocalizationAspNetCore/tree/angularLocalization071

Greetings Damien

**Comment by robisim74** [comment]
Hi Damien,

see [here](https://github.com/robisim74/angular2localization/releases): there are important Breaking changes from 0.7.0 version.

**Comment by damienbod** [comment]
Thanks, fixed.

**Comment by robisim74** [comment]
:+1:
