### ISSUE TITLE
addConfiguration is not a function

### ISSUE THREAD

**Issue by yonigo** [robisim74/angular-l10n#80]
Im trying to use this with ng-fullstack (ng2 & typescript), and i get the error:

"this.translation.addConfiguration is not a function", after following all the instructions.

What am I doing wrong?

Tanks

**Comment by robisim74** [comment]
Which version of the library are you using?

**Comment by yonigo** [comment]
Sorry, important detail.. 2.0.9
I can't use anything higher because of my angular version..

**Comment by robisim74** [comment]
Ok, for Angular v2 there is the old branch: https://github.com/robisim74/angular-l10n/blob/angular_v2/doc/spec.md

The methods of configurations were in _PascalCase_: 
```
    this.translation.AddConfiguration()
        .AddProvider('./assets/locale-');
```

**Comment by yonigo** [comment]
Works great! Thanks.

**Comment by IuriiKryventsov** [comment]
@robisim74 would be great to correct docs..
