### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by adjiandov** [robisim74/angular-l10n#82]
Sample app is not running on IE11. I have been looking at all the possibilities for localizing/translating angular application and once there is something useful and suitable, there always is some wall that stops me from implementing the solution.

This solution is very nice and before I started implementing it I found out that it would not work on IE11 (a browser I have to support for my app). This seems to be an angular issue, just posting it here so we can all push them to fix this asap. This is their [issue](https://github.com/angular/angular-cli/issues/5762) and this solution is also hit by it, since the sample [application ](https://robisim74.github.io/angular-l10n-sample/#/home)that is posted here is not running on IE11.

Hopefully this will be fixed by them, or if not I am open to suggestion and workarounds, so I can implement your solution.

**Comment by robisim74** [comment]
Hi @adjiandov,

thanks for reporting: I didn't know this Angular v4 bug. It seems a problem of _APP_INITIALIZER_ in AoT mode. This library doesn't use _APP_INITIALIZER_. The sample app uses it, but it is only a proposal, you are not forced to use it.
I prefer waiting for the official fix, but in the issue you have linked there seem to be some workarounds (I didn't try yet).

Greetings

**Comment by robisim74** [comment]
Sample app is back to running also in IE11.
