### ISSUE TITLE
After missing value for key I want to see whole key path

### ISSUE THREAD

**Issue by ignaszewski** [robisim74/angular-l10n#83]
Example:
`<div>My text {{ 'NESTED.JSON.KEY' | translate }}</div>`
displays in HTML:
`<div>KEY</div>`
i want to have:
`<div>NESTED.JSON.KEY</div>`

in angular-l10n.js (version 3.0.3) in line 799 you replace key to last value of key chain and you dont pass it further in full version.
`getValue(key, args, lang) {
...
key = keys.shift();
...
return this.parseValue(key, value, args, lang);
`

Best solution would be a switch that allow to decide which key should be displayed full or short

**Comment by robisim74** [comment]
I think it's okay to return the whole path without using an option.

**Comment by robisim74** [comment]
The latest realease returns whole path when value is missing.

Greetings

**Comment by ignaszewski** [comment]
Thx a lot, our translation team have a lot of easier work now :)
