### ISSUE TITLE
Translation pipe working only partial.

### ISSUE THREAD

**Issue by kochurov-serg** [robisim74/angular-l10n#84]
Hi, 

I update my application and change angular version to 4.0.3. 
After update, my tags stopped working 
Example:
```
<span translate>CREATE_REPORT</span>
```
Chrome browser
```
<span>CREATE_REPORT</span>
```
If i use pipe then my translate work only partial.
I have list object. First object translate and other is not translate. There are no errors in the console
```
<app-item *ngFor="let item of model; let i = index" [model]="item" (onDelete)="onDelete($event, item, i)"></app-item>

My app-item
 <p class="result__info-title" *ngIf="model.active">{{ 'NEXT_REPORT' | translate }}</p>

```

```
package.json

    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/forms": "^4.0.3",
    "@angular/http": "^4.0.3",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@angular/platform-server": "^4.0.3",
    "@angular/router": "^4.0.3",
    "@angularclass/conventions-loader": "1.0.13",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@angularclass/request-idle-callback": "1.0.7",
    "@angularclass/webpack-toolkit": "1.3.3",
    "angular-l10n": "^3.0.4",
    "angular2-highcharts": "^0.5.5",
    "bootstrap": "3.3.7",
    "bootstrap-daterangepicker": "2.1.25",
    "core-js": "^2.4.1",
    "deep-assign": "^2.0.0",
    "dragula": "^3.7.2",
    "es6-shim": "0.35.3",
    "http-server": "0.9.0",
    "ie-shim": "0.1.0",
    "jasmine-core": "2.6.0",
    "jquery": "3.2.1",
    "jquery.inputmask": "^3.3.4",
    "moment": "^2.17.1",
    "ngx-bootstrap": "1.6.6",
    "ng2-dragula": "^1.3.0",
    "protractor": "^5.1.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.2.0",
    "systemjs": "0.20.12",
    "ts-helpers": "^1.1.2",
    "zone.js": "0.8.4"
  },
```

**Comment by robisim74** [comment]
To work with pipes, you have to use the following syntax:

`expression | translate:lang`

and extend `Translation` or `Localization` class in the component. Please see the docs: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.1

About the directives, you don't need anything: check if your configuration is correct: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2

**Comment by kochurov-serg** [comment]
>and extend Translation or Localization class in the component. Please see the docs: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.1

ie I can not use property defaultLocale in my template?
```
@Component({
    selector: 'app-monitoring-report-item',
    template: '<span>{{ 'REPORT_HEADER.DATE' | translate:defaultLocale }}</span>'
})
export class ReportItemComponent {

    defaultLocale: string;
    constructor(
        locale: LocaleService) {
        this.defaultLocale = locale.getCurrentLanguage();
    }
```

**Comment by robisim74** [comment]
The only important thing is to provide the language parameter to the pipe, but in the way you are using it, it will not update when the selected language changes. Try to compare with the `Translation` class: https://github.com/robisim74/angular-l10n/blob/master/src/services/translation.ts

Otherwise you should use a _getter_ (which is however called continuously by the Angular Change Detection mechanism), but you have to get the language from `TranslationService` and not from `LocaleService`:

```
get lang(): string {
 return this.translation.getLanguage();
}
```
because the language of `TranslationService` is updated when the http request is completed.

**Comment by kochurov-serg** [comment]
Thanks.
I had problem this animation, because translation not worked. But console not had error messages.
