### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Etchelon** [robisim74/angular-l10n#86]
Hello,
I'm just using the new version of the library for the first time for a new project and I'm liking the new directive a lot, saves a lot of typing (especially on the typescript side, I don't have to modify all the existing components)
But it's a bit less flexible than the pipe: I can't chain another pipe after the text is translated. Consider this:
`<span>Paziente: {{ patient.Fullname }} ({{ patient.Age }} anni)</span>`
I have defined the following resources:
{
  [...]
  "Patient": "Paziente",
  "YearsOld": "Anni"
}
I want to write all translations so that they start with a capital letter, but here "Anni" needs to begin with a lower case a in the translation.
Therefore my html has become:
`<span><span translate>Patient</span>: {{ patient.Fullname }} ({{ patient.Age }} {{ 'YearsOId' | translate:lang | lowerCase }})</span>`
Not only have I had to use the more verbose pipe instead of the translate directive, but I've also had to modify the component so that it extends Localization.

Now, what I suggest, as a feature request, is that you add an Input property to the translate directive so we can specify what pipe(s) to push the translation through. I'm thinking off the top of my head it can be easy to specify angular's built in pipes, but it would be cool to be able to reference our own custom pipes by name.
Therefore something like:
export class TranslateDirective {
  [...]
  @Input() postProcessPipes: string[] = [];
  [...]
}

What do you think?

Thanks and great job as always, your library is so well written and documented, it should be an example to many other library writers out there! Big thumbs up!

**Comment by robisim74** [comment]
Hi Andrea,

I see. But the solution you propose could only work for Angular pipes (lower, upper & slice), because I could control the name, and run them, not for other custom pipes that the directive can not know.
Instead, it would be interesting to pass a custom function, which performs any manipulation you want after the translation (but even in this case, you should declare the function or import it into the component).

**Comment by Etchelon** [comment]
Yeah with built in pipes it's straightforward, but since custom pipes are parsed from templates and recognized by name, maybe it's doable with them as well by using some API from the angular compiler. Not that I'm asking you to do it, it's just an idea.
Maybe if I find some spare time I'll try to implement this function myself to handle Angular's pipes and submit a pull request, but I don't promise anything!

Have a nice day.
