### ISSUE TITLE
(Request) support for sessionStorage

### ISSUE THREAD

**Issue by johaven** [robisim74/angular-l10n#87]
It would be interesting to store locale in sessionStorage instead localStorage.
Thanks for this great lib 👍

**Comment by robisim74** [comment]
Why?

**Comment by johaven** [comment]
Because sessionStorage is cleaned when browser is closed, localStorage is persistent and i would prefer to not use cookie :)

**Comment by robisim74** [comment]
I know that it's cleaned when the browser is closed, but why do you prefer not use a session cookie?

**Comment by johaven** [comment]
I have already a lot of cookies to manage XSRF, Access, Refresh Access ... My backend doesn't need this cookie and i try to keep my headers smaller as i can. Just a matter of logic (for me).
I also have some problems to display all cookies with browsers like firefox. For what is stored in storage everything is ok.
It's really a story of convenience.

**Comment by robisim74** [comment]
It's true: Firefox is not showing cookies! I also notice it. In the documentation I read:
>The DevTools don't show by default whether a cookie is secure

However, it is not a problem to add support also for SessionStorage: it will be done in the next release.

**Comment by robisim74** [comment]
The latest version 3.1.0 also supports SessionStorage:

```
this.locale.addConfiguration()
    .useSessionStorage()
    ...
```

**Comment by johaven** [comment]
Thanks ! 👍 I will try this !
