### ISSUE TITLE
Fallback when key not found.

### ISSUE THREAD

**Issue by Ghostbird** [robisim74/angular-l10n#88]
Is there some way to use the most specific language translation first, and cascade fallback when the key is not found?

For example, I have three language files:
global.json (translations that are identical in most languages)
en.json (translations for generic English)
en-GB.json (translation for British English)

My language and locale is set to en-GB. I request the following keys:
0. pants → resolves to 'trousers' in en-GB.json
0. shirt → not found in en-GB.json → resolves to 'shirt' in en.json
0. en-GB → not found in en-GB.json → not found in en.json → resolves to 'English (United-Kingdom)' in global.json

global.json is a catch-all for both keys that haven't been translated into other languages yet, and things that should show up the same in any language, but still should be "translated" In this case I translate a country-specific language code to the name of a language, but I want to use a single worldwide name for each language; the name of the language in that language itself e.g. English, Français and Deutsch instead of English, French and German.

How would I do something like this?

**Comment by robisim74** [comment]
I've never tried, but maybe it's possible to do this:

- Assign the same extension to all files, for example `global-en-GB.json`, `lang-en-GB.json`, `locale-en-GB.json`
- Add each prefix file as a provider during the configuration in the reverse order:
```
    this.translation.addConfiguration()
        .addProvider('./assets/global-')
        .addProvider('./assets/lang-')
        .addProvider('./assets/locale-')
        .useLocaleAsLanguage(); // Sets the use of locale (languageCode-countryCode) as language
```
The service merges the providers in order: so if it doesn't find a key in _lang_ or in _locale_ file, it should use the key of _global_ file.
However you can't keep only a `global` file for all the countries: you need to duplicate it for each language, or you shold avoid to use it and use directly its key (if the key is not found, the service returns the same key).

**Comment by Ghostbird** [comment]
Yes, I can do that. However, it will not solve my problem.
Can I add a provider in a way that does not automatically append language/locale code?
Then I could do something like:
```typescript
this.translation.addConfiguration()
    .addProvider('./assets/global.json')
    .addProvider('./assets/lang-' + languageCode)
    .addProvider('./assets/locale-' + languageCode + '-' + countryCode)
```
That would solve my problem.

The stacking mechanism with fallbacks is clearly already implemented in a very sensible way. It just isn't accessible yet in the way I want.

**Comment by robisim74** [comment]
> Can I add a provider in a way that does not automatically append language/locale code?

No, adding it through variables during configuration would be useless, because then the service could not know when your variables change.

Even if I add the option to choose the extension for each provider (global, language, language + country), then the issue of the merge order would remain (you want it so, but others might want it different).

This change requires a general design, and not only the desired specific behavior.

**Comment by Ghostbird** [comment]
I agree that it requires some changes, I think those would be an improvement, since they would allow the translation mechanism to more closely match natural languages.

Do you think it would be a good functionality?
I could write it and make a PR.

**Comment by robisim74** [comment]
Feel free to do a PR.

**Comment by robisim74** [comment]
See #91: this feature should solve also your problem. Using a custom loader you'll be able to implement fallback for translation files, according to the logic you prefer. Let you know.

**Comment by robisim74** [comment]
I released the new version of the library, that contains the support for custom provider: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4

I think that now you could solve your problem, making something like this:

```
this.translation.addConfiguration()
    .addCustomProvider({ type: "global", path: './assets/global' })
    .addCustomProvider({ type: "lang", path: './assets/lang-' })
    .addCustomProvider({ type: "locale", path: './assets/locale-' })
    .useLocaleAsLanguage();
this.translation.init();
```

The custom provider:
```
@Injectable() export class FallbackTranslationProvider implements TranslationProvider {

    constructor(private http: Http) { }

    public getTranslation(language: string, args: any): Observable<any> {
        let url: string = "";

        switch (args.type) {
            case "global":
                url += args.path + ".json";
                break;
            case "lang":
                url += args.path + language.substring(0, 2) + ".json";
                break;
            default:
                url += args.path + language + ".json";
        }

        return this.http.get(url)
            .map((res: Response) => res.json());
    }

}
```
The module:
```
@NgModule({
    imports: [
        ...
        HttpModule,
        LocalizationModule.forRoot({ translationProvider: FallbackTranslationProvider })
    ],
    ...
})
```
Let me know.

**Comment by Ghostbird** [comment]
Thanks a lot! I got it working nicely.

I had some trouble with `useLocaleAsLanguage()` so I left that out, and defined the language-locale combinations as separate languages.
```typescript
this.locale.addConfiguration()
     .addLanguages(['en', 'en-GB', 'nl'])
// ---Snipped---
this.translation.addConfiguration()
    .addCustomProvider({type: 'global', path: './assets/global'})
    .addCustomProvider({type: 'lang', path: './assets/lang-'})
    .addCustomProvider({type: 'locale', path: './assets/locale-'})
this.translation.init();
```

Custom provider uses some more logic to separate language and locale code:
```typescript
@Injectable() export class FallbackTranslationProvider implements TranslationProvider {

    constructor(private http: Http) { }

    public getTranslation(language: string, args: any): Observable<any> {
        let url: string = "";
        switch (args.type) {
            case "global":
                url += args.path + ".json";
                break;
            case "lang":
                // Use languagecode entirely (for only language) or until the first dash (for lang-locale combo)
                url += args.path + language.substring(0, language.length > 3 ? language.indexOf('-') : language.length) + ".json";
                break;
            case "locale":
                // Check for dash that indicates locale specific language code.
                if (language.indexOf('-') > -1)
                    url += args.path + language + ".json";
                else
                    // No locale, so don't return any data.
                    // However it must be packaged as an observable or the fallback mechanism will stop working.
                    return Observable.create(observer => { observer.complete(); });
                break;
            default:
                url += args.path + language + ".json";
        }
        return this.http.get(url).map(res => res.json());
    }
```

**Comment by robisim74** [comment]
Well. But keep in mind that without using `useLocaleAsLanguage()` for language-locale, you'll have a wrong `defaultLocale`: so if you'll use pipes or directives for dates & numbers maybe they wont work.

To use `useLocaleAsLanguage()` correctly, you have to use `LocalizationModule`, `defineDefaultLocale`, and `setDefaultLocale` methods with languageCode & countryCode when the language change. Then the `language` parameter passed to your provider will cointain the _locale_ (languageCode-countryCode).

Greetings,
Roberto

**Comment by Ghostbird** [comment]
Thanks for the warning. Currently I've got translations working, but I got some problems I didn't understand when I tried to use localisation.

I'll have a look at this later when I get to the point where I have to show currencies and calendars.

**Comment by DavidDomB** [comment]
I tried the code provided for @Ghostbird  but the parameters type and path are always undefined, what could i be missing?

**Comment by robisim74** [comment]
@DavidDomB See the docs: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4.4 If you still have problems, please open a new issue and post your code, otherwise it is impossible to understand what is missing. Greetings

**Comment by DavidDomB** [comment]
Thanks for your help @robisim74 . I am making PoCs based on your _angular-l10n-sample_ project, and in the _app.module.ts_ I added the custom provider after LocalizationModule and now it works.

```
@NgModule({
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        AppRoutingModule,
        SharedModule,
        LocalizationModule.forRoot(), // New instance of LocaleService & TranslationService.
        LocaleValidationModule.forRoot(),
        TranslationModule.forRoot({ translationProvider: FallbackTranslationProvider })
    ],
...
```

**Comment by atluri64** [comment]
I created FallbackTranslationProvider and got it working. But, it does not suffice my requirement.
I have created global json as below.
{
   "Address": {
       "AddressLine1":"Address Line1",
       "AddressLine2":"Address Line2",
       "AddressLine3":"Address Line3",
      "ZipCode":"Zip Code"
     }
}

In en-GB locale, ZipCode should be Postal Code. So, I defined locale-en-GB.json as below

{
   "Address": {
      "ZipCode":"Postal Code"
     }
}

Now in en-GB locale, I am getting Postal Code in place of Zip Code, but other keys "AddressLine1, AddressLine2, AddressLine3" are not resolved. Is this the expected beahavior? I am expecting that AddressLine(n) keys should fall back on global.json since those are not defined in locale-en-GB.json.

**Comment by robisim74** [comment]
@atluri64 Please, post the configuration that you are using and your FallbackTranslationProvider.

**Comment by atluri64** [comment]
Thanks for the reply.

Here is my configuration.

translation.addConfiguration()
    .addCustomProvider({ type: "global", path: './assets/global' })
    .addCustomProvider({ type: "locale", path: './assets/locale-' })
    .useLocaleAsLanguage();
translation.init();

Here is my FallbackTranslationProvider

@Injectable() 
export class FallbackTranslationProvider implements TranslationProvider {

    constructor(private http: Http) { }

    public getTranslation(language: string, args: any): Observable<any> {
        let url: string = "";
        switch (args.type) {
            case "global":
                url += args.path + ".json";
                break;
            case "locale":
                if (language.indexOf('-') > -1)
                    url += args.path + language + ".json";
                else
                    return Observable.create(observer => { observer.complete(); });
                break;
        }
        return this.http.get(url).map(res => res.json());
    }
}

**Comment by robisim74** [comment]
I'm trying your code, and it works.

Are you sure that other keys are not resolved? `"AddressLine1"` is very similar to `"Address Line1".` Check also if your html is correct (_Address.AddressLine1_ etc.) and that you are using pipes or directives correctly.

**Comment by robisim74** [comment]
Check also if you have added `({ translationProvider: FallbackTranslationProvider })` to `TranslationModule.forRoot` or `LocalizationModule.forRoot` method.

**Comment by atluri64** [comment]
Thanks for your time @robisim74 

I am using pipes/directives properly and having LocalizationModule.forRoot({ translationProvider: FallbackTranslationProvider }) . I tried to implement the same in "angularl10-sample" app. It is having the same problem too.

If I specify all the keys in locale-en-GB.json, it's resolving keys fine from en-GB.json. If I specify only few keys, missing ones are not falling back on global.json. The keys which are available in en-GB.json are resolving fine.

Not sure what I am doing wrong. It would be great if you could provide the sample app which is working for you.

Thanks & Regards,
Srinivas Atluri.

**Comment by robisim74** [comment]
I created a simple plunker: http://embed.plnkr.co/q3EOV4olBTgAaf1SbsWs/ In this sample, the `Title` key is only in _global.json_ and not in _locale-en-GB.json_ etc.

Everyone can continue to customize it, depending on the needs of his app.

I hope this helps.

**Comment by atluri64** [comment]
I made below changes to your plunker project and got it reproduced. Below are the changes I did. Now, Test.Test2 is not being resolved. The problem actually comes when the key is in inner object. Attached is the updated project. Thank You !!!
[Project.zip](https://github.com/robisim74/angular-l10n/files/1236539/Project.zip)


_**globlal.json**_
{
  "Title": "Angular localization",
  "Test": {
      "Test1": "Test1",
      "Test2": "Test2"
  }
}
**_locale-en-GB.json_**

{
  "Subtitle": "It's a small world",
  "Change country": "Change country",
  "Greeting": "Hi!",
  "Change": "Change",
   "Test": {
      "Test1": "Test1-GB"
  }
}

**_locale-en-US.json_**

{
  "Subtitle": "It's a small world",
  "Change country": "Change country",
  "Greeting": "Hi!",
  "Change": "Change",
  "Test": {
      "Test1": "Test1-US"
  }
}

**_app.component.ts_**

     <h1>{{ 'Title' | translate:lang }}</h1>
      <h1>{{ 'Test.Test1' | translate:lang }}</h1>
      <h1>{{ 'Test.Test2' | translate:lang }}</h1>

**Comment by robisim74** [comment]
The problem here is not the nested keys, but the duplicate keys.

As I said in another issue (#103) _the order of providers does not guarantee that the data will be merged in the same order: for each request is made an Http get asynchronous request, and the fact that they are usually executed in order is only because Javascript is not really asynchronous but single thread, and the files end in queue._

_Performing asynchronous requests is the expected behavior for this library, because it would not make sense to wait sequentially to load the files._

**Comment by atluri64** [comment]
I understand. I am a Java developer. This is how any framework in Java works. We specify all the keys in default properties file and specify only the keys which needs change in locale specific properties file. So, the locale specific properties file takes precedence over the default one. If the key is present in locale specific file, it takes that otherwise it fallback on default one. This works although both have duplicate keys.

I found an alternate way to get it working in Angular-l10n. I updated the keys in JSON files as below and setComposedKeySerator(" ") so that HTML files does not need any change since 75% of my app development is done. Now the issue of duplicate keys is no more a problem. I appreciate your timely response.

{
"Address.AddressLine1":"Address Line1",
"Address.AddressLine2":"Address Line2",
"Address.AddressLine3":"Address Line3",
"Address.ZipCode":"Zip Code"
}

**Comment by robisim74** [comment]
The new major version 4.0.0 for Angular v5 (https://github.com/robisim74/angular-l10n/releases) supports fallback providers: just set up the providers during the configuration. Fallback providers will be loaded and merged in order, so also duplicated keys are no longer a problem: https://robisim74.github.io/angular-l10n/spec/configuration/#loading-the-translation-data

I'm sorry I could not introduce this feature for Angular v4, but it required breaking changes, and the new major version of the library was planned for Angular v5. 

The feature is still in beta. Any feedback about this new feature will be appreciated!

Greetings
