### ISSUE TITLE
Translation inside custom pipe

### ISSUE THREAD

**Issue by melvas** [robisim74/angular-l10n#89]
Hi Roberto,

I have a custom pipe which returns string and this result must be translated. I've tried to solve it via the same way as for components but with no luck. Can you help me with this please if it's impossible?

Thank you!

**Comment by robisim74** [comment]
This should work:

`<p>{{ 'Title' | customPipe | translate:lang }}</p>`

Here an example: https://github.com/robisim74/angular-l10n-sample/blob/master/app/i18n.component.html#L10

**Comment by melvas** [comment]
Thanks for your response but it seems that my question was incorrect: I want to use pipe's own translation provider with it's own translation JSON files if it is possible. My custom pipe is used in several modules and it's string result can be different combination of words which can be translated only separately in the pipe.

**Comment by robisim74** [comment]
Ok, now I see:
>I've tried to solve it via the same way as for components

Which kind of pipes are you using? _Pure pipes_ will not be updated when you change language... and _impure pipes_ destroy performance...

These are the reasons why the pipes in this library are pure, but they need an input parameter to update.

**Comment by melvas** [comment]
It's pure pipe and I guess I can add new parameter for it (as example 'needToTranslate') and change this parameter on translationChanged

**Comment by robisim74** [comment]
Yes, or use the _lang_ parameter.

**Comment by robisim74** [comment]
You could also use a directive instead of a pipe.

**Comment by melvas** [comment]
Thank you for your advises. I'll try it and tell about the result

**Comment by melvas** [comment]
It works! thank you very much!
