### ISSUE TITLE
'Observable<{}>' is not assignable to type 'Observable<string>' issue

### ISSUE THREAD

**Issue by MedAnd** [robisim74/angular-l10n#9]
Not sure if this is environmental however tsc is throwing the below compile errors:

node_modules/angular2localization/src/services/localization.service.ts(206,16): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<string>'.
  Type '{}' is not assignable to type 'string'.
node_modules/angular2localization/src/services/localization.service.ts(343,16): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<any[]>'.
  Type '{}' is not assignable to type 'any[]'.
    Property 'length' is missing in type '{}'.

"dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "adal-angular": "^1.0.10",
    "angular2localization": "^0.7.1",
    "bootstrap": "^3.3.6",
    "es6-module-loader": "^0.17.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "font-awesome": "^4.6.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "0.6.12"
  }

**Comment by robisim74** [comment]
Thanks a lot for pr! Yes it is only an environmental problem: this library has in the `tsconfig` `"noImplicitAny": true`

**Comment by MedAnd** [comment]
Hi Roberto,

Glad to help and look forward to using your library!

**Comment by robisim74** [comment]
Thanks again! The latest version 0.7.2 has compile errors resolved. Greetings
