### ISSUE TITLE
(Question) angular-l10n provide translation from database

### ISSUE THREAD

**Issue by GHVladimir** [robisim74/angular-l10n#91]
Hello Roberto, first of all thank you for the great l10n library. In my project, I have angular library that is imported into main application. I was wondering if there is a way to separate translation of these two. Right now, I can only use json files in the main application and it will translate everything that is marked for translation in the imported library. Is there a way to support a separate json file for the library only? Thank you in advance, I hope I was clear enough :)

**Comment by robisim74** [comment]
Please, can you provide more details or an example? Thanks

**Comment by GHVladimir** [comment]
I apologize for not responding earlier, I found out the solution on my own. However, I was wondering if you could answer another question. Is there a way to provide translation from a database?

**Comment by robisim74** [comment]
Only through a Web API. Otherwise you should extend the `TranslationService`, customize it, and inject it into the place of the existing one.

**Comment by robisim74** [comment]
About the second option: I realize it's not easy: and anyway I should change the visibility of some methods. So I'm thinking of creating a class loader, where you can only customize data access. In the coming days I will release a new version with this feature.

**Comment by GHVladimir** [comment]
Thank you very much. Looking forward to this new feature! 👍

**Comment by robisim74** [comment]
v3.3.0 is out with support for custom provider: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#2.4

Let me know.

**Comment by DavidDomB** [comment]
Hello, i want to use localization files with names including language and locale or just language, i.e. locale-en-US.json or locale-en.json. This is becase if an specific region file is not defined then default file for language should be used. Can this be achieved by implementing a custom provider? 

Here is how I want to work like.
Add language to configuration:
`this.locale.addConfiguration().addLanguage('en', 'ltr')`

Define the configuration as:
`this.translation.getConfiguration().localeAsLanguage = true;`

Set default locale:
`this.locale.setDefaultLocale(language, country);`

Then, look for language file as _locale-en-US.json_, if not found then look for _locale-en.json_.

I hope that I am clear in this.

**Comment by robisim74** [comment]
@DavidDomB See this issue: https://github.com/robisim74/angular-l10n/issues/88

**Comment by robisim74** [comment]
@GHVladimir I'm closing this issue. Reopen it if you need.

**Comment by asachan2707** [comment]
Can we support l10n from dynamic import in the custom angular library?
