### ISSUE TITLE
(Question) how to use this library in the ts code?

### ISSUE THREAD

**Issue by basuradeluis** [robisim74/angular-l10n#92]
Hello:
I am trying to use this library. I can use it in the html , using the "translate" template without problems.
I init the library using similar to this:
        super(translation);

        this.locale.AddConfiguration()
            .AddLanguages(['en', 'it'])
            .SetCookieExpiration(30)
            .DefineLanguage('en');
		this.locale.setCurrentLanguage('en');
        this.locale.init();
		this.locale.setCurrentLanguage('en');        

        this.translation.AddConfiguration()
            .AddProvider('./assets/translation/locale-');
        this.translation.init();             
Ok, perfect. Later in the .html I use "translate" word in the html and it works.

But I would like to know how to translate a string inside a function in typescript in a component.
Suposing I have got:
var aux1="fooo"
And in assets/translation/locale-en.json
{...."foo": "fooTRANSLATED",...}
how can i translate aux1?
I am trying to use 
translationService.translate("foo",null,'en');
and 
this.translation.translateAsync('foo',null,'en').subscribe(
			sucess => {console.log("result"+sucess) },
			err =>{console.log("aaa"+err) }

		)
but neither of them works. It seems internal translationData array is always empty, and it returns me the same "key" i am trying to translate.
Is any initialization required in the component ?

May you help me, please? Or publish an example? Thanks

**Comment by robisim74** [comment]
https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.4

**Comment by basuradeluis** [comment]
Thanks a lot. Now it works. This can be closed.
Thanks!
