### ISSUE TITLE
Localizing parameter in message

### ISSUE THREAD

**Issue by Arnaud-DT** [robisim74/angular-l10n#94]
Hi,

First of all, thanks for this great library!
I'm looking for a way to localize a parameter in a message. For example, i'd like to apply the correct formatting for decimal or date in this message:
<div>{{ 'luggage' | translate:lang:{weight:weight, date:date} }}</div>

with in my json file: 
"luggage": "The luggage you've sent on {{date}} weighs {{weight}}."

It would be ideal if I could do something like this:
"luggage": "The luggage you've sent on {{date | localeDate="fullDate"}} weighs {{weight | localeDecimal="1.5-5"}}."

But this doesn't seem to work.

Do you have an idea for a workaround on this? Thanks for your help!

**Comment by robisim74** [comment]
Hi,

first make sure you are importing `LocalizationModule` and that you have defined the _defaultLocale_ in the configuration.

Then try this:
```
@Component({
    template: `
        <p>{{ 'luggage' | translate:lang:{date:date | localeDate:df:'fullDate',weight:weight | localeDecimal:df:'1.5-5'} }}</p>
    `
})
export class HomeComponent implements OnInit {

    @Language() lang: string;
    @DefaultLocale() df: string;

    date: Date = new Date('5/23/2017');
    weight: number = 10;

    ngOnInit(): void {
        //
    }

}
```
Greetings,
Roberto

**Comment by Arnaud-DT** [comment]
Works great, thank you very much!
