### ISSUE TITLE
Component does not translate html on initial page load in Angular 2

### ISSUE THREAD

**Issue by bschmitz9** [robisim74/angular-l10n#95]
I have a simple Angular 2  component where I'm trying to translate the html values accordingly when I select the current language from the drop-down. My html:

        <md-select [(ngModel)]="currentLocale" name="currentLocale" placeholder="Language">
                  <md-option *ngFor="let locale of locales" [value]="locale.code (click)="selectLocale(locale.code);">{{locale.name}}</md-option>
       </md-select>

        <tr>
             <td>modules.localization.language</td>
             <td translate>modules.localization.language</td>
        </tr>

When a user selects a language from the dropdown (i.e. English, French, Russian) the data on the page should be translated/localized accordingly.  My issue is on page load I am not getting the translated value, it just shows as "modules.localization.language".

But when a user selects an option from the drop-down the page is translated and updated as it should be.

I'm trying to translate on page load within ngOnInit but can't seem to get any translations here, feel like I've tried every available method:

         public ngOnInit() {
		this.locales = LOCALES.locales;
		this.numberExample = 1000000;
		this.dateExample = new Date();
		this.locale.addConfiguration()
			.addLanguage('en-us', 'ltr')
			.addLanguage('fr-fr', 'ltr')
			.addLanguage('ru-ru', 'ltr')
			.setCookieExpiration(30)
			.defineCurrency('USD');

		this.locale.init();

		this.locale.setDefaultLocale('en-us', null);
		this.currentLocale = this.localeService.getCurrentLanguage();

		this.translation.addConfiguration()
			.addProvider('./assets/locale-');

		this.translation.init();
         }

        // calls when a user selects a language from the dropdown
        public selectLocale(language: string, country: string, currency: string): void {
		  this.localeService.setDefaultLocale(language, country);
         }

What am I missing here? The selectLocale function updates the page when a user selects something from the drop down. Why doesn't setDefaultLocale do the same in ngOnInit?

Thanks

**Comment by robisim74** [comment]
You are using a _locale_ (languageCode-countryCode) for language: but in this library these codes are separated in all the _signatures_ of the methods:

- `addLanguage(languageCode: string, textDirection?: string)`
- `defineDefaultLocale(languageCode: string, countryCode: string, scriptCode?: string, numberingSystem?: string, calendar?: string)
`
- `setDefaultLocale(languageCode: string, countryCode: string, scriptCode?: string, numberingSystem?: string, calendar?: string): void`

where:
* `language code`: ISO 639 **two-letter or three-letter** code of the language
* `country code`: ISO 3166 two-letter, **uppercase** code of the country

So you should change your configuration to this:
```
	this.locale.addConfiguration()
		.addLanguage('en', 'ltr')
		.addLanguage('fr', 'ltr')
		.addLanguage('ru', 'ltr')
		.setCookieExpiration(30)
                .defineDefaultLocale('en', 'US')
		.defineCurrency('USD');
	this.locale.init();
```
Then if you want use the _locale_ as language, you have `useLocaleAsLanguage()` method:

```
	this.translation.addConfiguration()
		.addProvider('./assets/locale-')
                .useLocaleAsLanguage();
	this.translation.init();
```
Your json files should be something like: `./assets/locale-en-US.json` and so on.

Then you have to pass to `selectLocale` method the correct codes of the signature: `language: string, country: string`.

After making these changes, also clean cookies in your browser cache.

All this things are in the specification: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md

Greetings

**Comment by bschmitz9** [comment]
thanks looks like I was just missing the .useLocaleAsLanguage(); and had to update what I was passing into my selection of drop downs.
