### ISSUE TITLE
Bug in child lazy loaded route

### ISSUE THREAD

**Issue by crh225** [robisim74/angular-l10n#96]
Hi Roberto,
I made  a repo you can pull down and look at.
https://github.com/crh225/angular-l10n-sample

The list component is lazy loaded from your example. In the list module, I want to have a child route. For our purpose, I called it test.component.ts and the route is list/test/

all the test component does is try and translate the word "Accountant"

When the app loads, go to http://localhost:8080/#/list/test

this simulates my current application exactly and has me scratching my head.

**Comment by robisim74** [comment]
Add the translation providers you've removed from ListModule in AppModule:

```
        translation.addConfiguration()
            .addProvider('./src/assets/locale-')
            .addProvider('./src/assets/locale-list-')
            .addProvider('./src/assets/locale-position-');
```
Then change the template in your test component in a correct form:
```
@Component({
    selector: 'test',
    template: `This Should translate: {{ 'Accountant' | translate:lang }}`,
    ...
})
```
You have to use _quotes_ for the keys: '
You have to use _backticks_  for the template: `

And it will work, also if Angular compiler indicates that it does not recognize the component (so there must be something that does not go in your child route).

Please, open issues for bugs, feature or support requests about this library, not for every Angular problem.

Thanks,
Roberto

**Comment by crh225** [comment]
To be fair, I didn't realize it was an Angular problem.

**Comment by robisim74** [comment]
With _Angular problem_ I mean: a problem in using Angular properly.
