### ISSUE TITLE
No provider for Localeconfig error in karma unit testing

### ISSUE THREAD

**Issue by anisharknair** [robisim74/angular-l10n#97]
@robisim74 After angular-I10n updation karma unit tests failing with following error.

  Error: No provider for LocaleConfig!
      at injectionError (node_modules/@angular/core/bundles/core.umd.js:1238:8

      at noProviderError (node_modules/@angular/core/bundles/core.umd.js:1276:

**Comment by robisim74** [comment]
Now the library injects several services: you should use `TranslationModule.forRoot()` or `LocalizationModule.forRoot()` also in tests as here: https://github.com/robisim74/angular-l10n-sample/blob/master/src/app/home/home.component.spec.ts#L20-L27.

**Comment by anisharknair** [comment]
Thank you,Now its working..
