### ISSUE TITLE
root configurations to be accessed from lazy loaded modules, while each LL module use it's own

### ISSUE THREAD

**Issue by PanosParalakis** [robisim74/angular-l10n#98]
Hello,

I want a app instance that will be shared by other lazy loaded modules, but I also want each lazy loaded module to use it's own instance. I have tried all possible configurations that you have suggested but still lazy loaded module component can not translate/use root (global) translation configurations.

Is that possible?

**Comment by robisim74** [comment]
You can't.
You can not have more instances for each lazy loaded module: the reference instance for the translation is one for each module.
If you need the translation data you use in your root, you can add another provider in the lazy loaded module.

**Comment by PanosParalakis** [comment]
Hello Roberto!

Thank you for you reply! That is what I am trying to do, but with no success. Shared is ignored. Do you plan to add an example on the guide or maybe share some info on how to achieve this?

Thank you!

**Comment by robisim74** [comment]
As I said, and as you can find in the documentation, when you create a new instance you can add all the translation providers that the module needs. Example:

**AppModule**
```
        this.translation.addConfiguration()
            .addProvider('./assets/locale-global-');
        this.translation.init();
```
**Lazy loaded module**
```
        this.translation.addConfiguration()
            .addProvider('./assets/locale-global-')
            .addProvider('./assets/locale-lazy-');
        this.translation.init();
```
Otherwise, you can add all the providers to `AppModule`, and then use a shared module without creating new instances.

Greetings

**Comment by PanosParalakis** [comment]
Hello again!

Thank you for your reply! I 've seen that before in the documentation but it is not what I want as with this approach I request global twice, triple etc depending on how many LL modules need to use shared translations. 

Using a shared module with all translations again is not an option as I want translations to be part of the lazy loaded module as it is a cleaner and more maintainable design. 

I will see what I can do. Again thank you!
