### ISSUE TITLE
`translate` directive does not work in ionic components

### ISSUE THREAD

**Issue by uloco** [robisim74/angular-l10n#99]
Please consider updating the major version in `package.json` when introducing breaking changes. The node/npm community highly relies on [semantic versioning](http://semver.org/). 
Node modules are saved to `package.json` with the `^` prefix per default, this means all _minor_ and _patch_ updates will be downloaded on a `npm update`.

This eases up build configuration and maintaining a lot. Please consider.

**Comment by robisim74** [comment]
> MAJOR version when you make incompatible API changes

The latest version doesn't have incompatible API: https://github.com/robisim74/angular-l10n/releases

**Comment by uloco** [comment]
When I update from version 3.3 to 3.4 the translations stop working. This is a breaking change. I think it is the `translate` directive. You renamed it...
Making this a non breaking change, you should have just added the new directives and keep the old `translate` for backwards compatibility. If you don't, this is a breaking API change.

**Comment by robisim74** [comment]
Just a moment: if it does not work it's not a major or minor version problem: can you tell what's happening?

**Comment by uloco** [comment]
I edited my comment...

**Comment by robisim74** [comment]
>New prefix for the selectors: l10n (old selectors are still valid)

https://github.com/robisim74/angular-l10n/releases/tag/v3.4.0

The code: https://github.com/robisim74/angular-l10n/blob/master/src/directives/translate.directive.ts#L11-L16

If your app is not working, there must be some other problem.

**Comment by uloco** [comment]
I don't know what the problem is.
If I downgrade to 3.3.0 It works. If I update to 3.4.0 it stops working. The translations simply don't get translated, I only see the translation names from my json files instead of the translated texts.
No log output or error messages....

You stated it yourself, you have breaking changes and should make a version bump to 4.x
It is super simple. If I just upgrade the minor version of your library, there should not be a breaking change. If this was not your intend, than this is just a bug.... 
I just wanted to make things clear :)

**Comment by robisim74** [comment]
As said, your app should work, because there aren't breaking changes in the APIs.

If it is not working, or there is a bug (and what to do with the major version?), or you are using this library in an unconventional way. So please post the essential code, so that I can understand.

**Comment by uloco** [comment]
Ah I see. I think I found the reason. I am running in a ionic app. In the version 3.3.0 I could just add the `translate` directive to ionic components like `<ion-input translate>my_text</ion-input>` but this does not work anymore. Only on normal html tags like `<div>`

**Comment by robisim74** [comment]
Please: can you post the `ion-input` rendering?  And see here: https://github.com/robisim74/angular-l10n/blob/master/doc/spec.md#3.2.4

I assume that for ionic components is not enough depth 3.

**Comment by uloco** [comment]
Lol.
Looks like I needed to clear the cookies of my browser and all storage/db stuff to get it working again.
I am really sorry for this issue. Works great. 😅

**Comment by robisim74** [comment]
It should not be necessary to clean the cookies, but I will add this advice to the release.

Since you are using Ionic, you can now create custom storage and use, for example, Ionic Storage.

**Comment by uloco** [comment]
I am using this ionic storage already, thanks for your advice though.

Sorry but, I forgot to restart my build. The error still is valid. It does not work....

**Comment by robisim74** [comment]
What should translate this? `<ion-input translate>my_text</ion-input>`. It is an input field.

**Comment by uloco** [comment]
Sorry this was a wrong example, i meant `<ion-item>`

**Comment by uloco** [comment]
Just the inner html, like in a `<div>` or a `<p>`

**Comment by uloco** [comment]
The pipes and the services still work. It is just the `translate` directive which stopped working on these elements. Also the `l10nTranslate` directive does not work on these components.

**Comment by robisim74** [comment]
Ok: I found the problem: it is a depth 4. I can change this setting, and release a new version. But I discourage the use of directives for such complex components.

**Comment by uloco** [comment]
It is not complex, it is just a `<ion-item translate>label<ion-item>`. I understand, that directives should not used in complex scenarios. 👍

**Comment by uloco** [comment]
Thanks for fixing this btw. This is the reason I love open source software. Kudos for this amazing library. It helps a lot 👍  👍  👍

**Comment by robisim74** [comment]
By tonight I will release the new version. Please change the title of this issue.

**Comment by robisim74** [comment]
v3.4.1 that should solve this issue is out.

I try to explain what happened here. Ui components like `<ion-item l10nTranslate>Title</ion-item>` are rendered in this way:
```
<ion-item class="item item-block item-md" l10ntranslate="" ng-reflect-l10n-translate="">
	<div class="item-inner">
		<div class="input-wrapper">
			<!--bindings={"ng-reflect-ng-if": "true"}-->
			<ion-label class="label label-md">Title</ion-label>
		</div><!--bindings={"ng-reflect-ng-if": "false"}-->
	</div>
	<div class="button-effect"></div>
</ion-item>
```
As you can see, the text to translate (Title) is into a subtree, in that case to depth 4 (just count the child nodes).
To find the value to translate, an algorithm must search in that subtree.
I added a limit to this searching (before to 3, now to 10): but I suggest to switch to pipes if you have a depth higher 4, or many of these components in your page (because the initialization time of the directive becomes longer).

Greetings

**Comment by uloco** [comment]
Looks like, this solved the issue. Thanks for fixing this!
